---
permalink: sm-storage/actions-you-can-perform-on-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volumes 
summary: 您可以對磁碟區執行多種不同的操作：增加容量、刪除、複製、初始化、重新分配、變更所有權、變更快取設定和變更媒體掃描設定。 
---
= 您可以在 SANtricity System Manager 中對磁碟區執行的操作
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以對磁碟區執行多種不同的操作：增加容量、刪除、複製、初始化、重新分配、變更所有權、變更快取設定和變更媒體掃描設定。



== 增加容量

您可以透過兩種方式擴充磁碟區的容量：

* 使用池或磁碟區群組中可用的可用容量。
+
您可以透過選擇功能表：Storage[Pools and Volume Groups > Add Capacity] 來新增磁碟區容量。

* 將未分配的容量（以未使用的磁碟機形式）新增至磁碟區的儲存池或磁碟區群組。當儲存池或磁碟區群組中沒有可用容量時，請使用此選項。
+
您可以透過選擇功能表：Storage [Pools and Volume Groups > Add Capacity] 來為儲存池或磁碟區群組新增未指派的容量。

+
如果儲存池或磁碟區群組中沒有可用容量，則無法增加磁碟區的容量。您必須先增加儲存池或磁碟區群組的大小，或刪除未使用的磁碟區。



擴展卷容量後，您必須手動增加檔案系統大小以與之匹配。具體操作方法取決於您使用的檔案系統。有關詳細資訊，請參閱主機作業系統文件。



== 刪除

通常情況下，如果磁碟區建立時參數或容量錯誤、不再滿足儲存配置需求，或只是不再用於備份或應用程式測試的快照映像，則需要刪除磁碟區。刪除磁碟區可以增加儲存池或磁碟區組的可用容量。

刪除磁碟區會導致這些磁碟區上的所有資料遺失。刪除磁碟區也會刪除所有關聯的 snapshot 映像、排程和 snapshot 磁碟區，並移除所有鏡像關係。



== 複製

複製磁碟區時，會在相同儲存陣列上建立兩個獨立磁碟區（來源磁碟區和目標磁碟區）的相同時間點副本。您可以透過選擇選單：Storage[Volumes > Copy Services > Copy volume] 來複製磁碟區。



== 初始化

初始化磁碟區會擦除磁碟區中的所有資料。磁碟區在首次建立時會自動初始化。但是，Recovery Guru 可能會建議您手動初始化磁碟區，以便從某些故障情況下進行復原。初始化磁碟區時，磁碟區會保留其 WWN、主機分配、已分配容量和已保留容量設定。它還會保留相同的 Data Assurance（DA）設定和安全設定。

您可以選擇功能表：Storage[Volumes > More > Initialize volumes] 來初始化磁碟區。



== 重新分配

您可以重新分配磁碟區，將磁碟區移回其偏好的控制器擁有者。通常，當主機和儲存陣列之間的資料路徑發生問題時，多路徑驅動程式會將磁碟區從其偏好的控制器擁有者移出。

大多數主機多路徑驅動程式會嘗試透過指向其首選控制器擁有者的路徑存取每個磁碟區。但是，如果此首選路徑不可用，主機上的多路徑驅動程式將故障轉移到備用路徑。此故障轉移可能會導致磁碟區的所有權變更為備用控制器。解決導致故障轉移的情況後，某些主機可能會自動將磁碟區的所有權移回首選控制器擁有者，但在某些情況下，您可能需要手動重新指派磁碟區。

您可以透過選擇選單：Storage [ Volumes > More > Redistribute volumes ] 來重新分配磁碟區。



== 變更磁碟區所有權

變更磁碟區的所有權會變更該磁碟區的首選控制器所有權。磁碟區的首選控制器擁有者列在功能表：Storage（儲存）[Volumes（磁碟區）> View/Edit Settings（檢視/編輯設定）> Advanced（進階）標籤] 下。

您可以透過選擇功能表：Storage[Volumes > More > Change ownership] 來變更磁碟區的所有權。



=== 鏡像和磁碟區所有權

如果鏡像對中的主磁碟區由控制器 A 擁有，則遠端儲存陣列的輔助磁碟區也將由控制器 A 擁有。更改主磁碟區的擁有者將自動變更輔助磁碟區的擁有者，以確保兩個磁碟區都由同一控制器擁有。主磁碟區上的目前所有權變更會自動傳播到輔助磁碟區上對應的目前所有權變更。

如果鏡像一致性群組包含本機次要磁碟區，且控制器所有權發生變更，則次要磁碟區會在第一次寫入作業時自動轉移回其原始控制器擁有者。您無法使用 *Change ownership* 選項來變更次要磁碟區的控制器所有權。



=== 複製磁碟區和磁碟區所有權

在複製磁碟區操作期間，來源磁碟區和目標磁碟區必須由同一控制器擁有。有時，在複製磁碟區操作開始時，兩個磁碟區的首選控制器可能不同。因此，目標磁碟區的所有權會自動轉移到來源磁碟區的首選控制器。當磁碟區複製完成或停止時，目標磁碟區的所有權將恢復到其首選控制器。

如果在複製磁碟區操作期間來源磁碟區的所有權發生更改，則目標磁碟區的所有權也會發生變更。在某些作業系統環境下，可能需要重新配置多路徑主機驅動程式，然後才能使用 I/O 路徑。（某些多路徑驅動程式需要進行編輯才能識別 I/O 路徑。如需更多資訊，請參閱驅動程式文件。）



== 更改快取設定

快取記憶體是控制器上的一個臨時易失性儲存區（RAM），其存取時間比磁碟機媒體更快。如果您使用快取記憶體，可以提高整體 I/O 效能，原因如下：

* 從主機請求讀取的資料可能已經存在於先前操作的快取中、因此無需存取磁碟機。
* 寫入資料首先寫入快取，這樣應用程式就可以繼續運行，而無需等待資料寫入磁碟機。


選擇功能表：Storage[Volumes > More > Change cache settings] 以變更下列快取設定：

* *讀取和寫入快取* -- 讀取快取是一個緩衝區，用來儲存從磁碟機讀取的資料。讀取操作所需的資料可能已經存在於快取中（來自先前的操作），這樣就無需存取磁碟機。資料會一直保留在讀取快取中，直到被清除。
+
寫入快取是一個緩衝區，用於儲存來自主機但尚未寫入磁碟機的資料。資料會一直保留在寫入快取中，直到被寫入磁碟機為止。寫入快取可以提高 I/O 效能。

* *帶有鏡像的寫入快取* -- 帶有鏡像的寫入快取是指將寫入一個控制器快取記憶體的資料也寫入另一個控制器的快取記憶體。因此，如果一個控制器發生故障，另一個控制器可以完成所有未完成的寫入操作。僅當啟用寫入快取且存在兩個控制器時，寫入快取鏡像才可用。建立磁碟區時，預設設定是帶有鏡像的寫入快取。
* *無電池寫入快取* -- 無電池寫入快取設定可讓寫入快取繼續運作，即使電池遺失、故障、完全放電或未充滿電也一樣。通常不建議選擇無電池寫入快取，因為如果電源中斷，資料可能會遺失。一般而言，控制器會暫時關閉寫入快取，直到電池充滿電或更換故障電池為止。
+
僅在啟用寫入快取後，此設定才可用。此設定不適用於精簡磁碟區。

* *Dynamic read cache prefetch* -- Dynamic cache read prefetch 允許控制器在從磁碟機讀取資料區塊到快取的同時，將額外的順序資料區塊複製到快取中。這種快取機制提高了後續資料請求能夠從快取中獲取所需資料的機率。Dynamic cache read prefetch 對於使用順序 I/O 的多媒體應用至關重要。預取到快取中的資料速率和數量會根據主機讀取的速率和請求大小自動調整。隨機存取不會導致資料預取到快取中。停用讀取快取時，此功能無效。
+
對於精簡磁碟區，動態快取讀取預先擷取始終處於停用狀態，且無法變更。





== 變更媒體掃描設定

媒體掃描可以偵測並修復應用程式不常讀取的磁碟區塊上的媒體錯誤。如果儲存池或磁碟區群組中的其他磁碟機發生故障,此掃描可防止資料遺失,因為它會利用冗餘資訊和儲存池或磁碟區群組中其他磁碟機的資料來重建故障磁碟機的資料。

媒體掃描會根據待掃描容量和掃描持續時間以恆定速率持續運作。後台掃描可能會因優先順序較高的後台任務（例如重建）而暫時中斷，但會以相同的恆定速率恢復。

您可以透過選擇選單：Storage［Volumes > More > Change media scan settings］來啟用和設定媒體掃描的運行時間。

只有當儲存陣列和該磁碟區都啟用了媒體掃描選項時，才會掃描該磁碟區。如果該磁碟區也啟用了冗餘檢查，則會檢查磁碟區中的冗餘資訊與資料的一致性（前提是該磁碟區具有冗餘）。預設情況下，每個磁碟區在建立時都會啟用冗餘檢查的媒體掃描。

如果在掃描過程中遇到無法復原的媒體錯誤，系統將使用冗餘資訊（如有）修復資料。例如，冗餘資訊存在於最佳化的 RAID 5 磁碟區中，或存在於最佳化的 RAID 6 磁碟區中，或僅存在一個故障磁碟機的 RAID 6 磁碟區中。如果無法使用冗餘資訊修復無法復原的錯誤，則該資料區塊將被新增至不可讀磁區日誌。可修正和不可修正的媒體錯誤都會報告到事件日誌中。

如果冗餘檢查發現資料與冗餘資訊之間存在不一致，則會將其報告到事件日誌。
