---
permalink: sm-storage/add-capacity-to-a-pool-or-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, capacity, pool, volume, group 
summary: 您可以新增磁碟機來擴充現有儲存池或磁碟區群組中的可用容量。 
---
= 在 SANtricity System Manager 中為資源池或磁碟區群組新增容量
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以新增磁碟機來擴充現有儲存池或磁碟區群組中的可用容量。

擴充操作會在儲存池或磁碟區群組中增加額外的可用容量。您可以使用這些可用容量來建立其他磁碟區。在此操作期間，磁碟區中的資料仍然可存取。

.開始之前
* 磁碟機必須處於最佳狀態。
* 磁碟機必須具有相同的磁碟機類型（HDD 或 SSD）。
* 資源池或磁碟區群組必須處於最佳狀態。
* 一個磁碟區群組中允許的最大磁碟區數為 256 。
* 儲存池中允許的最大磁碟區數取決於儲存系統型號：
+
** 2,048 個磁碟區（EF600 和 E5700 系列）
** 1,024 個磁碟區 (EF300)
** 512 個磁碟區（E4000 和 E2800 系列）


* 如果儲存池或磁碟區群組包含所有具有安全功能的磁碟機，只需新增具有安全功能的磁碟機，即可繼續使用具有安全功能的磁碟機的加密功能。
+
具備安全功能的磁碟機可以是全磁碟加密（FDE）磁碟機或聯邦資訊處理標準（FIPS）磁碟機。



.關於此任務
對於儲存池，一次最多可以新增 60 個磁碟機。對於磁碟區群組，一次最多可以新增兩個磁碟機。如果需要新增的磁碟機數量超過最大限制，請重複上述步驟。（儲存池包含的磁碟機數量不能超過儲存系統的最大限制。）

[NOTE]
====
增加磁碟機後，您的保留容量可能需要增加。您應該考慮在擴充作業後增加預留容量。

====
[NOTE]
====
避免使用支援 Data Assurance (DA) 的磁碟機來為不支援 DA 的儲存池或磁碟區群組增加容量。儲存池或磁碟區群組無法利用支援 DA 的磁碟機的功能。在這種情況下，請考慮使用不支援 DA 的磁碟機。

====
.步驟
. 選擇選單：Storage [ Pools & Volume Groups ]。
. 選擇要新增磁碟機的儲存池或磁碟區群組，然後按一下 *Add Capacity* 。
+
此時會顯示「新增容量」對話框。僅顯示與儲存池或磁碟區群組相容的未指派磁碟機。

. 在 *Select drives to add capacity...* 下，選擇要新增至現有池或磁碟區群組的一個或多個磁碟機。
+
控制器韌體會將未指派的磁碟機按最佳選項排序，並將其列在頂部。新增至儲存池或磁碟區群組的總可用容量會顯示在清單下方的 *Total capacity selected* 中。

+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
機櫃
 a| 
指示磁碟機的機櫃位置。



 a| 
機槽
 a| 
指示磁碟機的機櫃位置。



 a| 
容量 (GiB)
 a| 
表示磁碟機容量。

** 盡可能選擇容量與儲存池或磁碟區群組中現有磁碟機容量相同的磁碟機。
** 如果必須新增容量較小的未指派磁碟機、請注意、集區或磁碟區群組中每個磁碟機的可用容量都會減少。因此、磁碟機容量在整個集區或磁碟區群組中都相同。
** 如果您必須新增容量較大的未指派磁碟機，請注意，您新增的未指派磁碟機的可用容量會減少，以便與儲存池或磁碟區群組中磁碟機的目前容量相符。




 a| 
安全功能
 a| 
指示該磁碟機是否具備安全功能。

** 若要使用磁碟機安全功能保護您的儲存池或磁碟區群組，所有磁碟機都必須具備安全功能。
** 可以建立包含安全磁碟機和非安全性磁碟機的混合池或磁碟區群組，但無法啟用 Drive Security 功能。
** 即使加密功能未使用，包含所有安全磁碟機的儲存池或磁碟區群組也無法接受不具備安全功能的磁碟機作為備用或擴充磁碟機。
** 報告為具有安全功能的磁碟機可以是全磁碟加密（FDE）磁碟機或聯邦資訊處理標準（FIPS）磁碟機。
** FIPS 驅動器可以是 140-2 級或 140-3 級，其中 140-3 級安全等級更高。如果選擇 140-2 級和 140-3 級驅動器的混合使用，則儲存池或磁碟區群組將以較低的安全等級（140-2）運作。




 a| 
DA 功能
 a| 
指示該磁碟機是否具備資料保障（DA）功能。

** 不建議使用不具備 Data Assurance (DA) 功能的磁碟機為支援 DA 的儲存池或磁碟區群組新增容量。儲存池或磁碟區群組將不再具備 DA 功能，且您無法再為在該儲存池或磁碟區群組中新建的磁碟區啟用 DA 功能。
** 不建議使用支援 Data Assurance (DA) 的磁碟機來為不支援 DA 的儲存池或磁碟區群組增加容量，因為該儲存池或磁碟區群組無法利用支援 DA 的磁碟機的功能（磁碟機屬性不符）。在這種情況下，請考慮使用不支援 DA 的磁碟機。




 a| 
具備 DULBE 功能
 a| 
指示磁碟機是否具有已釋放或未寫入邏輯區塊錯誤（DULBE）選項。DULBE 是 NVMe 驅動器上的選項，可讓 EF300 或 EF600 儲存陣列支援資源預置磁碟區。

|===
====
. 點擊 *Add* 。
+
如果您要將磁碟機新增至儲存池或磁碟區群組，而您選擇的磁碟機會導致儲存池或磁碟區群組不再具有下列一個或多個屬性，則會顯示確認對話方塊：

+
** 貨架損耗保護 ^*^
** 抽屜遺失保護 ^*^
** 全磁碟加密功能
** 資料保證功能
** DULBE 功能





NOTE: ^*^ 目前，當為具有機櫃遺失保護或抽屜遺失保護的資源池新增磁碟機時，不會顯示確認對話方塊。

. 若要繼續、請按一下 *Yes* ；否則、請按一下 *Cancel* 。


.結果
將未指派的磁碟機新增至儲存池或磁碟區群組後，儲存池或磁碟區群組中每個磁碟區中的資料都會重新分配，以包含這些附加的磁碟機。
