---
permalink: sm-storage/assign-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, assign volumes 
summary: 您必須將磁碟區指派給主機或主機叢集，以便其可用於 I/O 操作。此指派授予主機或主機叢集對儲存陣列中一個或多個磁碟區的存取權限。 
---
= 在 SANtricity System Manager 中為主機指派磁碟區
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須將磁碟區指派給主機或主機叢集，以便其可用於 I/O 操作。此指派授予主機或主機叢集對儲存陣列中一個或多個磁碟區的存取權限。

.關於此任務
將磁碟區指派給主機時，請牢記以下準則：

* 一次只能將一個磁碟區指派給一台主機或一個主機叢集。
* 儲存陣列中的控制器之間共用已指派的磁碟區。
* 主機或主機叢集不能使用相同的邏輯單元號碼（LUN）兩次來存取磁碟區。您必須使用唯一的 LUN。
* 對於新建的磁碟區組，如果在將其指派給主機之前等待所有磁碟區都已建立並初始化完畢，則可以縮短磁碟區初始化時間。請注意，一旦與磁碟區組關聯的磁碟區被映射，_所有_ 磁碟區的初始化速度都會恢復到較慢的初始狀態。您可以從選單：主頁 [正在進行的操作] 查看初始化進度。


在以下情況下，指派磁碟區會失敗：

* 所有磁碟區均已指派。
* 該磁碟區已指派給另一台主機或主機叢集。


在以下情況下，無法指派磁碟區：

* 不存在有效的主機或主機叢集。
* 尚未為主機定義任何主機連接埠識別碼。
* 所有磁碟區指派均已定義。


在此任務期間，將顯示所有未指派的磁碟區，但對於具有或不具有 Data Assurance（DA）的主機，其功能按如下方式應用：

* 對於支援 DA 的主機、您可以選擇已啟用 DA 或未啟用 DA 的磁碟區。
* 對於不支援 DA 功能的主機，如果您選擇支援 DA 功能的磁碟區，則會發出警告，指出系統必須先自動關閉該磁碟區上的 DA 功能，然後再將該磁碟區指派給主機。


.步驟
. 選擇選單：Storage[Hosts]。
. 選擇要為其指派磁碟區的主機或主機叢集、然後按一下 *指派磁碟區* 。
+
此時會跳出對話框，列出所有可以指派的磁碟區。您可以對任意列進行排序，也可以在 *Filter* 方塊中輸入內容，以便更輕鬆地找到特定磁碟區。

. 選取要指派的每個 Volume 旁邊的核取方塊，或選取表格標題中的核取方塊以選取所有 Volume。
. 點選 *Assign* 完成操作。


.結果
成功將一個或多個磁碟區指派給主機或主機叢集後，系統將執行下列操作：

* 分配的磁碟區會獲得下一個可用的 LUN 編號。主機使用 LUN 編號來存取磁碟區。
* 使用者提供的磁碟區名稱會顯示在與主機關聯的磁碟區清單中。如果適用，出廠設定的存取磁碟區也會顯示在與主機關聯的磁碟區清單中。

