---
permalink: sm-storage/automatic-versus-manual-pool-creation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, manual, pool 
summary: 您可以自動或手動建立儲存池，以便對實體儲存進行分組，並根據需要動態分配空間。建立儲存池後，您可以新增實體磁碟機。 
---
= 了解 SANtricity System Manager 中自動建立池和手動建立池的差異
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以自動或手動建立儲存池，以便對實體儲存進行分組，並根據需要動態分配空間。建立儲存池後，您可以新增實體磁碟機。



== 自動建立

當 System Manager 偵測到儲存陣列中有未指派的容量時，會自動啟動儲存池建立。偵測到未指派的容量後，System Manager 會自動提示您建立一個或多個儲存池，或將未指派的容量新增至現有儲存池，或同時進行這兩項操作。

當滿足以下任一條件時，將自動建立資源池：

* 儲存陣列中不存在儲存池，但有足夠多的類似磁碟機可以建立新的儲存池。
* 將新磁碟機新增至至少包含一個儲存池的儲存陣列。


儲存池中的每個磁碟機必須是相同類型的磁碟機（HDD 或 SSD），且容量相近。System Manager 將提示您完成以下任務：

* 如果這類磁碟機的數量足夠，請建立單一儲存池。
* 如果未指派的容量由不同類型的磁碟機組成，則建立多個儲存池。
* 如果儲存陣列中已定義儲存池，請將磁碟機新增至現有儲存池，並將相同磁碟機類型的新磁碟機新增至該儲存池。
* 將相同磁碟機類型的磁碟機新增至現有資源池，如果新磁碟機屬於不同的磁碟機類型，則使用其他磁碟機類型建立不同的資源池。




== 手動建立

當自動建立無法確定最佳組態時、您可能需要手動建立集區。發生這種情況的原因可能是下列其中一項：

* 新硬碟有可能新增至多個儲存池。
* 一個或多個新儲存池候選者可以使用機櫃遺失保護或抽屜遺失保護。
* 目前候選名單中的一個或多個無法維持其機櫃損失保護或抽屜損失保護狀態。


如果您的儲存陣列上有多個應用程式，並且您不希望它們爭用相同的磁碟機資源，那麼您可能需要手動建立儲存池。在這種情況下，您可以考慮為一個或多個應用程式手動建立較小的儲存池。您可以只指派一兩個磁碟區，而不是將工作負載指派給一個包含多個磁碟區的大型儲存池來分發資料。手動建立一個專用於特定應用程式工作負載的獨立儲存池，可提高儲存陣列操作的速度，並減少資源爭用。
