---
permalink: sm-storage/capacity-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity terms 
summary: 了解容量術語如何應用於您的儲存陣列。 
---
= 了解 SANtricity 軟體中的容量術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解容量術語如何應用於您的儲存陣列。



== 儲存物件

以下術語描述了可以與儲存陣列互動的不同類型的儲存物件。

[cols="25h,~"]
|===
| 儲存物件 | 說明 


 a| 
主機
 a| 
主機是向儲存陣列上的磁碟區發送 I/O 的伺服器。



 a| 
LUN
 a| 
邏輯單元號碼（LUN）是指派給主機用於存取磁碟區的位址空間的編號。磁碟區以 LUN 的形式作為容量呈現給主機。

每台主機都有自己的 LUN 位址空間。因此，同一個 LUN 可以被不同的主機用來存取不同的磁碟區。



 a| 
鏡像一致性群組
 a| 
鏡像一致性群組是容納一個或多個鏡像配對的容器。對於非同步鏡像操作，您必須建立鏡像一致性群組。



 a| 
鏡像磁碟區配對
 a| 
鏡像配對由兩個磁碟區組成，一個主要磁碟區和一個次要磁碟區。



 a| 
資源池
 a| 
儲存池是一組邏輯上分組的磁碟機。您可以使用儲存池建立一個或多個可供主機存取的磁碟區。（您可以從儲存池或磁碟區組建立磁碟區。）



 a| 
Snapshot 一致性群組
 a| 
快照一致性群組是指在建立快照映像時被視為一個整體的多個磁碟區的集合。每個磁碟區都有自己的快照映像，但所有映像都是在同一時間點建立的。



 a| 
快照群組
 a| 
快照群組是來自單一基礎磁碟區的快照映像集合。



 a| 
快照磁碟區
 a| 
快照磁碟區可讓主機存取快照映像中的資料。快照磁碟區擁有自己的保留容量，可儲存對基礎磁碟區所做的任何修改，而不會影響原始快照映像。



 a| 
磁碟區
 a| 
磁碟區是應用程式、資料庫和檔案系統儲存資料的容器。它是為主機存取儲存陣列上的儲存設備而建立的邏輯元件。



 a| 
磁碟區群組
 a| 
磁碟區群組是用來存放具有共用特徵的磁碟區的容器。磁碟區群組具有已定義的容量和 RAID 等級。您可以使用磁碟區群組建立一個或多個可供主機存取的磁碟區。（您可以從磁碟區群組或儲存池建立磁碟區。）

|===


== 儲存容量

以下術語說明儲存陣列上使用的不同容量類型。

[cols="25h,~"]
|===
| 容量類型 | 說明 


 a| 
已分配容量
 a| 
已分配容量是指從資源池或磁碟區群組中的磁碟機分配的實體容量。

您可以使用分配的容量來建立磁碟區和進行複製服務作業。



 a| 
可用容量
 a| 
可用容量是指資源池或磁碟區群組中尚未分配給磁碟區建立或複製服務作業和儲存物件的可用容量。



 a| 
資源池或磁碟區群組容量
 a| 
儲存池、磁碟區或磁碟區群組容量是指儲存陣列中已指派給儲存池或磁碟區群組的容量。此容量用於建立磁碟區，並滿足複製服務作業和儲存物件的各種容量需求。



 a| 
資源池無法使用的容量
 a| 
儲存池不可用容量是指由於磁碟機大小不符而無法使用的儲存池空間。



 a| 
保留容量
 a| 
保留容量是指在儲存池中預留的容量（磁碟機數量），用於支援潛在的磁碟機故障。



 a| 
報告容量
 a| 
已報告容量是指已報告給主機且主機可以存取的容量。



 a| 
預留容量
 a| 
預留容量是指用於任何複製服務作業和儲存物件的實體分配容量。主機無法直接讀取該容量。



 a| 
SSD 快取
 a| 
SSD Cache 是一組固態硬碟（SSD）驅動器，您可以將它們按邏輯分組到儲存陣列中。SSD Cache 功能會將最常存取的資料（「熱」資料）快取到低延遲的 SSD 磁碟機上，從而動態加速應用程式工作負載。



 a| 
未分配容量
 a| 
未分配容量是指儲存陣列中*尚未*指派給儲存池或磁碟區群組的空間。



 a| 
寫入容量
 a| 
已寫入容量是指已從分配給精簡磁碟區的保留容量中寫入的容量。

|===