---
permalink: sm-storage/capacity-for-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity, volumes, 
summary: 儲存陣列中的磁碟機為資料提供實體儲存容量。在開始儲存資料之前，必須將指派的容量配置成稱為儲存池或磁碟區群組的邏輯元件。您可以使用這些儲存物件來設定、儲存、維護和保存儲存陣列上的資料。 
---
= 如何在 SANtricity System Manager 中為磁碟區分配容量
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存陣列中的磁碟機為資料提供實體儲存容量。在開始儲存資料之前，必須將指派的容量配置成稱為儲存池或磁碟區群組的邏輯元件。您可以使用這些儲存物件來設定、儲存、維護和保存儲存陣列上的資料。



== 使用容量來建立和擴充磁碟區

您可以從資源池或磁碟區群組中未指派的容量或可用容量建立磁碟區。

* 從未分配容量建立磁碟區時，可以同時建立儲存池或磁碟區群組以及該磁碟區。
* 當您從可用容量建立磁碟區時、您是在已存在的儲存池或磁碟區群組上建立額外的磁碟區。


擴展卷容量後，您必須手動增加檔案系統大小以與之匹配。具體操作方法取決於您使用的檔案系統。有關詳細資訊，請參閱主機作業系統文件。



== 厚磁碟區和精簡磁碟區的容量類型

您可以建立厚磁碟區或精簡磁碟區。厚磁碟區的報告容量和已分配容量相同，但精簡磁碟區則不同。

* 對於厚磁碟區，報告的磁碟區容量等於已分配的實體儲存容量。必須存在全部實體儲存容量。實體分配的空間等於報告給主機的空間。
+
通常情況下，您會將厚磁碟區的報告容量設定為您認為該磁碟區將成長到的最大容量。厚磁碟區能夠為您的應用程式提供高效能和可預測的效能，這主要是因為所有使用者容量在建立時都會被預留和分配。

* 對於精簡磁碟區，報告容量是指報告給主機的容量，而分配容量是指目前分配給寫入資料的磁碟機空間量。
+
報告的容量可以大於儲存陣列上分配的容量。精簡磁碟區的大小可以根據增長進行調整，而無需考慮當前可用資產。



[NOTE]
====
SANtricity System Manager 不提供建立精簡磁碟區的選項。如果需要建立精簡磁碟區，請使用命令列介面（CLI）。

====


== 厚磁碟區的容量限制

厚磁碟區的最小容量為 1 MiB，最大容量由資源池或磁碟區群組中磁碟機的數量和容量決定。

在增加厚磁碟區的報告容量時，請牢記以下準則：

* 您可以指定最多三位小數（例如 65.375 GiB）。
* 容量必須小於（或等於）磁碟區群組中的最大可用容量。
+
建立磁碟區時，系統會預先分配一些額外容量用於動態段大小（DSS）遷移。DSS 遷移是軟體的功能，可讓您變更磁碟區的段大小。

* 某些主機作業系統支援大於 2 TiB 的磁碟區（最大報告容量由主機作業系統決定）。實際上，某些主機作業系統支援高達 128 TiB 的磁碟區。如需其他詳細資訊，請參閱您的主機作業系統文件。




== 精簡磁碟區的容量限制

您可以建立報告容量較大但分配容量相對較小的精簡磁碟區，這有利於提高儲存利用率和效率。精簡磁碟區有助於簡化儲存管理，因為分配容量可以隨著應用程式需求的變化而增加，而不會中斷應用程式，從而實現更高的儲存利用率。

除了已報告容量和已分配容量外，精簡磁碟區還包含已寫入容量。已寫入容量是指已從分配給精簡磁碟區的保留容量中寫入的容量。

下表列出了精簡磁碟區的容量限制。

[cols="3*"]
|===
| 容量類型 | 最小尺寸 | 最大大小 


 a| 
已報告
 a| 
32 MiB
 a| 
256 TiB



 a| 
已分配
 a| 
4 MiB
 a| 
64 TiB

|===
對於精簡磁碟區，如果已達到 256 TiB 的最大報告容量，則無法增加其容量。請確保精簡磁碟區的保留容量設定為大於最大報告容量的大小。

系統會根據分配容量限制自動擴充已分配容量。分配容量限制可讓您將精簡磁碟區的自動成長限制在報告容量以下。當寫入的資料量接近分配容量時，您可以變更分配容量限制。

若要變更已分配的容量限制，請選取功能表：Storage［Volumes > Thin Volume Monitoring 標籤 > Change Limit］。

由於 System Manager 在建立精簡磁碟區時不會分配全部容量，因此儲存池中可能存在可用容量不足的情況。空間不足會阻塞對儲存池的寫入操作，不僅會影響精簡磁碟區的寫入，還會影響其他需要使用儲存池容量的操作（例如，快照映像或快照磁碟區）。但是，您仍然可以從儲存池執行讀取操作。如果發生這種情況，您會收到警示臨界值警告。
