---
permalink: sm-storage/change-media-scan-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, media scan settings, volume 
summary: 媒體掃描是一項背景操作，它會掃描磁碟區中的所有資料和冗餘資訊。使用此選項可以啟用或停用一個或多個磁碟區的媒體掃描設定，或變更掃描持續時間。 
---
= 在 SANtricity System Manager 中變更磁碟區的媒體掃描設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
媒體掃描是一項背景操作，它會掃描磁碟區中的所有資料和冗餘資訊。使用此選項可以啟用或停用一個或多個磁碟區的媒體掃描設定，或變更掃描持續時間。

.開始之前
請理解以下內容：

* 媒體掃描會根據待掃描容量和掃描持續時間以恆定速率持續運作。後台掃描可能會因優先順序較高的後台任務（例如重建）而暫時中斷，但會以相同的恆定速率恢復。
* 只有當儲存陣列和該磁碟區都啟用了媒體掃描選項時，才會掃描該磁碟區。如果該磁碟區也啟用了冗餘檢查，則會檢查磁碟區中的冗餘資訊與資料的一致性（前提是該磁碟區具有冗餘）。預設情況下，每個磁碟區在建立時都會啟用冗餘檢查的媒體掃描。
* 如果在掃描過程中遇到無法復原的媒體錯誤，將使用冗餘資訊 （如果有） 修復資料。
+
例如，冗餘資訊存在於最優的 RAID 5 磁碟區中，或存在於最優的 RAID 6 磁碟區中，或存在於僅有一個磁碟機發生故障的 RAID 6 磁碟區中。如果無法使用冗餘資訊修復不可恢復的錯誤，則該資料區塊將被新增至不可讀扇區日誌。可修正和不可修正的媒體錯誤都會被記錄到事件日誌中。

+
如果冗餘檢查發現資料與冗餘資訊之間存在不一致，則會將其報告到事件日誌。




NOTE: 預設的媒體掃描週期設定為 120 天。

.關於此任務
媒體掃描可以偵測並修復應用程式不常讀取的磁碟區塊上的媒體錯誤。這可以防止磁碟機發生故障時資料遺失，因為故障磁碟機的資料會利用冗餘資訊和磁碟區群組或儲存池中其他磁碟機的資料進行重建。

您可以執行以下操作：

* 啟用或停用整個儲存陣列的背景媒體掃描
* 變更整個儲存陣列的掃描持續時間
* 啟用或停用一個或多個磁碟區的媒體掃描
* 啟用或停用一個或多個磁碟區的備援檢查


.步驟
. 選擇選單：Storage [ Volumes ]。
. 選擇任意磁碟區，然後選擇功能表：更多 [變更媒體掃描設定]。
+
此時會顯示「變更磁碟機媒體掃描設定」對話方塊。儲存陣列上的所有磁碟區都會顯示在此對話方塊中。

. 若要啟用媒體掃描，請勾選 *Scan media over the course of...* 核取方塊。
+
取消勾選媒體掃描核取方塊會暫停所有媒體掃描設定。

. 指定您希望媒體掃描執行的天數。
. 針對您要執行媒體掃描的每個磁碟區，選取 *Media Scan* 核取方塊。
+
System Manager 會為要執行媒體掃描的每個磁碟區啟用冗餘檢查選項。如果您不想對某些磁碟區執行冗餘檢查，請取消選取 *Redundancy Check* 核取方塊。

. 按一下 *Save* 。
+
System Manager 會根據您的選擇對背景媒體掃描套用變更。


