---
permalink: sm-storage/change-the-settings-for-a-snapshot-schedule.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, snapshot, schedule 
summary: 對於快照排程，您可以變更自動收集時間或收集頻率。 
---
= 在 SANtricity System Manager 中變更快照排程的設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於快照排程，您可以變更自動收集時間或收集頻率。

.關於此任務
您可以從現有的快照排程匯入設定，也可以根據需要修改設定。

由於快照計劃與快照組或快照一致性組相關聯，因此預留容量可能會受到計劃設定變更的影響。

.步驟
. 選擇選單：Storage [ Snapshots ]。
. 點選 *Schedules* 標籤。
. 選擇要變更的快照排程，然後按一下 *Edit* 。
+
Edit Snapshot Schedule 對話方塊隨即出現。

. 請執行下列其中一項操作：
+
** *使用先前從另一個快照物件定義的排程* -- 按一下 *Import Schedule* 、選取您要匯入排程的物件、然後按一下 *Import* 。
** *編輯排程設定* -- 請參閱下面的欄位詳細資訊。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
日 / 月
 a| 
請選擇下列其中一個選項：

*** *每日 / 每週* -- 選擇要同步快照的特定日期。如果您想要設定每日排程，您也可以選取右上角的 *Select all days* 核取方塊。
*** *每月 / 每年* -- 選擇要同步快照的月份。在 *On day(s)* 欄位中，輸入同步發生的日期。有效輸入為 *1* 至 *31* 以及 *Last*。您可以使用逗號或分號分隔多個日期。對於包含日期，請使用連字符。例如：1,3,4,10-15,Last。如果您需要按月同步，您也可以選取右上角的 *Select all months* 複選框。




 a| 
開始時間
 a| 
從下拉清單中選擇每日快照的新開始時間。選項以半小時為單位遞增。預設開始時間比目前時間提早半小時。



 a| 
時區
 a| 
從下拉清單中選擇儲存陣列的時區。



 a| 
每日快照數量

快照之間的時間
 a| 
選擇每天要建立的快照映像數量。

如果選擇多個還原點，請同時選擇還原點之間的時間間隔。對於多個還原點，請確保您有足夠的預留容量。



 a| 
開始日期

結束日期

沒有結束日期
 a| 
請輸入同步開始日期。同時請輸入結束日期，或選擇 *無結束日期*。

|===
====


. 按一下 *Save* 。

