---
permalink: sm-storage/change-host-port-identifiers-for-a-host.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host port, identifiers, host 
summary: 當您想要變更主機連接埠識別碼的使用者標籤、向主機新增新的主機連接埠識別碼或從主機中刪除主機連接埠識別碼時，請變更主機連接埠識別碼。 
---
= 在 SANtricity System Manager 中變更主機的主機連接埠識別碼
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您想要變更主機連接埠識別碼的使用者標籤、向主機新增新的主機連接埠識別碼或從主機中刪除主機連接埠識別碼時，請變更主機連接埠識別碼。

.關於此任務
變更主機連接埠識別碼時，請記住以下準則：

* *新增* -- 新增主機連接埠時，您將主機連接埠識別碼與您建立的用於連接儲存陣列的主機關聯。您可以使用主機匯流排適配器（HBA）公用程式手動輸入連接埠資訊。
* *編輯* -- 您可以編輯主機連接埠，將主機連接埠移動（關聯）到不同的主機。您可能已將主機匯流排適配器或 iSCSI 啟動器移至不同的主機，因此您必須將主機連接埠移動（關聯）至新主機。
* *Delete* -- 您可以刪除主機連接埠，以從主機移除（取消關聯）主機連接埠。


.步驟
. 選擇選單：Storage[Hosts]。
. 選擇要關聯連接埠的主機，然後按一下 *View/Edit Settings* 。
+
如果要向主機叢集中的某個主機新增連接埠，請展開該主機叢集並選擇所需的主機。無法在主機叢集層級新增連接埠。

+
此時會出現一個對話方塊，顯示目前的主機設定。

. 點選 *Host Ports* 標籤。
+
對話方塊顯示目前主機連接埠識別碼。

. 根據實際情況變更主機連接埠識別碼設定。
+
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
主機連接埠
 a| 
您可以選擇以下選項之一：

** *新增* -- 使用「新增」功能將新的主機連接埠識別碼關聯到主機。主機連接埠識別碼名稱的長度取決於主機介面技術。Fibre Channel 和 Infiniband 主機連接埠識別碼名稱必須為 16 個字元。iSCSI 主機連接埠識別碼名稱最多可包含 223 個字元。連接埠必須唯一。不允許使用已設定的連接埠號碼。
** *刪除* -- 使用 Delete 移除（取消關聯）主機連接埠識別碼。Delete 選項不會實際移除主機連接埠。此選項會移除主機連接埠與主機之間的關聯。除非您移除主機匯流排適配器或 iSCSI 發起程序，否則控制器仍會識別該主機連接埠。
+
[NOTE]
====
如果刪除主機連接埠識別碼，則該識別碼將不再與此主機關聯。此外，主機將失去透過此主機連接埠識別碼存取其所有已指派磁碟區的權限。

====




 a| 
標籤
 a| 
若要變更連接埠標籤名稱，請按一下 *Edit* 圖示（鉛筆）。連接埠標籤名稱必須唯一。不允許使用已配置的標籤名稱。



 a| 
CHAP 密碼
 a| 
僅適用於 iSCSI 主機。您可以設定或變更啟動器（iSCSI 主機）的 CHAP 密碼。

System Manager 使用 Challenge Handshake Authentication Protocol（CHAP）方法，該方法在初始連線期間驗證目標和啟動器的身分。驗證基於稱為 CHAP 密碼的共用安全金鑰。

|===
. 按一下 *Save* 。

