---
permalink: sm-storage/change-settings-for-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, volume 
summary: 您可以變更磁碟區的設定，例如磁碟區的名稱、主機指派、區段大小、修改優先順序、快取等等。 
---
= 在 SANtricity System Manager 中變更磁碟區的設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以變更磁碟區的設定，例如磁碟區的名稱、主機指派、區段大小、修改優先順序、快取等等。

.開始之前
您要變更的磁碟區處於最佳狀態。


NOTE: 變更磁碟區設定期間，某些操作可能無法使用。

.步驟
. 選擇選單：Storage [ Volumes ]。
. 選擇要變更的磁碟區，然後選擇 *View/Edit Settings* 。
+
Volume Settings 對話方塊隨即出現。您所選磁碟區的組態設定將顯示在此對話方塊中。

. 選擇 *Basic* 標籤以變更磁碟區的名稱和主機分配。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
Name
 a| 
顯示磁碟區名稱。當目前名稱不再有意義或適用時，請變更磁碟區名稱。



 a| 
容量
 a| 
顯示所選磁碟區的已報告容量和已分配容量。

對於厚磁碟區，報告容量和已分配容量相同；但對於精簡磁碟區，兩者則不同。對於厚磁碟區，實體分配空間等於報告給主機的空間。對於精簡磁碟區，報告容量是報告給主機的容量，而已分配容量是目前分配用於寫入資料的磁碟機空間量。



 a| 
儲存池 / Volume 群組
 a| 
顯示儲存池或磁碟區群組的名稱和 RAID 等級。指示儲存池或磁碟區群組是否具備安全功能以及是否已啟用安全功能。



 a| 
主機
 a| 
顯示磁碟區指派。您可以將磁碟區指派給主機或主機叢集，以便對其進行 I/O 操作存取。此指派授予主機或主機叢集對特定磁碟區或儲存陣列中多個磁碟區的存取權限。

** *Assigned to* -- 識別有權存取所選磁碟區的主機或主機叢集。
** *LUN* -- 邏輯單元號碼（LUN）是指派給主機用於存取磁碟區的位址空間的編號。磁碟區以 LUN 的形式呈現給主機，代表容量。每台主機都有自己的 LUN 位址空間。因此，不同的主機可以使用同一個 LUN 存取不同的磁碟區。
+

NOTE: 對於 NVMe 介面，此欄會顯示命名空間 ID。命名空間是格式化為區塊存取的 NVM 儲存設備。它類似於 SCSI 中的邏輯單元，與儲存陣列中的磁碟區相關。命名空間 ID 是 NVMe 控制器對此命名空間的唯一識別碼，可設定為 1 到 255 之間的值。它類似於 SCSI 中的邏輯單元編號（LUN）。





 a| 
識別符
 a| 
顯示所選磁碟區的識別碼。

** *全球識別碼（WWID）* -- 磁碟區的唯一十六進位識別碼。
** *擴充唯一識別碼 (EUI)* -- 磁碟區的 EUI-64 識別碼。
** *子系統識別碼（SSID）* -- 磁碟區的儲存陣列子系統識別碼。


|===
====
. 選擇 *Advanced* 選項卡，以變更池或磁碟區群組中磁碟區的其他組態設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
應用程式與工作負載資訊
 a| 
建立磁碟區時、您可以建立應用程式專屬的工作負載或其他工作負載。如果適用、所選磁碟區會顯示工作負載名稱、應用程式類型和磁碟區類型。

您可以視需要變更工作負載名稱。



 a| 
服務品質設定
 a| 
*永久停用資料保障* -- 此設定僅在磁碟區啟用資料保障 (DA) 時顯示。DA 會檢查並修正資料從控制器傳輸到磁碟機過程中可能出現的錯誤。使用此選項可永久停用所選磁碟區上的 DA。停用後，無法在此磁碟區重新啟用 DA。

*啟用預讀冗餘檢查* -- 此設定僅在磁碟區為厚磁碟區時顯示。預讀冗餘檢查會在每次讀取操作時確定磁碟區上的資料是否一致。如果控制器韌體偵測到資料不一致，則啟用此功能的磁碟區會傳回讀取錯誤。



 a| 
控制器所有權
 a| 
定義被指定為磁碟區的擁有者或主要控制器的控制器。

控制器所有權至關重要，應精心規劃。控制器之間的總 I/O 量應盡可能保持平衡。



 a| 
區段大小調整
 a| 
顯示區段大小設定，該設定僅對磁碟區群組中的磁碟區可見。您可以變更區段大小以最佳化效能。

*允許的區段大小轉換* -- System Manager 會決定允許的區段大小轉換。不適合從目前區段大小轉換的區段大小無法在下拉式清單中使用。允許的轉換通常是目前區段大小的兩倍或一半。例如、如果目前磁碟區區段大小為 32 KiB、則允許新的磁碟區區段大小為 16 KiB 或 64 KiB。

*啟用 SSD Cache 的磁碟區* -- 您可以為啟用 SSD Cache 的磁碟區指定 4-KiB 區段大小。請確保僅針對處理小區塊 I/O 作業（例如 16 KiB I/O 區塊大小或更小）的啟用 SSD Cache 的磁碟區選取 4-KiB 區段大小。如果針對處理大型區塊循序作業的啟用 SSD Cache 的磁碟區選取 4 KiB 作為區段大小、可能會影響效能。

*變更區段大小所需時間* -- 變更磁碟區區段大小所需時間取決於下列變數：

** 來自主機的 I/O 負載
** 磁碟區的修改優先順序
** 磁碟區群組中的磁碟機數量
** 磁碟機通道的數量
** 儲存陣列控制器的處理能力當您變更磁碟區的區段大小時、I/O 效能會受到影響、但您的資料仍可使用。




 a| 
修改優先順序
 a| 
顯示修改優先權設定，該設定僅對磁碟區群組中的磁碟區顯示。

修改優先權定義了相對於系統效能，指派給磁碟區修改作業的處理時間量。您可以提高磁碟區修改優先權，但這可能會影響系統效能。

移動滑桿以選擇優先順序。

*修改優先權率* -- 最低優先權率有利於系統效能，但修改作業耗時較長。最高優先權率有利於修改作業，但系統效能可能會受到影響。



 a| 
快取
 a| 
顯示快取設定，您可以變更此設定以影響磁碟區的整體 I/O 效能。



 a| 
SSD 快取
 a| 
顯示 SSD Cache 設定，您可以在相容的磁碟區上啟用此設定，以提高唯讀效能。如果磁碟區具有相同的 Drive Security 和 Data Assurance 功能，則它們相容。

*SSD Cache 功能使用單一或多個固態硬碟（SSD）來實現讀取快取*。由於 SSD 的讀取速度更快，應用程式效能得以提升。由於讀取快取位於儲存陣列中，因此使用該儲存陣列的所有應用程式均可共用快取。只需選擇要快取的磁碟區，快取即可自動動態運行。

|===
====
. 按一下 *Save* 。
+
System Manager 會根據您的選擇變更磁碟區的設定。



.完成後
選擇選單：首頁 [查看正在進行的操作] 以查看目前正在對所選磁碟區執行的變更操作的進度。
