---
permalink: sm-storage/change-configuration-settings-for-a-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configuration settings, volume group 
summary: 您可以編輯磁碟區群組的設定，包括其名稱和 RAID 層級。 
---
= 在 SANtricity System Manager 中變更磁碟區群組的組態設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以編輯磁碟區群組的設定，包括其名稱和 RAID 層級。

.開始之前
如果您要變更 RAID 等級以滿足存取磁碟區群組的應用程式的效能需求，請務必滿足以下先決條件：

* Volume 群組必須處於最佳狀態。
* 磁碟區群組必須有足夠的容量才能轉換為新的 RAID 層級。


.步驟
. 選擇選單：Storage [ Pools & Volume Groups ]。
. 選擇要編輯的磁碟區群組，然後按一下 *View/Edit Settings* 。
+
Volume Group Settings 對話方塊隨即出現。

. 選擇 *Settings* 選項卡，然後根據需要編輯磁碟區群組設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
Name
 a| 
您可以變更使用者提供的磁碟區群組名稱。必須為磁碟區群組指定名稱。



 a| 
RAID 層級
 a| 
從下拉式選單中選取新的 RAID 層級。

** *RAID 0 條帶化* -- 提供高效能，但不提供任何資料備援。如果磁碟區群組中的單一磁碟機故障，所有相關的磁碟區都會故障，且所有資料都會遺失。條帶化 RAID 群組會將兩個或多個磁碟機結合成一個大型邏輯磁碟機。
** *RAID 1 鏡像* -- 提供高效能和最佳資料可用性，適用於在企業或個人層級儲存敏感資料。透過自動將一個磁碟機的內容鏡像到鏡像配對中的第二個磁碟機來保護您的資料。可在單一磁碟機故障時提供保護。
** *RAID 10 條帶化/鏡像* -- 結合了 RAID 0（條帶化）和 RAID 1（鏡像）的特性，當選擇四個或更多硬碟時即可實現。RAID 10 適用於需要高效能和容錯能力的高容量事務處理應用程式，例如資料庫。
** *RAID 5* -- 最適合多使用者環境（例如資料庫或檔案系統儲存設備），在這些環境中，典型的 I/O 大小較小，且讀取活動的比例很高。
** *RAID 6* -- 最適合需要比 RAID 5 更高冗餘保護、但不需要高寫入效能的環境。


RAID 3 只能透過命令列介面（CLI）指派給磁碟區群組。

更改 RAID 等級後，操作一旦開始便無法取消。更改期間，您的資料仍然可用。



 a| 
最佳化容量（僅限 EF600 陣列）
 a| 
建立磁碟區群組時，系統會產生建議的最佳化容量，在可用容量、效能和磁碟機耗損壽命之間取得平衡。您可以調整此平衡：向右移動滑桿以犧牲可用容量為代價來獲得更佳的效能和磁碟機耗損壽命；或向左移動滑桿以犧牲效能和磁碟機耗損壽命為代價來增加可用容量。

當 SSD 磁碟機的部分容量未分配時，其使用壽命更長，最大寫入效能也更佳。對於與 Volume Group 相關聯的磁碟機，未分配容量包括群組的可用容量（未被 Volume 使用的容量）以及預留為額外最佳化容量的部分可用容量。額外的最佳化容量透過減少可用容量來確保最低最佳化容量等級，因此無法用於建立 Volume。

|===
====
. 按一下 *Save* 。
+
如果因 RAID 等級變更而導致容量減少、磁碟區冗餘遺失或機架/抽屜遺失保護失效，則會顯示確認對話方塊。選擇 *Yes* 繼續；否則，按一下 *No*。



.結果
如果變更磁碟區群組的 RAID 層級，System Manager 會變更組成該磁碟區群組的每個磁碟區的 RAID 層級。此作業期間效能可能會受到輕微影響。
