---
permalink: sm-storage/change-configuration-settings-for-a-pool.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configuration settings, pool 
summary: 您可以編輯儲存池的設定，包括其名稱、容量警示設定、修改優先順序和保留容量。 
---
= 在 SANtricity System Manager 中變更資源池的組態設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以編輯儲存池的設定，包括其名稱、容量警示設定、修改優先順序和保留容量。

.關於此任務
本任務說明如何變更資源池的組態設定。

[NOTE]
====
您無法透過 System Manager 介面變更儲存池的 RAID 等級。System Manager 會自動將儲存池配置為 RAID 6。

====
.步驟
. 選擇選單：Storage [ Pools & Volume Groups ]。
. 選擇要編輯的資源池，然後點擊 *View/Edit Settings* 。
+
出現 Pool Setting 對話框。

. 選擇 *Settings* 選項卡，然後根據需要編輯集區設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
Name
 a| 
您可以變更使用者提供的資源池名稱。必須指定資源池名稱。



 a| 
容量警報
 a| 
您可以設定當儲存池中的可用容量達到或超過指定閾值時發送警報通知。當儲存池中儲存的資料超過指定閾值時，System Manager 會傳送訊息，以便您有時間新增更多儲存空間或刪除不必要的物件。

警報會顯示在儀表板的通知區域，並且可以透過電子郵件和 SNMP trap 訊息從伺服器傳送給管理員。

您可以定義以下容量警報：

** *緊急警報* -- 當儲存池中的可用容量達到或超過指定臨界值時，此緊急警報會通知您。使用微調控制項來調整臨界值百分比。選取核取方塊以停用此通知。
** *提前預警* -- 此提前預警功能會在池中可用容量接近指定閾值時通知您。使用微調控制項來調整閾值百分比。選取核取方塊即可停用此通知。




 a| 
修改優先順序
 a| 
您可以根據系統效能指定儲存池中修改作業的優先順序層級。儲存池中修改作業的優先順序越高，作業完成速度越快，但可能會降低主機 I/O 效能。優先順序越低，作業耗時越長，但對主機 I/O 效能的影響越小。

您可以從五個優先權層級中進行選擇：最低、低、中、高和最高。優先權層級越高，對主機 I/O 和系統效能的影響就越大。

** *關鍵重建優先順序* -- 此滑桿可決定資料重建作業的優先順序，當多個磁碟機故障導致某些資料沒有備援、且額外的磁碟機故障可能導致資料遺失時。
** *降級重建優先順序* -- 此滑桿決定了在發生磁碟機故障但資料仍有備援且額外的磁碟機故障不會導致資料遺失時，資料重建作業的優先順序。
** *後台操作優先權* -- 此滑桿用於設定儲存池處於最佳狀態時後台操作的優先權。這些操作包括 Dynamic Volume Expansion (DVE)、Instant Availability Format (IAF) 以及將資料移轉到已更換或新增的磁碟機。




 a| 
保存容量（EF600 或 EF300 的「最佳化容量」）
 a| 
*保留容量* -- 您可以定義磁碟機數量，以決定儲存池上保留的容量，用於支援潛在的磁碟機故障。當磁碟機故障發生時，保留容量用於保存重建的資料。儲存池在資料重建過程中使用保留容量，而非磁碟區群組中使用的熱備援磁碟機。

使用微調控制項來調整磁碟機數量。根據磁碟機數量，儲存池中的保留容量會顯示在微調方塊旁。

請注意以下有關保留容量的資訊。

** 由於保留容量是從儲存池的總可用容量中扣除的，因此您預留的容量會影響可用於建立磁碟區的可用容量。如果您將保留容量指定為 0，則儲存池上的所有可用容量都將用於建立磁碟區。
** 如果降低保留容量，就可以增加可用於資源池磁碟區的容量。


*額外最佳化容量*（僅限 EF600 和 EF300 陣列）-- 建立儲存池時，系統會產生一個建議的最佳化容量，以平衡可用容量、效能和磁碟機耗損壽命。您可以透過向右移動滑桿來調整此平衡，以犧牲增加的可用容量為代價來獲得更好的效能和磁碟機耗損壽命，或向左移動滑桿來增加可用容量，以犧牲更好的效能和磁碟機耗損壽命為代價。

當 SSD 磁碟機的部分容量未分配時，其使用壽命更長，最大寫入效能也更佳。對於與儲存池關聯的磁碟機，未分配容量包括儲存池的保留容量、可用容量（未被磁碟區使用的容量）以及預留作為額外最佳化容量的一部分可用容量。額外的最佳化容量透過減少可用容量來確保最低最佳化容量，因此不能用於建立磁碟區。

|===
====
. 按一下 *Save* 。

