---
permalink: sm-storage/change-cache-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cache settings 
summary: 您可以變更讀取快取和寫入快取設定，以影響磁碟區的整體 I/O 效能。 
---
= 在 SANtricity System Manager 中變更磁碟區的快取設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以變更讀取快取和寫入快取設定，以影響磁碟區的整體 I/O 效能。

.關於此任務
變更磁碟區的快取設定時，請記住以下準則：

* 開啟「變更快取設定」對話方塊後，您可能會在選定的快取內容旁邊看到圖示。此圖示表示控制器已暫時暫停快取作業。
+
當新電池正在充電、控制器被移除或控制器偵測到快取大小不匹配時，可能會發生此操作。情況清除後，對話方塊中選擇的快取屬性將生效。如果所選快取屬性未生效，請聯絡技術支援。

* 您可以變更儲存陣列上單一磁碟區或多個磁碟區的快取設定。您可以同時變更所有標準磁碟區或所有精簡磁碟區的快取設定。


.步驟
. 選擇選單：Storage [ Volumes ]。
. 選擇任意磁碟區，然後選擇功能表：更多 [變更快取設定]。
+
「變更快取設定」對話方塊隨即出現。儲存陣列上的所有磁碟區都會顯示在此對話方塊中。

. 選擇 *Basic* 選項卡，以變更讀取快取和寫入快取的設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 快取設定 | 說明 


 a| 
讀取快取
 a| 
讀取快取是一個緩衝區，用於儲存從磁碟機讀取的資料。讀取操作所需的資料可能已經存在於快取中（來自先前的操作），這樣就無需存取磁碟機。資料會一直保留在讀取快取中，直到被刷新。



 a| 
寫入快取
 a| 
寫入快取是一個緩衝區，用於儲存來自主機但尚未寫入磁碟機的資料。資料會一直保留在寫入快取中，直到被寫入磁碟機為止。寫入快取可以提高 I/O 效能。


NOTE: 停用磁碟區的 *Write caching* 後，快取會自動刷新。

|===
====
. 選擇 *Advanced* 標籤以變更厚卷的進階設定。進階快取設定僅適用於厚卷。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 快取設定 | 說明 


 a| 
動態讀取快取預先擷取
 a| 
動態快取讀取預取允許控制器在從磁碟機讀取資料區塊到快取的同時，將額外的順序資料區塊複製到快取中。這種快取機制提高了後續資料請求能夠從快取中獲取所需資料的機率。動態快取讀取預取對於使用順序 I/O 的多媒體應用至關重要。預取到快取中的資料速率和資料量會根據主機讀取的速率和請求大小自動調整。隨機存取不會導致資料預取到快取中。停用讀取快取時，此功能無效。

對於精簡磁碟區，動態快取讀取預先擷取始終處於停用狀態，且無法變更。



 a| 
無需電池的寫入快取
 a| 
「無電池寫入快取」設定允許在電池缺失、故障、完全放電或未充滿電的情況下繼續寫入快取。通常不建議選擇「無電池寫入快取」，因為斷電時資料可能會遺失。通常情況下，控制器會暫時關閉寫入快取，直到電池充滿電或更換故障電池。


CAUTION: *資料可能遺失* -- 如果您選擇此選項且沒有通用電源供應器保護，則可能會遺失資料。此外，如果您沒有控制器電池並啟用 *Write caching without batteries* 選項，也可能會遺失資料。

僅在啟用寫入快取後，此設定才可用。此設定不適用於精簡磁碟區。



 a| 
帶鏡像的寫入快取
 a| 
寫入快取鏡像是指將寫入一個控制器快取記憶體的資料也寫入另一個控制器的快取記憶體。因此，如果一個控制器發生故障，另一個控制器可以完成所有未完成的寫入操作。寫入快取鏡像僅在啟用寫入快取且存在兩個控制器時可用。建立磁碟區時，寫入快取鏡像為預設設定。

僅在啟用寫入快取後，此設定才可用。此設定不適用於精簡磁碟區。

|===
====
. 點擊 *Save* 以變更快取設定。

