---
permalink: sm-storage/check-volume-redundancy.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, check, volume, redundancy 
summary: 在技術支援人員的指導下或按照 Recovery Guru 的指示，您可以檢查儲存池或磁碟區群組中某個磁碟區的備援情況，以確定該磁碟區上的資料是否一致。備援資料用於在儲存池或磁碟區群組中的某個磁碟機發生故障時，快速在替換磁碟機上重建資訊。 
---
= 在 SANtricity System Manager 中檢查磁碟區備援
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在技術支援的指導下或按照 Recovery Guru 的指示，您可以檢查資源池或磁碟區群組中某個磁碟區的備援情況，以確定該磁碟區上的資料是否一致。

冗餘資料用於在儲存池或磁碟區群組中的某個磁碟機發生故障時，快速在替換磁碟機上重建資訊。

.開始之前
* 池或磁碟區群組的狀態必須為 Optimal。
* 資源池或磁碟區群組不得有任何正在進行的磁碟區修改作業。
* 除了 RAID 0 之外，您可以檢查任何 RAID 等級的冗餘情況，因為 RAID 0 沒有資料冗餘。


[NOTE]
====
僅在 Recovery Guru 指示並在技術支援的指導下檢查磁碟區備援。

====
.關於此任務
此檢查一次只能針對一個儲存池或磁碟區群組執行。磁碟區備援檢查會執行下列動作：

* 掃描 RAID 3 磁碟區、RAID 5 磁碟區或 RAID 6 磁碟區中的資料區塊，並檢查每個資料區塊的冗餘資訊。（RAID 3 只能透過命令列介面指派給磁碟區群組。）
* 比較 RAID 1 鏡像磁碟機上的資料區塊。
* 如果控制器韌體確定資料不一致，則傳回備援錯誤。


[NOTE]
====
立即對相同儲存池或磁碟區群組執行備援檢查可能會導致錯誤。為避免此問題，請等待一到兩分鐘後再對相同儲存池或磁碟區群組執行另一次備援檢查。

====
.步驟
. 選擇選單：Storage [ Pools & Volume Groups ]。
. 選擇選單：非常規任務 [檢查磁碟區備援]。
+
Check Redundancy 對話框隨即出現。

. 選擇要檢查的磁碟區，然後輸入  `check` 以確認要執行此操作。
. 點選 *Check* 。
+
檢查磁碟區備援作業開始。資源池或磁碟區群組中的磁碟區會依序掃描，從對話方塊中表格的頂端開始。掃描每個磁碟區時會執行下列動作：

+
** 在磁碟區表中選擇磁碟區。
** 冗餘檢查的狀態顯示在 *Status* 欄位中。
** 檢查會在遇到任何媒體或同位錯誤時停止，然後報告錯誤。
+
.關於備援檢查狀態的更多資訊
[%collapsible]
====
[cols="25h,~"]
|===
| 狀態 | 說明 


 a| 
待處理
 a| 
這是要掃描的第一個磁碟區,您尚未按一下「開始」來啟動備援檢查。

或

正在對資源池或磁碟區群組中的其他磁碟區執行備援檢查作業。



 a| 
檢查
 a| 
該磁碟區正在進行備援檢查。



 a| 
已通過
 a| 
該磁碟區已通過備援檢查。備援資訊中未偵測到任何不一致之處。



 a| 
失敗
 a| 
該磁碟區未通過備援檢查。在備援資訊中偵測到不一致之處。



 a| 
媒體錯誤
 a| 
驅動器媒體已損壞，無法讀取。請按照 Recovery Guru 中的說明進行操作。



 a| 
奇偶校驗錯誤
 a| 
特定資料部分的同位不正確。同位錯誤可能非常嚴重，並可能導致資料永久遺失。

|===
====


. 檢查完資源池或磁碟區群組中的最後一個磁碟區後、按一下 *Done* 。

