---
permalink: sm-storage/comparison-between-thick-volumes-and-thin-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, comparison, thick volumes, thin volumes 
summary: 厚磁碟區始終採用完全配置，這表示在建立磁碟區時就分配了所有容量。精簡磁碟區始終採用精簡配置，這表示容量是在將資料寫入磁碟區時分配的。 
---
= 了解 SANtricity 軟體中的厚磁碟區和精簡磁碟區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
厚磁碟區始終採用完全配置，這表示在建立磁碟區時就分配了所有容量。精簡磁碟區始終採用精簡配置，這表示容量是在將資料寫入磁碟區時分配的。

[NOTE]
====
系統管理器不提供建立精簡磁碟區的選項。如果您想要建立精簡磁碟區、請使用命令列介面（CLI）。

====
[cols="25h,~"]
|===
| 磁碟區類型 | 說明 


 a| 
厚磁碟區
 a| 
* 厚磁碟區是從資源池或磁碟區群組建立的。
* 對於厚磁碟區，會預先提供大量儲存空間，以因應未來的儲存需求。
* 厚卷是指在建立磁碟區時，已在實體儲存上預先指派了磁碟區的全部大小。這種預先分配意味著，建立 100 GiB 的磁碟區實際上會佔用磁碟機上 100 GiB 的已指派容量。然而，部分空間可能未被使用，導致儲存容量利用率不足。
* 建立厚磁碟區時，請確保不要為單一磁碟區過度分配容量。為單一磁碟區過度分配容量可能會迅速耗盡系統中所有的實體儲存空間。
* 請注意，複製服務（快照映像、快照磁碟區、磁碟區副本和非同步鏡像）也需要儲存容量，因此請勿將所有容量都指派給厚磁碟區。空間不足可能會阻止對儲存池或磁碟區群組的寫入操作。如果發生這種情況，您將收到可用容量臨界值警示警告。




 a| 
精簡磁碟區
 a| 
* 精簡磁碟區只能從資源池建立，不能從磁碟區群組建立。
* 精簡磁碟區必須為 RAID 6。
* EF600/EF600C 或 EF300/EF300C 儲存系統不提供精簡磁碟區。
* 您必須使用 CLI 建立精簡磁碟區。
* 與厚磁碟區不同，精簡磁碟區所需的空間不會在建立期間配置，而是稍後視需要提供。
* 精簡磁碟區可讓您超額分配其大小。也就是說，您可以指派大於磁碟區大小的 LUN 大小。然後，您可以根據需要擴充磁碟區（如有必要，可在此過程中新增磁碟機），而無需擴充 LUN 的大小，因此也不會中斷使用者連線。
* 您可以使用精簡配置區塊空間回收（UNMAP）功能，透過主機發出的 SCSI UNMAP 指令回收儲存陣列上精簡配置磁碟區中的區塊空間。支援精簡配置的儲存陣列可以將回收的空間重新用於滿足同一儲存陣列中其他精簡配置磁碟區的分配請求，從而更好地報告磁碟空間消耗並更有效地利用資源。


|===


== 精簡磁碟區限制

精簡磁碟區支援與完整磁碟區相同的所有作業，但以下情況除外：

* 您無法變更精簡磁碟區的區段大小。
* 您無法為精簡磁碟區啟用預先讀取備援檢查。
* 在 Copy Volume 操作中，不能將精簡磁碟區用作目標磁碟區。
* 您只能在非同步鏡像對的主側變更精簡磁碟區的分配容量限制和警告臨界值。在主側對這些參數所做的任何變更都會自動傳播到從側。

