---
permalink: sm-storage/consolidate-volume-group-free-capacity.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, consolidate, free capacity, volume group 
summary: 使用「合併可用容量」選項可以合併所選磁碟區群組中現有的可用範圍。執行此操作後，您可以從磁碟區群組中的最大可用容量建立額外的磁碟區。 
---
= 在 SANtricity System Manager 中整合磁碟區群組的可用容量
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用「合併可用容量」選項可以合併所選磁碟區群組中現有的可用範圍。執行此操作後，您可以從磁碟區群組中的最大可用容量建立額外的磁碟區。

.開始之前
* 磁碟區群組必須至少包含一個可用容量區域。
* 磁碟區群組中的所有磁碟區都必須處於線上狀態且處於最佳狀態。
* 磁碟區修改作業不得正在進行中，例如變更磁碟區的區段大小。


.關於此任務
操作開始後無法取消。在合併操作期間，您的資料仍然可以存取。

您可以使用下列任一方法啟動「合併可用容量」對話方塊：

* 當偵測到磁碟區群組中至少有一個可用容量區域時，「合併可用容量」建議將顯示在首頁的通知區域中。按一下 *合併可用容量* 連結即可啟動對話方塊。
* 您也可以從 Pools & Volume Groups 頁面啟動 Consolidate Free Capacity 對話框，如下列任務所述。


.關於可用容量區域的更多資訊
[%collapsible]
====
可用容量區域是指刪除磁碟區或在建立磁碟區時未使用所有可用容量而產生的剩餘容量。在具有一個或多個可用容量區域的磁碟區群組中建立磁碟區時,該磁碟區的容量將限制為該磁碟區群組中最大的可用容量區域。例如,如果一個磁碟區群組總共有 15 GiB 的可用容量,而最大的可用容量區域為 10 GiB,則您可以建立的最大磁碟區大小為 10 GiB。

您可以整合磁碟區群組上的可用容量，以提升寫入效能。隨著主機寫入、修改和刪除檔案，您的磁碟區群組可用容量會隨著時間逐漸分散。最終，可用容量將不會位於單一連續區塊中，而是分散在磁碟區群組的各個小片段上。這會導致進一步的檔案分散，因為主機必須將新檔案寫入為片段，以便將其放入可用叢集的可用範圍內。

透過整合選定磁碟區群組的可用容量，您會發現主機寫入新檔案時檔案系統效能有所提升。整合過程也有助於防止將來新檔案出現碎片化。

====
.步驟
. 選擇選單：Storage [ Pools & Volume Groups ]。
. 選擇要合併的具有可用容量的磁碟區群組，然後選擇功能表：非常規任務 [合併磁碟區群組可用容量]。
+
此時會顯示「合併可用容量」對話方塊。

. 輸入  `consolidate` 以確認您要執行此操作。
. 點選 *Consolidate* 。
+
System Manager 開始將磁碟區群組的可用容量區域合併（重組）成一個連續的容量，以便進行後續的儲存組態作業。



.完成後
選擇選單：Home [ View Operations in Progress ] 以檢視 Consolidate Free Capacity 操作的進度。此操作可能需要較長時間，並可能影響系統效能。
