---
permalink: sm-storage/copy-volume-function.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy, volume, 
summary: 複製磁碟區功能可讓您透過在相同儲存陣列上建立兩個單獨的磁碟區（來源磁碟區和目標磁碟區），來建立磁碟區的某個時間點副本。 
---
= 了解 SANtricity System Manager 中的 Copy Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
複製磁碟區功能可讓您透過在相同儲存陣列上建立兩個單獨的磁碟區（來源磁碟區和目標磁碟區），來建立磁碟區的某個時間點副本。

此函數將來源磁碟區上的資料逐位元組複製到目標磁碟區，使目標磁碟區上的資料與來源磁碟區上的資料完全相同。



== 資料複製以便更方便地存取

當磁碟區的儲存需求變更時，您可以使用 Copy Volume 功能將資料從使用較小容量磁碟機的儲存池或磁碟區組複製到使用較大容量磁碟機的儲存池或磁碟區組。例如，您可以使用 Copy Volume 功能執行下列操作：

* 將資料移至容量更大的磁碟機。
* 更換為資料傳輸速率更高的磁碟機。
* 更換為採用新技術的磁碟機，以獲得更高的效能。
* 將精簡磁碟區變更為完整磁碟區。


複製來源磁碟區和目標磁碟區必須具有相同的報告主機可定址 / 邏輯區塊大小（磁區大小）。

報告的磁碟區區塊大小為：

* *原生區塊大小* – 磁碟區的區塊大小與磁碟機的區塊大小相符，可以是 512 或 4K。
* *模擬 512 區塊大小* - 磁碟機為 4K ，但報告的區塊大小為 512 。




== 將精簡磁碟區變更為完整磁碟區

如果要將精簡磁碟區變更為完整磁碟區，請使用 Copy Volume 作業來建立精簡磁碟區的複本。Copy Volume 作業的目標一律為完整磁碟區。

[NOTE]
====
系統管理器不提供建立精簡磁碟區的選項。如果您想要建立精簡磁碟區、請使用命令列介面（CLI）。

====


== 備份資料

Copy Volume 功能可讓您透過將資料從一個磁碟區複製到相同儲存陣列上的另一個磁碟區來備份磁碟區。您可以將目標磁碟區用作來源磁碟區的備份、用於系統測試，或備份到其他設備（例如磁帶機）。



== 將快照磁碟區資料還原到基礎磁碟區

如果需要將資料從關聯的 Snapshot Volume 還原到基礎 Volume，可以使用 Copy Volume 功能將資料從 Snapshot Volume 複製到基礎 Volume。您可以先建立 Snapshot Volume 上資料的 Volume 副本，然後將該資料複製到基礎 Volume。



== 來源和目標磁碟區

下表規定了 Copy Volume 功能可用作來源磁碟區和目標磁碟區的磁碟區類型。

[cols="1a,1a,1a,1a"]
|===
| 磁碟區類型 | 離線磁碟區複製來源磁碟區 | 線上磁碟區複本來源磁碟區 | 線上和離線目標磁碟區 


 a| 
資源池中的完整磁碟區
 a| 
是的
 a| 
是的
 a| 
是的



 a| 
磁碟區群組中的厚磁碟區
 a| 
是的
 a| 
是的
 a| 
是的



 a| 
精簡磁碟區
 a| 
是的^1^
 a| 
是的
 a| 
否



 a| 
快照磁碟區
 a| 
是的^2^
 a| 
否
 a| 
否



 a| 
快照基礎磁碟區
 a| 
是的
 a| 
是的
 a| 
否



 a| 
遠端鏡像主磁碟區
 a| 
是的^3^
 a| 
是的
 a| 
否

|===
^1^ 目標磁碟區的容量必須等於或大於精簡磁碟區報告的容量。

^2^ 在線上複製作業完成之前，您無法使用 Snapshot 磁碟區複本。

^3^ 如果來源磁碟區是主磁碟區，則目標磁碟區的容量必須等於或大於來源磁碟區的可用容量。
