---
permalink: sm-storage/copy-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy volume 
summary: 您可以將資料從相同儲存陣列中的一個磁碟區複製到另一個磁碟區，並建立來源磁碟區的實體、時間點複本（複製）。 
---
= 在 SANtricity System Manager 中複製磁碟區
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將資料從相同儲存陣列中的一個磁碟區複製到另一個磁碟區，並建立來源磁碟區的實體、時間點複本（複製）。

.開始之前
* 必須停止對來源磁碟區和目標磁碟區的所有 I/O 活動。
* 必須卸載來源磁碟區和目標磁碟區上的所有檔案系統。
* 如果您之前在複製磁碟區作業中使用過目標磁碟區，則您不再需要該資料或您已備份該資料。


.關於此任務
來源磁碟區是接收主機 I/O 並儲存應用程式資料的磁碟區。啟動 Copy Volume 時，來源磁碟區中的資料將完整複製到目標磁碟區。

目標 Volume 是一個標準 Volume ，用於保存來源 Volume 的資料副本。Copy Volume 操作完成後，目標 Volume 與來源 Volume 完全相同。目標 Volume 的容量必須等於或大於來源 Volume ；但是，它們的 RAID 等級可以不同。

.關於線上和離線副本的更多資訊
[%collapsible]
====
*線上複本*

線上複製會在儲存陣列中建立任意磁碟區的某個時間點的副本，同時在複製過程中仍可對磁碟區進行寫入操作。此功能透過建立磁碟區的快照並將該快照用作複製的實際來源磁碟區來實現。用於建立時間點映像的磁碟區稱為基礎磁碟區，它可以是儲存陣列中的標準磁碟區或精簡磁碟區。

* 離線副本 *

離線複製作業會從來源磁碟區讀取資料並複製到目標磁碟區，同時在複製進行期間暫停來源磁碟區的所有更新。暫停來源磁碟區的所有更新是為了防止目標磁碟區上出現時間順序不一致的情況。離線磁碟區複製關係存在於來源磁碟區和目標磁碟區之間。

====
[NOTE]
====
複製磁碟區作業會覆寫目標磁碟區上的資料，並使與目標磁碟區相關聯的所有快照磁碟區（如果存在）失效。

====
.步驟
. 選擇選單：Storage [ Volumes ]。
. 選擇要用作 Copy Volume 操作來源的磁碟區，然後選擇功能表：Copy Services [Copy volume]。
+
此時會顯示「複製磁碟區 - 選擇目標」對話方塊。

. 選擇要將資料複製到的目標磁碟區。
+
此對話方塊中顯示的表格列出所有符合條件的目標磁碟區。

. 使用滑桿設定 Copy Volume 操作的複製優先權。
+
複製優先順序決定了與服務 I/O 請求相比，用於完成 Copy Volume 操作的系統資源有多少。

+
.深入瞭解複製優先順序速率
[%collapsible]
====
有五種複製優先順序率：

** 最低
** 低
** 中
** 高
** 最高


如果複製優先權設定為最低，則優先執行 I/O 活動，複製磁碟區操作所需時間會更長。如果複製優先權設定為最高，則優先執行複製磁碟區操作，但可能會影響儲存陣列的 I/O 活動。

====
. 選擇要建立線上副本還是離線副本。若要建立線上副本，請選取 **在複製作業期間保持來源磁碟區上線** 核取方塊。
. 請執行下列其中一項操作：
+
** 若要執行 _online_ 複製操作，請點選 *Next* 繼續進入 *Reserve Capacity* 對話方塊。
** 若要執行 _offline_ 複製操作，請按一下 *Finish* 開始離線複製。


. 如果您選擇建立線上副本，請設定儲存線上副本的資料和其他資訊所需的預留容量，然後按一下 *Finish* 以開始建立線上副本。
+
磁碟區候選表僅顯示支援指定保留容量的候選磁碟區。保留容量是用於任何複製服務作業和儲存物件的實體分配容量。主機無法直接讀取。

+
請依照以下準則分配保留容量：

+
** 預留容量的預設設定為基本磁碟區容量的 40% ，通常這個容量就足夠了。
** 然而，預留容量會根據原始資料的變更次數而變化。儲存物件處於作用中狀態的時間越長，預留容量就應該越大。




.結果
System Manager 會將來源磁碟區中的所有資料複製到目標磁碟區。複製磁碟區操作完成後，目標磁碟區將自動對主機變成唯讀。

.完成後
選擇選單：Home [ View Operations in Progress ] 以查看 Copy Volume 操作的進度。此操作可能耗時較長，並可能影響系統效能。
