---
permalink: sm-storage/create-pool-manually.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, pool, manually 
summary: 如果「Pool Auto Configuration」功能無法提供滿足您需求的 pool，您可以手動建立 pool（從一組候選項目中）。 
---
= 在 SANtricity System Manager 中手動建立資源池
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果「Pool Auto Configuration」功能無法提供滿足您需求的 pool，您可以手動建立 pool（從一組候選項目中）。

儲存池提供必要的邏輯儲存容量，您可以從中建立個別磁碟區，然後用於託管應用程式。

.開始之前
* 您必須至少有 11 個相同類型的磁碟機（HDD 或 SSD）。
* 機架遺失保護要求組成儲存池的磁碟機位於至少六個不同的磁碟機架中，且單一磁碟機架中的磁碟機不得超過兩個。
* 抽屜遺失保護要求組成儲存池的磁碟機位於至少五個不同的抽屜中，並且儲存池包含來自每個抽屜的相同數量的磁碟機櫃。
* 配置 EF600 或 EF300 儲存陣列時，請確保每個控制器在前 12 個插槽和後 12 個插槽中分別擁有相同數量的磁碟機。此配置有助於控制器更有效地利用磁碟機端的 PCIe 匯流排。目前 System Manager 允許在建立磁碟區群組時透過進階功能選擇磁碟機。對於儲存池的建立，建議使用儲存陣列中的所有磁碟機。


.步驟
. 選擇選單：Storage [ Pools & Volume Groups ]。
. 點選選單：建立 [Pool]。
+
此時會出現「建立資源池」對話方塊。

. 輸入集區的名稱。
. *選用：* 如果您的儲存陣列中有多種類型的磁碟機，請選擇要使用的磁碟機類型。
+
結果表格列出了您可以建立的所有可能集區。

. 根據下列特徵選擇要使用的候選池，然後按一下 *Create* 。
+
[cols="25h,~"]
|===
| 特性 | 使用 


 a| 
可用容量
 a| 
顯示候選儲存池的可用容量（單位：GiB）。選擇容量符合應用程式儲存需求的候選儲存池。

保留（備用）容量也分佈在整個資源池中，不屬於可用容量的一部分。



 a| 
總磁碟機數
 a| 
顯示候選池中可用的磁碟機數量。

System Manager 會自動預留盡可能多的磁碟機作為保留容量（集區中每六個磁碟機，System Manager 會預留一個磁碟機作為保留容量）。

當磁碟機發生故障時，會使用保留容量來保存重建的資料。



 a| 
磁碟機區塊大小（僅限 EF300 和 EF600）
 a| 
顯示儲存池中各個磁碟機可寫入的區塊大小（磁區大小）。值可能包括：

** 512 -- 512 位元組磁區大小。
** 4K -- 4,096 位元組扇區大小。




 a| 
安全功能
 a| 
指示此資源池候選項目是否完全由具有安全功能的磁碟機組成，這些磁碟機可以是 Full Disk Encryption（FDE）磁碟機或 Federal Information Processing Standard（FIPS）磁碟機。

** 您可以使用 Drive Security 保護您的儲存池，但所有磁碟機都必須具備安全功能才能使用此功能。
** 如果要建立僅支援 FDE 的儲存池，請在「安全功能」欄位中尋找 *Yes - FDE*。如果要建立僅支援 FIPS 的儲存池，請尋找 *Yes - FIPS* 或 *Yes - FIPS (Mixed)*。「Mixed」表示混合使用了 140-2 和 140-3 等級的磁碟機。如果混合使用這些等級的磁碟機，請注意，儲存池將以較低的安全等級（140-2）運作。
** 您可以建立一個包含可能具備或不具備安全功能的磁碟機、或混合安全等級磁碟機的儲存池。如果儲存池中的磁碟機包含不具備安全功能的磁碟機，則無法將該儲存池設定為安全儲存。




 a| 
啟用安全功能？
 a| 
此選項用於啟用支援安全功能的磁碟機的 Drive Security 功能。如果儲存池支援安全功能且您已建立安全金鑰，則勾選此核取方塊即可啟用安全功能。

[NOTE]
====
啟用 Drive Security 後，唯一移除該功能的方法就是刪除儲存池並清除磁碟機。

====


 a| 
DA 功能
 a| 
指示此儲存池候選對像是否支援資料保障（DA）。DA 會檢查並修正資料從控制器傳輸到磁碟機過程中可能出現的錯誤。

如果所有磁碟機都支援 DA，則會啟用 DA。建立磁碟區後，可以透過選取功能表：Storage[Volumes > View/Edit Settings > Advanced > Permanently disable data assurance] 來停用 DA。如果磁碟區上的 DA 已停用，則無法重新啟用。



 a| 
資源配置功能（僅限 EF300 和 EF600）
 a| 
顯示此儲存池候選對象是否支援資源配置。資源配置是 EF300 和 EF600 儲存陣列的功能，它允許磁碟區立即投入使用，無需背景初始化程序。



 a| 
貨架損耗保護
 a| 
顯示是否有機櫃遺失保護。

機架遺失保護功能可確保在單一磁碟機架發生完全通訊中斷時、仍可存取資源池中磁碟區上的資料。



 a| 
抽屜遺失保護
 a| 
顯示是否提供抽屜遺失保護，此保護僅在使用包含抽屜的磁碟機櫃時提供。

抽屜遺失保護功能可確保在磁碟機櫃中的單一抽屜發生完全通訊中斷時，仍可存取資源池中磁碟區上的資料。



 a| 
支援的磁碟區區塊大小（僅限 EF300 和 EF600）
 a| 
顯示可為儲存池中的磁碟區建立的區塊大小：

** 512n -- 512 位元組原生。
** 512e -- 模擬 512 位元組。
** 4K -- 4,096 位元組。


|===

