---
permalink: sm-storage/create-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, volume, group 
summary: 您可以使用磁碟區群組建立一個或多個可供主機存取的磁碟區。磁碟區群組是一個容器，用於存放具有共享特徵（例如 RAID 等級和容量）的磁碟區。 
---
= 在 SANtricity System Manager 中建立磁碟區群組
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用磁碟區群組建立一個或多個可供主機存取的磁碟區。磁碟區群組是一個容器，用於存放具有共享特徵（例如 RAID 等級和容量）的磁碟區。

借助更大容量的磁碟機和跨控制器分配磁碟區的能力，為每個磁碟區群組建立多個磁碟區是充分利用儲存容量和保護資料的好方法。

.開始之前
在建立磁碟區群組之前，請先檢閱以下準則：

* 您至少需要一個未指派的磁碟機。
* 單一磁碟區群組中可包含的磁碟機數量是有限制的。這些限制會根據 RAID 層級而有所不同。
* 要啟用機架 / 抽屜遺失保護，您必須建立一個磁碟區群組，該磁碟區群組使用位於至少三個機架或抽屜中的磁碟機，除非您使用 RAID 1，其中兩個機架 / 抽屜是最低要求。
* 如果您使用的是 EF600 或 EF300 儲存陣列，並且規劃手動建立磁碟區群組，請確保每個控制器在前 12 個插槽和後 12 個插槽中分別可以存取相同數量的磁碟機。這種組態有助於控制器更有效地利用磁碟機端的 PCIe 匯流排。目前 System Manager 允許在建立磁碟區群組時，透過進階功能選擇磁碟機。
* 檢閱您選擇的 RAID 層級如何影響磁碟區群組的最終容量：
+
** 如果選擇 RAID 1，則必須一次新增兩個磁碟機，以確保選擇鏡像配對。選擇四個或更多磁碟機時，即可實現鏡像和條帶化（稱為 RAID 10 或 RAID 1+0）。
** 如果選擇 RAID 5、則必須至少新增三個磁碟機才能建立磁碟區群組。
** 如果選擇 RAID 6，則必須至少新增五個磁碟機才能建立磁碟區群組。




.步驟
. 選擇選單：Storage [ Pools & Volume Groups ]。
. 點選選單：建立 [Volume group]。
+
此時會顯示「建立 Volume Group」對話方塊。

. 輸入磁碟區群組的名稱。
. 選擇最符合您資料儲存和保護要求的 RAID 等級。
+
磁碟區群組候選表隨即出現，並且僅顯示支援所選 RAID 層級的候選磁碟區群組。

. *選用：* 如果您的儲存陣列中有多種類型的磁碟機，請選擇要使用的磁碟機類型。
+
磁碟區群組候選表隨即出現，並且僅顯示支援所選磁碟機類型和 RAID 層級的候選磁碟區群組。

. *選用：* 您可以選擇自動方法或手動方法來定義磁碟區群組中使用的磁碟機。自動方法是預設選項。
+
若要手動選擇磁碟機、請按一下 *Manually select drives (advanced)* 連結。按一下後、會變更為 *Automatically select drives (advanced)* 。

+
手動方法可讓您選擇構成磁碟區群組的特定磁碟機。您可以選擇特定的未指派磁碟機來取得所需的容量。如果儲存陣列包含不同媒體類型或不同介面類型的磁碟機，您只能選擇單一磁碟機類型的未設定容量來建立新的磁碟區群組。

+
[NOTE]
====
只有了解磁碟機備援和最佳磁碟機組態的專家才應該使用手動方法。

====
. 根據顯示的磁碟機特性，選擇要在磁碟區群組中使用的磁碟機，然後按一下 *Create* 。
+
顯示的磁碟機特性取決於您選擇的是自動方法還是手動方法。

+
.自動方法驅動特性
[%collapsible]
====
[cols="25h,~"]
|===
| 特性 | 使用 


 a| 
可用容量
 a| 
顯示可用容量（單位：GiB）。選擇容量符合應用程式儲存需求的磁碟區群組候選對象。



 a| 
總磁碟機數
 a| 
顯示此磁碟區群組可用的磁碟機數量。選取具有所需磁碟機數量的磁碟區群組候選項目。



 a| 
磁碟機區塊大小（僅限 EF300 和 EF600）
 a| 
顯示群組中各個磁碟機可寫入的區塊大小（磁區大小）。值可能包括：

** 512 -- 512 位元組磁區大小。
** 4K -- 4,096 位元組扇區大小。




 a| 
安全功能
 a| 
指示此磁碟區群組候選物件是否完全由具有安全功能的磁碟機組成，這些磁碟機可以是 Full Disk Encryption (FDE) 磁碟機或 Federal Information Processing Standard (FIPS) 磁碟機。

** 您可以使用 Drive Security 保護磁碟區群組，但所有磁碟機都必須具備安全功能才能使用此功能。
** 如果要建立僅支援 FDE 的磁碟區組，請在「安全功能」列中尋找 *Yes - FDE*。如果要建立僅支援 FIPS 的磁碟區組，請尋找 *Yes - FIPS* 或 *Yes - FIPS (Mixed)*。"Mixed" 表示混合使用了 140-2 和 140-3 等級的驅動器。如果混合使用這些等級的驅動器，請注意，磁碟區組將以較低的安全等級 (140-2) 運作。
** 您可以建立一個磁碟區群組，其中包含可能具備安全功能、也可能不具備安全功能或安全性等級混合的磁碟機。如果磁碟區群組中的磁碟機包含不具備安全功能的磁碟機，則無法將該磁碟區群組設定為安全磁碟區群組。




 a| 
啟用安全功能？
 a| 
此選項用於啟用支援安全功能的磁碟機的 Drive Security 功能。如果磁碟區群組支援安全功能且您已設定安全金鑰，則勾選此核取方塊即可啟用 Drive Security 功能。


NOTE: 啟用 Drive Security 後，唯一移除該功能的方法就是刪除磁碟區群組並擦除磁碟機。



 a| 
DA 功能
 a| 
指示此群組是否可使用資料保障 (DA)。資料保障 (DA) 會檢查並修正資料從控制器傳送到磁碟機過程中可能出現的錯誤。

如果要使用 DA，請選擇一個支援 DA 的磁碟區群組。（對於支援 DA 的磁碟機，在儲存池中建立的磁碟區會自動啟用 DA。）

磁碟區群組可以包含支援 DA 功能的磁碟機或不支援 DA 功能的磁碟機，但所有磁碟機都必須支援 DA 功能才能使用此功能。



 a| 
資源配置功能（僅限 EF300 和 EF600）
 a| 
顯示此群組是否支援 Resource Provisioning。Resource Provisioning 是 EF300 和 EF600 儲存陣列的功能，它允許磁碟區立即投入使用，無需後台初始化過程。



 a| 
貨架損耗保護
 a| 
顯示是否可使用磁碟櫃遺失保護。磁碟櫃遺失保護可確保在與磁碟櫃通訊完全中斷的情況下，仍能存取磁碟區群組中各磁碟區上的資料。



 a| 
抽屜遺失保護
 a| 
顯示抽屜遺失保護功能是否可用，此功能僅在您使用包含抽屜的磁碟機櫃時才可使用。抽屜遺失保護功能可確保在磁碟機櫃中的單一抽屜發生完全通訊中斷時，磁碟區群組中所有磁碟區的資料仍可存取。



 a| 
支援的磁碟區區塊大小（僅限 EF300 和 EF600）
 a| 
顯示可為群組中磁碟區建立的區塊大小：

** 512n -- 512 位元組原生。
** 512e -- 模擬 512 位元組。
** 4K -- 4,096 位元組。


|===
====
+
.手動方法驅動特性
[%collapsible]
====
[cols="25h,~"]
|===
| 特性 | 使用 


 a| 
媒體類型
 a| 
指示媒體類型。支援下列媒體類型：

** 硬碟
** 固態硬碟 (SSD)


磁碟區群組中的所有磁碟機都必須屬於相同的媒體類型（全部為 SSD 或全部為硬碟）。磁碟區群組不能混合使用媒體類型或介面類型。



 a| 
磁碟機區塊大小（僅限 EF300 和 EF600）
 a| 
顯示群組中各個磁碟機可寫入的區塊大小（磁區大小）。值可能包括：

** 512 -- 512 位元組磁區大小。
** 4K -- 4,096 位元組扇區大小。




 a| 
磁碟機容量
 a| 
表示磁碟機容量。

** 盡可能選擇容量與磁碟區群組中現有磁碟機容量相同的磁碟機。
** 如果必須添加容量較小的未分配磁碟機，請注意，磁碟區群組中每個磁碟機的可用容量都會減少。因此，磁碟機容量在整個磁碟區群組中是相同的。
** 如果您必須新增容量較大的未指派磁碟機，請注意，您新增的未指派磁碟機的可用容量會減少，以便與磁碟區群組中磁碟機的目前容量相符。




 a| 
紙匣
 a| 
指示磁碟機的托架位置。



 a| 
插槽
 a| 
指示磁碟機的插槽位置。



 a| 
轉速 (rpm)
 a| 
指示磁碟機的速度。



 a| 
邏輯磁區大小
 a| 
表示磁區大小和格式。



 a| 
安全功能
 a| 
指示此磁碟區群組候選物件是否完全由具有安全功能的磁碟機組成，這些磁碟機可以是 Full Disk Encryption (FDE) 磁碟機或 Federal Information Processing Standard (FIPS) 磁碟機。

** 您可以使用 Drive Security 保護磁碟區群組，但所有磁碟機都必須具備安全功能才能使用此功能。
** 如果要建立僅支援 FDE 的磁碟區組，請在「安全功能」列中尋找 *Yes - FDE*。如果要建立僅支援 FIPS 的磁碟區組，請尋找 *Yes - FIPS* 或 *Yes - FIPS (Mixed)*。"Mixed" 表示混合使用了 140-2 和 140-3 等級的驅動器。如果混合使用這些等級的驅動器，請注意，磁碟區組將以較低的安全等級 (140-2) 運作。
** 您可以建立一個磁碟區群組，其中包含可能具備安全功能、也可能不具備安全功能或安全性等級混合的磁碟機。如果磁碟區群組中的磁碟機包含不具備安全功能的磁碟機，則無法將該磁碟區群組設定為安全磁碟區群組。




 a| 
DA 功能
 a| 
指示此群組是否可使用資料保障（DA）。資料保障（DA）會檢查並修正資料透過控制器傳送到磁碟機時可能發生的錯誤。

如果要使用 DA，請選擇一個支援 DA 的磁碟區群組。（對於支援 DA 的磁碟機，在儲存池中建立的磁碟區會自動啟用 DA。）

磁碟區群組可以包含支援 DA 功能的磁碟機或不支援 DA 功能的磁碟機，但所有磁碟機都必須支援 DA 功能才能使用此功能。



 a| 
支援的磁碟區區塊大小（僅限 EF300 和 EF600）
 a| 
顯示可為群組中磁碟區建立的區塊大小：

** 512n -- 512 位元組原生。
** 512e -- 模擬 512 位元組。
** 4K -- 4,096 位元組。




 a| 
資源配置功能（僅限 EF300 和 EF600）
 a| 
顯示此群組是否支援 Resource Provisioning。Resource Provisioning 是 EF300 和 EF600 儲存陣列的功能，它允許磁碟區立即投入使用，無需後台初始化過程。

|===
====

