---
permalink: sm-storage/create-host-cluster.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, host, cluster 
summary: 當兩個或多個主機需要對同一磁碟區進行 I/O 存取時，您需要建立主機叢集。 
---
= 在 SANtricity System Manager 中建立主機叢集
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當兩個或多個主機需要對同一磁碟區進行 I/O 存取時，您需要建立主機叢集。

.關於此任務
建立主機叢集時，請牢記以下準則：

* 只有當有兩個或兩個以上主機可用於建立叢集時，此作業才會啟動。
* 主機叢集中的主機可以有不同的作業系統（異質）。
* 主機叢集中的 NVMe 主機無法與非 NVMe 主機混合。
* 若要建立啟用 Data Assurance (DA) 的磁碟區，您計劃使用的主機連線必須支援 DA。
+
如果儲存陣列中控制器上的任何主機連線不支援 DA，則關聯的主機無法存取啟用 DA 的磁碟區上的資料。

* 如果您選擇的名稱已被使用，則此操作不會成功。
* 名稱長度不能超過 30 個字元。


.步驟
. 選擇選單：Storage[Hosts]。
. 選擇選單：Create [ Host Cluster ]。
+
此時將顯示「建立主機叢集」對話方塊。

. 根據實際情況選擇主機叢集的設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
Name
 a| 
輸入新主機叢集的名稱。



 a| 
選擇要共享磁碟區存取的主機
 a| 
從下拉清單中選擇兩個或多個主機。清單中僅顯示尚未屬於任何主機叢集的主機。

|===
====
. 按一下 *Create* 。
+
如果所選主機連接到具有不同 Data Assurance (DA) 功能的介面類型，則會顯示一個對話框，提示主機叢集將無法使用 DA。此不可用狀態會阻止將啟用 DA 的磁碟區新增至主機叢集。選擇 *Yes* 繼續，或選擇 *No* 取消。

+
DA 可提高整個儲存系統的資料完整性。DA 使儲存陣列能夠檢查在主機和磁碟機之間移動資料時可能出現的錯誤。對新卷使用 DA 可確保偵測到任何錯誤。



.結果
新的主機叢集會顯示在表格中，指派的主機列在下方的行中。
