---
permalink: sm-storage/create-host-manually.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, host, manually 
summary: 對於無法自動發現的主機，您可以手動建立主機。建立主機是讓儲存陣列了解哪些主機已連接到它並允許對磁碟區進行 I/O 存取的必要步驟之一。 
---
= 在 SANtricity System Manager 中手動建立主機
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於無法自動發現的主機，您可以手動建立主機。建立主機是讓儲存陣列了解哪些主機已連接到它並允許對磁碟區進行 I/O 存取的必要步驟之一。

.關於此任務
建立主機時請牢記以下準則：

* 您必須定義與主機相關聯的主機識別碼連接埠。
* 請確保提供的名稱與主機指派的系統名稱相同。
* 如果您選擇的名稱已被使用，則此操作不會成功。
* 名稱長度不能超過 30 個字元。


.步驟
. 選擇選單：Storage[Hosts]。
. 點選選單：建立 [主機]。
+
Create Host 對話方塊隨即出現。

. 根據需要選擇主機的設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
Name
 a| 
輸入新主機的名稱。



 a| 
主機作業系統類型
 a| 
從下拉清單中選擇新主機上執行的作業系統。



 a| 
主機介面類型
 a| 
（選用）如果您的儲存陣列支援多種類型的主機介面，請選擇要使用的主機介面類型。



 a| 
主機連接埠
 a| 
請執行下列其中一項操作：

** *選擇 I/O 介面*
+
通常情況下，主機連接埠應該已經登入並顯示在下拉清單中。您可以從清單中選擇主機連接埠標識符。

** *手動新增*
+
如果清單中未顯示主機連接埠識別碼，則表示該主機連接埠尚未登入。可以使用 HBA 公用程式或 iSCSI 啟動器公用程式來尋找主機連接埠識別碼，並將其與主機建立關聯。

+
您可以手動輸入主機連接埠識別碼，或從公用程式將其複製 / 貼上（一次一個）至 *Host ports* 欄位。

+
您必須一次選擇一個主機連接埠識別碼並將其與主機建立關聯，但您可以繼續選擇與主機建立關聯的多個識別碼。每個識別碼都會顯示在 *Host ports* 欄位中。如有必要，您也可以選取識別碼旁邊的 *X* 來移除識別碼。





 a| 
CHAP 啟動器
 a| 
（選用）如果您選擇或手動輸入了帶有 iSCSI IQN 的主機連接埠、並且希望要求嘗試存取儲存陣列的主機使用 Challenge Handshake Authentication Protocol （ CHAP ）進行驗證、請選取 *CHAP initiator* 核取方塊。對於您選擇或手動輸入的每個 iSCSI 主機連接埠、請執行以下操作：

** 輸入與每個 iSCSI 主機啟動器上設定的 CHAP 密碼相同的 CHAP 密碼，用於 CHAP 驗證。如果您使用雙向 CHAP 驗證（雙向驗證可讓主機向儲存陣列驗證自身，並讓儲存陣列向主機驗證自身），則還必須在初始設定時或透過變更設定來設定儲存陣列的 CHAP 密碼。
** 如果不需要主機驗證，請將此欄位留空。


目前，System Manager 使用的唯一 iSCSI 驗證方法是 CHAP。

|===
====
. 按一下 *Create* 。


.結果
主機建立成功後，系統會為該主機配置的每個主機連接埠建立一個預設名稱 （使用者標籤）。

預設別名是 <``Hostname_Port Number``> 。例如，為建立的第一個連接埠的預設別名是  `host IPT is IPT_1` 。
