---
permalink: sm-storage/create-snapshot-image.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, snapshot, image 
summary: 您可以手動從基礎磁碟區或快照一致性群組建立快照映像。這也被稱為即時快照或即時映像。 
---
= 在 SANtricity System Manager 中建立快照映像
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以手動從基礎磁碟區或快照一致性群組建立快照映像。這也被稱為 _instant snapshot_ 或 _instant image_。

.開始之前
* 基礎磁碟區必須達到最佳狀態。
* 磁碟機必須處於最佳狀態。
* 快照群組不能被指定為「`reserved.`」
* 預留容量磁碟區必須與快照群組的關聯基礎磁碟區具有相同的 Data Assurance (DA) 設定。


.步驟
. 若要建立快照影像，請執行下列其中一項操作：
+
** 選擇選單：Storage[Volumes]。選擇物件（基本磁碟區或快照一致性群組），然後選擇選單：Copy Services[Create instant snapshot]。
** 選擇選單：Storage[Snapshots]。選擇 *Snapshot Images* 選項卡，然後選擇選單：Create[Instant snapshot]。
+
此時將顯示「建立快照映像」對話方塊。選擇物件（基礎磁碟區或快照一致性群組）、然後按一下 *Next* 。如果先前已為該磁碟區或快照一致性群組建立過快照映像、則系統會立即建立即時快照。否則、如果這是首次為該磁碟區或快照一致性群組建立快照映像、則會顯示「確認建立快照映像」對話方塊。



. 按一下 *Create* 以接受需要保留容量的通知，並繼續執行 Reserve Capacity 步驟。
+
此時會顯示「備用容量」對話方塊。

. 使用微調框調整容量百分比，然後按一下 *Next* 接受表格中反白顯示的候選磁碟區。
+
「編輯設定」對話方塊隨即出現。

. 根據需要選擇快照映像的設定，並確認您要執行此操作。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
*Snapshot 影像設定*



 a| 
Snapshot 影像限制
 a| 
如果您希望快照影像在達到指定數量後自動刪除，請選取此核取方塊；使用微調方塊變更此數量限制。如果您取消選取此核取方塊，則快照影像的建立數量將在 32 張後停止。



 a| 
*保留容量設定*



 a| 
有以下情況請通知我⋯
 a| 
使用微調框調整系統在快照群組的預留容量接近滿時發送警示通知的百分比點。

當快照群組的保留容量超過指定臨界值時，請使用提前通知來增加保留容量或刪除不必要的物件，以免剩餘空間耗盡。



 a| 
完全保留容量的原則
 a| 
請選擇以下其中一項原則：

** *清除最舊的 Snapshot 映像* -- 系統會自動清除 Snapshot 群組中最舊的 Snapshot 映像，從而釋放 Snapshot 映像保留容量，以便在群組內重複使用。
** *拒絕寫入基本磁碟區* -- 當預留容量達到其定義的最大百分比時，系統將拒絕任何觸發預留容量存取的基本磁碟區 I/O 寫入請求。


|===
====


.結果
* System Manager 會在「快照映像」表中顯示新的快照映像。此表按時間戳記和關聯的基準 Volume 或快照一致性群組列出新映像。
* 由於以下情況，快照建立可能會保持在擱置狀態：
+
** 包含此 Snapshot 映像的基礎磁碟區是非同步鏡射群組的成員。
** 基礎磁碟區目前正在進行同步作業。同步作業完成後，快照映像建立即會完成。



