---
permalink: sm-storage/create-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, snapshot, volume 
summary: 您可以建立快照磁碟區，以提供主機存取磁碟區或快照一致性群組的快照映像。您可以將快照磁碟區指定為唯讀或讀寫。 
---
= 在 SANtricity System Manager 中建立快照磁碟區
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立快照磁碟區，以提供主機存取磁碟區或快照一致性群組的快照映像。您可以將快照磁碟區指定為唯讀或讀寫。

.關於此任務
快照磁碟區建立序列可讓您從快照映像建立快照磁碟區，並提供在磁碟區為讀取 / 寫入時分配保留容量的選項。快照磁碟區可以指定為下列類型之一：

* 唯讀快照磁碟區可讓主機應用程式讀取快照映像中所含資料的複本，但無法修改快照映像。唯讀快照磁碟區沒有相關的保留容量。
* 讀寫快照磁碟區為主機應用程式提供快照映像中包含的資料副本的寫入權限。它擁有自己的預留容量，用於儲存主機應用程式對基礎磁碟區所做的任何後續修改，而不會影響引用的快照映像。


建立快照磁碟區的程序是一個多步驟程序。



== 步驟 1：檢閱快照磁碟區的成員

選擇基礎磁碟區的快照映像或快照一致性群組。如果選擇快照一致性群組快照映像，快照一致性群組的成員磁碟區會顯示以供檢視。

.步驟
. 選擇選單：Storage [ Snapshots ]。
. 選擇 *Snapshot Volumes* 選項卡。
. 選擇 *Create* 。
+
「建立快照磁碟區」對話方塊隨即出現。

. 選擇要轉換為快照磁碟區的快照映像（磁碟區或快照一致性群組），然後按一下 *Next* 。在 *Filter* 欄位中使用文字輸入來縮小清單範圍。
+
如果選擇的是 Snapshot 一致性群組 Snapshot 映像，則會顯示「檢視成員」對話方塊。

+
在「檢視成員」對話方塊中，檢視已選擇轉換為快照磁碟區的磁碟區清單，然後按一下 *Next* 。

. 前往 <<步驟 2：將 Snapshot 磁碟區指派給主機>>。




== 步驟 2：將 Snapshot 磁碟區指派給主機

選擇要指派給快照磁碟區的特定主機或主機叢集。此指派將授予主機或主機叢集對快照磁碟區的存取權限。如有需要，您可以稍後選擇指派主機。

.開始之前
* 「主機」頁面下存在有效的主機或主機叢集。
* 必須為主機定義主機連接埠識別碼。
* 在建立啟用 DA 的磁碟區之前，請確認您計劃使用的主機連線支援 Data Assurance (DA) 功能。如果儲存陣列中任何控制器上的主機連線不支援 DA，則關聯的主機將無法存取啟用 DA 的磁碟區上的資料。


.關於此任務
分配磁碟區時，請牢記以下準則：

* 主機的作業系統可以對主機能夠存取的磁碟區數量進行特定限制。
* 您可以為儲存陣列中的每個 Snapshot 磁碟區定義一個主機指派。
* 儲存陣列中的控制器之間共用已指派的磁碟區。
* 主機或主機叢集無法使用相同的邏輯單元號碼 (LUN) 兩次來存取快照磁碟區。您必須使用唯一的 LUN。


[NOTE]
====
如果嘗試將磁碟區指派給與主機叢集中主機已建立的指派衝突的主機叢集，則將磁碟區指派給主機將會失敗。

====
.步驟
. 在「指派給主機」對話方塊中，選擇要指派給新磁碟區的主機或主機叢集。如果要建立磁碟區而不指派主機，請從下拉式清單中選擇「稍後指派」。
. 選擇存取模式。請選擇以下其中一項：
+
** *讀取 / 寫入* -- 此選項為主機提供快照磁碟區的讀取 / 寫入存取權限，並且需要預留容量。
** *唯讀* -- 此選項為主機提供快照磁碟區的唯讀存取權限，且不需要保留容量。


. 按一下 *Next* ，然後執行下列其中一項作業：
+
** 如果您的快照磁碟區是讀取 / 寫入磁碟區，則會顯示「檢閱容量」對話方塊。前往 <<步驟 3：為 Snapshot Volume 保留容量>>。
** 如果您的快照磁碟區是唯讀的，則會顯示「編輯優先順序」對話方塊。轉到 <<步驟 4：編輯 Snapshot 磁碟區的設定>>。






== 步驟 3：為 Snapshot Volume 保留容量

將預留容量關聯到讀取 / 寫入快照磁碟區。System Manager 會根據基礎磁碟區或快照一致性群組的屬性建議磁碟區和容量。您可以接受建議的預留容量配置，也可以自訂已指派的儲存空間。

.關於此任務
您可以根據需要增加或減少快照磁碟區的預留容量。如果發現快照預留容量過大，您可以減少其大小，以釋放其他邏輯磁碟區所需的空間。

.步驟
. 使用微調框為快照磁碟區分配預留容量。
+
Volume Candidate 表僅顯示支援指定保留容量的候選項目。

+
執行下列其中一項動作：

+
** *接受預設設定*。
+
使用此建議選項，以預設設定為快照磁碟區分配保留容量。

** *配置您自己的預留容量設定，以滿足您的資料儲存需求*。
+
如果您變更預設保留容量設定，請按一下 *Refresh Candidates* 以重新整理您指定之保留容量的候選清單。

+
請依照以下準則分配保留容量。

+
*** 預留容量的預設設定為基本磁碟區容量的 40% ，通常這個容量就足夠了。
*** 所需容量會根據磁碟區的 I/O 寫入頻率和大小、以及快照映像收集的數量和持續時間而有所不同。




. *選用：* 如果您正在為快照一致性群組建立快照磁碟區，則「保留容量候選」表中會顯示「變更候選」選項。按一下 *Change candidate* 以選擇其他保留容量候選者。
. 點擊 *Next*，然後轉到 <<步驟 4：編輯 Snapshot 磁碟區的設定>>。




== 步驟 4：編輯 Snapshot 磁碟區的設定

變更快照磁碟區的設定，例如其名稱、快取、保留容量警示臨界值等。

.關於此任務
您可以將該磁碟區新增至固態硬碟（SSD）快取中，以提高唯讀效能。SSD 快取由一組 SSD 磁碟機組成，您在儲存陣列中將它們邏輯分組在一起。

.步驟
. 根據需要接受或變更 Snapshot Volume 的設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
*Snapshot 磁碟區設定*



 a| 
Name
 a| 
指定快照磁碟區的名稱。



 a| 
啟用 SSD 快取
 a| 
選擇此選項可在 SSD 上啟用唯讀快取。



 a| 
*保留容量設定*



 a| 
有以下情況請通知我⋯
 a| 
*僅對讀取 / 寫入快照磁碟區顯示*。

使用微調框調整系統在快照群組的預留容量接近滿時發送警示通知的百分比點。

當快照群組的保留容量超過指定臨界值時，請使用提前通知來增加保留容量或刪除不必要的物件，以免剩餘空間耗盡。

|===
====
. 檢閱快照磁碟區組態。按一下 *Back* 進行任何變更。
. 當您對快照磁碟區配置滿意後，按一下 *Finish*。

