---
permalink: sm-storage/create-pool-automatically.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, pool, automatically 
summary: 當 System Manager 偵測到儲存陣列中存在未指派的磁碟機時，會自動啟動儲存池建立。您可以使用自動建立儲存池功能，輕鬆地將儲存陣列中所有未指派的磁碟機配置到一個儲存池中，也可以將磁碟機新增至現有儲存池中。 
---
= 在 SANtricity System Manager 中自動建立資源池
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當 SANtricity System Manager 偵測到儲存陣列中存在未指派的磁碟機時，儲存池建立會自動啟動。您可以使用自動建立儲存池功能，輕鬆地將儲存陣列中所有未指派的磁碟機配置到一個儲存池中，也可以將磁碟機新增至現有儲存池中。

.開始之前
當滿足下列任一條件時，即可啟動 Pool Auto-Configuration 對話方塊：

* 已偵測到至少一個未指派的磁碟機，可以將其新增至具有類似磁碟機類型的現有儲存池中。
* 偵測到 11 個或更多未指派的磁碟機，可用於建立新資源池（如果由於磁碟機類型不同而無法新增至現有資源池）。


.關於此任務
請記住以下幾點：

* 當您為儲存陣列新增磁碟機時，System Manager 會自動偵測磁碟機，並根據磁碟機類型和目前組態提示您建立單一集區或多個集區。
* 如果先前已定義儲存池，System Manager 會自動提示您是否要將相容的磁碟機新增至現有儲存池。當新磁碟機新增至現有儲存池時，System Manager 會自動將資料重新分配至新容量，其中現在包含您新增的新磁碟機。
* 配置 EF600 或 EF300 儲存陣列時，請確保每個控制器在前 12 個插槽中可存取的磁碟機數量相同，在後 12 個插槽中可存取的磁碟機數量也相同。此組態有助於控制器更有效地使用兩個磁碟機端 PCIe 匯流排。


您可以使用下列任一方法啟動 Pool Auto-Configuration 對話方塊：

* 當偵測到未分配容量時，Pool Auto-Configuration 建議會出現在 Home 頁面的 Notification 區域中。按一下 *View Pool Auto-Configuration* 以啟動對話方塊。
* 您也可以從 Pools and Volume Groups 頁面啟動 Pool Auto-Configuration 對話框，如下列任務所述。


.步驟
. 選擇選單：Storage [ Pools & Volume Groups ]。
. 選擇選單：更多 [ 啟動池自動配置 ]。
+
結果表列出了新建立的儲存池、新增了磁碟機的現有儲存池，或兩者兼具。預設情況下，新建立的儲存池會以循序編號命名。

+
System Manager 執行下列工作：

+
** 如果存在足夠多的相同類型（HDD 或 SSD）且容量相近的磁碟機，則建立單一儲存池。
** 如果未指派的容量由不同類型的磁碟機組成，則會建立多個儲存池。
** 如果儲存陣列中已定義儲存池，並且您向該儲存池新增相同磁碟機類型的新磁碟機，則將磁碟機新增至現有儲存池。
** 將相同磁碟機類型的磁碟機新增至現有集區，如果新磁碟機屬於不同的磁碟機類型，則使用其他磁碟機類型建立不同的集區。


. 若要變更新集區的名稱，請按一下 *Edit* 圖示（鉛筆）。
. 若要查看集區的其他特性，請將游標停留在 *詳細資料* 圖示 （頁面） 上或觸碰該圖示。
+
會顯示有關磁碟機類型、安全功能、資料保證（DA）功能、機櫃遺失保護和抽屜遺失保護的資訊。

+
對於 EF600 和 EF300 儲存陣列，也會顯示資源配置和磁碟區區塊大小的設定。

. 點選 *Accept* 。

