---
permalink: sm-storage/create-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, volumes 
summary: 您可以建立磁碟區，為特定應用程式的工作負載增加儲存容量，並使建立的磁碟區對特定主機或主機叢集可見。此外，磁碟區建立順序提供選項，可為您要建立的每個磁碟區分配特定容量。 
---
= 在 SANtricity System Manager 中建立磁碟區
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立磁碟區，為特定應用程式的工作負載增加儲存容量，並使建立的磁碟區對特定主機或主機叢集可見。此外，磁碟區建立順序提供選項，可為您要建立的每個磁碟區分配特定容量。

.關於此任務
大多數應用程式類型預設使用使用者定義的磁碟區配置。某些應用程式類型在建立磁碟區時會套用智慧配置。例如，如果您要為 Microsoft Exchange 應用程式建立磁碟區，系統會詢問您需要多少個信箱、平均信箱容量需求為何，以及您需要多少個資料庫複本。System Manager 會使用這些資訊為您建立最佳磁碟區配置，您可以視需要進行編輯。

建立磁碟區的程序包含多個步驟。



== 步驟 1：選取磁碟區的主機

您可以建立磁碟區，為特定應用程式的工作負載增加儲存容量，並使建立的磁碟區對特定主機或主機叢集可見。此外，磁碟區建立順序提供選項，可為您要建立的每個磁碟區分配特定容量。

.開始之前
* 「主機」標籤下存在有效的主機或主機叢集。
* 已為主機定義主機連接埠識別碼。
* 在建立啟用 DA 的磁碟區之前，您計劃使用的主機連線必須支援 DA。如果儲存陣列中控制器上的任何主機連線不支援 DA，則關聯的主機將無法存取啟用 DA 的磁碟區上的資料。


.關於此任務
分配磁碟區時請牢記以下準則：

* 主機作業系統可能對主機可存取的磁碟區數量有特定限制。為特定主機建立磁碟區時，請務必注意此限制。
* 您可以為儲存陣列中的每個磁碟區定義一個指派。
* 儲存陣列中的控制器之間共用已指派的磁碟區。
* 主機或主機叢集不能使用相同的邏輯單元號碼（LUN）兩次來存取磁碟區。您必須使用唯一的 LUN。
* 如果要加快建立磁碟區的過程、可以跳過主機指派步驟、以便新建立的磁碟區在離線狀態下初始化。


[NOTE]
====
如果嘗試將磁碟區指派給與主機叢集中主機已建立的指派衝突的主機叢集，則將磁碟區指派給主機將會失敗。

====
.步驟
. 選擇選單：Storage [ Volumes ]。
. 選擇選單：建立 [Volume]。
+
此時會出現「建立磁碟區」對話方塊。

. 從下拉清單中，選擇要為其指派磁碟區的特定主機或主機叢集，或選擇稍後指派主機或主機叢集。
. 若要繼續為選定的主機或主機叢集建立磁碟區，請按一下 *Next*，然後前往 <<步驟 2：為磁碟區選擇工作負載>>。
+
此時將顯示「選擇工作負載」對話方塊。





== 步驟 2：為磁碟區選擇工作負載

選擇工作負載，即可針對特定應用程式（例如 Microsoft SQL Server、Microsoft Exchange、Video Surveillance 應用程式或 VMware）自訂儲存陣列配置。如果您要在此儲存陣列上使用的應用程式未列出，則可以選擇「Other application」。

.關於此任務
本任務說明如何為現有工作負載建立磁碟區。

* _當您使用特定於應用程式的工作負載建立磁碟區時_，系統可能會建議最佳化的磁碟區配置，以最大限度地減少應用程式工作負載 I/O 與應用程式執行個體其他流量之間的爭用。您可以使用「新增 / 編輯磁碟區」對話方塊檢視建議的磁碟區配置，並編輯、新增或刪除系統建議的磁碟區及其特性。
* _當您使用「其他」應用程式（或沒有特定磁碟區建立支援的應用程式）建立磁碟區時_，您可以使用「新增/編輯磁碟區」對話方塊手動指定磁碟區配置。


.步驟
. 請執行下列其中一項操作：
+
** 選擇 *為現有工作負載建立磁碟區* 選項，為現有工作負載建立磁碟區。
** 選擇 *Create a new workload* 選項，為支援的應用程式或「其他」應用程式定義新的工作負載。
+
*** 從下拉清單中選擇要為其建立新工作負載的應用程式名稱。
+
如果您打算在此儲存陣列上使用的應用程式未列出，請選擇「其他」條目之一。

*** 輸入要建立的工作負載的名稱。




. 按一下 *Next* 。
. 如果您的工作負載與受支援的應用程式類型相關聯，請輸入所要求的資訊；否則，請轉到 <<步驟 3：新增或編輯磁碟區>>。




== 步驟 3：新增或編輯磁碟區

System Manager 可能會根據您選擇的應用程式或工作負載建議磁碟區配置。此磁碟區配置會根據工作負載支援的應用程式類型進行最佳化。您可以接受建議的磁碟區配置，也可以根據需要進行編輯。如果您選擇了「其他」應用程式，則必須手動指定要建立的磁碟區及其特性。

.開始之前
* 資源池或磁碟區群組必須有足夠的可用容量。
* 一個磁碟區群組中允許的最大磁碟區數為 256 。
* 儲存池中允許的最大磁碟區數取決於儲存系統型號：
+
** 2,048 個磁碟區（EF600、EF600C 和 E5700 系列）
** 1,024 個磁碟區（EF300 和 EF300C）
** 512 個磁碟區（E4000 和 E2800 系列）


* 若要建立啟用 Data Assurance (DA) 的磁碟區，您計劃使用的主機連線必須支援 DA。
+
.選擇具有安全功能的資源池或磁碟區群組
[%collapsible]
====
如果要建立支援 DA 的磁碟區，請選擇支援 DA 的儲存池或磁碟區群組（在儲存池和磁碟區群組候選表中尋找「DA」旁的 *Yes*）。

資料存取 (DA) 功能在系統管理員中以儲存池和磁碟區群組層級顯示。DA 保護功能會檢查並修正資料從控制器傳輸到驅動器過程中可能出現的錯誤。為新磁碟區選擇支援 DA 功能的儲存池或磁碟區組，可確保偵測到並修正所有錯誤。

如果儲存陣列中控制器上的任何主機連線不支援 DA，則關聯的主機無法存取啟用 DA 的磁碟區上的資料。

====
* 若要建立啟用安全功能的磁碟區，必須為儲存陣列建立安全金鑰。
+
.選擇具有安全功能的資源池或磁碟區群組
[%collapsible]
====
如果要建立安全卷，請選擇具有安全功能的儲存池或磁碟區組（在儲存池和磁碟區組候選表中尋找「具有安全功能」旁的 *是*）。

磁碟機安全功能在 System Manager 中的儲存池和磁碟區群組層級顯示。具備安全功能的磁碟機可防止未經授權存取已從儲存陣列中實體移除的磁碟機上的資料。啟用安全功能的磁碟機使用唯一的_加密金鑰_，在寫入期間加密資料，在讀取期間解密資料。

儲存池或磁碟區群組可以包含具備安全功能的磁碟機和不具備安全功能的磁碟機，但所有磁碟機都必須具備安全功能才能使用其加密功能。

====
* 若要建立資源預置磁碟區，所有磁碟機都必須是具有已釋放或未寫入邏輯區塊錯誤（DULBE）選項的 NVMe 磁碟機。


.關於此任務
您可以從儲存池或磁碟區群組建立磁碟區。「新增/編輯磁碟區」對話方塊會顯示儲存陣列上所有符合資格的儲存池和磁碟區群組。對於每個符合資格的儲存池和磁碟區群組，會顯示可用磁碟機數量和總可用容量。

對於某些特定於應用程式的工作負載，每個符合條件的儲存池或磁碟區群組都會根據建議的磁碟區組態顯示建議容量，並以 GiB 為單位顯示剩餘可用容量。對於其他工作負載，建議容量會在您新增磁碟區至儲存池或磁碟區群組並指定報告容量時顯示。

.步驟
. 根據您選擇的是 Other 還是特定於應用程式的工作負載，選擇以下操作之一：
+
** *其他* -- 在要建立一個或多個磁碟區的每個池或磁碟區群組中按一下 *Add new volume*。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
磁碟區名稱
 a| 
在建立磁碟區的過程中，System Manager 會自動指派一個預設名稱給磁碟區。您可以接受預設名稱，或提供一個更具描述性的名稱，以說明該磁碟區所儲存的資料類型。



 a| 
報告容量
 a| 
定義新磁碟區的容量以及要使用的容量單位（MiB、GiB 或 TiB）。對於 Thick 磁碟區，最小容量為 1 MiB，最大容量取決於儲存池或磁碟區群組中磁碟機的數量和容量。

請記住，複製服務 （快照映像、快照磁碟區、磁碟區副本和遠端鏡像） 也需要儲存容量；因此，請勿將所有容量都指派給標準磁碟區。

儲存池中的容量以 4-GiB 或 8-GiB 為增量進行分配，具體取決於您的磁碟機類型。任何不是 4-GiB 或 8-GiB 倍數的容量都會被分配，但無法使用。為確保所有容量均可使用，請以 4-GiB 或 8-GiB 為增量指定容量。如果存在不可用容量，則只能透過增加磁碟區的容量來恢復這些容量。



 a| 
磁碟區區塊大小（僅限 EF300 和 EF600）
 a| 
顯示可為該磁碟區建立的區塊大小：

*** 512 -- 512 位元組
*** 4K -- 4,096 位元組




 a| 
區段大小
 a| 
顯示區段大小設定，該設定僅對磁碟區群組中的磁碟區可見。您可以變更區段大小以最佳化效能。

*允許的區段大小轉換* -- System Manager 會決定允許的區段大小轉換。不適合從目前區段大小轉換的區段大小無法在下拉式清單中使用。允許的轉換通常是目前區段大小的兩倍或一半。例如、如果目前磁碟區區段大小為 32 KiB、則允許新的磁碟區區段大小為 16 KiB 或 64 KiB。

*啟用 SSD Cache 的磁碟區* -- 您可以為啟用 SSD Cache 的磁碟區指定 4-KiB 區段大小。請確保僅針對處理小區塊 I/O 作業（例如 16 KiB I/O 區塊大小或更小）的啟用 SSD Cache 的磁碟區選取 4-KiB 區段大小。如果針對處理大型區塊循序作業的啟用 SSD Cache 的磁碟區選取 4 KiB 作為區段大小、可能會影響效能。

*變更區段大小所需時間* -- 變更磁碟區區段大小所需時間取決於下列變數：

*** 來自主機的 I/O 負載
*** 磁碟區的修改優先順序
*** 磁碟區群組中的磁碟機數量
*** 磁碟機通道的數量
*** 儲存陣列控制器的處理能力


變更磁碟區的區段大小時、I/O 效能會受到影響、但您的資料仍可使用。



 a| 
具備安全能力
 a| 
只有當資源池或磁碟區群組中的磁碟機具有安全功能時，「具有安全功能」旁邊才會顯示 *Yes*。

Drive Security 可防止未經授權存取已從儲存陣列中實體移除的磁碟機上的資料。僅當啟用 Drive Security 功能並為儲存陣列設定了安全金鑰時，此選項才可用。

儲存池或磁碟區群組可以包含具備安全功能的磁碟機和不具備安全功能的磁碟機，但所有磁碟機都必須具備安全功能才能使用其加密功能。



 a| 
DA
 a| 
只有當池或磁碟區組中的磁碟機支援 Data Assurance (DA) 時，「DA」旁邊才會顯示 *Yes*。

DA 可提高整個儲存系統的資料完整性。DA 使儲存陣列能夠檢查資料從控制器傳輸到磁碟機流程中可能出現的錯誤。對新磁碟區使用 DA 可確保偵測到任何錯誤。



 a| 
已配置資源（僅限 EF300 和 EF600）
 a| 
只有當磁碟機支援此選項時，「資源已配置」旁邊才會顯示 *Yes* 。Resource Provisioning 是 EF300 和 EF600 儲存陣列的功能，它允許磁碟區立即投入使用，無需後台初始化過程。

|===
====
** *特定於應用程式的工作負載* -- 按一下 *Next* 接受系統為所選工作負載建議的磁碟區和特性，或按一下 *Edit Volumes* 變更、新增或刪除系統為所選工作負載建議的磁碟區和特性。
+
.欄位詳細資料
[%collapsible]
====
[cols="1a,1a"]
|===
| 欄位 | 說明 


 a| 
磁碟區名稱
 a| 
在建立磁碟區的過程中，System Manager 會自動指派一個預設名稱給磁碟區。您可以接受預設名稱，或提供一個更具描述性的名稱，以說明該磁碟區所儲存的資料類型。



 a| 
報告容量
 a| 
定義新磁碟區的容量以及要使用的容量單位（MiB、GiB 或 TiB）。對於 Thick 磁碟區，最小容量為 1 MiB，最大容量取決於儲存池或磁碟區群組中磁碟機的數量和容量。

請記住，複製服務 （快照映像、快照磁碟區、磁碟區副本和遠端鏡像） 也需要儲存容量；因此，請勿將所有容量都指派給標準磁碟區。

儲存池中的容量以 4-GiB 或 8-GiB 為增量進行分配，具體取決於您的磁碟機類型。任何不是 4-GiB 或 8-GiB 倍數的容量都會被分配，但無法使用。為確保所有容量均可使用，請以 4-GiB 或 8-GiB 為增量指定容量。如果存在不可用容量，則只能透過增加磁碟區的容量來恢復這些容量。



 a| 
磁碟區類型
 a| 
磁碟區類型指示為特定應用程式工作負載建立的磁碟區類型。



 a| 
磁碟區區塊大小（僅限 EF300 和 EF600）
 a| 
顯示可為該磁碟區建立的區塊大小：

*** 512 -- 512 位元組
*** 4K -- 4,096 位元組




 a| 
區段大小
 a| 
顯示區段大小設定，該設定僅對磁碟區群組中的磁碟區可見。您可以變更區段大小以最佳化效能。

*允許的區段大小轉換* -- System Manager 會決定允許的區段大小轉換。不適合從目前區段大小轉換的區段大小無法在下拉式清單中使用。允許的轉換通常是目前區段大小的兩倍或一半。例如、如果目前磁碟區區段大小為 32 KiB、則允許新的磁碟區區段大小為 16 KiB 或 64 KiB。

*啟用 SSD Cache 的磁碟區* -- 您可以為啟用 SSD Cache 的磁碟區指定 4-KiB 區段大小。請確保僅針對處理小區塊 I/O 作業（例如 16 KiB I/O 區塊大小或更小）的啟用 SSD Cache 的磁碟區選取 4-KiB 區段大小。如果針對處理大型區塊循序作業的啟用 SSD Cache 的磁碟區選取 4 KiB 作為區段大小、可能會影響效能。

*變更區段大小所需時間* -- 變更磁碟區區段大小所需時間取決於下列變數：

*** 來自主機的 I/O 負載
*** 磁碟區的修改優先順序
*** 磁碟區群組中的磁碟機數量
*** 磁碟機通道的數量
*** 儲存陣列控制器的處理能力當您變更磁碟區的區段大小時、I/O 效能會受到影響、但您的資料仍可使用。




 a| 
具備安全能力
 a| 
只有當資源池或磁碟區群組中的磁碟機具有安全功能時，「具有安全功能」旁邊才會顯示 *Yes*。

磁碟機安全功能可防止未經授權存取已從儲存陣列中實體移除的磁碟機上的資料。僅當啟用磁碟機安全功能並為儲存陣列設定安全金鑰時，此選項才可用。

儲存池或磁碟區群組可以包含具備安全功能的磁碟機和不具備安全功能的磁碟機，但所有磁碟機都必須具備安全功能才能使用其加密功能。



 a| 
DA
 a| 
只有當池或磁碟區組中的磁碟機支援 Data Assurance (DA) 時，「DA」旁邊才會顯示 *Yes*。

DA 可提高整個儲存系統的資料完整性。DA 使儲存陣列能夠檢查資料從控制器傳輸到磁碟機流程中可能出現的錯誤。對新磁碟區使用 DA 可確保偵測到任何錯誤。



 a| 
已配置資源（僅限 EF300 和 EF600）
 a| 
只有當磁碟機支援此選項時，「Resource Provisioned」旁邊才會顯示 *Yes*。Resource Provisioning 是 EF300 和 EF600 儲存陣列的功能，它允許磁碟區立即投入使用，無需後台初始化過程。

|===
====


. 若要繼續為所選應用程式建立磁碟區序列，請按一下 *Next*，然後前往 <<步驟 4：檢閱磁碟區組態>>。




== 步驟 4：檢閱磁碟區組態

查看您計劃建立的磁碟區摘要，並進行任何必要的變更。

.步驟
. 請查看您要建立的磁碟區。按一下 *Back* 進行任何變更。
. 當您對磁碟區組態滿意後，按一下 *Finish* 。


.結果
System Manager 會在選定的資源池和 Volume 群組中建立新的 Volume，然後在「所有 Volume」表格中顯示新的 Volume。

.完成後
* 對應用程式主機進行必要的作業系統修改，以便應用程式可以使用該磁碟區。
* 執行作業系統專用公用程式（可從第三方供應商取得），然後執行 SMcli 指令 `-identifyDevices`，將磁碟區名稱與主機儲存陣列名稱關聯起來。
+
SMcli 可直接透過 SANtricity System Manager 取得。此下載版本的 SMcli 適用於 E4000、EF600、EF600C、EF300、EF300C、E5700、EF570、E2800 和 EF280 控制器。若要在 SANtricity System Manager 中下載 SMcli，請選擇 *Settings* > *System* 和 *Add-ons* > *Command Line Interface*。


