---
permalink: sm-storage/create-snapshot-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, snapshot, consistency group 
summary: 為了確保擁有一致的副本，您可以建立一組稱為 Snapshot 一致性群組的多個磁碟區。 
---
= 在 SANtricity System Manager 中建立快照一致性群組
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了確保擁有一致的副本，您可以建立一組稱為 _snapshot consistency group_ 的多個磁碟區。

此群組允許您同時建立所有磁碟區的快照映像，以確保一致性。屬於快照一致性群組的每個磁碟區稱為 _成員磁碟區_。將磁碟區新增至快照一致性群組時，系統會自動建立與該成員磁碟區對應的新快照群組。

.關於此任務
快照一致性群組建立順序可讓您為該群組選擇成員磁碟區，並為成員磁碟區指派容量。

建立快照一致性群組的程序包含多個步驟。



== 步驟 1：將成員新增至 Snapshot 一致性群組

選擇成員以指定構成快照一致性群組的磁碟區集合。對快照一致性群組執行的任何操作都會統一應用於所選成員磁碟區。

.開始之前
成員磁碟區必須為最佳狀態。

.步驟
. 選擇選單：Storage [ Snapshots ]。
. 按一下 *Snapshot Consistency Groups* 標籤。
. 選擇選單：建立 [Snapshot 一致性群組]。
+
Create Snapshot Consistency Group 對話方塊隨即出現。

. 選擇要新增至快照一致性群組成員磁碟區的磁碟區。
. 點擊 *Next*，然後轉到 <<步驟 2 ：為快照一致性群組保留容量>>。




== 步驟 2 ：為快照一致性群組保留容量

將預留容量關聯到快照一致性群組。System Manager 會根據快照一致性群組的屬性建議磁碟區和容量。您可以接受建議的預留容量配置，也可以自訂已指派的儲存空間。

.關於此任務
在「預留容量」對話方塊中，磁碟區候選表僅顯示支援指定預留容量的候選磁碟區。預留容量是指用於任何複製服務作業和儲存物件的實體分配容量。主機無法直接讀取該容量。

.步驟
. 使用微調框為快照一致性群組分配保留容量。執行下列其中一項動作：
+
** *接受預設設定*。
+
使用此建議選項，以預設設定為每個成員磁碟區分配保留容量。

** *分配您自己的預留容量設定，以滿足您的資料儲存需求。*
+
請依照以下準則分配保留容量。

+
*** 預留容量的預設值為基本磁碟區容量的 40%。通常這個容量就足夠了。
*** 所需容量會根據磁碟區的 I/O 寫入頻率和大小、以及快照映像收集的數量和持續時間而有所不同。




. *選用：* 如果您變更預設保留容量設定，請按一下 *重新整理候選項目* 以重新整理您指定之保留容量的候選項目清單。
. 點擊 *Next*，然後轉到 <<步驟 3：編輯 Snapshot 一致性群組的設定>>。




== 步驟 3：編輯 Snapshot 一致性群組的設定

接受或選擇快照一致性群組的自動刪除設定和保留容量警示臨界值。

.關於此任務
快照一致性群組建立順序可讓您為該群組選擇成員磁碟區，並為成員磁碟區指派容量。

.步驟
. 根據需要接受或變更 Snapshot 一致性群組的預設設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
*Snapshot 一致性群組設定*



 a| 
Name
 a| 
指定 Snapshot 一致性群組的名稱。



 a| 
啟用自動刪除快照影像功能時…
 a| 
如果您希望快照影像在達到指定數量後自動刪除，請選取此核取方塊；使用微調方塊變更此數量限制。如果您取消選取此核取方塊，則快照影像的建立數量將在 32 張後停止。



 a| 
*保留容量設定*



 a| 
有以下情況請通知我⋯
 a| 
使用微調框調整系統在快照一致性群組的預留容量接近滿時發送警示通知的百分比點。

當快照一致性群組的保留容量超過指定臨界值時，請利用提前通知來增加保留容量或刪除不必要的物件，以免剩餘空間耗盡。



 a| 
完全保留容量的原則
 a| 
請選擇以下其中一項原則：

** *清除最舊的 Snapshot 映像* -- 系統會自動清除 Snapshot 一致性群組中最舊的 Snapshot 映像，從而釋放 Snapshot 映像保留容量，以便在群組內重複使用。
** *拒絕寫入基本磁碟區* -- 當預留容量達到其定義的最大百分比時，系統將拒絕任何觸發預留容量存取的基本磁碟區 I/O 寫入請求。


|===
====
. 在您對快照一致性群組組態感到滿意後，請按一下 *Finish* 。

