---
permalink: sm-storage/faq-pools-volume-groups.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= SANtricity System Manager 的資源池和磁碟區群組常見問題集
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 什麼是磁碟區群組？

磁碟區群組是用來存放具有共用特徵的磁碟區的容器。磁碟區群組具有已定義的容量和 RAID 等級。您可以使用磁碟區群組建立一個或多個可供主機存取的磁碟區。（您可以從磁碟區群組或儲存池建立磁碟區。）



== 什麼是資源池？

儲存池是一組邏輯上分組的磁碟機。您可以使用儲存池建立一個或多個可供主機存取的磁碟區。（您可以從儲存池或磁碟區組建立磁碟區。）

儲存池可以免去管理員監控每台主機儲存空間使用情況的麻煩，從而判斷何時可能耗盡儲存空間，並避免傳統的磁碟調整大小停機。當儲存池接近耗盡時，可以無中斷地在其中新增額外的磁碟機，容量增長對主機完全透明。

利用資料池，資料會自動重新分配以維持平衡。透過在資料池中分配同位元檢查資訊和備用容量，資料池中的每個磁碟機都可以用於重建故障磁碟機。這種方法不使用專用的熱備援磁碟機；而是在整個資料池中保留保留（備用）容量。磁碟機故障時，會讀取其他磁碟機上的區段以重新建立資料。然後選擇新的磁碟機來寫入故障磁碟機上的每個區段，以維持磁碟機之間的資料分佈。



== 什麼是預留容量？

預留容量是實體配置的容量，用於儲存複製服務物件（例如 Snapshot 映像、一致性群組成員磁碟區和鏡像配對磁碟區）的資料。

與複製服務作業相關聯的保留容量磁碟區位於儲存池或磁碟區群組中。您可以從儲存池或磁碟區群組建立保留容量。



== 什麼是 FDE/FIPS 安全性？

FDE/FIPS 安全性指的是具備安全功能的磁碟機，它使用唯一的加密金鑰在寫入時加密資料，在讀取時解密資料。這些具備安全功能的磁碟機可以防止未經授權存取已從儲存陣列中實體移除的磁碟機上的資料。

具備安全功能的磁碟機可以是全磁碟加密（FDE）磁碟機或聯邦資訊處理標準（FIPS）磁碟機。FIPS 磁碟機已通過認證測試。

[NOTE]
====
對於需要 FIPS 支援的磁碟區，請僅使用 FIPS 磁碟機。在磁碟區群組或儲存池中混合使用 FIPS 和 FDE 磁碟機會導致所有磁碟機被視為 FDE 磁碟機。此外，FDE 磁碟機無法新增至全部為 FIPS 的磁碟區群組或儲存池中，也不能用作備用磁碟機。

====


== 什麼是備援檢查？

冗餘檢查用於確定儲存池或磁碟區群組中某個磁碟區上的資料是否一致。如果儲存池或磁碟區群組中的某個磁碟機發生故障,則冗餘資料可用於在替換磁碟機上快速重建資訊。

此檢查一次只能針對一個儲存池或磁碟區群組執行。磁碟區備援檢查會執行下列動作：

* 掃描 RAID 3 磁碟區、RAID 5 磁碟區或 RAID 6 磁碟區中的資料區塊，然後檢查每個資料區塊的冗餘資訊。（RAID 3 只能透過命令列介面指派給磁碟區群組。）
* 比較 RAID 1 鏡像磁碟機上的資料區塊。
* 如果控制器韌體判定資料不一致，則傳回備援錯誤。


[NOTE]
====
立即對相同儲存池或磁碟區群組執行備援檢查可能會導致錯誤。為避免此問題，請等待一到兩分鐘後再對相同儲存池或磁碟區群組執行另一次備援檢查。

====


== 池和磁碟區群組有什麼區別？

資源池與磁碟區群組類似，但有以下差異。

* 儲存池中的資料會隨機儲存在儲存池中的所有磁碟機上，與磁碟區群組中儲存在同一組磁碟機上的資料不同。
* 當磁碟機發生故障時，儲存池的效能降低幅度較小，重建所需的時間也較短。
* 儲存池具有內建的保留容量；因此不需要專用的熱備援磁碟機。
* 儲存池允許將大量磁碟機分組。
* 儲存池不需要指定 RAID 等級。




== 為什麼我要手動配置儲存池？

以下範例說明了為什麼需要手動設定儲存池。

* 如果您的儲存陣列上有多個應用程式，並且不希望它們爭用相同的磁碟機資源，您可以考慮為一個或多個應用程式手動建立一個較小的資源池。
+
您可以只指派一兩個磁碟區，而不是將工作負載指派給一個包含多個磁碟區的大型儲存池來分發資料。手動建立一個專用於特定應用程式工作負載的獨立儲存池，可加快儲存陣列操作的速度，並減少資源爭用。

+
若要手動建立儲存池：選取 *Storage*，然後選取 *Pools & Volume Groups*。從 All Capacity 標籤，按一下 menu:Create[Pool]。

* 如果存在多個相同磁碟機類型的儲存池，則會顯示一則訊息，指出 System Manager 無法自動為儲存池建議磁碟機。但是，您可以手動將磁碟機新增至現有儲存池。
+
若要手動為現有池新增磁碟機：從「池和磁碟區組」頁面，選擇池，然後按一下 *新增容量*。





== 為什麼容量警示很重要？

容量警報會在需要向儲存池新增磁碟機時發出。儲存池需要足夠的可用容量才能成功執行儲存陣列操作。您可以透過配置 SANtricity System Manager，使其在儲存池的可用容量達到或超過指定百分比時發送警報，從而防止這些操作中斷。

您可以在建立儲存池時設定此百分比，可以使用 *Pool auto-configuration* 選項或 *Create pool* 選項。如果您選擇自動選項，系統會自動使用預設設定來確定何時接收警示通知。如果您選擇手動建立儲存池，則可以設定警示通知設定；或者，如果您願意，也可以接受預設設定。您稍後可以在 menu:Settings[Alerts] 中調整這些設定。

[NOTE]
====
當資源池中的可用容量達到指定百分比時，系統會使用您在警示組態中指定的方法傳送警示通知。

====


== 為什麼我無法增加保留容量？

如果您已在所有可用容量上建立磁碟區，則可能無法增加保留容量。

保留容量是指在儲存池中預留的容量（磁碟機數量），用於支援潛在的磁碟機故障。建立儲存池時，系統會根據儲存池中的磁碟機數量自動預留預設的保留容量。如果您已在所有可用容量上建立磁碟區，則無法增加保留容量，除非透過新增磁碟機或刪除磁碟區來增加儲存池的容量。

您可以從 *Pools & Volume Groups* 變更保留容量。選取您要編輯的儲存池。按一下 *View/Edit Settings* ，然後選取 *Settings* 標籤。

[NOTE]
====
保留容量以磁碟機數量來指定，即使實際保留容量分佈在資源池中的各個磁碟機上。

====


== 我可以從儲存池中移除的磁碟機數量有限制嗎？

SANtricity System Manager 會設定您可以從資源池移除的磁碟機數量限制。

* 您無法將資源池中的磁碟機數量減少到少於 11 個磁碟機。
* 如果儲存池中沒有足夠的可用容量來容納從已移除磁碟機重新分配到儲存池中其餘磁碟機的資料，則無法移除磁碟機。
* 您一次最多可以移除 60 個磁碟機。如果選擇超過 60 個磁碟機、「移除磁碟機」選項將會停用。如果需要移除超過 60 個磁碟機、請重複執行「移除磁碟機」作業。




== 驅動器支援哪些媒體類型？

支援以下媒體類型：硬碟（HDD）和固態硬碟（SSD）。



== 為什麼有些磁碟機無法顯示？

在「新增容量」對話方塊中，並非所有磁碟機都可用於為現有資源池或磁碟區群組新增容量。

磁碟機因下列任何原因而不符合資格：

* 磁碟機必須未指派且未啟用安全功能。已屬於其他儲存池、其他磁碟區群組或配置為熱備碟的磁碟機不符合條件。如果磁碟機未指派但已啟用安全功能，則必須手動擦除該磁碟機才能使其符合條件。
* 處於非最佳狀態的磁碟機不符合條件。
* 如果磁碟機容量太小，則不符合資格。
* 同一儲存池或磁碟區群組中的磁碟機媒體類型必須相符。以下類型不能混用：
+
** 硬碟機（HDD）與固態硬碟（SSD）
** 採用 SAS 磁碟機的 NVMe
** 具有 512 位元組和 4KiB 磁碟區區塊大小的磁碟機


* 如果儲存池或磁碟區群組包含所有具有安全功能的磁碟機、則不會列出不具有安全功能的磁碟機。
* 如果一個池或磁碟區群組包含所有符合聯邦資訊處理標準（FIPS）的磁碟機，則不會列出不符合 FIPS 標準的磁碟機。
* 如果儲存池或磁碟區群組包含所有支援 Data Assurance (DA) 的磁碟機，且該儲存池或磁碟區群組中至少有一個已啟用 DA 的磁碟區，則不支援 DA 的磁碟機不符合資格，因此無法新增至該儲存池或磁碟區群組。但是，如果儲存池或磁碟區群組中沒有已啟用 DA 的磁碟區，則可以將不支援 DA 的磁碟機新增至該儲存池或磁碟區群組。如果您決定混合使用這些磁碟機，請注意您無法建立任何已啟用 DA 的磁碟區。


[NOTE]
====
可以透過新增磁碟機或刪除集區或磁碟區群組來增加儲存陣列的容量。

====


== 如何維護磁碟櫃 / 磁碟機櫃遺失保護？

若要維護資源池或磁碟區群組的磁碟櫃/抽屜遺失保護，請使用下表中指定的條件。

[cols="1a,1a,1a"]
|===
| 等級 | 磁碟櫃/抽屜遺失保護標準 | 所需的最少層板 / 抽屜數量 


 a| 
資源池
 a| 
對於硬碟架，資源池中單一硬碟架內的磁碟機數量不得超過兩個。

對於抽屜，資源池必須包含來自每個抽屜的相同數量的磁碟機。
 a| 
6 個用於貨架

5 個抽屜



 a| 
RAID 6
 a| 
磁碟區群組在單一機架或抽屜中包含的磁碟機不超過兩個。
 a| 
3



 a| 
RAID 3 或 RAID 5
 a| 
磁碟區群組中的每個磁碟機都位於不同的機櫃或抽屜中。
 a| 
3



 a| 
RAID 1
 a| 
鏡像配對中的每個磁碟機都必須位於不同的機櫃或抽屜中。
 a| 
2



 a| 
RAID 0
 a| 
無法實現磁碟櫃/抽屜遺失保護。
 a| 
不適用

|===
[NOTE]
====
若儲存池或磁碟區群組中已有磁碟機發生故障，則無法維持機架 / 抽屜遺失保護。在這種情況下，失去對磁碟機架或抽屜的存取權限，進而導致儲存池或磁碟區群組中另一個磁碟機無法存取，因而造成資料遺失。

====


== 對於資源池和磁碟區群組而言，最佳的磁碟機定位是什麼？

建立儲存池和磁碟區群組時、請確保上下磁碟機插槽之間的磁碟機選擇保持平衡。

對於 EF600 和 EF300 控制器，磁碟機插槽 0-11 連接到一個 PCI 橋接器，而插槽 12-23 連接到另一個 PCI 橋接器。為了獲得最佳效能，您應該平衡磁碟機選擇，使上下插槽中的磁碟機數量大致相等。這種定位可確保您的磁碟區不會過早達到頻寬限制。



== 哪種 RAID 等級最適合我的應用程式？

若要最大限度地發揮磁碟區群組的效能，您必須選擇適當的 RAID 層級。您可以透過了解存取磁碟區群組的應用程式的讀取和寫入百分比來確定適當的 RAID 層級。請使用「效能」頁面取得這些百分比。



=== RAID 等級和應用程式效能

RAID 依靠一系列稱為_層級_的組態來決定如何將使用者資料和備援資料寫入磁碟機及從磁碟機擷取。每個 RAID 層級都提供不同的效能功能。讀取比例高的應用程式在使用 RAID 5 磁碟區或 RAID 6 磁碟區時效能表現良好，因為 RAID 5 和 RAID 6 組態具有出色的讀取效能。

讀取比例低（寫入密集）的應用程式在 RAID 5 磁碟區或 RAID 6 磁碟區上的效能不佳。效能下降是由於控制器向 RAID 5 磁碟區群組或 RAID 6 磁碟區群組中的磁碟機寫入資料和備援資料的方式造成的。

根據以下資訊選擇 RAID 層級。

*RAID 0*

* *說明*
+
** 非冗餘、條帶化模式。


* *運作方式*
+
** RAID 0 將資料條帶化分佈在磁碟區群組中的所有磁碟機上。


* *資料保護功能*
+
** RAID 0 不建議用於高可用性需求。RAID 0 更適合儲存非關鍵資料。
** 如果磁碟區群組中的單一磁碟機發生故障，則所有相關的磁碟區都會發生故障，且所有資料都會遺失。


* *磁碟機編號要求*
+
** RAID Level 0 至少需要一個磁碟機。
** RAID 0 磁碟區群組可以包含超過 30 個磁碟機。
** 您可以建立一個包含儲存陣列中所有磁碟機的磁碟區群組。




*RAID 1 或 RAID 10*

* *說明*
+
** 等量分割 / 鏡射模式。


* *運作方式*
+
** RAID 1 使用磁碟鏡像技術，同時將資料寫入兩個相同的磁碟。
** RAID 10 使用磁碟機條帶化技術將資料條帶化分佈在一組鏡像磁碟機對上。


* *資料保護功能*
+
** RAID 1 和 RAID 10 提供高效能和最佳的資料可用性。
** RAID 1 和 RAID 10 使用磁碟機鏡像技術，將一個磁碟機上的資料精確複製到另一個磁碟機上。
** 如果磁碟機配對中的其中一個磁碟機故障，儲存陣列可以立即切換到另一個磁碟機，而不會遺失任何資料或服務。
** 單一磁碟機故障會導致相關磁碟區降級。鏡像磁碟機允許存取資料。
** 磁碟區群組中的磁碟機配對故障會導致所有相關磁碟區故障，並可能發生資料遺失。


* *磁碟機編號要求*
+
** RAID 1 至少需要兩個磁碟機：一個磁碟機用於使用者資料，一個磁碟機用於鏡像資料。
** 如果選擇四個或更多磁碟機，則會自動在磁碟區群組中設定 RAID 10：兩個磁碟機用於使用者資料，兩個磁碟機用於鏡像資料。
** 磁碟區組中必須包含偶數個磁碟機。如果磁碟機數量不是偶數，並且還有一些未指派的磁碟機，請前往 *Pools & Volume Groups* 為磁碟區組新增其他磁碟機，然後重試該操作。
** RAID 1 和 RAID 10 磁碟區群組可以包含超過 30 個磁碟機。可以建立包含儲存陣列中所有磁碟機的磁碟區群組。




*RAID 5*

* *說明*
+
** 高 I/O 模式。


* *運作方式*
+
** 使用者資料和冗餘資訊（同位）分佈在各個磁碟機上。
** 一個磁碟機的等效容量用於冗餘資訊。


* *資料保護功能*
+
** 如果 RAID 5 磁碟區群組中的單一磁碟機故障，所有相關的磁碟區都會降級。備援資訊允許資料仍可存取。
** 如果 RAID 5 磁碟區群組中有兩個或多個磁碟機故障，所有相關的磁碟區都會故障，且所有資料都會遺失。


* *磁碟機編號要求*
+
** 磁碟區群組中必須至少有三個磁碟機。
** 通常情況下，磁碟區群組中最多只能有 30 個磁碟機。




*RAID 6*

* *說明*
+
** 高 I/O 模式。


* *運作方式*
+
** 使用者資料和冗餘資訊（雙同位）會分散儲存在各個磁碟機上。
** 兩個磁碟機的等效容量用於冗餘資訊。


* *資料保護功能*
+
** 如果 RAID 6 磁碟區群組中有一個或兩個磁碟機故障，所有相關的磁碟區都會降級，但備援資訊仍允許存取資料。
** 如果 RAID 6 磁碟區群組中有三個或更多磁碟機故障，所有相關的磁碟區都會故障，且所有資料都會遺失。


* *磁碟機編號要求*
+
** 磁碟區群組中必須至少有五個磁碟機。
** 通常情況下，磁碟區群組中最多只能有 30 個磁碟機。




[NOTE]
====
您無法變更儲存池的 RAID 等級。使用者介面會自動將儲存池配置為 RAID 6。

====


=== RAID 等級和資料保護

RAID 1、RAID 5 和 RAID 6 會將冗餘資料寫入磁碟機媒體以實現容錯。冗餘資料可以是資料的副本（鏡像），也可以是從資料衍生出來的糾錯碼。如果某個磁碟機發生故障，您可以使用冗餘資料在替換磁碟機上快速重建資訊。

您可以在單一磁碟區群組中設定單一 RAID 層級。該磁碟區群組的所有備援資料都儲存在該磁碟區群組內。磁碟區群組的容量是成員磁碟機的總容量減去為備援資料保留的容量。備援所需的容量取決於所使用的 RAID 層級。



== 什麼是資料保證？

Data Assurance（DA）實施 T10 Protection Information（PI）標準，透過檢查和修正資料沿著 I/O 路徑傳輸時可能出現的錯誤來提高資料完整性。

資料保障功能的典型用途是檢查控制器和磁碟機之間的 I/O 路徑部分。DA 功能在儲存池和磁碟區群組層級提供。

啟用此功能後，儲存陣列會將錯誤校驗碼（也稱為循環冗餘校驗碼或 CRC）附加到磁碟區中的每個資料區塊。資料區塊移動後，儲存陣列會使用這些 CRC 碼來確定傳輸過程中是否發生任何錯誤。可能已損壞的資料既不會寫入磁碟，也不會返回給主機。如果要使用 DA 功能，請在建立新磁碟區時選擇支援 DA 的儲存池或磁碟區組（在儲存池和磁碟區組候選表中尋找「DA」旁的「是」）。

請確保將這些啟用 DA 的磁碟區指派給使用支援 DA 的 I/O 介面的主機。支援 DA 的 I/O 介面包括 Fibre Channel、SAS、iSCSI over TCP/IP、NVMe/FC、NVMe/IB、NVMe/RoCE 和 iSER over InfiniBand（iSCSI Extensions for RDMA/IB）。DA 不支援 SRP over InfiniBand。



== 什麼是安全功能（Drive Security）？

Drive Security 功能可防止從儲存陣列移除的已啟用安全功能的磁碟機上的資料遭到未經授權的存取。這些磁碟機可以是 Full Disk Encryption（FDE）磁碟機或 Federal Information Processing Standard（FIPS）磁碟機。



== 關於增加預留容量，我需要了解哪些資訊？

通常情況下，當您收到預留容量即將用完的警告時，應增加預留容量。預留容量只能以 8 GiB 的增量增加。

* 集區或磁碟區群組中必須有足夠的可用容量，以便在必要時進行擴充。
+
如果任何儲存池或磁碟區群組上都沒有可用容量、您可以將未指派的容量（以未使用的磁碟機形式）新增至儲存池或磁碟區群組。

* 資源池或磁碟區群組中的磁碟區必須處於最佳狀態，且不得處於任何修改狀態。
* 若要增加容量，池或磁碟區群組必須有可用容量。
* 您無法為唯讀快照磁碟區增加預留容量。只有讀寫快照磁碟區才需要預留容量。


對於快照操作，預留容量通常為基礎磁碟區的 40%。對於非同步鏡像操作，預留容量通常為基礎磁碟區的 20%。如果您預期基礎磁碟區將發生多次更改，或儲存物件的複製服務作業的預期生命週期非常長，則應使用較高的百分比。



== 為什麼我不能選擇其他減少的金額？

您只能減少與增加容量時所用容量相同的預留容量。成員磁碟區的預留容量只能以新增順序的相反順序移除。

如果存在以下任一情況，則無法減少儲存物件的預留容量：

* 如果儲存物件是鏡像配對磁碟區。
* 如果儲存物件僅包含一個用於保留容量的磁碟區。儲存物件必須至少包含兩個用於保留容量的磁碟區。
* 如果儲存物件是已停用的 Snapshot 磁碟區。
* 如果儲存物件包含一個或多個相關的快照映像。


您只能按照新增磁碟區的相反順序刪除預留容量的磁碟區。

您無法減少唯讀快照磁碟區的預留容量，因為它沒有任何關聯的預留容量。只有讀寫快照磁碟區才需要預留容量。



== 為什麼我需要為每個成員磁碟區預留容量？

快照一致性群組中的每個成員磁碟區都必須擁有自己的預留容量，用於儲存主機應用程式對基礎磁碟區所做的任何修改，而不會影響所引用的一致性群組快照映像。預留容量為主機應用程式提供對成員磁碟區中包含的資料副本的寫入存取權限，該成員磁碟區被指定為讀寫。

一致性群組快照映像對主機沒有直接的讀取或寫入存取權限。相反地，快照映像僅用於儲存從基礎磁碟區擷取的資料。

在建立指定為讀寫的一致性群組 Snapshot 磁碟區時，System Manager 會為一致性群組中的每個成員磁碟區建立保留容量。此保留容量可讓主機應用程式對一致性群組 Snapshot 映像中所含資料的副本進行寫入存取。



== 如何檢視和解讀所有 SSD 快取統計資料？

您可以查看 SSD Cache 的標稱統計資料和詳細統計資料。標稱統計資料是詳細統計資料的子集。

只有將所有 SSD 統計資料匯出到 `.csv`檔案後，才能查看詳細的統計資料。在查看和解讀統計數據時，請記住，某些解讀是透過綜合分析多項統計數據得出的。



=== 名目統計

若要檢視 SSD 快取統計資料，請選取功能表：Storage[Pools & Volume Groups]。選取您要檢視統計資料的 SSD Cache，然後選取功能表：More[View Statistics]。名義統計資料會顯示在 View SSD Cache Statistics 對話方塊中。

以下清單包含名義統計資料，這些資料是詳細統計資料的子集。

[cols="25h,~"]
|===
| 名義統計 | 說明 


 a| 
讀取 / 寫入
 a| 
主機對啟用 SSD Cache 的磁碟區的讀取或寫入總次數。比較讀取次數與寫入次數。為了確保 SSD Cache 有效運行，讀取次數必須大於寫入次數。讀取與寫入的比率越高，快取運作效果越好。



 a| 
快取命中
 a| 
快取命中次數統計。



 a| 
快取命中率（%）
 a| 
衍生自快取命中數 / （讀取 + 寫入）。快取命中百分比應大於 50% ，才能有效執行 SSD 快取作業。數字較小可能表示以下幾種情況：

* 讀取次數與寫入次數之比太小
* 讀取操作不會重複進行
* 快取容量太小




 a| 
快取分配（%）
 a| 
已指派的 SSD Cache 儲存空間，以該控制器可用 SSD Cache 儲存空間的百分比表示。計算方法為：已分配位元組數 / 可用位元組數。Cache Allocation 百分比通常顯示為 100%。如果該數值小於 100%，則表示快取尚未預熱，或 SSD Cache 容量大於所有正在存取的資料量。在後一種情況下，較小的 SSD Cache 容量也能提供相同的效能。請注意，這並不意味著快取資料已放入 SSD Cache；這只是將資料放入 SSD Cache 之前的準備步驟。



 a| 
快取利用率 (%)
 a| 
包含已啟用磁碟區資料的 SSD Cache 儲存容量，以已分配 SSD Cache 儲存容量的百分比表示。此值代表 SSD Cache 的使用率或密度，衍生自使用者資料位元組 / 已分配位元組。Cache 使用率百分比通常低於 100%，甚至可能遠低於此數值。此數字顯示填入快取資料的 SSD Cache 容量百分比。此數字低於 100% 的原因是 SSD Cache 的每個分配單元（SSD Cache 區塊）都會分割成較小的單元（稱為子區塊），這些子區塊會以某種程度獨立填入。數字越高通常越好，但即使數字較小，效能提升仍可能相當顯著。

|===


=== 詳細統計資料

詳細統計資料由名目統計資料和其他統計資料組成。這些附加統計資料與名目統計資料一起儲存，但與名目統計資料不同，它們不會顯示在 View SSD Cache Statistics 對話方塊中。您只能在將統計資料匯出到 `.csv`檔案後才能檢視詳細統計資料。

查看  `.csv` 文件時，請注意詳細統計資料列在名義統計資料之後：

[cols="25h,~"]
|===
| 詳細統計資料 | 說明 


 a| 
讀取區塊
 a| 
主機讀取的區塊數量。



 a| 
寫入區塊
 a| 
主機寫入中的區塊數。



 a| 
完全格擋
 a| 
快取命中中的區塊數。完全命中區塊數表示已從 SSD 快取中完全讀取的區塊數。SSD 快取僅對完全快取命中的操作提升效能。



 a| 
部分命中
 a| 
主機讀取次數中，至少有一個資料區塊（但並非所有資料區塊）位於 SSD Cache 中。部分命中是指 SSD Cache *未命中*，此時讀取操作由基礎磁碟區完成。



 a| 
部分命中 - 區塊
 a| 
部分命中中的區塊數。部分快取命中和部分快取命中區塊是指只有部分資料存在於 SSD 快取中的操作。在這種情況下，操作必須從快取的硬碟（HDD）磁碟區中取得資料。SSD 快取對此類命中沒有效能提升。如果部分快取命中區塊數高於完全快取命中區塊數，則使用其他 I/O 功能類型（例如檔案系統、資料庫或 Web 伺服器）可能會提高效能。預計在 SSD 快取預熱期間，部分命中和未命中的數量將高於快取命中。



 a| 
未命中
 a| 
SSD Cache 中沒有任何資料區塊的主機讀取次數。當讀取操作已從基礎磁碟區取得資料時，就會發生 SSD Cache 未命中。在 SSD Cache 預熱期間，部分命中和未命中次數預計會比 Cache 命中次數更多。



 a| 
未命中 - 區塊
 a| 
Misses 中的區塊數量。



 a| 
填充動作（主機讀取）
 a| 
將資料從基礎磁碟區複製到 SSD 快取的主機讀取次數。



 a| 
填入動作 (主機讀取) - 區塊
 a| 
Populate Actions （ Host Reads ）中的區塊數。



 a| 
填充操作（主機寫入）
 a| 
主機寫入次數是指將資料從基礎磁碟區複製到 SSD Cache 的次數。如果快取配置設定不允許透過寫入 I/O 操作填充快取，則 Populate Actions（Host Writes）計數可能為零。



 a| 
填滿操作 ( 主機寫入 ) - 區塊
 a| 
Populate Actions （主機寫入）中的區塊數。



 a| 
使動作無效
 a| 
SSD 快取中資料失效或移除的次數。每次主機寫入請求、每次使用強制單元存取（FUA）的主機讀取請求、每次驗證請求以及其他一些情況下，都會執行快取失效操作。



 a| 
回收動作
 a| 
SSD Cache 區塊重複用於其他基本磁碟區和/或不同邏輯區塊定址（LBA）範圍的次數。為了確保快取高效運行，回收次數必須遠小於讀取和寫入操作的總和。如果回收動作次數接近讀取和寫入操作的總和，則表示 SSD Cache 正在發生抖動。此時，要么需要增加快取容量，要么工作負載不適合使用 SSD Cache。



 a| 
可用位元組
 a| 
SSD 快取中可供此控制器使用的位元組數。



 a| 
已分配位元組數
 a| 
此控制器從 SSD Cache 分配的位元組數。從 SSD Cache 分配的位元組可能為空，也可能包含來自基礎磁碟區的資料。



 a| 
使用者資料位元組
 a| 
SSD 快取中已分配的位元組數，這些位元組包含來自基礎磁碟區的資料。可用位元組數、已分配位元組數和使用者資料位元組數用於計算快取分配百分比和快取使用率百分比。

|===


== 什麼是儲存池的最佳化容量？

當 SSD 磁碟機的部分容量未分配時，其使用壽命會更長，最大寫入效能也會更好。

對於與儲存池關聯的磁碟機，未分配容量包括儲存池的保留容量、可用容量（未被磁碟區使用的容量）以及一部分預留為額外最佳化容量的可用容量。額外的最佳化容量透過減少可用容量來確保最低最佳化容量，因此不能用於建立磁碟區。

建立儲存池時，系統會產生一個建議的最佳化容量，以平衡效能、磁碟機耗損壽命和可用容量。「儲存池設定」對話方塊中的「額外最佳化容量」滑桿可讓您調整儲存池的最佳化容量。調整此滑桿可提高效能和磁碟機耗損壽命，但會降低可用容量；或增加可用容量，但會降低效能和磁碟機耗損壽命。

[NOTE]
====
附加最佳化容量滑桿僅適用於 EF600 和 EF300 儲存系統。

====


== 什麼是磁碟區群組的最佳化容量？

當 SSD 磁碟機的部分容量未分配時，其使用壽命會更長，最大寫入效能也會更好。

對於與磁碟區群組相關聯的磁碟機，未分配容量包括磁碟區群組的可用容量（磁碟區未使用的容量），以及一部分預留為最佳化容量的可用容量。額外的最佳化容量透過減少可用容量來確保最低最佳化容量等級，因此無法用於建立磁碟區。

建立磁碟區群組時，系統會產生建議的最佳化容量，以平衡效能、磁碟機耗損壽命和可用容量。Volume Group Settings 對話方塊中的 Additional Optimization Capacity 滑桿可調整磁碟區群組的最佳化容量。調整滑桿可犧牲可用容量來提升效能和磁碟機耗損壽命，或犧牲效能和磁碟機耗損壽命來增加可用容量。

[NOTE]
====
附加最佳化容量滑桿僅適用於 EF600 和 EF300 儲存系統。

====


== 什麼是資源配置功能？

資源配置是 EF300 和 EF600 儲存陣列中的一項功能，可讓磁碟區立即投入使用，而無需背景初始化程序。

資源配置磁碟區是 SSD 磁碟區群組或集區中的完整磁碟區，其中磁碟機容量會在建立磁碟區時分配（指派給磁碟區），但磁碟機區塊會解除分配（取消對應）。相較之下，在傳統的完整磁碟區中，所有磁碟機區塊都會在背景磁碟區初始化作業期間進行對應或分配，以便初始化 Data Assurance 保護資訊欄位，並使每個 RAID 等量磁碟區中的資料和 RAID 同位元保持一致。使用資源配置磁碟區時，不會有時間限制的背景初始化。相反地，每個 RAID 等量磁碟區會在首次寫入等量磁碟區中的磁碟區區塊時進行初始化。

資源預置磁碟區僅在 SSD 磁碟區群組和儲存池中受支援，且該磁碟區群組或儲存池中的所有磁碟機均需支援 NVMe Deallocated 或 Unwritten Logical Block Error Enable（DULBE）錯誤復原功能。建立資源預置磁碟區時，指派給該磁碟區的所有磁碟機區塊都會被取消配置（取消對應）。此外，主機可以使用 NVMe Dataset Management 命令或 SCSI Unmap 命令取消配置磁碟區中的邏輯區塊。取消配置區塊可以延長 SSD 的使用壽命並提高最大寫入效能。具體提升效果因磁碟機型號和容量而異。


NOTE: 目前 EF300C 或 EF600C 儲存陣列不支援 DULBE 。



== 關於資源配置磁碟區功能，我需要了解哪些內容？

資源配置是 EF300 和 EF600 儲存陣列中的一項功能，可讓磁碟區立即投入使用，而無需背景初始化程序。

資源配置磁碟區是 SSD 磁碟區群組或集區中的完整磁碟區，其中磁碟機容量會在建立磁碟區時分配（指派給磁碟區），但磁碟機區塊會解除分配（取消對應）。相較之下，在傳統的完整磁碟區中，所有磁碟機區塊都會在背景磁碟區初始化作業期間進行對應或分配，以便初始化 Data Assurance 保護資訊欄位，並使每個 RAID 等量磁碟區中的資料和 RAID 同位元保持一致。使用資源配置磁碟區時，不會有時間限制的背景初始化。相反地，每個 RAID 等量磁碟區會在首次寫入等量磁碟區中的磁碟區區塊時進行初始化。

資源預置磁碟區僅在 SSD 磁碟區群組和儲存池中受支援，且該磁碟區群組或儲存池中的所有磁碟機均需支援 NVMe Deallocated 或 Unwritten Logical Block Error Enable（DULBE）錯誤復原功能。建立資源預置磁碟區時，指派給該磁碟區的所有磁碟機區塊都會被取消配置（取消對應）。此外，主機可以使用 NVMe Dataset Management 命令或 SCSI Unmap 命令取消配置磁碟區中的邏輯區塊。取消配置區塊可以延長 SSD 的使用壽命並提高最大寫入效能。具體提升效果因磁碟機型號和容量而異。

在磁碟機支援 DULBE 的系統中，資源配置預設為啟用。您可以在*儲存池和磁碟區組*中停用此預設設定。


NOTE: 目前 EF300C 或 EF600C 儲存陣列不支援 DULBE 。
