---
permalink: sm-storage/faq-snapshots.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= SANtricity System Manager 快照常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 為什麼我看不到我的所有磁碟區、主機或主機叢集？

如果快照磁碟區的基礎磁碟區啟用了 Data Assurance (DA)，則該快照磁碟區無法指派給不具備 Data Assurance (DA) 功能的主機。必須先在基礎磁碟區上停用 DA，然後才能將快照磁碟區指派給不具備 DA 功能的主機。

請參考下列準則，將 Snapshot 磁碟區指派給該主機：

* 如果主機透過不支援 DA 的 I/O 介面連接到儲存陣列，則該主機不具備 DA 功能。
* 如果主機叢集中至少有一個主機成員不具備 DA 功能，則該主機叢集不具備 DA 功能。


[NOTE]
====
您無法在與快照（一致性群組、快照群組、快照映像和快照磁碟區）、磁碟區副本和映像關聯的磁碟區上停用 DA。必須先刪除所有關聯的預留容量和快照物件，才能在基礎磁碟區上停用 DA。

====


== 什麼是快照映像？

快照映像是磁碟區內容的邏輯副本，在特定時間點擷取。快照映像佔用極少的儲存空間。

快照影像資料儲存如下：

* 建立快照映像時，它與基礎磁碟區完全一致。快照建立完成後，當基礎磁碟區上的任何資料區塊或資料區塊組發生首次寫入要求時，原始資料會先複製到快照預留容量，然後再將新資料寫入基礎磁碟區。
* 後續快照僅包含自建立第一個快照映像以來已變更的資料區塊。每次後續的寫入時複製操作都會將即將在基礎磁碟區上被覆寫的原始資料儲存到快照預留容量，然後再將新資料寫入基礎磁碟區。




== 為什麼要使用快照映像？

您可以使用快照來防止資料意外或惡意遺失或損毀，並允許從中復原。

選擇基礎磁碟區或一組基礎磁碟區（稱為快照一致性群組），然後透過以下一種或多種方式擷取快照映像：

* 您可以建立單一基礎磁碟區的快照映像，或建立由多個基礎磁碟區組成的快照一致性群組。
* 您可以手動建立快照，也可以為基本磁碟區或快照一致性群組建立排程，以自動擷取定期快照映像。
* 您可以建立快照映像的主機可存取快照磁碟區。
* 您可以執行回滾操作來還原 Snapshot 映像。


系統會保留多個快照映像作為還原點，您可以使用這些還原點回滾到特定時間點的已知良好資料集。回滾功能可防止資料意外刪除和資料損壞。



== 哪些類型的磁碟區可以用於快照？

標準磁碟區和精簡磁碟區是唯一可用於儲存快照映像的磁碟區類型。非標準磁碟區無法使用。基礎磁碟區可以位於儲存池或磁碟區群組上。



== 為什麼要建立快照一致性群組？

當您希望確保同時在多個磁碟區上建立 Snapshot 映像時，可以建立 Snapshot 一致性群組。

例如，一個由多個磁碟區組成的資料庫，為了復原目的需要保持一致性，就需要一個快照一致性群組來收集所有磁碟區的協調快照，並使用這些快照來還原整個資料庫。

快照一致性群組中包含的磁碟區稱為 _成員磁碟區_ 。

您可以對快照一致性群組執行下列快照操作：

* 建立快照一致性群組的快照映像，以取得成員磁碟區的同步映像。
* 為快照一致性群組建立排程，以自動擷取成員磁碟區的定期同步映像。
* 建立主機可存取的快照一致性群組映像快照磁碟區。
* 對快照一致性群組執行復原作業。




== 什麼是快照磁碟區，何時需要預留容量？

快照磁碟區可讓主機存取快照映像中的資料。快照磁碟區擁有自己的預留容量，可以儲存基礎磁碟區的任何修改，而不會影響原始快照映像。主機無法讀取或寫入快照映像。如果需要讀取或寫入快照資料，請建立快照磁碟區並將其指派給主機。

您可以建立兩種類型的快照磁碟區。快照磁碟區的類型決定了它是否使用預留容量。

* *唯讀* -- 以唯讀方式建立的快照磁碟區為主機應用程式提供快照映像中所包含的資料副本的讀取權限。唯讀快照磁碟區不使用預留容量。
* *讀寫* -- 以讀寫模式建立的快照磁碟區可讓您在不影響所引用的快照映像的情況下變更快照磁碟區。讀寫快照磁碟區使用預留容量來儲存這些變更。您可以隨時將唯讀快照磁碟區轉換為讀寫快照磁碟區。




== 什麼是快照群組？

快照群組是單一關聯基礎磁碟區的時間點快照映像集合。

System Manager 會將 Snapshot 映像組織成 _Snapshot 群組_。Snapshot 群組無需使用者操作，但您可以隨時調整 Snapshot 群組的保留容量。此外，當滿足以下條件時，系統可能會提示您建立保留容量：

* 每當您對尚未建立快照群組的基礎磁碟區建立快照時，System Manager 都會自動建立快照群組。這會為基礎磁碟區建立預留容量，用於儲存後續的快照映像。
* 無論何時為基礎磁碟區建立快照排程時， System Manager 都會自動建立快照群組。




== 為什麼要停用 Snapshot 磁碟區？

當您想要將不同的快照磁碟區指派給快照映像時，需要停用快照磁碟區。您可以將停用的快照磁碟區保留以供以後使用。

如果您不再需要快照磁碟區或一致性群組快照磁碟區，並且不打算以後重新建立它，則應刪除該磁碟區而不是停用它。



== 什麼是停用狀態？

處於「已停用」狀態的快照磁碟區目前未指派給快照映像。若要啟用快照磁碟區，必須使用重新建立操作將新的快照映像指派給已停用的快照磁碟區。

快照磁碟區的特性由指派給它的快照映像定義。在 Disabled 狀態下，快照磁碟區上的讀寫活動將會被暫停。



== 為什麼要暫停快照排程？

當排程暫停時，排程的 Snapshot 映像建立作業將不會執行。您可以暫停 Snapshot 排程以節省儲存空間，然後在稍後繼續執行排程的 Snapshot 作業。

如果您不需要快照排程，則應刪除該排程而不是暫停它。
