---
permalink: sm-storage/faq-volumes-workloads.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= SANtricity System Manager 的磁碟區和工作負載常見問題集
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 什麼是磁碟區？

磁碟區是應用程式、資料庫和檔案系統儲存資料的容器。它是為主機存取儲存陣列上的儲存設備而建立的邏輯元件。

磁碟區是根據儲存池或磁碟區群組中的可用容量建立的。磁碟區具有已定義的容量。儘管一個磁碟區可能包含多個磁碟機，但對於主機而言，該磁碟區表現為一個邏輯元件。



== 為什麼我在磁碟區群組中有足夠的可用容量來建立磁碟區，卻仍然會看到容量超額分配錯誤？

選定的磁碟區群組可能有一個或多個可用容量區域。可用容量區域是指刪除磁碟區或在建立磁碟區期間未使用所有可用容量而產生的可用容量。

在具有一個或多個可用容量區域的磁碟區群組中建立磁碟區時，該磁碟區的容量將限制為該磁碟區群組中最大的可用容量區域。例如，如果一個磁碟區群組總共有 15 GiB 的可用容量，而最大的可用容量區域為 10 GiB，則您可以建立的最大磁碟區容量為 10 GiB。

如果某個磁碟區群組有可用容量區域，則該磁碟區群組圖表會包含一個連結，指示現有可用容量區域的數量。選取該連結即可顯示一個彈出視窗，其中指示每個區域的容量。

透過整合可用容量，您可以利用磁碟區群組中的最大可用容量來建立額外的磁碟區。您可以使用下列其中一種方法整合所選磁碟區群組中的現有可用容量：

* 當偵測到磁碟區群組中至少有一個可用容量區域時，「合併可用容量」建議將顯示在首頁的通知區域中。按一下 *合併可用容量* 連結即可啟動對話方塊。
* 您也可以選擇功能表：Pools & Volume Groups[Uncommon Tasks > Consolidate volume group free capacity] 來啟動對話方塊。


如果您想使用特定的可用容量區域而不是最大的可用容量區域，請使用命令列介面（CLI）。



== 我選擇的工作負載如何影響磁碟區建立？

在建立磁碟區期間，系統會提示您提供有關工作負載使用情況的資訊。系統會使用這些資訊為您建立最佳的磁碟區組態，您可以視需要進行編輯。您也可以選擇在磁碟區建立順序中跳過此步驟。

工作負載是支援應用程式的儲存物件。您可以為每個應用程式定義一個或多個工作負載（或執行個體）。對於某些應用程式，系統會將工作負載配置為包含具有相似底層磁碟區特性的磁碟區。這些磁碟區特性會根據工作負載支援的應用程式類型進行最佳化。例如，如果您建立了支援 Microsoft SQL Server 應用程式的工作負載，然後隨後為該工作負載建立磁碟區，則底層磁碟區特性會針對 Microsoft SQL Server 進行最佳化。

* *應用程式專屬* -- 當您使用應用程式專屬工作負載建立磁碟區時，系統可能會建議最佳化的磁碟區組態，以最大限度地減少應用程式工作負載 I/O 與應用程式執行個體其他流量之間的爭用。磁碟區特性（例如 I/O 類型、區段大小、控制器擁有權以及讀取和寫入快取）會針對下列應用程式類型所建立的工作負載自動建議並最佳化。
+
** Microsoft® SQL Server™
** Microsoft® Exchange Server™
** 視訊監控應用程式
** VMware ESXi™ （適用於與 Virtual Machine File System 搭配使用的磁碟區）
+
您可以使用「新增 / 編輯磁碟區」對話方塊檢視建議的磁碟區配置，並編輯、新增或刪除系統建議的磁碟區和特性。



* *其他*（或不支援特定磁碟區建立的應用程式）— 其他工作負載使用磁碟區配置，如果您要建立的工作負載未與特定應用程式關聯、或儲存陣列上沒有針對您打算使用的應用程式的內建最佳化，則必須手動指定該磁碟區配置。您必須使用「新增 / 編輯磁碟區」對話方塊手動指定磁碟區配置。




== 為什麼這些磁碟區沒有與工作負載建立關聯？

如果磁碟區是使用命令列介面（CLI）建立的，或是從不同的儲存陣列遷移（匯入/匯出）的，則這些磁碟區與工作負載無關。



== 為什麼我無法刪除選取的工作負載？

此工作負載包含一組磁碟區，這些磁碟區是透過命令列介面（CLI）建立的，或是從其他儲存陣列遷移（匯入 / 匯出）的。因此，此工作負載中的磁碟區未與特定應用程式的工作負載關聯，所以無法刪除該工作負載。



== 應用程式專屬工作負載如何協助我管理儲存陣列？

應用程式特定工作負載的磁碟區特性決定了工作負載如何與儲存陣列的元件互動，並有助於確定特定組態下環境的效能。

應用程式是指諸如 SQL Server 或 Exchange 之類的軟體。您可以定義一個或多個工作負載來支援每個應用程式。



== 提供這些資訊如何協助建立儲存設備？

工作負載資訊用於最佳化所選工作負載的磁碟區特性，例如 I/O 類型、區段大小和讀取/寫入快取。這些最佳化後的特性決定了工作負載如何與儲存陣列元件互動。

根據您提供的工作負載資訊，System Manager 會建立適當的磁碟區，並將其放置在系統目前存在的可用儲存池或磁碟區群組上。系統會建立磁碟區，並根據您所選工作負載的目前最佳實務來最佳化其特性。

在為給定工作負載建立磁碟區之前，您可以查看建議的磁碟區組態，並使用「新增 / 編輯磁碟區」對話方塊編輯、新增或刪除系統建議的磁碟區和特性。

請參閱應用程式專屬文件以取得最佳實務資訊。



== 我需要做什麼才能識別擴充的容量？

如果增加磁碟區的容量，主機可能不會立即辨識磁碟區容量的增加。

大多數作業系統都能辨識擴充後的磁碟區容量，並在磁碟區擴充啟動後自動擴充。但是，有些作業系統可能無法辨識。如果您的作業系統無法自動辨識擴充後的磁碟區容量，您可能需要重新掃描磁碟或重新啟動系統。

擴展磁碟區容量後，您必須手動增加檔案系統大小以與之匹配。具體操作方法取決於您使用的檔案系統。

如需其他詳細資料，請參閱主機作業系統文件。



== 為什麼我看不到我所有的資源池和 / 或磁碟區群組？

任何無法將磁碟區移至的儲存池或磁碟區群組都不會顯示在清單中。

因下列任何原因，儲存池或磁碟區群組均不符合資格：

* 資源池或磁碟區群組資源池的資料保證 (DA) 功能不相符。
* 資源池或磁碟區群組處於非最佳狀態。
* 儲存池或磁碟區群組的容量太小。




== 什麼是區段大小？

區段是指儲存陣列在條帶（RAID 群組）移動到下一個磁碟機之前，儲存在磁碟機上的資料量，單位為千位元組（KiB）。區段大小僅適用於磁碟區群組，不適用於儲存池。

區段大小由其包含的資料區塊數量決定。在確定區段大小時，必須了解磁碟區中將儲存的資料類型。如果應用程式通常使用小型隨機讀寫作業（IOPS），則較小的區段大小通常更合適。相反，如果應用程式具有大型循序讀寫作業（處理量），則較大的區段大小通常更合適。

無論應用程式使用小批量隨機讀寫操作，還是大批量順序讀寫操作，如果區段大小大於典型的資料區塊區塊大小，儲存陣列的效能都會更好。這通常可以使磁碟機更容易、更快速地存取資料，這對提高儲存陣列的效能至關重要。



=== IOPS 效能很重要的環境

在以每秒 I/O 操作數（IOPS）為目標的環境中，如果使用大於典型資料區塊大小（「`chunk`」）的區段大小（讀取 / 寫入磁碟機），儲存陣列的效能會更好。這樣可以確保每個 chunk 都寫入單一磁碟機。



=== 吞吐量很重要的環境

在高吞吐量環境下，資料段大小應為資料磁碟機總數的整數倍，且應與典型的資料區塊大小（I/O 大小）相符。這樣可以將資料以單一條帶的形式分散到磁碟區群組中的所有磁碟機上，從而加快讀寫速度。



== 什麼是偏好的控制器擁有權？

首選控制器所有權定義了被指定為磁碟區的擁有或主要控制器的控制器。

控制器所有權至關重要，應精心規劃。控制器之間的總 I/O 量應盡可能保持平衡。

例如，如果一個控制器主要讀取大型的連續資料區塊，而另一個控制器讀取的是小型資料區塊且讀寫操作頻繁，那麼兩者的負載就截然不同。了解哪些磁碟區包含哪些類型的資料，可以幫助您在兩個控制器之間均衡分配 I/O 傳輸。



== 我什麼時候會想使用「稍後分配主機」選項？

如果要加快建立磁碟區的過程、可以跳過主機指派步驟、以便新建立的磁碟區在離線狀態下初始化。

新建立的磁碟區必須進行初始化。系統可以使用兩種模式之一來初始化它們——即 Immediate Available Format（IAF）後台初始化過程或離線過程。

將磁碟區對應到主機時，會強制該群組中所有正在初始化的磁碟區切換到背景初始化。此背景初始化程序允許並行主機 I/O，有時可能會很耗時。

當磁碟區群組中沒有任何磁碟區被對應時，將執行離線初始化。離線程序比背景程序快得多。



== 關於主機區塊大小要求，我需要了解哪些資訊？

對於 EF300 和 EF600 系統，磁碟區可以設定為支援 512 位元組或 4KiB 的區塊大小（也稱為「磁區大小」）。您必須在建立磁碟區時設定正確的值。如果可能，系統會建議合適的預設值。

在設定磁碟區區塊大小之前、請閱讀以下限制和準則。

* 某些作業系統和虛擬機器（目前尤其是 VMware）需要 512 位元組的區塊大小，不支援 4KiB，因此在建立磁碟區之前，請務必了解主機的要求。通常，將磁碟區的區塊大小設為 4KiB 可以獲得最佳效能；但是，請確保您的主機支援 4KiB（或「`4Kn`」）區塊。
* 為儲存池或磁碟區群組選擇的磁碟機類型也會決定支援的磁碟區區塊大小，如下所示：
+
** 如果使用寫入 512 位元組區塊的磁碟機建立磁碟區群組，則只能建立具有 512 位元組區塊的磁碟區。
** 如果使用寫入 4KiB 區塊的磁碟機建立磁碟區群組，則可以建立 512 位元組或 4KiB 區塊的磁碟區。


* 如果陣列配備了 iSCSI 主機介面卡，則所有磁碟區的資料區塊大小都限制為 512 位元組（無論磁碟區群組的資料區塊大小為何）。這是由於特定的硬體實作所致。
* 區塊大小一旦設定就無法更改。如果需要更改區塊大小，必須刪除該磁碟區並重新建立。

