---
permalink: sm-storage/faq-systems-clusters.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= SANtricity System Manager 的主機系統和主機叢集常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 什麼是主機和主機叢集？

主機是指向儲存陣列上的磁碟區發送 I/O 的伺服器。主機叢集是一組主機。您可以建立主機叢集，以便輕鬆將相同的磁碟區指派給多個主機。

您可以單獨定義主機。它可以是獨立實體，也可以新增至主機叢集。您可以將磁碟區指派給個別主機，或者主機可以是主機叢集的一部分，與主機叢集中的其他主機共用一個或多個磁碟區的存取權限。

主機叢集是您在 SANtricity System Manager 中建立的邏輯實體。您必須先將主機新增至主機叢集，然後才能指派磁碟區。



== 為什麼需要建立主機叢集？

如果希望兩台或多台主機共用相同磁碟區集的存取權限，則需要建立主機叢集。通常情況下，每台主機上都會安裝叢集軟體來協調磁碟區存取。



== 我如何知道哪種主機作業系統類型是正確的？

「主機作業系統類型」欄位包含主機的作業系統。您可以從下拉式清單中選取建議的主機類型。

下拉清單中顯示的主機類型取決於儲存陣列型號和韌體版本。最新版本會優先顯示最常用的選項，這些選項通常最適用。出現在此清單中並不表示該選項完全受支援。

[NOTE]
====
如需主機支援的詳細資訊，請參閱 https://imt.netapp.com/matrix/#welcome["NetApp 互通性矩陣工具"^]。

====
以下部分主機類型可能會出現在清單中：

[cols="35h,~"]
|===
| 主機作業系統類型 | 作業系統（OS）和多路徑驅動程式 


 a| 
Linux DM-MP （Kernel 3.10 或更新版本）
 a| 
支援使用 Device Mapper 多路徑容錯移轉解決方案且核心版本為 3.10 或更新版本的 Linux 作業系統。



 a| 
VMware ESXi
 a| 
支援執行使用 VMware 內建 Storage Array Type Policy 模組 SATP_ALUA 的 Native Multipathing Plug-in （NMP） 架構的 VMware ESXi 作業系統。



 a| 
Windows （叢集式或非叢集式）
 a| 
支援未執行 ATTO 多路徑驅動程式的 Windows 叢集或非叢集組態。



 a| 
ATTO Cluster （所有作業系統）
 a| 
支援使用 ATTO Technology, Inc. 多重路徑驅動程式的所有叢集組態。



 a| 
Linux（Veritas DMP）
 a| 
支援使用 Veritas DMP 多路徑解決方案的 Linux 作業系統。



 a| 
Linux（ATTO）
 a| 
支援使用 ATTO Technology, Inc. 多重路徑驅動程式的 Linux 作業系統。



 a| 
Mac OS（ATTO）
 a| 
支援使用 ATTO Technology, Inc. 多重路徑驅動程式的 Mac OS 版本。



 a| 
Windows（ATTO）
 a| 
支援使用 ATTO Technology, Inc. 多重路徑驅動程式的 Windows 作業系統。



 a| 
IBM SVC
 a| 
支援 IBM SAN Volume Controller 配置。



 a| 
原廠預設值
 a| 
保留用於儲存陣列的初始啟動。如果您的主機作業系統類型設定為 Factory Default，請將其變更為與連接主機上執行的主機作業系統和多路徑驅動程式相符。



 a| 
Linux DM-MP（Kernel 3.9 或更早版本）
 a| 
支援使用 Device Mapper 多路徑容錯移轉解決方案且核心版本為 3.9 或更早版本的 Linux 作業系統。



 a| 
視窗叢集（已棄用）
 a| 
如果您的主機作業系統類型設定為此值，請改用 Windows （叢集或非叢集）設定。

|===


== 什麼是 HBA 和適配器連接埠？

主機匯流排適配器（HBA）是一塊位於主機內部的電路板，包含一個或多個主機連接埠。主機連接埠是主機匯流排適配器（HBA）上的連接埠，用於提供與控制器的實體連接並執行 I/O 操作。

HBA 上的適配器連接埠稱為主機連接埠。大多數 HBA 具有一個或兩個主機連接埠。HBA 具有唯一的全球識別碼（WWID），每個 HBA 主機連接埠也都有一個唯一的 WWID。當您透過 SANtricity System Manager 手動建立主機時，主機連接埠識別碼用於將對應的 HBA 與實體主機關聯。



== 如何將主機連接埠與主機配對？

如果您要手動建立主機，則必須先使用主機上提供的對應主機匯流排適配器（HBA）公用程式來確定與主機中安裝的每個 HBA 關聯的主機連接埠識別碼。

取得這些資訊後，從「建立主機」對話方塊提供的清單中選擇已登入儲存陣列的主機連接埠識別碼。

[NOTE]
====
請確保為要建立的主機選擇適當的主機連接埠識別碼。如果關聯了錯誤的主機連接埠識別碼，可能會導致其他主機意外存取此資料。

====


== 如何建立 CHAP 密鑰？

如果在連接到儲存陣列的任何 iSCSI 主機上設定了 Challenge Handshake Authentication Protocol (CHAP) 驗證，則必須為每個 iSCSI 主機重新輸入該發起方 CHAP 金鑰。

為此、您可以使用 System Manager 做為「建立主機」作業的一部分、或透過「檢視 / 編輯設定」選項。

如果您使用 CHAP 相互驗證，則還必須在「設定」頁面中為儲存陣列定義目標 CHAP 密碼，並在每個 iSCSI 主機上重新輸入該目標 CHAP 密碼。



== 什麼是預設叢集？

預設叢集是一個系統定義的實體，它允許任何已登入儲存陣列的未關聯主機連接埠識別碼存取指派給該預設叢集的磁碟區。未關聯主機連接埠識別碼是指邏輯上未與特定主機關聯的主機連接埠，但該連接埠已實際安裝在主機上並已登入儲存陣列。

[NOTE]
====
如果您希望主機對儲存陣列中的特定磁碟區擁有特定的存取權限，則不能使用預設叢集。相反，您必須將主機連接埠識別碼與其對應的主機關聯起來。此任務可以在 Create Host 操作期間手動完成。然後，您可以將磁碟區指派給單一主機或主機叢集。

====
只有在外部儲存環境允許所有主機和所有已登入主機連接埠識別碼連接到儲存陣列並可存取所有磁碟區（全存取模式）的特殊情況下，才應使用預設叢集，而無需明確地將主機資訊告知儲存陣列或使用者介面。

最初，您只能透過命令列介面（CLI）將磁碟區指派給預設叢集。但是，在您將至少一個磁碟區指派給預設叢集後，該實體（稱為 Default Cluster）將顯示在使用者介面中，您可以在其中管理該實體。



== 什麼是主機連線報告？

啟用主機連線報告後，儲存陣列會持續監控控制器與已設定主機之間的連線，並在連線中斷時發出警示。

如果電纜鬆脫、損壞或遺失，或主機出現其他問題，則可能會出現連線中斷。在這種情況下，系統可能會開啟 Recovery Guru 訊息：

* *主機備援遺失* -- 如果任一控制器無法與主機通訊，則會開啟。
* *主機類型錯誤* -- 如果儲存陣列上主機的類型指定錯誤，則會開啟此選項，這可能會導致容錯移轉問題。


在某些情況下，如果重新啟動控制器所需的時間可能超過連線逾時時間，則可能需要停用主機連線報告。停用此功能會阻止 Recovery Gurus 訊息的顯示。

[NOTE]
====
停用主機連線報告也會停用自動負載平衡，該功能用於監控和平衡控制器資源使用。但是，如果您重新啟用主機連線報告，自動負載平衡功能不會自動重新啟用。

====