---
permalink: sm-storage/faq-storage-array-settings.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= SANtricity System Manager 的儲存陣列設定常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 什麼是自動負載平衡？

Automatic Load Balancing 功能提供自動 I/O 平衡，並確保來自主機的傳入 I/O 流量在兩個控制器之間進行動態管理和平衡。

自動負載平衡功能透過動態回應負載隨時間的變化，並自動調整磁碟區控制器所有權，從而改善 I/O 資源管理，以修正工作負載在控制器之間轉移時出現的任何負載不平衡問題。

每個控制器的工作負載都會受到持續監控，並且在主機上安裝的多路徑驅動程式的配合下，可以在必要時自動進行負載平衡。當負載在控制器之間自動重新平衡後，儲存管理員無需手動調整磁碟區控制器的所有權以適應儲存陣列上的負載變化。

啟用自動負載平衡後，它將執行以下功能：

* 自動監控並平衡控制器資源使用率。
* 根據需要自動調整磁碟區控制器所有權，從而優化主機和儲存陣列之間的 I/O 頻寬。


[NOTE]
====
任何被指派使用控制器 SSD Cache 的磁碟區都不符合自動負載平衡傳輸的條件。

====


== 什麼是控制器快取？

控制器快取是一個實體記憶體空間，它簡化了兩種類型的 I/O（輸入/輸出）操作：控制器和主機之間的 I/O 操作，以及控制器和磁碟之間的 I/O 操作。

對於讀取和寫入資料傳輸，主機和控制器透過高速連線進行通訊。然而，從控制器後端到磁碟的通訊速度較慢，因為磁碟是相對較慢的裝置。

當控制器快取接收到資料時，控制器會通知主機應用程式它已保存該資料。這樣，主機應用程式無需等待 I/O 資料寫入磁碟。應用程式可以繼續執行操作。伺服器應用程式也可以隨時存取快取資料，無需額外進行磁碟讀取。

控制器快取會以多種方式影響儲存陣列的整體效能：

* 快取起到緩衝區的作用，因此主機和磁碟資料傳輸不需要同步。
* 主機讀取或寫入操作所需的資料可能來自先前操作的快取，這樣就無需存取磁碟。
* 如果使用寫入快取，主機可以在先前寫入作業的資料寫入磁碟之前傳送後續寫入命令。
* 如果啟用快取預取，順序讀取存取將會最佳化。快取預取使讀取操作更有可能在快取中找到所需資料，而不是從磁碟讀取資料。


[CAUTION]
====
*資料可能遺失* -- 如果您啟用 *Write caching without batteries* 選項，且沒有通用電源進行保護，則可能會遺失資料。此外，如果您沒有控制器電池，並且啟用了 *Write caching without batteries* 選項，也可能導致資料遺失。

====


== 什麼是快取刷新？

當快取中未寫入的資料量達到一定水準時，控制器會定期將快取資料寫入磁碟機。這個寫入過程稱為「flushing」。

控制器使用兩種快取刷新演算法：按需刷新和基於快取年齡的刷新。控制器會使用按需刷新演算法，直到快取資料量低於快取刷新閾值為止。預設情況下，當快取使用率達到 80% 時，刷新操作就會開始。

在 System Manager 中，您可以設定「`Start demand cache flushing`」閾值，以更好地支援您環境中使用的 I/O 類型。在主要以寫入作業為主的環境中，您應該將「`Start demand cache flushing`」百分比設定得較高，以提高任何新的寫入請求無需存取磁碟即可通過快取處理的機率。較高的百分比設定會限制快取刷新次數，從而使更多資料保留在快取中，進而提高快取命中率。

在 I/O 不穩定（資料突發）的環境中，可以使用較低的快取刷新率，以便系統在資料突發之間頻繁刷新快取。在處理各種負載的多樣化 I/O 環境中，或當負載類型未知時，建議將閾值設為 50%，這是一個不錯的折衷方案。請注意，如果選擇的起始百分比低於 80%，則可能會出現效能下降，因為主機讀取所需的資料可能無法使用。選擇較低的百分比也會增加維持快取等級所需的磁碟寫入次數，從而增加系統開銷。

基於年齡的演算法會指定寫入資料在快取中保留多長時間後、才能將其清除至磁碟。控制器會使用基於年齡的演算法、直到達到快取清除臨界值為止。預設值為 10 秒、但此時間週期僅在非使用期間計算。您無法在 System Manager 中修改清除時間；而是必須使用命令列介面（CLI）中的 *Set Storage Array* 命令。

[CAUTION]
====
*資料可能遺失* -- 如果您啟用 *Write caching without batteries* 選項，且沒有通用電源進行保護，則可能會遺失資料。此外，如果您沒有控制器電池，並且啟用了 *Write caching without batteries* 選項，也可能導致資料遺失。

====


== 什麼是快取區塊大小？

儲存陣列的控制器將其快取組織成「區塊」，這些區塊是大小為 8、16 或 32 KiB 的記憶體單元。儲存系統上的所有磁碟區共享相同的快取空間；因此，磁碟區只能有一種快取區塊大小。

應用程式使用不同的區塊大小，這會影響儲存效能。系統管理員中的預設區塊大小為 32 KiB，但您可以將其設定為 8、16 或 32 KiBs。較小的區塊大小適合檔案系統或資料庫應用程式。較大的區塊大小適合需要大數據傳輸、順序 I/O 或高頻寬的應用程式，例如多媒體應用程式。



== 何時應該同步儲存陣列時脈？

如果您發現 SANtricity System Manager 中顯示的時間戳記與管理用戶端（透過瀏覽器存取 SANtricity System Manager 的電腦）中顯示的時間戳記不一致，則應手動同步儲存陣列中的控制器時脈。只有當 SANtricity System Manager 中未啟用 NTP （Network Time Protocol） 時，才需要執行此操作。

[NOTE]
====
我們強烈建議您使用 NTP 伺服器，而不是手動同步時鐘。NTP 使用 SNTP（Simple Network Time Protocol）自動與外部伺服器同步時鐘。

====
您可以透過「同步儲存陣列時鐘」對話方塊檢查同步狀態，該對話方塊位於「系統」頁面。如果對話方塊中顯示的時間不匹配，請執行同步操作。您可以定期查看此對話方塊，以了解控制器時鐘的時間顯示是否有偏差，不再同步。
