---
permalink: sm-storage/faq-remote-storage.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= SANtricity System Manager 遠端儲存常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 在建立遠端儲存連線之前，我需要了解哪些資訊？

若要設定遠端儲存功能，您必須透過 iSCSI 直接連接遠端裝置和目標儲存系統。

若要設定 iSCSI 系統連線，請參閱：

* link:../sm-hardware/configure-iscsi-ports-hardware.html["配置 iSCSI 連接埠"]
* https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["遠端儲存技術報告"^]




== 為什麼系統提示我移除遠端磁碟區？

當儲存系統達到其最大遠端磁碟區數時，它會自動偵測任何未使用的遠端磁碟區，並提示您將其刪除。

有些情況下，建立過程中不會清理未使用的遠端磁碟區。在開始任何其他匯入操作之前，請確保您的系統運作狀況良好且網路連線穩定。



== 為什麼我在目的地陣列上看不到所有磁碟區？

配置 Remote Storage 功能的匯入時、您可能會注意到、由於區塊大小、容量或磁碟區可用度、某些磁碟區不會出現在目標候選清單中。

若要顯示在清單中，Volume 候選項目必須具備：

* 容量等於或大於遠端磁碟區。
* 與遠端磁碟區相同的區塊大小。
* Optimal 的目前狀態。


如果磁碟區符合以下條件，則會從清單中排除：

* 以下任何一種關係：磁碟區複本、Snapshot 或鏡射。
* 重新配置作業正在進行中。
* 對應到另一個裝置（主機或主機叢集）。
* 已啟用讀取快閃記憶體快取。




== 在導入過程中，我需要了解遠端磁碟區的哪些資訊？

使用 Remote Storage 功能時，請注意遠端磁碟區是資料的來源。

匯入過程中，資料會從遠端磁碟區傳送到目的地儲存系統上的目標磁碟區。這兩個磁碟區必須具有相符的區塊大小。



== 在開始遠端儲存匯入之前、我需要了解哪些資訊？

遠端儲存功能可讓您將資料從遠端儲存系統複製到本機 E-Series 儲存系統上的磁碟區。在使用此功能前，請閱讀以下指南。



=== 組態

在建立遠端儲存匯入之前，您必須完成下列動作並驗證下列條件：

* 確保本機 E-Series 儲存系統的每個控制器都與遠端儲存系統建立 iSCSI 連線。
* 在本機 E-Series 儲存系統上，為匯入操作建立目標磁碟區。確保該磁碟區的容量等於或大於來源磁碟區，區塊大小與來源磁碟區匹配，且未對應。請參閱 link:create-volumes.html["建立磁碟區"]。
* 使用 iSCSI 限定名稱 (IQN) 將本機 E-Series 儲存系統設定為遠端系統的主機。您可以從選單：Settings[System > iSCSI settings > Target IQN] 查看 IQN。此外，請務必根據所使用的系統設定對應的主機類型。
* 停止遠端儲存系統上所選磁碟區的所有 I/O 操作、卸載所有檔案系統，並移除主機或應用程式的所有指派。
* 將遠端儲存系統的磁碟區指派給新建立的本機 E-Series 儲存系統主機。
* 從遠端儲存系統收集以下資訊，以便建立匯入：
+
** iSCSI 限定名稱（IQN）
** iSCSI IP 位址
** 遠端儲存設備的 LUN 編號，來源資料即來源於此


* 匯入程序開始後，整個本機目的地磁碟區會被複製的資料覆寫。建立匯入後，寫入本機目的地磁碟區的任何新資料都會傳播到遠端儲存裝置上的磁碟區。因此，我們建議您在開始匯入程序之前，先備份遠端儲存系統上的磁碟區。




=== 匯入流程

以下步驟概述了匯入程序。

. 存取 System Manager 介面，然後前往*遠端儲存*頁面。選取*匯入*以開始建立新的匯入作業。如需詳細說明，請參閱 link:rtv-import-remote-storage.html["匯入遠端儲存設備"]。
+
如果要執行離線匯入，請在匯入完成後再對應目標磁碟區。

. 監控匯入進度。
+
匯入開始後，即可對應目標磁碟區。完成匯入作業所需的時間取決於遠端儲存設備（來源磁碟區）的大小、匯入優先權設定以及兩個儲存系統及其關聯磁碟區的 I/O 負載量。

+
匯入完成後，目標磁碟區與來源磁碟區完全相同。

. 當您準備中斷對應關係時，請從 *Operations In Progress* 面板對匯入物件執行 *Disconnect* 操作。


匯入中斷連線後，本機目的地的效能會恢復正常，不再受到遠端連線的影響。



=== 限制

遠端儲存功能存在以下限制：

* 必須停用鏡像功能。
* E 系列系統上的目標磁碟區不能有快照。
* 在開始匯入之前，E 系列系統上的目標磁碟區不得對應至任何主機。
* E 系列系統上的目標磁碟區必須停用資源配置。
* 不支援將遠端儲存磁碟區直接對應到一台或多台主機。
* 不支援 Web Services Proxy。
* 不支援 iSCSI CHAP 密碼。
* 不支援 SMcli。
* 不支援 VMware Datastore。
* 當存在匯入配對時，關係/匯入配對中一次只能升級一個儲存系統。




=== 其他資訊

有關遠端儲存功能的更多資訊可從 https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["遠端儲存技術報告"^]取得。
