---
permalink: sm-storage/faq-storage-drives.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= SANtricity System Manager 的儲存磁碟機常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 什麼是熱備用磁碟機？

熱備援磁碟在 RAID 1、RAID 5 或 RAID 6 磁碟區群組中作為待命磁碟機。它們是功能完整且不含任何資料的磁碟機。如果磁碟區群組中的磁碟機故障，控制器會自動將故障磁碟機的資料重建至熱備援磁碟。

如果儲存陣列中的某個磁碟機發生故障，熱備援磁碟機會自動取代故障磁碟機，無需進行實體更換。如果磁碟機發生故障時熱備援磁碟機可用，控制器會利用備援資料將故障磁碟機中的資料重建到熱備援磁碟機上。

熱備援磁碟機並非專用於特定的磁碟區群組。相反地，您可以將熱備援磁碟機用於儲存陣列中任何容量相同或更小的故障磁碟機。熱備援磁碟機必須與其所保護的磁碟機具有相同的媒體類型（HDD 或 SSD）。

[NOTE]
====
儲存池不支援熱備用磁碟機。儲存池不使用熱備用磁碟機，而是使用組成儲存池的每個磁碟機內的保留容量。

====


== 什麼是保留容量？

保留容量是指在儲存池中預留的容量（磁碟機數量），用於支援潛在的磁碟機故障。

建立儲存池時、系統會根據儲存池中的磁碟機數量自動保留預設的保留容量。

儲存池在重建過程中使用保留容量，而磁碟區群組則使用熱備援磁碟機來實現相同目的。保留容量方法優於熱備援磁碟機，因為它能加快重建速度。保留容量分佈在儲存池中的多個磁碟機上，而不是像熱備援磁碟機那樣集中在單一磁碟機上，因此您不會受到單一磁碟機的速度或可用性的限制。



== 為什麼要以邏輯方式更換磁碟機？

如果磁碟機故障或您因任何其他原因想要更換磁碟機，且儲存陣列中有未指派的磁碟機，您可以邏輯上用未指派的磁碟機取代故障的磁碟機。如果您沒有未指派的磁碟機，則可以實際更換磁碟機。

原始磁碟機的資料會複製或重建到替換磁碟機上。



== 我可以在哪裡查看正在重建的磁碟機狀態？

您可以從「進行中的操作」儀表板檢視磁碟機重建狀態。

從首頁點擊右上角的 *View Operations in Progress* 連結。

根據磁碟機的情況，完整重建可能需要相當長的時間。如果磁碟區所有權發生變更，則可能會進行完整重建，而非快速重建。
