---
permalink: sm-storage/host-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host, terms 
summary: 了解主機術語如何應用於您的儲存陣列。 
---
= 了解 SANtricity 軟體中的主機術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解主機術語如何應用於您的儲存陣列。

[cols="25h,~"]
|===
| 元件 | 定義 


 a| 
主機
 a| 
主機是向儲存陣列上的磁碟區發送 I/O 的伺服器。



 a| 
主機名稱
 a| 
主機名稱應與主機的系統名稱一致。



 a| 
主機叢集
 a| 
主機叢集是一組主機。建立主機叢集可以方便地將相同的磁碟區指派給多個主機。



 a| 
主機介面協定
 a| 
主機介面協定是控制器和主機之間的連接（例如 Fibre Channel、iSCSI 等）。



 a| 
HBA 或網路介面卡（NIC）
 a| 
主機匯流排適配器（HBA）是位於主機中的一塊電路板，包含一個或多個主機連接埠。



 a| 
主機連接埠
 a| 
主機連接埠是主機匯流排適配器（HBA）上的連接埠，可提供與控制器的實體連線，並用於 I/O 作業。



 a| 
主機連接埠識別碼
 a| 
主機連接埠識別碼是與主機匯流排適配器（HBA）上的每個主機連接埠關聯的全球唯一名稱。

* 網際網路小型電腦系統介面（iSCSI）主機連接埠識別碼必須介於 1 到 233 個字元之間。iSCSI 主機連接埠識別碼以標準 IQN 格式顯示（例如， `iqn.xxx.com.xxx:8b3ad`）。
* 非 iSCSI 主機連接埠識別碼（例如 Fibre Channel 和 Serial Attached SCSI (SAS)）以冒號分隔，每兩個字元之間以冒號分隔（例如， `xx:yy:zz`）。Fibre Channel 主機連接埠識別碼必須包含 16 個字元。




 a| 
主機作業系統類型
 a| 
主機作業系統類型是一個配置設置，它定義了儲存陣列中的控制器如何根據主機的作業系統（或其變體）回應 I/O 操作。有時也簡稱為 _host type_。



 a| 
控制器主機連接埠
 a| 
控制器主機連接埠是控制器上的連接埠，可提供與主機的實體連線，並用於 I/O 作業。



 a| 
LUN
 a| 
邏輯單元號碼（LUN）是指派給主機用於存取磁碟區的位址空間的編號。磁碟區以 LUN 的形式作為容量呈現給主機。

每台主機都有自己的 LUN 位址空間。因此，同一個 LUN 可以被不同的主機用來存取不同的磁碟區。

|===