---
permalink: sm-storage/how-reserved-capacity-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved, capacity, 
summary: 當您為磁碟區提供複製服務操作（例如快照或非同步鏡像操作）時，會自動建立保留容量。 
---
= SANtricity 軟體中的預留容量是如何運作的
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您為磁碟區提供複製服務操作（例如快照或非同步鏡像操作）時，會自動建立保留容量。

預留容量的目的是為了在出現問題時儲存這些磁碟區上的資料變更。與磁碟區一樣，預留容量也是從儲存池或磁碟區群組中建立的。



== 複製使用保留容量的服務物件

預留容量是這些複製服務物件所使用的底層儲存機制：

* 快照群組
* 讀取 / 寫入快照磁碟區
* 一致性群組成員磁碟區
* 鏡像配對磁碟區


建立或擴充這些複製服務物件時，必須從儲存池或磁碟區群組中建立新的預留容量。對於快照操作，預留容量通常為基本磁碟區的 40%；對於非同步鏡像操作，預留容量通常為基本磁碟區的 20%。但是，預留容量會根據原始資料的變更次數而變化。



== 精簡磁碟區和保留容量

對於精簡磁碟區，如果已達到報告的最大容量 256 TiB，則無法增加其容量。請確保將精簡磁碟區的預留容量設定為大於報告的最大容量。（精簡磁碟區始終採用精簡配置，這意味著容量是在資料寫入磁碟區時分配的。）

如果在儲存池中使用精簡磁碟區建立保留容量，請檢閱以下有關保留容量的動作和結果：

* 如果精簡磁碟區的保留容量發生故障，精簡磁碟區本身不會自動轉換為 Failed 狀態。但是，由於精簡磁碟區上的所有 I/O 作業都需要存取保留容量磁碟區，因此 I/O 作業始終會導致向請求主機傳回 Check Condition。如果保留容量磁碟區的根本問題能夠解決，則保留容量磁碟區將恢復為 Optimal 狀態，精簡磁碟區也將恢復正常運作。
* 如果使用現有的精簡磁碟區來完成非同步鏡像對，則該精簡磁碟區將使用新的預留容量磁碟區重新初始化。初始同步過程中，僅傳輸主側已配置的資料區塊。




== 容量警報

複製服務物件具有可設定的容量警告和警示臨界值，以及保留容量已滿時的可設定回應。

當複本服務物件磁碟區的保留容量接近填滿點時，系統會向使用者發出警示。根據預設，當保留容量磁碟區已滿 75% 時會發出此警示；不過，您可以視需要向上或向下調整此警示點。如果您收到此警示，可以在當時增加保留容量磁碟區的容量。在這方面，每個複本服務物件都可以獨立設定。



== 孤立的預留容量磁碟區

孤立的預留容量磁碟區是指由於其關聯的複製服務物件已被刪除，因此不再儲存複製服務作業資料的磁碟區。刪除複製服務物件時，其預留容量磁碟區也應被刪除。然而，該預留容量磁碟區的刪除失敗。

由於孤立的預留容量磁碟區未被任何主機存取，因此它們是可回收的候選項目。請手動刪除孤立的預留容量磁碟區，以便將其容量用於其他作業。

System Manager 會在主頁的「通知」區域中顯示「回收未使用的容量」訊息，提醒您存在孤立的預留容量磁碟區。您可以按一下 *回收未使用的容量* 以顯示「回收未使用的容量」對話框，並在其中刪除孤立的預留容量磁碟區。



== 預留容量的特性

* 在建立磁碟區時，需要考慮分配給保留容量的容量，以保持足夠的可用容量。
* 保留容量可以小於基礎磁碟區（最小大小為 8 MiB）。
* 中繼資料會佔用一些空間，但非常少（192 KiB），因此在確定保留容量磁碟區的大小時無需考慮。
* 預留容量無法直接從主機讀取或寫入。
* 每個讀取 / 寫入快照磁碟區、快照群組、一致性群組成員磁碟區和鏡像配對磁碟區都有預留容量。

