---
permalink: sm-storage/how-workloads-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, application, workloads, volume, 
summary: 建立磁碟區時、您可以選擇工作負載、為特定應用程式自訂儲存陣列組態。 
---
= 工作負載在 SANtricity 軟體中的運作方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建立磁碟區時、您可以選擇工作負載、為特定應用程式自訂儲存陣列組態。

工作負載是支援應用程式的儲存物件。您可以為每個應用程式定義一個或多個工作負載（或執行個體）。對於某些應用程式，系統會將工作負載配置為包含具有相似底層磁碟區特性的磁碟區。這些磁碟區特性會根據工作負載支援的應用程式類型進行最佳化。例如，如果您建立了支援 Microsoft SQL Server 應用程式的工作負載，然後隨後為該工作負載建立磁碟區，則底層磁碟區特性會針對 Microsoft SQL Server 進行最佳化。

在建立磁碟區的過程中，系統會提示您回答有關工作負載使用情況的問題。例如，如果您要建立 Microsoft Exchange 磁碟區，系統會詢問您需要多少個郵箱、平均郵箱容量需求以及所需的資料庫副本數量。系統會使用這些資訊為您建立最佳磁碟區配置，您可以根據需要進行編輯。您也可以選擇跳過磁碟區建立過程中的此步驟。



== 工作負載類型

您可以建立兩種類型的工作負載：Application-specific 和 Other。

* *特定於應用程式*。當您使用特定於應用程式的工作負載建立磁碟區時，系統可能會建議最佳化的磁碟區組態，以最大限度地減少應用程式工作負載 I/O 與應用程式執行個體其他流量之間的爭用。磁碟區特性（例如 I/O 類型、區段大小、控制器擁有權以及讀寫快取）會針對為下列應用程式類型所建立的工作負載自動建議並最佳化。
+
** Microsoft® SQL Server™
** Microsoft® Exchange Server™
** 視訊監控應用程式
** VMware ESXi™ （適用於與 Virtual Machine File System 搭配使用的磁碟區）
+
您可以使用「新增 / 編輯磁碟區」對話方塊檢視建議的磁碟區配置，並編輯、新增或刪除系統建議的磁碟區和特性。



* *其他*（或不支援特定磁碟區建立的應用程式）。其他工作負載使用磁碟區組態，當您要建立未與特定應用程式相關聯的工作負載時，或者如果系統沒有針對您打算在儲存陣列上使用的應用程式內建最佳化時，您必須手動指定此組態。您必須使用「新增/編輯磁碟區」對話方塊手動指定磁碟區組態。




== 應用程式和工作負載檢視

若要查看應用程式和工作負載，請啟動 SANtricity System Manager。透過該介面，您可以透過以下幾種方式查看與特定應用程式工作負載相關的資訊：

* 您可以在「磁碟區」磁貼中選取 *Applications & Workloads* 索引標籤，以檢視依工作負載和與工作負載相關聯的應用程式類型分組的儲存陣列磁碟區。
* 您可以在「效能」磁貼中選擇 *Applications & Workloads* 標籤，查看邏輯物件的效能指標（延遲、IOPS 和 MB）。這些物件按應用程式和關聯的工作負載分組。透過定期收集這些效能數據，您可以建立基準測量值並分析趨勢，這有助於您調查與 I/O 效能相關的問題。

