---
permalink: sm-storage/how-ssd-cache-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd cache, 
summary: 'SSD Cache 功能是一種基於控制器的解決方案，它將存取頻率最高的資料（「熱」資料）快取到低延遲的 Solid State Drives (SSD) 上，從而動態提升系統效能。SSD Cache 專門用於主機讀取操作。' 
---
= SANtricity 軟體中 SSD 快取的工作原理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSD Cache 功能是一種基於控制器的解決方案，它將存取頻率最高的資料（「熱」資料）快取到低延遲的固態硬碟（SSD）上，從而動態提升系統效能。SSD Cache 專門用於主機讀取操作。



== SSD 快取與主快取的比較

SSD Cache 是與控制器動態隨機存取記憶體（DRAM）中的主快取一起使用的輔助快取。

SSD 快取的運作方式與主快取不同：

* 對於主快取，每個 I/O 操作都必須先將資料透過快取進行暫存才能執行該操作。
+
在主快取中，主機讀取後，資料儲存在 DRAM 中。

* 只有當將資料放置在快取中有助於提高整體系統效能時,才會使用 SSD Cache。
+
在 SSD Cache 中，資料從磁碟區複製並儲存在兩個內部 RAID 磁碟區（每個控制器一個）上，這兩個磁碟區會在建立 SSD Cache 時自動建立。



內部 RAID 磁碟區用於內部快取處理。這些磁碟區無法在使用者介面中存取或顯示。但是，這兩個磁碟區會佔用儲存陣列允許的磁碟區總數。



== 如何使用 SSD Cache

智慧型快取會將資料儲存在低延遲磁碟機中，從而更快地回應後續的資料請求。如果程式請求的資料已存在於快取中（稱為「`cache hit`」），則低延遲磁碟機可以立即處理該交易。否則，將發生「`cache miss`」，此時必須從原始的、速度較慢的磁碟機存取資料。隨著快取命中次數的增加，整體效能也會提升。

當主機程式存取儲存陣列的磁碟機時，資料會儲存在 SSD Cache 中。當主機程式再次存取相同的資料時，會直接從 SSD Cache 讀取資料，而不是從硬碟讀取。常用的資料都儲存在 SSD Cache 中。只有當無法從 SSD Cache 讀取資料時，才會存取硬碟。

只有當將資料放置在快取中有助於提升整體系統效能時,才會使用 SSD Cache。

當 CPU 需要處理讀取的資料時，它會遵循以下步驟：

. 檢查 DRAM 快取。
. 如果在 DRAM 快取中找不到，則檢查 SSD Cache。
. 如果在 SSD Cache 中找不到，則從硬碟取得。如果資料被認為值得快取，則複製到 SSD Cache。




== 效能提升

將存取頻率最高的資料（熱點）複製到 SSD Cache 可以提高硬碟的運作效率、降低延遲，並加快讀寫速度。使用高效能 SSD 快取來自 HDD 磁碟區的資料可以提升 I/O 效能和回應時間。

簡單的磁碟區 I/O 機制用於在 SSD Cache 之間傳輸資料。資料快取並儲存在 SSD 上後，後續對該資料的讀取操作均在 SSD Cache 上進行，因此無需存取 HDD 磁碟區。



== SSD Cache 和 Drive Security 功能

若要在啟用了 Drive Security（安全模式）的磁碟區上使用 SSD Cache，該磁碟區和 SSD Cache 的 Drive Security 功能必須相符。如果它們不匹配，則該磁碟區將無法啟用安全功能。



== 實作 SSD 快取

若要實作 SSD 快取，請執行下列動作：

. 建立 SSD 快取。
. 將 SSD Cache 與要實作 SSD 讀取快取的磁碟區建立關聯。


[NOTE]
====
任何被指派使用控制器 SSD Cache 的磁碟區都不符合自動負載平衡傳輸的條件。

====