---
permalink: sm-storage/how-volumes-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, copy, 
summary: 磁碟區是管理和組織儲存陣列上儲存空間的資料容器。 
---
= SANtricity 軟體中的磁碟區是如何運作的
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
磁碟區是管理和組織儲存陣列上儲存空間的資料容器。

您可以利用儲存陣列上的可用儲存容量建立磁碟區，從而輕鬆組織和使用系統資源。這個概念類似於在電腦上使用資料夾 / 目錄來組織檔案，以便輕鬆快速地存取。

磁碟區是主機唯一可見的資料層。在 SAN 環境中，磁碟區會對應到邏輯單元號碼（LUN），主機可以看到這些邏輯單元號碼。LUN 儲存使用者資料，這些資料可透過儲存陣列支援的一或多個主機存取傳輸協定進行存取，包括 FC、iSCSI 和 SAS。



== 您可以從資源池和磁碟區群組建立的磁碟區類型

磁碟區的容量來自於儲存池或磁碟區群組。您可以從儲存陣列上已有的儲存池或磁碟區群組建立下列類型的磁碟區。

* *從儲存池* -- 您可以從儲存池建立磁碟區，可以是_完全配置（厚）磁碟區_或_精簡配置（瘦）磁碟區_。
+
[NOTE]
====
System Manager 介面不提供建立精簡磁碟區的選項。如果您想要建立精簡磁碟區，請使用 Command Line Interface （CLI）。

====
* *從磁碟區群組* -- 您只能從磁碟區群組建立_完全配置（厚）磁碟區_。


厚磁碟區和精簡磁碟區從儲存陣列中獲取容量的方式不同：

* 建立磁碟區時，會分配厚磁碟區的容量。
* 當資料寫入磁碟區時，精簡磁碟區的容量會配置為資料。


精簡配置有助於避免浪費已分配的容量，並能為企業節省前期儲存成本。然而，完全配置的優勢在於延遲更低，因為在建立厚磁碟區時，所有儲存空間都會一次性分配。

[NOTE]
====
EF600/EF600C 和 EF300/EF300C 儲存系統不支援精簡配置。

====


== 磁碟區的特性

儲存池或磁碟區群組中的每個磁碟區都可以根據其儲存的資料類型具有各自的特性。這些特性包括：

* *區段大小* -- 區段是指儲存陣列在條帶（RAID 群組）中移動到下一個磁碟機之前、儲存在磁碟機上的資料量（以 KB（KiB）為單位）。區段大小等於或小於 Volume 群組的容量。區段大小是固定的、無法針對資源池進行變更。
* *容量* -- 您可以從儲存池或磁碟區群組中的可用容量建立磁碟區。在建立磁碟區之前，儲存池或磁碟區群組必須已存在，並且必須有足夠的可用容量來建立磁碟區。
* *控制器所有權* -- 所有儲存陣列都可以配備一個或兩個控制器。在單控制器陣列中，磁碟區的工作負載由單一控制器管理。在雙控制器陣列中，每個磁碟區都有一個「擁有」該磁碟區的首選控制器（A 或 B）。在雙控制器配置中，當工作負載在控制器之間轉移時，系統會使用自動負載平衡功能自動調整磁碟區的所有權，以修正任何負載平衡問題。自動負載平衡功能可自動平衡 I/O 工作負載，並確保來自主機的傳入 I/O 流量在兩個控制器之間得到動態管理和平衡。
* *磁碟區指派* -- 您可以在建立磁碟區時或稍後為主機授予磁碟區存取權限。所有主機存取均透過邏輯單元號碼（LUN）進行管理。主機偵測 LUN，而 LUN 又分配給對應的磁碟區。如果您要將磁碟區指派給多個主機，請使用叢集軟體來確保所有主機都能存取該磁碟區。
+
主機類型可能對主機可存取的磁碟區數量有特定限制。為特定主機建立磁碟區時，請注意此限制。

* *描述性名稱* -- 您可以隨意為磁碟區命名，但我們建議使用描述性名稱。


建立磁碟區時，每個磁碟區都會被指派容量，並被賦予名稱、區段大小（僅限磁碟區群組）、控制器所有權和磁碟區到主機的指派關係。磁碟區資料會根據需要自動在控制器之間進行負載平衡。
