---
permalink: sm-storage/initialize-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, initialize, volumes 
summary: 磁碟區在首次建立時會自動初始化。但是，Recovery Guru 可能會建議您手動初始化磁碟區，以便從某些故障情況下復原。請僅在技術支援人員的指導下使用此選項。您可以選擇一個或多個磁碟區進行初始化。 
---
= 在 SANtricity System Manager 中初始化磁碟區
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
磁碟區在首次建立時會自動初始化。但是，Recovery Guru 可能會建議您手動初始化磁碟區，以便從某些故障情況下復原。請僅在技術支援人員的指導下使用此選項。您可以選擇一個或多個磁碟區進行初始化。

.開始之前
* 所有 I/O 操作已停止。
* 要初始化的磁碟區上的任何裝置或檔案系統都必須先卸載。
* 該磁碟區處於最佳狀態，且該磁碟區上沒有正在進行的修改作業。


[CAUTION]
====
操作開始後無法取消。所有磁碟區資料都將被擦除。除非 Recovery Guru 建議，否則請勿嘗試此操作。開始此程序前，請聯絡技術支援。

====
.關於此任務
初始化磁碟區時，該磁碟區會保留其 WWN、主機指派、已分配容量和保留容量設定。它還會保留相同的 Data Assurance (DA) 設定和安全設定。

下列類型的磁碟區 _無法_ 初始化：

* 快照磁碟區的基礎磁碟區
* 鏡像關係中的主要磁碟區
* 鏡像關係中的次要磁碟區
* 磁碟區複本中的來源磁碟區
* 磁碟區複本中的目標磁碟區
* 已在進行初始化的磁碟區


本主題僅適用於從儲存池或磁碟區群組建立的標準磁碟區。

.步驟
. 選擇選單：Storage [ Volumes ]。
. 選擇任意磁碟區，然後選擇功能表：更多 [初始化磁碟區]。
+
Initialize Volumes 對話方塊隨即出現。儲存陣列上的所有磁碟區都會顯示在此對話方塊中。

. 選取您要初始化的一個或多個磁碟區，並確認您要執行該作業。


.結果
System Manager 執行下列動作：

* 清除已初始化磁碟區中的所有資料。
* 清除區塊索引，導致未寫入的區塊被讀取為零填充（磁碟區看起來完全為空）。


選擇功能表：Home[View Operations in Progress]，即可查看目前正在對所選磁碟區執行的初始化操作的進度。此操作可能耗時較長，並可能影響系統效能。
