---
permalink: sm-storage/interpret-performance-data.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, interpret, performance data 
summary: 效能資料可引導您調整儲存陣列的效能。 
---
= 在 SANtricity System Manager 中解讀效能資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
效能資料可引導您調整儲存陣列的效能。

解讀效能資料時，請記住，儲存陣列的效能受多種因素影響。下表列出了需要考慮的主要方面。

[cols="25h,~"]
|===
| 效能資料 | 對效能調校的影響 


 a| 
延遲（毫秒或 ms）
 a| 
監控特定物件的 I/O 活動。

識別可能構成瓶頸的物件：

* 如果多個磁碟區共用一個磁碟區群組，則個別磁碟區可能需要自己的磁碟區群組，以提高磁碟機的循序效能並降低延遲。
* 使用儲存池時，會引入更大的延遲，並且磁碟機之間可能存在不均勻的工作負載，這使得延遲值變得不那麼有意義，而且通常會更高。
* 磁碟機類型和速度會影響延遲。在隨機 I/O 中，轉速較快的磁碟機在磁碟上不同位置之間移動所需的時間較短。
* 磁碟機數量過少會導致排隊的命令增多，磁碟機處理命令所需的時間也更長，從而增加系統的整體延遲。
* 較大的 I/O 操作由於資料傳輸需要額外時間，因此延遲也更大。
* 較高的延遲可能表示 I/O 模式具有隨機性。採用隨機 I/O 的磁碟機比採用循序串流的磁碟機具有更高的延遲。
* 同一磁碟區群組中不同磁碟機或磁碟區之間的延遲差異可能表示某個磁碟機速度較慢。




 a| 
IOPS
 a| 
影響每秒輸入 / 輸出操作數（IOPS 或 IOs/sec）的因素包括以下幾項：

* 存取模式 （隨機或循序）
* I/O 大小
* RAID 層級
* 快取區塊大小
* 是否啟用讀取快取
* 是否啟用寫入快取
* 動態快取讀取預先擷取
* 區段大小
* 磁碟區群組或儲存陣列中的磁碟機數量


快取命中率越高，I/O 速率也越高。啟用寫入快取後，寫入 I/O 速率會比停用寫入快取時更高。在決定是否為特定磁碟區啟用寫入快取時，請查看目前 IOPS 和最大 IOPS。順序 I/O 模式的速率應該高於隨機 I/O 模式。無論 I/O 模式如何，啟用寫入快取都能最大限度地提高 I/O 速率並縮短應用程式回應時間。

您可以在磁碟區的 IOPS 統計資料中看到因變更區段大小而造成的效能改善。請進行實驗以確定最佳區段大小，或使用檔案系統大小或資料庫區塊大小。



 a| 
MiB/s
 a| 
傳輸速率或吞吐量取決於應用程式的 I/O 大小和 I/O 速率。通常，較小的應用程式 I/O 請求會導致較低的傳輸速率，但可以提供更快的 I/O 速率和更短的回應時間。較大的應用程式 I/O 請求則可以實現更高的吞吐量。

了解典型的應用程式 I/O 模式可以幫助您確定特定儲存陣列的最大 I/O 傳輸速率。



 a| 
CPU
 a| 
此值為正在使用的處理容量百分比。

您可能會注意到，相同類型的物件在 CPU 使用率上存在差異。例如，某個控制器的 CPU 使用率很高或隨時間推移而增加，而另一個控制器的 CPU 使用率則較低或更穩定。在這種情況下，您可能需要將一個或多個磁碟區的控制器所有權變更為 CPU 百分比較低的控制器。

您可能需要監控整個儲存陣列的 CPU 使用情況。如果 CPU 使用率持續上升而應用程式效能下降，則可能需要新增儲存陣列。透過為企業新增儲存陣列，您可以繼續以可接受的效能等級滿足應用程式的需求。



 a| 
淨空
 a| 
效能餘裕是指控制器、控制器主機通道和控制器磁碟機通道的剩餘效能能力。該值以百分比表示，代表這些物件能夠提供的最大效能與目前效能層級之間的差距。

* 對於控制器而言，餘裕是最大可能 IOPS 的百分比。
* 對於通道而言，裕量是最大吞吐量的百分比，或 MiB/s。計算中包括讀取吞吐量、寫入吞吐量和雙向吞吐量。


|===