---
permalink: sm-storage/performance-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, performance, terms 
summary: 了解效能術語如何應用於您的儲存陣列。 
---
= 了解 SANtricity 軟體中的效能術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解效能術語如何應用於您的儲存陣列。

[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
應用程式
 a| 
應用程式是一種軟體程式，例如 SQL 或 Exchange。



 a| 
CPU
 a| 
CPU 是「中央處理器」的縮寫。CPU 表示儲存陣列處理能力的利用百分比。



 a| 
主機
 a| 
主機是向儲存陣列上的磁碟區發送 I/O 的伺服器。



 a| 
IOPS
 a| 
IOPS 代表每秒輸入 / 輸出作業數。



 a| 
延遲
 a| 
延遲是指從發出讀取或寫入命令等請求到主機或儲存陣列做出回應之間的時間間隔。



 a| 
LUN
 a| 
邏輯單元號碼（LUN）是指派給主機用於存取磁碟區的位址空間的編號。磁碟區以 LUN 的形式作為容量呈現給主機。

每台主機都有自己的 LUN 位址空間。因此，同一個 LUN 可以被不同的主機用來存取不同的磁碟區。



 a| 
MiB
 a| 
MiB 是 mebibyte（mega binary byte）的縮寫。1 個 MiB 等於 2²⁰，或 1,048,576 個位元組。與此相對的是 MB，MB 表示十進位值。1 個 MB 等於 1,024 個位元組。



 a| 
物件
 a| 
物件是指任何邏輯或實體儲存元件。

邏輯物件包括磁碟區群組、集區和磁碟區。實體物件包括儲存陣列、陣列控制器、主機和磁碟機。



 a| 
資源池
 a| 
儲存池是一組邏輯上分組的磁碟機。您可以使用儲存池建立一個或多個可供主機存取的磁碟區。（您可以從儲存池或磁碟區組建立磁碟區。）



 a| 
讀取
 a| 
讀取是「讀取操作」的縮寫，指的是主機向儲存陣列請求資料時發生的操作。



 a| 
磁碟區
 a| 
磁碟區是應用程式、資料庫和檔案系統儲存資料的容器。它是為主機存取儲存陣列上的儲存設備而建立的邏輯元件。

磁碟區是根據儲存池或磁碟區群組中的可用容量建立的。磁碟區具有已定義的容量。儘管一個磁碟區可能包含多個磁碟機，但對於主機而言，該磁碟區表現為一個邏輯元件。



 a| 
磁碟區名稱
 a| 
磁碟區名稱是建立磁碟區時指派給該磁碟區的一串字元。您可以接受預設名稱，也可以提供更具描述性的名稱，以指示磁碟區中儲存的資料類型。



 a| 
磁碟區群組
 a| 
磁碟區群組是用來存放具有共用特徵的磁碟區的容器。磁碟區群組具有已定義的容量和 RAID 等級。您可以使用磁碟區群組建立一個或多個可供主機存取的磁碟區。（您可以從磁碟區群組或儲存池建立磁碟區。）



 a| 
工作負載
 a| 
工作負載是支援應用程式的儲存物件。您可以為每個應用程式定義一個或多個工作負載（或執行個體）。對於某些應用程式，系統會將工作負載配置為包含具有相似底層磁碟區特性的磁碟區。這些磁碟區特性會根據工作負載支援的應用程式類型進行最佳化。例如，如果您建立了支援 Microsoft SQL Server 應用程式的工作負載，然後隨後為該工作負載建立磁碟區，則底層磁碟區特性會針對 Microsoft SQL Server 進行最佳化。



 a| 
寫入
 a| 
Write 是「寫入作業」的縮寫，指的是將資料從主機傳送到陣列進行儲存。

|===