---
permalink: sm-storage/replace-drive-logically-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, replace, drive, logically 
summary: 如果磁碟機故障或您因任何其他原因想要更換磁碟機，且儲存陣列中有未指派的磁碟機，您可以邏輯上用未指派的磁碟機取代故障的磁碟機。如果您沒有未指派的磁碟機，則可以實際更換磁碟機。 
---
= 在 SANtricity System Manager 中以邏輯方式更換磁碟機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果磁碟機故障或您因任何其他原因想要更換磁碟機，且儲存陣列中有未指派的磁碟機，您可以邏輯上用未指派的磁碟機取代故障的磁碟機。如果您沒有未指派的磁碟機，則可以實際更換磁碟機。

.關於此任務
當您使用未指派的磁碟機對現有磁碟機進行邏輯取代時，該未指派的磁碟機將會被指派，並成為關聯儲存池或磁碟區群組的永久成員。您可以使用邏輯取代選項來取代以下類型的磁碟機：

* 故障磁碟機
* 缺少磁碟機
* Recovery Guru 已通知您即將達到使用壽命終點的 SSD 硬碟
* Recovery Guru 已通知您即將發生磁碟機故障的硬碟
* 已指派磁碟機（僅適用於磁碟區群組中的磁碟機，不適用於儲存池中的磁碟機）


替換磁碟機必須具備以下特性：

* 處於最佳狀態
* 處於未指派狀態
* 與被替換的磁碟機具有相同的屬性（媒體類型、介面類型等）
* 相同的 FDE 功能（建議使用，但非必要）
* 相同的 DA 功能（推薦，但非必要）


.步驟
. 選擇 *Hardware* 。
. 如果圖形顯示了控制器，請按一下 *Drives* 標籤。
+
圖形變更為顯示磁碟機而非控制器。

. 按一下要進行邏輯替換的磁碟機。
+
驅動器的內容功能表隨即出現。

. 點擊 *Logically replace* 。
. *選用：*勾選 *Fail drive after it is replaced* 核取方塊，即可在更換磁碟機後使原始磁碟機失效。
+
僅當原始指派的磁碟機未發生故障或遺失時，此核取方塊才會啟用。

. 從 *Select a replacement drive* 表中，選擇要使用的替換磁碟機。
+
表格中僅列出與您要更換的磁碟機相容的磁碟機。如果可能，請選擇能夠維持機櫃遺失保護和抽取匣遺失保護的磁碟機。

. 點擊 *Replace* 。
+
如果原硬碟發生故障或遺失，系統會使用奇偶校驗資訊在替換硬碟上重建資料。此重建過程會自動開始。硬碟的故障指示燈熄滅，儲存池或磁碟區群組中硬碟的活動指示燈開始閃爍。

+
如果原始磁碟機未故障或遺失，其資料會複製到替換磁碟機。此複製作業會自動開始。複製作業完成後，系統會將原始磁碟機轉換為「未指派」狀態，或者如果已選取核取方塊，則轉換為「故障」狀態。


