---
permalink: sm-storage/rtv-import-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, import, remote, storage 
summary: 若要將遠端系統中的儲存匯入至本機 E-Series 儲存系統，請使用「匯入遠端儲存」精靈。 
---
= 在 SANtricity System Manager 中匯入遠端儲存設備
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要將遠端系統中的儲存匯入至本機 E-Series 儲存系統，請使用「匯入遠端儲存」精靈。

.開始之前
* E-Series 儲存系統必須配置為與遠端儲存系統通訊。
+
[NOTE]
====
硬體配置在遠端儲存功能的使用者指南中有詳細說明，該指南可從 E-Series 和 SANtricity 文件中心獲取 https://docs.netapp.com/us-en/e-series/remote-storage-volumes/setup-remote-volumes-concept.html["配置硬體"^]，以及 https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["遠端儲存技術報告"^]。

====
* 對於遠端儲存系統，請收集以下資訊：
+
** iSCSI IQN
** iSCSI IP 位址
** 遠端儲存設備（來源磁碟區）的 LUN 編號


* 對於本機 E 系列儲存系統，建立或選擇用於資料匯入的磁碟區。請參閱 link:create-volumes.html["建立磁碟區"]。目標磁碟區必須符合以下要求：
+
** 與遠端儲存設備 （來源磁碟區） 的區塊大小相符。
** 容量等於或大於遠端儲存裝置。
** 狀態為最佳且可用。




有關完整要求列表，請參閱 link:rtv-remote-storage-volume-requirements.html["遠端儲存磁碟區要求"]。

* *建議：* 在開始匯入程序之前，請備份遠端儲存系統上的磁碟區。


.關於此任務
在此任務中，您需要建立遠端儲存裝置與本機 E-Series 儲存系統上的磁碟區之間的對應。配置完成後，導入過程將開始。

[NOTE]
====
由於許多變數都會影響匯入作業及其完成時間，我們建議您先執行較小的「`test`」匯入。使用這些測試來確保所有連線都能正常運作，並且匯入作業能在適當的時間內完成。

====
.步驟
. 選擇選單：Storage [ Remote storage ]。
. 點選 *Import Remote Storage* 。
+
隨即顯示匯入遠端儲存設備的精靈。

. 在「設定來源」面板的 *步驟 1a* 中，輸入連線資訊。如果要新增另一個 iSCSI 連線，請按一下 *新增另一個 IP 位址*，為遠端儲存新增額外的 IP 位址。完成後，按一下 *下一步*。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
Name
 a| 
輸入遠端儲存裝置的名稱，以便在 System Manager 介面中識別它。

名稱最多可包含 30 個字元，且只能包含字母、數字以及以下特殊字元：底線（_）、破折號（-）和井字號（#）。名稱中不能包含空格。



 a| 
iSCSI 連線內容
 a| 
輸入遠端儲存設備的連線內容：

** *iSCSI 限定名稱（IQN）*：輸入 iSCSI IQN。
** *IP 位址*：請輸入 IPv4 位址。
** *Port*：輸入來源設備和目標設備之間通訊所使用的連接埠號碼。預設連接埠號碼為 3260。


|===
====
+
按一下 *Next* 後，將顯示 Configure Source 面板的 *Step 1b*。

. 在 *LUN* 欄位中，選擇要用作來源的遠端儲存裝置 LUN 編號，然後按一下 *Next* 。
+
「配置目標」面板開啟後，會顯示可作為匯入目標的磁碟區候選清單。由於區塊大小、容量或磁碟區可用性等原因，某些磁碟區可能不會顯示在候選清單中。

. 從表格中選擇 E-Series 儲存系統上的目標磁碟區。如有需要，可使用滑桿變更匯入優先權。按一下 *Next* 。在下一個對話方塊中輸入 `continue`，然後按一下 *Continue* ，以確認操作。
+
如果目標磁碟區的容量大於來源磁碟區，則多餘的容量不會報告給連接到 E-Series 系統的主機。若要使用新增容量，必須在匯入操作完成並中斷連線後，在主機上執行檔案系統擴充操作。

+
在對話方塊中確認配置後，將顯示 Review 面板。

. 在「審核」面板中、確認設定正確、然後按一下 *完成* 以開始匯入。
+
另一個對話方塊開啟，詢問您是否要啟動另一個匯入。

. 如有需要，請按一下 *Yes* 以建立另一個遠端儲存匯入。按一下 *Yes* 將返回 Configure Source 面板的 *Step 1a*，您可以在其中選擇現有組態或新增組態。如果您不想建立另一個匯入，請按一下 *No* 退出對話方塊。
+
匯入過程開始後，整個目標磁碟區將被複製的資料覆蓋。如果在此過程中主機向目標磁碟區寫入任何新資料，則該新資料將傳播回遠端裝置（來源磁碟區）。

. 在「遠端儲存」面板下的「檢視作業」對話方塊中檢視作業進度。


.結果
完成匯入作業所需的時間取決於遠端儲存系統的大小、匯入的優先順序設定，以及兩個儲存系統及其相關磁碟區上的 I/O 負載量。

匯入完成後，本機磁碟區將成為遠端儲存裝置的副本。

.完成後
當您準備中斷兩個磁碟區之間的關聯時，請在 Operations In Progress 檢視中選取匯入物件上的 *Disconnect* 。中斷關聯後，本機磁碟區的效能將恢復正常，不再受遠端連線的影響。
