---
permalink: sm-storage/schedule-snapshot-images.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, schedule, snapshot, images 
summary: 您可以建立快照排程，以便在基礎磁碟區出現問題時進行還原，並執行排程備份。基礎磁碟區或快照一致性群組的快照可以按每日、每週或每月排程建立，可在一天中的任何時間建立。 
---
= 在 SANtricity System Manager 中排程快照映像
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立快照排程，以便在基礎磁碟區出現問題時進行還原，並執行排程備份。基礎磁碟區或快照一致性群組的快照可以按每日、每週或每月排程建立，可在一天中的任何時間建立。

.開始之前
基礎磁碟區必須為最佳狀態。

.關於此任務
本任務說明如何為現有的快照一致性群組或基礎磁碟區建立快照排程。

[NOTE]
====
您也可以在建立基本磁碟區或快照一致性群組的快照映像的同時建立快照排程。

====
.步驟
. 若要建立快照排程，請執行下列其中一項操作：
+
** 選擇選單：Storage [ Volumes ]。
+
選擇此快照排程的物件（磁碟區或快照一致性群組）、然後選取功能表：複製服務 [建立快照排程]。

** 選擇選單：Storage [ Snapshots ]。
+
選擇 *Schedules* 選項卡，然後按一下 *Create*。



. 選擇此快照排程的物件（磁碟區或快照一致性群組），然後按一下 *Next* 。
+
此時會出現「建立快照排程」對話方塊。

. 執行下列其中一項動作：
+
** *使用先前從另一個快照物件定義的排程*。
+
確保已顯示進階選項。點選 *Show more options*。點選 *Import Schedule*，選擇包含要匯入計劃表的對象，然後點選 *Import*。

** *修改基本或進階選項*。
+
在對話方塊的右上角，按一下 *Show more options* 以顯示所有選項，然後參考下表。



+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
*基本設定*



 a| 
選擇天數
 a| 
選擇一週中的特定日期以拍攝快照影像。



 a| 
開始時間
 a| 
從下拉清單中選擇每日快照的新開始時間（以半小時為單位遞增）。預設開始時間比目前時間晚半小時。



 a| 
時區
 a| 
從下拉清單中選擇陣列的時區。



 a| 
*進階設定*



 a| 
日 / 月
 a| 
請選擇下列其中一個選項：

** *每日 / 每週* -- 選擇要同步快照的特定日期。如果您想要設定每日排程，您也可以選取右上角的 *Select all days* 核取方塊。
** *每月 / 每年* -- 選擇要同步快照的月份。在 *On day(s)* 欄位中，輸入同步發生的日期。有效輸入為 *1* 至 *31* 以及 *Last*。您可以使用逗號或分號分隔多個日期。對於包含日期，請使用連字符。例如：1,3,4,10-15,Last。如果您需要按月同步，您也可以選取右上角的 *Select all months* 複選框。




 a| 
開始時間
 a| 
從下拉清單中選擇每日快照的新開始時間（以半小時為單位遞增）。預設開始時間比目前時間晚半小時。



 a| 
時區
 a| 
從下拉清單中選擇陣列的時區。



 a| 
每日快照次數 / 快照間隔時間
 a| 
選取每天要建立的快照映像數量。如果選取多個快照映像，也請選取快照映像之間的時間間隔。對於多個快照映像，請確保您有足夠的保留容量。



 a| 
現在就建立快照映像嗎？
 a| 
選取此核取方塊，即可在排程的自動映像之外建立即時映像。



 a| 
開始 / 結束日期或無結束日期
 a| 
請輸入同步開始日期。同時請輸入結束日期，或選擇 *無結束日期*。

|===
====
. 執行下列其中一項動作：
+
** 如果物件是快照一致性群組，請按一下 *Create* 以接受設定並建立排程。
** 如果物件是磁碟區，請按一下 *Next* 為快照映像分配保留容量。
+
磁碟區候選表僅顯示支援指定保留容量的候選磁碟區。保留容量是用於任何複製服務作業和儲存物件的實體分配容量。主機無法直接讀取。



. 使用微調框分配快照影像的預留容量。執行下列其中一項操作：
+
** *接受預設設定。*
+
使用此建議選項，以預設設定為快照映像分配保留容量。

** *分配您自己的預留容量設定，以滿足您的資料儲存需求。*
+
如果您變更預設保留容量設定，請按一下 *Refresh Candidates* 以重新整理您指定之保留容量的候選清單。

+
請依照以下準則分配保留容量：

+
*** 預留容量的預設值為基本磁碟區容量的 40%。通常這個容量就足夠了。
*** 所需容量會根據磁碟區的 I/O 寫入頻率和大小、以及快照映像收集的數量和持續時間而有所不同。




. 按一下 *Next* 。
+
「編輯設定」對話方塊隨即出現。

. 根據需要編輯快照排程的設定，然後按一下 *Finish* 。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
*Snapshot 影像數量限制*



 a| 
啟用自動刪除快照影像功能時…
 a| 
如果您希望快照影像在達到指定數量後自動刪除，請選取此核取方塊；使用微調方塊變更此數量限制。如果您取消選取此核取方塊，則快照影像的建立數量將在 32 張後停止。



 a| 
*保留容量設定*



 a| 
有以下情況請通知我⋯
 a| 
使用微調框調整系統在排程的保留容量即將用完時發送警示通知的百分比點。

當排程的保留容量超過指定臨界值時，請使用提前通知來增加保留容量或刪除不必要的物件，以免剩餘空間用盡。



 a| 
完全保留容量的原則
 a| 
請選擇以下其中一項原則：

** *清除最舊的 Snapshot 映像* -- 系統會自動清除最舊的 Snapshot 映像，從而釋放 Snapshot 映像保留容量，以便在 Snapshot 群組內重複使用。
** *拒絕寫入基本磁碟區* -- 當預留容量達到其定義的最大百分比時，系統將拒絕任何觸發預留容量存取的基本磁碟區 I/O 寫入請求。


|===
====

