---
permalink: sm-storage/snapshot-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, snapshot, terms 
summary: 了解快照術語如何應用於您的儲存陣列。 
---
= 了解 SANtricity 軟體中的快照術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解快照術語如何應用於您的儲存陣列。

[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
快照功能
 a| 
快照功能用於建立和管理磁碟區的映像。



 a| 
快照映像
 a| 
快照映像是磁碟區資料的邏輯副本，在特定時間點擷取。與還原點類似，快照映像可讓您回滾到已知良好的資料集。雖然主機可以存取快照映像，但不能直接讀取或寫入。



 a| 
基礎磁碟區
 a| 
基礎磁碟區是建立快照映像的來源。它可以是厚磁碟區或精簡磁碟區，通常分配給一台主機。基礎磁碟區可以位於磁碟區群組或磁碟集區中。



 a| 
快照磁碟區
 a| 
快照磁碟區可讓主機存取快照映像中的資料。快照磁碟區擁有自己的保留容量，可儲存對基礎磁碟區所做的任何修改，而不會影響原始快照映像。



 a| 
快照群組
 a| 
快照群組是來自單一基礎磁碟區的快照映像集合。



 a| 
預留容量磁碟區
 a| 
預留容量磁碟區會追蹤基礎磁碟區的哪些資料區塊被覆寫，以及這些區塊的保留內容。



 a| 
快照排程
 a| 
快照排程是用於自動建立快照映像的時間表。透過該排程，您可以控制映像建立的頻率。



 a| 
Snapshot 一致性群組
 a| 
快照一致性群組是指在建立快照映像時被視為一個整體的多個磁碟區的集合。每個磁碟區都有自己的快照映像，但所有映像都是在同一時間點建立的。



 a| 
快照一致性群組成員磁碟區
 a| 
屬於快照一致性群組的每個磁碟區稱為成員磁碟區。將磁碟區新增至快照一致性群組時、System Manager 會自動建立與該成員磁碟區對應的新快照群組。



 a| 
復原
 a| 
復原是將基礎磁碟區中的資料還原到先前某個時間點的程序。



 a| 
預留容量
 a| 
預留容量是指用於任何複製服務作業和儲存物件的實體分配容量。主機無法直接讀取該容量。

|===