---
permalink: sm-storage/start-snapshot-image-rollback-for-consistency-group-member-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, start, snapshot, image, rollback, snapshot, consistency, group, member, volumes 
summary: 您可以執行回滾操作，將 Snapshot 一致性群組成員磁碟區的內容變更為與 Snapshot 映像中儲存的內容相符。 
---
= 在 SANtricity System Manager 中啟動快照一致性群組成員磁碟區的快照映像復原
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以執行回滾操作，將 Snapshot 一致性群組成員磁碟區的內容變更為與 Snapshot 映像中儲存的內容相符。

復原作業不會變更與 Snapshot 一致性群組相關聯的 Snapshot 映像內容。

.開始之前
* 有足夠的保留容量可以啟動復原作業。
* 選定的快照映像為最佳，選定的磁碟區為最佳。
* 所選磁碟區目前沒有正在進行的復原作業。


.關於此任務
復原啟動序列可讓您在 Snapshot 一致性群組的 Snapshot 映像上啟動復原，同時提供新增儲存容量的選項。您一次只能為一個 Snapshot 一致性群組啟動一個復原作業。

[NOTE]
====
主機可以立即存取新回滾的磁碟區，但回滾開始後，現有成員磁碟區將不再允許主機進行讀寫存取。您可以在開始回滾之前建立成員磁碟區的快照映像，以保留回滾前的基礎磁碟區用於復原。

====
啟動 snapshot 一致性群組 snapshot 映像回滾的過程是一個多步驟程序。



== 步驟 1：選擇成員

您必須選擇要回滾的成員磁碟區。

.步驟
. 選擇選單：Storage [ Snapshots ]。
. 選擇 *Snapshot Images* 標籤。
. 選擇 Snapshot 一致性群組 Snapshot 映像，然後選擇功能表：Rollback [Start]。
+
Start Rollback 對話方塊隨即出現。

. 選擇成員磁碟區。
. 按一下 *Next* ，然後執行下列其中一項作業：
+
** 如果任何選定的成員磁碟區與多個儲存快照映像的預留容量物件關聯，則會顯示「檢視容量」對話方塊。轉到 <<步驟 2：檢閱容量>>。
** 如果所選成員磁碟區均未與多個儲存快照映像的預留容量物件關聯，則會顯示「編輯優先順序」對話方塊。轉到 <<步驟 3：編輯優先順序>>。






== 步驟 2：檢閱容量

如果您選擇了與多個預留容量物件關聯的成員磁碟區（例如快照群組和預留容量磁碟區），則可以檢視並增加回滾磁碟區的預留容量。

.步驟
. 對於任何預留容量非常低（或為零）的成員磁碟區，請點擊 *編輯* 欄中的 *增加容量* 連結。
+
此時會顯示「增加預留容量」對話方塊。

. 使用微調框調整容量百分比，然後按一下 *Increase* 。
+
如果包含所選儲存物件的儲存池或磁碟區群組上沒有可用容量，且儲存陣列具有未指派容量，則可以新增容量。您可以建立新的儲存池或磁碟區群組，並使用該儲存池或磁碟區群組上的新可用容量重試此操作。

. 點擊 *Next*，然後轉到 <<步驟 3：編輯優先順序>>。
+
Edit Priority 對話方塊隨即出現。





== 步驟 3：編輯優先順序

如有需要，您可以編輯復原作業的優先順序。

.關於此任務
回滾優先權決定了有多少系統資源會分配給回滾操作,而這會犧牲系統效能。

.步驟
. 根據需要使用滑桿調整復原優先順序。
. 確認您要執行此操作，然後按一下 *Finish* 。


.結果
System Manager 執行下列動作：

* 使用選定快照映像中儲存的內容還原快照一致性群組成員磁碟區。
* 使回滾的磁碟區立即可供主機存取。您無需等待回滾作業完成。


.完成後
選擇功能表：Home [ View Operations in Progress ] 以檢視復原作業的進度。

如果回滾操作失敗，操作將暫停。您可以恢復暫停的操作，如果仍然失敗，請按照 Recovery Guru 程序解決問題或聯絡技術支援。
