---
permalink: sm-storage/start-snapshot-image-rollback-for-base-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, start, snapshot, image, rollback, base, volume 
summary: 您可以執行回滾操作，將基礎磁碟區的內容變更為與快照映像中儲存的內容一致。回滾操作不會變更與基礎磁碟區關聯的快照映像的內容。 
---
= 在 SANtricity System Manager 中啟動基礎磁碟區的快照映像復原
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以執行回滾操作，將基礎磁碟區的內容變更為與快照映像中儲存的內容相符。

復原作業不會變更與基礎磁碟區相關聯的快照映像內容。

.開始之前
* 有足夠的保留容量可以啟動復原作業。
* 選定的快照映像為最佳，選定的磁碟區為最佳。
* 所選磁碟區目前沒有正在進行的復原作業。


.關於此任務
復原啟動順序可讓您在基礎磁碟區的快照映像上開始復原，同時提供新增儲存容量的選項。您一次無法為一個基礎磁碟區啟動多個復原作業。

[NOTE]
====
主機可以立即存取新回滾的基礎磁碟區，但回滾開始後，主機將無法對現有基礎磁碟區進行讀寫存取。您可以在開始回滾之前建立基礎磁碟區的快照，以便保留回滾前的基礎磁碟區用於復原。

====
.步驟
. 選擇選單：Storage [ Snapshots ]。
. 選擇 *Snapshot Images* 標籤。
. 選擇快照映像，然後選擇功能表：復原 [開始]。
+
隨即顯示「確認開始回滾」對話方塊。

. *可選：* 如有必要，請選擇 *Increase Capacity* 選項。
+
此時會顯示「增加預留容量」對話方塊。

+
.. 使用微調框調整容量百分比。
+
如果包含所選儲存物件的儲存池或磁碟區群組上沒有可用容量，且儲存陣列具有未指派容量，則可以新增容量。您可以建立新的儲存池或磁碟區群組，然後使用該儲存池或磁碟區群組上的新可用容量重試此操作。

.. 點擊 *Increase* 。


. 確認要執行此操作，然後按一下 *Rollback* 。


.結果
System Manager 執行下列動作：

* 使用選定快照映像中儲存的內容還原磁碟區。
* 使回滾的磁碟區立即可供主機存取。您無需等待回滾作業完成。


.完成後
選擇功能表：Home [ View Operations in Progress ] 以檢視復原作業的進度。

如果回滾操作失敗，操作將暫停。您可以恢復暫停的操作，如果仍然失敗，請按照 Recovery Guru 程序解決問題或聯絡技術支援。
