---
permalink: sm-storage/types-of-copy-volume-operations.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy, volume, 
summary: 您可以執行離線 Copy Volume 操作或線上 Copy Volume 操作。離線操作從來源磁碟區讀取資料並將其複製到目標磁碟區。線上操作使用快照磁碟區作為來源，並將其資料複製到目標磁碟區。 
---
= 了解 SANtricity 軟體中的 Copy Volume 操作類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以執行 _offline_ Copy Volume 操作或 _online_ Copy Volume 操作。offline 操作從來源磁碟區讀取資料並將其複製到目標磁碟區。online 操作使用 snapshot 磁碟區作為來源，並將其資料複製到目標磁碟區。

為確保資料完整性，在任何類型的 Copy Volume 作業期間，對目標磁碟區的所有 I/O 活動都會暫停。發生此暫停是因為目標磁碟區上的資料狀態在程序完成之前不一致。

下面將介紹離線和線上 Copy Volume 操作。



== 離線複製磁碟區操作

離線 Copy Volume 關係存在於來源磁碟區和目標磁碟區之間。離線複製從來源磁碟區讀取資料並將其複製到目標磁碟區，同時在複製進行期間暫停對來源磁碟區的所有更新。暫停所有對來源磁碟區的更新是為了防止在目標磁碟區上出現時間順序不一致的情況。

[cols="25h,~"]
|===
2+| 您需要了解的離線複製作業相關資訊 


 a| 
讀取和寫入請求
 a| 
* 參與離線複製的來源磁碟區在 Copy Volume 操作狀態為「進行中」或「掛起」時，可用於唯讀 I/O 活動。
* 離線複製完成後即允許寫入請求。
* 為防止出現寫入保護錯誤訊息，請勿存取狀態為「正在進行」的「複製磁碟區」作業中的來源磁碟區。




 a| 
日誌檔案系統
 a| 
* 如果來源磁碟區已使用日誌檔案系統進行格式化，則任何向來源磁碟區發出讀取要求的嘗試都可能被儲存陣列控制器拒絕，並可能出現錯誤訊息。
* 日誌檔案系統驅動程式在嘗試發出讀取請求之前會先發出寫入請求。控制器會拒絕該寫入請求，並且由於寫入請求被拒絕，讀取請求可能無法發出。這種情況可能會導致出現錯誤訊息，指示來源磁碟區已被寫入保護。
* 為防止此問題，請勿在 Copy Volume 操作狀態為「進行中」時嘗試存取正在參與離線複製的來源磁碟區。


|===


== 線上複製磁碟區作業

線上 Copy Volume 關係是指快照磁碟區和目標磁碟區之間的關係。當來源磁碟區處於線上狀態且可用於資料寫入時、您可以啟動 Copy Volume 作業。此功能透過建立磁碟區的快照並將該快照用作複製的實際來源磁碟區來實現。

當您對來源磁碟區啟動「複製磁碟區」操作時，System Manager 會建立基礎磁碟區的快照映像，並在基礎磁碟區快照映像和目標磁碟區之間建立複製關係。使用快照映像作為來源磁碟區，可以讓儲存陣列在複製過程中繼續向來源磁碟區寫入資料。

在線上複製作業期間，由於寫入時複製程序，效能會受到影響。線上複製完成後，基礎磁碟區效能將恢復。

[cols="25h,~"]
|===
2+| 關於線上複製操作您需要了解的資訊 


 a| 
可以使用哪些類型的磁碟區？
 a| 
* 建立時間點映像所依據的磁碟區稱為基礎磁碟區，它必須是儲存陣列上的標準磁碟區或精簡磁碟區。
* 目標磁碟區可以是磁碟區群組中的標準磁碟區，也可以是儲存池中的標準磁碟區。目標磁碟區不能是精簡磁碟區或快照群組中的基礎磁碟區。
* 您可以使用線上 Copy Volume 功能將資料從精簡磁碟區複製到相同儲存陣列中儲存池內的標準磁碟區。但您不能使用 Copy Volume 功能將資料從標準磁碟區複製到精簡磁碟區。




 a| 
基礎磁碟區效能
 a| 
* 如果用作複製來源的快照磁碟區處於活動狀態，則由於寫入時複製操作，基礎磁碟區的效能會降低。複製完成後，快照將被停用，基礎磁碟區的效能將恢復。即使快照已停用，預留容量磁碟區和複製關係仍然保持不變。




 a| 
建立的磁碟區類型
 a| 
* 線上複製作業期間會建立快照磁碟區和保留容量磁碟區。
* 快照磁碟區並不是包含資料的實際磁碟區；而是對特定時間磁碟區上所包含資料的參照。
* 對於每個拍攝的快照，都會建立一個預留容量磁碟區來保存快照資料。此預留容量磁碟區僅用於管理快照映像。




 a| 
預留容量磁碟區
 a| 
* 在修改來源磁碟區上的資料區塊之前，會將要修改的區塊內容複製到保留容量磁碟區以進行安全保存。
* 因為預留容量磁碟區儲存的是原始資料在這些資料區塊中的副本，所以對這些資料區塊的進一步變更只會寫入來源磁碟區。
* 線上複製作業比完整實體複製作業佔用更少的磁碟空間，因為只有自快照以來發生變更的資料區塊才會儲存在保留容量磁碟區中。


|===