---
permalink: sm-storage/volume-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, terms 
summary: 了解磁碟區術語如何套用至您的儲存陣列。 
---
= 了解 SANtricity 軟體中的磁碟區術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解磁碟區術語如何套用至您的儲存陣列。



== 所有磁碟區類型

[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
已分配容量
 a| 
您可以使用分配的容量來建立磁碟區和進行複製服務作業。

對於厚磁碟區，已分配容量和報告容量相同；但對於精簡磁碟區，兩者則不同。對於厚磁碟區，實體分配空間等於報告給主機的空間。對於精簡磁碟區，報告容量是報告給主機的容量，而已分配容量是目前分配用於寫入資料的磁碟機空間量。



 a| 
應用程式
 a| 
應用程式是指諸如 SQL Server 或 Exchange 之類的軟體。您可以定義一個或多個工作負載來支援每個應用程式。對於某些應用程式，系統會自動推薦一種能夠最佳化儲存的磁碟區配置。磁碟區配置中包含 I/O 類型、區段大小、控制器所有權以及讀寫快取等特性。



 a| 
容量
 a| 
容量是指一個磁碟區中可以儲存的資料量。



 a| 
控制器所有權
 a| 
控制器所有權定義了被指定為磁碟區的擁有者或主控制器的控制器。一個磁碟區可以有一個首選控制器（A 或 B），該控制器「擁有」該磁碟區。當工作負載在控制器之間轉移時，磁碟區的所有權會使用 Automatic Load Balancing 功能自動調整，以修正任何負載平衡問題。Automatic Load Balancing 提供自動化的 I/O 工作負載平衡，並確保來自主機的傳入 I/O 流量在兩個控制器之間進行動態管理和平衡。



 a| 
動態快取讀取預先擷取
 a| 
動態快取讀取預取允許控制器在從磁碟機讀取資料區塊到快取的同時，將額外的順序資料區塊複製到快取中。這種快取機制提高了後續資料請求能夠從快取中獲取所需資料的機率。動態快取讀取預取對於使用順序 I/O 的多媒體應用至關重要。預取到快取中的資料速率和資料量會根據主機讀取的速率和請求大小自動調整。隨機存取不會導致資料預取到快取中。停用讀取快取時，此功能無效。

對於精簡磁碟區，動態快取讀取預先擷取始終處於停用狀態，且無法變更。



 a| 
可用容量區域
 a| 
可用容量區域是指刪除磁碟區或在建立磁碟區時未使用所有可用容量而產生的剩餘容量。在具有一個或多個可用容量區域的磁碟區群組中建立磁碟區時,該磁碟區的容量將限制為該磁碟區群組中最大的可用容量區域。例如,如果一個磁碟區群組總共有 15 GiB 的可用容量,而最大的可用容量區域為 10 GiB,則您可以建立的最大磁碟區大小為 10 GiB。

透過整合可用容量、您可以利用磁碟區群組中的最大可用容量來建立額外的磁碟區。



 a| 
主機
 a| 
主機是向儲存陣列上的磁碟區發送 I/O 的伺服器。



 a| 
主機叢集
 a| 
主機叢集是一組主機。建立主機叢集可以方便地將相同的磁碟區指派給多個主機。



 a| 
熱備援磁碟機
 a| 
熱備用磁碟機僅在磁碟區群組中支援。熱備用磁碟機不包含任何資料，在磁碟區群組中的 RAID 1、RAID 3、RAID 5 或 RAID 6 磁碟區中的磁碟機發生故障時，它會充當待命磁碟機。熱備用磁碟機為您的儲存陣列增加了另一層備援。



 a| 
LUN
 a| 
邏輯單元號碼（LUN）是指派給主機用於存取磁碟區的位址空間的編號。磁碟區以 LUN 的形式作為容量呈現給主機。

每台主機都有自己的 LUN 位址空間。因此，同一個 LUN 可以被不同的主機用來存取不同的磁碟區。



 a| 
媒體掃描
 a| 
媒體掃描提供了一種在正常讀取或寫入磁碟機之前偵測磁碟機媒體錯誤的方法。媒體掃描作為背景操作執行，並掃描已定義使用者磁碟區中的所有資料和備援資訊。



 a| 
命名空間
 a| 
命名空間是格式化為區塊存取的 NVM 儲存設備。它類似於 SCSI 中的邏輯單元，後者對應於儲存陣列中的磁碟區。



 a| 
資源池
 a| 
儲存池是一組邏輯上分組的磁碟機。您可以使用儲存池建立一個或多個可供主機存取的磁碟區。（您可以從儲存池或磁碟區組建立磁碟區。）



 a| 
資源池或磁碟區群組容量
 a| 
儲存池、磁碟區或磁碟區群組容量是指儲存陣列中已指派給儲存池或磁碟區群組的容量。此容量用於建立磁碟區，並滿足複製服務作業和儲存物件的各種容量需求。



 a| 
讀取快取
 a| 
讀取快取是一個緩衝區，用於儲存從磁碟機讀取的資料。讀取操作所需的資料可能已經存在於快取中（來自先前的操作），這樣就無需存取磁碟機。資料會一直保留在讀取快取中，直到被刷新。



 a| 
報告容量
 a| 
已報告容量是指已報告給主機且主機可以存取的容量。

對於厚磁碟區，報告容量和已分配容量相同；但對於精簡磁碟區，兩者則不同。對於厚磁碟區，實體分配空間等於報告給主機的空間。對於精簡磁碟區，報告容量是報告給主機的容量，而已分配容量是目前分配用於寫入資料的磁碟機空間量。



 a| 
區段大小
 a| 
區段是指儲存陣列在條帶（RAID 群組）中移至下一個磁碟機之前、儲存在磁碟機上的資料量（以 KB (KiB) 為單位）。區段大小等於或小於 Volume 群組的容量。區段大小是固定的，無法針對集區進行變更。



 a| 
等量磁碟區分割
 a| 
條帶化是一種在儲存陣列上儲存資料的方式。條帶化將資料流分割成特定大小（稱為「區塊大小」）的資料區塊，然後將這些資料區塊逐一寫入各個磁碟機。這種資料儲存方式用於將資料分佈並儲存在多個實體磁碟機上。條帶化與 RAID 0 同義，它將資料分散儲存在 RAID 群組中的所有磁碟機上，且不使用奇偶校驗。



 a| 
磁碟區
 a| 
磁碟區是應用程式、資料庫和檔案系統儲存資料的容器。它是為主機存取儲存陣列上的儲存設備而建立的邏輯元件。



 a| 
Volume 指派
 a| 
磁碟區指派是指將主機 LUN 指派給磁碟區的方式。



 a| 
磁碟區名稱
 a| 
磁碟區名稱是建立磁碟區時指派給該磁碟區的一串字元。您可以接受預設名稱，也可以提供更具描述性的名稱，以指示磁碟區中儲存的資料類型。



 a| 
磁碟區群組
 a| 
磁碟區群組是用來存放具有共用特徵的磁碟區的容器。磁碟區群組具有已定義的容量和 RAID 等級。您可以使用磁碟區群組建立一個或多個可供主機存取的磁碟區。（您可以從磁碟區群組或儲存池建立磁碟區。）



 a| 
工作負載
 a| 
工作負載是支援應用程式的儲存物件。您可以為每個應用程式定義一個或多個工作負載（或執行個體）。對於某些應用程式，系統會將工作負載配置為包含具有相似底層磁碟區特性的磁碟區。這些磁碟區特性會根據工作負載支援的應用程式類型進行最佳化。例如，如果您建立了支援 Microsoft SQL Server 應用程式的工作負載，然後隨後為該工作負載建立磁碟區，則底層磁碟區特性會針對 Microsoft SQL Server 進行最佳化。



 a| 
寫入快取
 a| 
寫入快取是一個緩衝區，用於儲存來自主機但尚未寫入磁碟機的資料。資料會一直保留在寫入快取中，直到被寫入磁碟機為止。寫入快取可以提高 I/O 效能。



 a| 
具鏡像功能的寫入快取
 a| 
寫入快取鏡像是指將寫入一個控制器快取記憶體的資料也寫入另一個控制器的快取記憶體。因此，如果一個控制器發生故障，另一個控制器可以完成所有未完成的寫入操作。寫入快取鏡像僅在啟用寫入快取且存在兩個控制器時可用。建立磁碟區時，寫入快取鏡像為預設設定。



 a| 
無需電池的寫入快取
 a| 
「無電池寫入快取」設定允許在電池缺失、故障、完全放電或未充滿電的情況下繼續寫入快取。通常不建議選擇「無電池寫入快取」，因為斷電時資料可能會遺失。通常情況下，控制器會暫時關閉寫入快取，直到電池充滿電或更換故障電池。

|===


== 適用於精簡磁碟區

[NOTE]
====
System Manager 不提供建立精簡磁碟區的選項。如果您想要建立精簡磁碟區，請使用命令列介面（CLI）。

====
[NOTE]
====
EF600/EF600C 或 EF300/EF300C 儲存系統不提供精簡磁碟區。

====
[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
分配容量限制
 a| 
分配容量限制是指精簡磁碟區的分配實體容量可以成長的上限。



 a| 
寫入容量
 a| 
已寫入容量是指已從分配給精簡磁碟區的保留容量中寫入的容量。



 a| 
警告閾值
 a| 
您可以設定警告閾值警報，當精簡磁碟區的分配容量達到百分比已滿（警告閾值）時，將發出該警報。

|===