---
permalink: sm-mirroring/asynchronous-mirror-status.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, asynchronous, mirror, status, consistency, group, 
summary: 鏡像狀態定義了鏡像一致性群組和鏡像磁碟區配對的狀態。 
---
= 在 SANtricity System Manager 中檢視非同步鏡像狀態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
鏡像狀態定義了鏡像一致性群組和鏡像磁碟區配對的狀態。



== 鏡像一致性群組的狀態

[cols="25h,~"]
|===
| 狀態 | 說明 


 a| 
同步 （初始同步）
 a| 
鏡像磁碟區配對之間已完成的初始資料同步進度。

在初始同步期間，磁碟區可能會轉換到以下狀態：Degraded / Failed / Optimal / Unknown。



 a| 
同步 (間隔同步)
 a| 
鏡像磁碟區配對之間已完成的定期資料同步進度。



 a| 
系統已暫停
 a| 
儲存系統暫停鏡像一致性群組層級上所有鏡像配對的資料同步。

鏡像一致性群組中至少有一個鏡像配對處於停止或失敗狀態。



 a| 
使用者已暫停
 a| 
在鏡像一致性群組層級，使用者暫停所有鏡像配對的資料同步。

此狀態有助於減少將本機儲存陣列上的任何變更資料複製到遠端儲存陣列時、可能對主機應用程式造成的任何效能影響。



 a| 
暫停
 a| 
由於存取遠端儲存陣列時發生錯誤，資料同步程序已暫時暫停。



 a| 
孤立
 a| 
當一致性鏡像群組中的成員磁碟區在一致性鏡像群組的一側（主要端或次要端）被移除，但在另一側未被移除時，就會出現孤立的鏡像配對磁碟區。

當陣列間通訊恢復且鏡像組態的兩側協調鏡像參數時，即可偵測到孤立的鏡像配對磁碟區。

您可以刪除鏡像配對來修正孤立鏡像配對狀態。



 a| 
角色變更待定 / 進行中
 a| 
鏡像一致性群組之間的角色變更處於擱置中或進行中。

角色互換變更（變成主要角色或次要角色）會影響所選鏡像一致性群組內的所有非同步鏡像配對。

您可以取消待處理的角色變更，但不能取消正在進行的角色變更。



 a| 
角色衝突
 a| 
在角色變更作業期間，由於本機儲存陣列和遠端儲存陣列之間的通訊問題，鏡射一致性群組之間發生角色衝突。

通訊問題解決後，會出現角色衝突。請使用 Recovery Guru 來解決此錯誤。

解決角色衝突時，不允許強制升級。

|===


== 鏡像配對的狀態

鏡像配對的狀態指示主磁碟區和次要磁碟區上的資料是否同步。

[cols="25h,~"]
|===
| 狀態 | 說明 


 a| 
正在同步
 a| 
鏡像配對之間已完成的初始或定期資料同步進度。

同步分為兩種：初始同步和週期性同步。初始同步進度也會顯示在 Long Running Operations 對話方塊中。



 a| 
最佳
 a| 
鏡像配對中的磁碟區已同步，這表示儲存陣列之間的連線正常運作，且每個磁碟區都處於所需的工作狀態。



 a| 
未完成
 a| 
由於鏡像配對建立序列是在 System Manager 不支援的儲存陣列上啟動的，且鏡像配對尚未在次要儲存陣列上完成，因此遠端儲存陣列上的非同步鏡像配對不完整。

當將磁碟區新增至遠端儲存陣列上的鏡像一致性群組時，鏡像配對建立程序即完成。此磁碟區會成為非同步鏡像配對中的次要磁碟區。

如果遠端儲存陣列由 System Manager 管理，則鏡像配對會自動完成。



 a| 
失敗
 a| 
由於主磁碟區、次要磁碟區或鏡像保留容量發生故障,非同步鏡像作業無法正常運作。



 a| 
孤立
 a| 
當一致性鏡像群組中的成員磁碟區在一致性鏡像群組的一側（主要端或次要端）被移除，但在另一側未被移除時，就會出現孤立的鏡像配對磁碟區。

當兩個儲存陣列之間的通訊恢復，並且鏡像配置的兩側協調鏡像參數時，即可偵測到孤立的鏡像配對磁碟區。

您可以刪除鏡像配對來修正孤立鏡像配對狀態。



 a| 
已停止
 a| 
由於鏡像一致性群組處於系統暫停狀態，因此鏡像配對處於停止狀態。

|===