---
permalink: sm-mirroring/complete-mirrored-pair-for-primary-volumes-created-on-legacy-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, complete, mirrored, pair, volumes, created, legacy, 
summary: 如果您在無法由 SANtricity System Manager 管理的舊型儲存陣列上建立了主要磁碟區，您可以使用 System Manager 在此陣列上建立次要磁碟區。 
---
= 在 SANtricity System Manager 中，為在舊系統上建立的主磁碟區完成鏡像配對
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您在 SANtricity System Manager 無法管理的傳統儲存陣列上建立了主磁碟區，則可以使用 SANtricity System Manager 在此陣列上建立次要磁碟區。

.關於此任務
您可以對使用不同介面的舊式陣列和可由 System Manager 管理的新式陣列執行非同步鏡像。

* 如果您在兩個使用 System Manager 的儲存陣列之間進行鏡像，則可以跳過此任務，因為您已經在鏡像配對建立序列中完成了鏡像配對。
* 在遠端儲存陣列上執行此工作。


.步驟
. 選擇功能表：Storage[Asynchronous Mirroring]。
. 選擇 *Mirrored Pair* 選項卡。
+
鏡像配對表隨即出現，並顯示與儲存陣列相關聯的所有鏡像配對。

. 找到狀態為「不完整」的鏡像對磁碟區，然後按一下鏡像對欄中顯示的 *完成鏡像對* 連結。
. 選擇以下其中一個選項按鈕，以決定要自動或手動完成鏡像配對建立順序：
+
** *Automatic* -- 建立新的輔助磁碟區。
+
選擇要建立次要磁碟區的現有儲存池或磁碟區群組，接受鏡像配對遠端的預設設定。使用此建議選項，以預設設定為次要磁碟區配置保留容量。

** *Manual* -- 選擇現有磁碟區。
+
定義輔助磁碟區的參數。

+
... 按一下 *Next* 以選取次要磁碟區。
... 選擇要用作次要磁碟區的現有磁碟區，然後按一下 *Next* 以配置保留容量。
... 分配預留容量。執行下列其中一項作業：
+
**** 接受預設設定。
+
預留容量的預設設定為基本磁碟區容量的 20% ，通常這個容量就足夠了。

**** 根據非同步鏡像相關的資料儲存需求、分配您自己的保留容量設定。
+
所需容量取決於對主磁碟區的 I/O 寫入頻率和大小，以及您需要保留該容量的時間。一般來說，如果滿足以下一個或兩個條件，則應選擇較大的預留容量：

+
***** 您打算長期保留鏡像配對。
***** 由於 I/O 活動頻繁，主磁碟區上很大一部分資料區塊將會發生變化。請使用歷史效能資料或其他作業系統公用程式來協助您確定主磁碟區的典型 I/O 活動。








. 選擇 *Complete* 。


.結果
System Manager 執行下列動作：

* 在遠端儲存陣列上建立次要磁碟區，並為鏡像配對的遠端端指派保留容量。
* 開始本機儲存陣列和遠端儲存陣列之間的初始同步。
* 如果被鏡像的磁碟區是精簡磁碟區，則在初始同步期間，只有已指派的資料區塊會傳送到次要磁碟區。此傳輸可減少完成初始同步所需傳輸的資料量。
* 在本機儲存陣列和遠端儲存陣列上為鏡像配對建立保留容量。

