---
permalink: sm-mirroring/faq-sync-mirroring.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= SANtricity System Manager 同步鏡像常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 非同步鏡像與同步鏡像有何不同？

非同步鏡像功能與同步鏡像功能在一個本質方面有所不同：它會捕獲來源磁碟區在特定時間點的狀態，並且只複製自上次映像擷取以來發生變化的資料。

採用同步鏡像時，主磁碟區的狀態並非在某個特定時間點被捕獲，而是將主磁碟區上的所有變更反映到輔助磁碟區。輔助磁碟區在每個時刻都與主磁碟區相同，因為在這種鏡像方式下，每次對主磁碟區進行寫入時，也會對輔助磁碟區進行寫入。只有當輔助磁碟區成功更新主磁碟區上所做的變更後，主機才會收到寫入成功的確認。

使用非同步鏡像時，遠端儲存陣列與本機儲存陣列並不完全同步，因此如果由於本機儲存陣列遺失而導致應用程式需要轉換到遠端儲存陣列，則可能會遺失一些交易。

鏡像功能比較：

[cols="1a,1a"]
|===
| 非同步鏡像 | 同步鏡像 


 a| 
* 複寫方法 *



 a| 
* *特定時間點*
+
鏡像操作可依需求進行，也可依使用者定義的排程自動進行。排程可以精確到分鐘。兩次同步之間的最小間隔為 10 分鐘。


 a| 
* *連續*
+
鏡像操作會自動持續執行，每次主機寫入資料時都會複製資料。





 a| 
* 預留容量 *



 a| 
* *多種*
+
每個鏡像配對都需要保留容量磁碟區。


 a| 
* *單一*
+
所有鏡像磁碟區都需要單一保留容量磁碟區。





 a| 
*溝通*



 a| 
* *iSCSI 與 Fibre Channel*
+
支援儲存陣列之間的 iSCSI 和 Fibre Channel 介面。


 a| 
* *Fibre Channel*
+
僅支援儲存陣列之間的 Fibre Channel 介面。





 a| 
*距離*



 a| 
* * 無限 *
+
支援本地儲存陣列和遠端儲存陣列之間幾乎無限的距離，距離通常僅受網路功能和通道擴充技術的限制。


 a| 
* *受限*
+
通常必須在距離本地儲存陣列約 10 公里（6.2 英里）的範圍內，才能滿足延遲和應用程式效能要求。



|===


== 同步鏡像 - 為什麼我看不到所有的磁碟區？

在為鏡像對選擇主磁碟區時，會顯示一個列表，其中列出了所有符合條件的磁碟區。

任何不符合使用條件的磁碟區都不會顯示在該清單中。磁碟區可能由於以下任何原因不符合使用條件：

* 該磁碟區是非標準磁碟區，例如快照磁碟區或精簡磁碟區。
* 磁碟區並不理想。
* 該磁碟區已參與鏡像關係。




== 同步鏡像 - 為什麼我在遠端儲存陣列上看不到所有磁碟區？

在遠端儲存陣列上選擇次要磁碟區時，會顯示一個列表，其中列出了該鏡像配對的所有合格磁碟區。

任何不符合使用條件的磁碟區都不會顯示在該清單中。磁碟區可能由於以下任何原因不符合使用條件：

* 該磁碟區是非標準磁碟區，例如快照磁碟區或精簡磁碟區。
* 磁碟區並不理想。
* 該磁碟區已參與鏡像關係。
* 如果您使用 Data Assurance (DA)，則主磁碟區和次要磁碟區必須具有相同的 DA 設定。
+
** 如果主磁碟區已啟用 DA，則次要磁碟區也必須啟用 DA。
** 如果主磁碟區未啟用 DA，則次要磁碟區也必須未啟用 DA。






== 同步鏡像 - 建立鏡像配對之前我需要瞭解哪些內容？

您可以在 SANtricity Unified Manager 介面中設定鏡像對，然後在 SANtricity System Manager 中管理這些鏡像對。

在建立鏡像配對之前、請遵循下列準則：

* 您必須有兩個儲存陣列。
* 每個儲存陣列必須有兩個控制器。
* 主陣列和次要陣列中的每個控制器都必須配置 Ethernet 管理連接埠，並且必須連接到您的網路。
* 本機和遠端儲存陣列透過 Fibre Channel 架構連接。
* 儲存陣列的最低韌體版本為 7.84。（它們可以運行不同的作業系統版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 遠端儲存陣列上必須有足夠的可用容量來建立等於或大於要鏡像的主磁碟區的輔助磁碟區。
* 您已安裝 Web Services Proxy 和 Unified Manager。鏡像配對已在 Unified Manager 介面中設定。
* 在 Unified Manager 中發現了這兩個儲存陣列。




== 同步優先順序對同步速率有何影響？

同步優先權定義了相對於系統效能，分配給同步活動的處理時間量。

主磁碟區的控制器擁有者在背景執行此操作。同時，控制器擁有者處理對主磁碟區的本機 I/O 寫入以及對輔助磁碟區的相關遠端寫入。由於重新同步會將控制器處理資源從 I/O 活動中轉移出去，因此重新同步可能會對主機應用程式的效能產生影響。

請記住以下準則，以幫助您確定同步優先順序可能需要多長時間，以及同步優先順序如何影響系統效能。

.關於同步優先順序率
[%collapsible]
====
可使用以下優先順序速率：

* 最低
* 低
* 中
* 高
* 最高


最低優先權速率有利於系統效能，但重新同步所需時間較長。最高優先權速率有利於重新同步，但系統效能可能會受到影響。

====
這些準則大致反映了優先順序之間的差異。

[cols="35h,~"]
|===
| 完全同步的優先順序速率 | 與最高同步速率相比所經過的時間 


 a| 
最低
 a| 
大約是最高優先順序速率的八倍。



 a| 
低
 a| 
大約是最高優先順序速率的六倍。



 a| 
中
 a| 
大約是最高優先權處理時間的 3.5 倍。



 a| 
高
 a| 
大約是最高優先順序速率的兩倍時長。

|===
磁碟區大小和主機 I/O 速率負載會影響同步時間比較。



== 為什麼建議使用手動同步策略？

建議手動重新同步，因為它可以讓您以最佳方式管理重新同步過程，從而為資料恢復提供最佳機會。

如果您使用 Automatic 重新同步策略，並且在重新同步期間出現間歇性通訊問題，則輔助磁碟區上的資料可能會暫時損壞。重新同步完成後，資料將會修復。
