---
permalink: sm-mirroring/faq-async-mirroring.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= SANtricity System Manager 非同步鏡像常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 非同步鏡像與同步鏡像有何不同？

非同步鏡像功能與同步鏡像功能在一個本質方面有所不同：它會捕獲來源磁碟區在特定時間點的狀態，並且只複製自上次映像擷取以來發生變化的資料。

採用同步鏡像時，主磁碟區的狀態並非在某個特定時間點被捕獲，而是將主磁碟區上的所有變更反映到輔助磁碟區。輔助磁碟區在每個時刻都與主磁碟區相同，因為在這種鏡像方式下，每次對主磁碟區進行寫入時，也會對輔助磁碟區進行寫入。只有當輔助磁碟區成功更新主磁碟區上所做的變更後，主機才會收到寫入成功的確認。

使用非同步鏡像時，遠端儲存陣列與本機儲存陣列並不完全同步，因此如果由於本機儲存陣列遺失而導致應用程式需要轉換到遠端儲存陣列，則可能會遺失一些交易。

鏡像功能比較：

[cols="1a,1a"]
|===
| 非同步鏡像 | 同步鏡像 


 a| 
* 複寫方法 *



 a| 
* *特定時間點*
+
鏡像操作可依需求進行，也可依使用者定義的排程自動進行。排程可以精確到分鐘。兩次同步之間的最小間隔為 10 分鐘。


 a| 
* *連續*
+
鏡像操作會自動持續執行，每次主機寫入資料時都會複製資料。





 a| 
* 預留容量 *



 a| 
* *多種*
+
每個鏡像配對都需要保留容量磁碟區。


 a| 
* *單一*
+
所有鏡像磁碟區都需要單一保留容量磁碟區。





 a| 
*溝通*



 a| 
* *iSCSI 與 Fibre Channel*
+
支援儲存陣列之間的 iSCSI 和 Fibre Channel 介面。


 a| 
* *Fibre Channel*
+
僅支援儲存陣列之間的 Fibre Channel 介面。





 a| 
*距離*



 a| 
* * 無限 *
+
支援本地儲存陣列和遠端儲存陣列之間幾乎無限的距離，距離通常僅受網路功能和通道擴充技術的限制。


 a| 
* *受限*
+
通常必須在距離本地儲存陣列約 10 公里（6.2 英里）的範圍內，才能滿足延遲和應用程式效能要求。



|===


== 為什麼我無法使用我選擇的鏡像功能？

鏡像功能在 SANtricity Unified Manager 介面中進行設定。

[NOTE]
====
EF600/EF600C 或 EF300/EF300C 儲存陣列不提供同步鏡像。

====
若要啟用和設定兩個陣列之間的鏡像，請驗證以下內容：

* Web Services Proxy 服務必須正在執行。（Unified Manager 與 Web Services Proxy 一起安裝在主機系統上。）
* Unified Manager 必須透過 HTTPS 連線在本機主機上執行。
* 您要用於鏡像的兩個儲存陣列必須在 Unified Manager 中被發現。
* Unified Manager 必須擁有儲存陣列的有效 SSL 憑證。您可以接受自簽名憑證，也可以從 Unified Manager 安裝由 CA 簽署的憑證。


如需配置說明，請參閱下列內容：

* link:../um-manage/create-asynchronous-mirrored-pair-um.html["在 Unified Manager 中建立非同步鏡像配對"]
* link:../um-manage/create-synchronous-mirrored-pair-um.html["建立同步鏡像配對（在 Unified Manager 中）"]




== 在建立鏡像一致性群組之前，我需要了解哪些資訊？

在建立鏡像一致性群組之前，請遵循下列準則。

[NOTE]
====
EF600/EF600C 或 EF300/EF300C 儲存系統不提供同步鏡像。

====
您可以在 Unified Manager 的「建立鏡像配對」精靈中建立一致性群組。

請滿足以下 Unified Manager 的要求：

* Web Services Proxy 服務必須正在執行。
* Unified Manager 必須透過 HTTPS 連線在本機主機上執行。
* Unified Manager 必須顯示儲存陣列的有效 SSL 憑證。您可以接受自簽憑證，或使用 Unified Manager 並瀏覽至功能表：Certificate[Certificate Management] 來安裝您自己的安全性憑證。


此外，請確保儲存陣列符合以下要求：

* 必須在 Unified Manager 中發現這兩個儲存陣列。
* 每個儲存陣列必須有兩個控制器。
* 主陣列和次要陣列中的每個控制器都必須配置 Ethernet 管理連接埠，並且必須連接到您的網路。
* 儲存陣列的最低韌體版本為 7.84。（它們可以運行不同的作業系統版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 您的本機和遠端儲存陣列透過 Fibre Channel 架構或 iSCSI 介面連接。




== 非同步鏡像 - 建立鏡像配對之前我需要了解哪些內容？

您可以在 SANtricity Unified Manager 介面中設定鏡像對，然後在 SANtricity System Manager 中管理這些鏡像對。

在建立鏡像配對之前、請遵循下列準則。

* 您必須有兩個儲存陣列。
* 每個儲存陣列必須有兩個控制器。
* 主陣列和次要陣列中的每個控制器都必須配置 Ethernet 管理連接埠，並且必須連接到您的網路。
* 您的本機和遠端儲存陣列透過 Fibre Channel 架構或 iSCSI 介面連接。
* 儲存陣列的最低韌體版本為 7.84。（它們可以運行不同的作業系統版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 遠端儲存陣列上必須有足夠的可用容量來建立等於或大於要鏡像的主磁碟區的輔助磁碟區。
* 您已安裝 Web Services Proxy 和 Unified Manager。鏡像配對已在 Unified Manager 介面中設定。
* 在 Unified Manager 中發現了這兩個儲存陣列。
* 您的儲存陣列必須包含至少一個鏡像一致性群組。您可以在 Unified Manager 的建立鏡像配對精靈中建立一致性群組。




== 在增加鏡像配對磁碟區的保留容量之前，我需要了解哪些資訊？

通常情況下，當您收到鏡像配對的預留容量即將用完的警告時，應增加預留容量。您只能以 8 GiB 的增量增加預留容量。

對於非同步鏡像操作，預留容量通常為基礎磁碟區的 20%。如果存在以下一個或兩個條件，請為預留容量選擇更大的容量：

* 您打算長期保留鏡像配對。
* 由於 I/O 活動頻繁，主磁碟區上很大一部分資料區塊將會發生變化。請使用歷史效能資料或其他作業系統公用程式來協助您確定主磁碟區的典型 I/O 活動。


您可以透過執行以下其中一項操作來增加鏡像配對的保留容量：

* 若要調整鏡像對磁碟區的容量百分比，請選擇選單：Storage[Pools and Volumes Groups]，然後按一下 *Reserved Capacity* 標籤。
* 使用資源池或磁碟區群組中可用的可用容量建立新磁碟區。
+
如果任何儲存池或磁碟區群組上都沒有可用容量，您可以將未配置的容量（以未使用的磁碟機形式）新增至儲存池或磁碟區群組。





== 為什麼我無法以要求的數量增加預留容量？

您只能以 4 GiB 的增量增加保留容量。

請查閱以下準則：

* 集區或磁碟區群組中必須有足夠的可用容量，以便在必要時進行擴充。
+
如果任何儲存池或磁碟區群組上都沒有可用容量、您可以將未指派的容量（以未使用的磁碟機形式）新增至儲存池或磁碟區群組。

* 資源池或磁碟區群組中的磁碟區必須處於最佳狀態，且不得處於任何修改狀態。
* 若要增加容量，池或磁碟區群組必須有可用容量。


對於非同步鏡像操作，預留容量通常為基本磁碟區的 20%。如果您認為基本磁碟區將發生許多變更，或儲存物件的複製服務作業的預期生命週期非常長，則應使用較高的百分比。



== 為什麼要變更此百分比？

快照操作的預留容量通常為基本磁碟區的 40%，非同步鏡像操作的預留容量通常為基本磁碟區的 20%。

通常情況下，這種容量就足夠了。所需的容量會根據對基礎磁碟區的 I/O 寫入頻率和大小，以及您計劃使用儲存物件的複製服務作業的時間長度而有所不同。

一般來說，如果滿足以下一個或兩個條件，請選擇較大的預留容量百分比：

* 如果特定儲存物件的複製服務作業生命週期非常長。
* 如果由於 I/O 活動頻繁，導致基礎磁碟區上大量資料區塊發生變化。請使用歷史效能資料或其他作業系統公用程式來協助您確定基礎磁碟區的典型 I/O 活動。




== 為什麼我看到不只一個保留容量候選項目？

如果儲存池或磁碟區群組中有多個磁碟區符合您為儲存物件選取的容量百分比數量，您將會看到多個候選項目。

您可以透過變更要為複製服務作業在基礎磁碟區上預留的實體磁碟機空間百分比來重新整理建議候選清單。系統會根據您的選擇顯示最佳候選方案。



== 為什麼表格中會顯示 Not Available 值？

當遠端儲存陣列上的資料無法顯示時，該表會列出 Not Available 值。

若要顯示遠端儲存陣列資料，請從 Unified Manager 啟動 System Manager。



== 為什麼我看不到我所有的資源池和 Volume 群組？

為非同步鏡像對建立次要磁碟區時，系統會顯示該非同步鏡像對所有符合資格的儲存池和磁碟區群組清單。任何不符合資格的儲存池或磁碟區群組都不會顯示在該清單中。

因以下任何原因，儲存池或磁碟區群組可能不符合資格。

* 池或磁碟區群組的安全功能不符。
* 資源池或磁碟區群組處於非最佳狀態。
* 儲存池或磁碟區群組的容量太小。




== 非同步鏡像 - 為什麼我看不到我的所有磁碟區？

在為鏡像對選擇主磁碟區時，會顯示一個列表，其中列出了所有符合條件的磁碟區。

任何不符合使用條件的磁碟區都不會顯示在該清單中。磁碟區可能由於以下任何原因不符合使用條件：

* 磁碟區並不理想。
* 該磁碟區已參與鏡像關係。
* 對於精簡磁碟區，必須啟用自動擴充。



NOTE: 對於 EF600 和 EF300 控制器，非同步鏡像對的主磁碟區和輔助磁碟區必須具有相同的協定、托架等級、區段大小、安全性類型和 RAID 等級。不符合資格的非同步鏡像對將不會出現在可用磁碟區清單中。



== 非同步鏡像 - 為什麼我在遠端儲存陣列上看不到所有磁碟區？

在遠端儲存陣列上選擇次要磁碟區時，會顯示一個列表，其中列出了該鏡像配對的所有合格磁碟區。

任何不符合使用條件的磁碟區都不會顯示在該清單中。磁碟區可能由於以下任何原因不符合使用條件：

* 磁碟區並不理想。
* 該磁碟區已參與鏡像關係。
* 主磁碟區和次磁碟區之間的精簡磁碟區屬性不符。
* 如果您使用 Data Assurance (DA)，則主磁碟區和次要磁碟區必須具有相同的 DA 設定。
+
** 如果主磁碟區已啟用 DA，則次要磁碟區也必須啟用 DA。
** 如果主磁碟區未啟用 DA，則次要磁碟區也必須未啟用 DA。






== 我為什麼要更新遠端儲存陣列的 IP 位址？

當 iSCSI 連接埠的 IP 位址發生變化，導致本機儲存陣列無法與遠端儲存陣列通訊時，您需要更新遠端儲存陣列的 IP 位址。

建立與 iSCSI 連線的非同步鏡像關係時，本機儲存陣列和遠端儲存陣列都會在非同步鏡像組態中記錄遠端儲存陣列的 IP 位址。如果 iSCSI 連接埠的 IP 位址發生變更，嘗試使用該連接埠的遠端儲存陣列會遇到通訊錯誤。

IP 位址變更後的儲存陣列會向與鏡像一致性群組關聯且配置為透過 iSCSI 連線進行鏡像的每個遠端儲存陣列傳送訊息。收到此訊息的儲存陣列會自動更新其遠端目標 IP 位址。

如果變更了 IP 位址的儲存陣列無法向遠端儲存陣列傳送陣列間訊息，系統會向您傳送連線問題警報。請使用 Update Remote IP Address 選項重新建立與本機儲存陣列的連線。
