---
permalink: sm-mirroring/increase-reserved-capacity.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, synchronous, mirroring, increase, reserved, capacity 
summary: 您可以增加預留容量，預留容量是指用於儲存物件上任何複製服務作業的實體分配容量。 
---
= 增加 SANtricity System Manager 中的預留容量
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以增加預留容量，預留容量是指用於儲存物件上任何複製服務作業的實體分配容量。

對於快照操作，預留容量通常為基礎磁碟區的 40%；對於非同步鏡像操作，預留容量通常為基礎磁碟區的 20%。通常情況下，當收到儲存物件預留容量即將用完的警告時，您需要增加預留容量。

.開始之前
* 資源池或磁碟區群組中的磁碟區必須處於最佳狀態，且不得處於任何修改狀態。
* 若要增加容量，池或磁碟區群組必須有可用容量。
+
如果任何儲存池或磁碟區群組上都沒有可用容量、您可以將未指派的容量（以未使用的磁碟機形式）新增至儲存池或磁碟區群組。



.關於此任務
對於下列儲存物件，您只能以 8 GiB 的增量增加保留容量：

* 快照群組
* 快照磁碟區
* 一致性群組成員磁碟區
* 鏡像配對磁碟區


如果您認為主要磁碟區將經歷多次變更，或者特定複本服務作業的生命週期將非常長，則可以使用較高的百分比。

[NOTE]
====
您無法為唯讀快照磁碟區增加預留容量。只有讀寫快照磁碟區才需要預留容量。

====
.步驟
. 選擇選單：Storage [ Pools & Volume Groups ]。
. 選擇 *Reserved Capacity* 標籤。
. 選擇要增加保留容量的儲存物件，然後按一下 *增加容量* 。
+
此時會顯示「增加預留容量」對話方塊。

. 使用微調框調整容量百分比。
+
如果包含所選儲存物件的儲存池或磁碟區群組上沒有可用容量，且儲存陣列具有未指派容量，則可以建立新的儲存池或磁碟區群組。然後，您可以使用該儲存池或磁碟區群組上的新可用容量重試此操作。

. 點擊 *Increase* 。


.結果
System Manager 執行下列動作：

* 增加儲存物件的保留容量。
* 顯示新增的保留容量。

