---
permalink: sm-mirroring/requirements-for-using-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, requirements, asynchronous, mirroring, 
summary: 如果您打算使用非同步鏡像，請記住以下要求。 
---
= 在 SANtricity 軟體中使用非同步鏡像的要求
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您打算使用非同步鏡像，請記住以下要求。



== Unified Manager

若要啟用和配置兩個陣列之間的鏡像，必須使用 Unified Manager 介面。Unified Manager 與 Web Services Proxy 一起安裝在主機系統上。

* Web Services Proxy 服務必須正在執行。
* Unified Manager 必須透過 HTTPS 連線在本機主機上執行。
* Unified Manager 必須顯示儲存陣列的有效 SSL 憑證。您可以接受自簽憑證，或使用 Unified Manager 並瀏覽至功能表：Certificate[Certificate Management] 來安裝您自己的安全性憑證。




== 儲存陣列

* 您必須有兩個儲存陣列。
* 每個儲存陣列必須有兩個控制器。
* 必須在 Unified Manager 中發現這兩個儲存陣列。
* 主陣列和次要陣列中的每個控制器都必須配置 Ethernet 管理連接埠，並且必須連接到您的網路。
* 儲存陣列的最低韌體版本為 7.84。（它們可以運行不同的作業系統版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 遠端儲存陣列上必須有足夠的可用容量來建立等於或大於要鏡像的主磁碟區的輔助磁碟區。
* 您的本機和遠端儲存陣列透過 Fibre Channel 架構或 iSCSI 介面連接。




== 支援的連線

非同步鏡像可以使用 FC 或 iSCSI 連線，或兩者都使用，來實現本地和遠端儲存系統之間的通訊。建立鏡像一致性群組時，如果遠端儲存陣列同時連接到 FC 和 iSCSI，管理員可以為該群組選擇 FC 或 iSCSI。兩種通道類型之間不存在故障轉移。

非同步鏡像使用儲存陣列的主機端 I/O 連接埠，將鏡像資料從主要端傳送到次要端。

* *透過光纖通道 （FC） 介面進行鏡像*
+
儲存陣列的每個控制器都將其編號最高的 FC 主機連接埠專用於鏡射作業。

+
如果控制器同時具備基本 FC 連接埠和主機介面卡（HIC）FC 連接埠，則編號最高的連接埠位於 HIC 上。任何登入該專用連接埠的主機都會被登出，並且不接受任何主機登入要求。只有參與鏡像操作的控制器才能接受此連接埠上的 I/O 請求。

+
專用鏡像連接埠必須連接到支援目錄服務和名稱服務介面的 FC 交換矩陣環境。尤其需要注意的是，參與鏡像關係的控制器之間不支援 FC-AL 和點對點連接方式。

* *透過 iSCSI 介面進行鏡像*
+
與 FC 不同、iSCSI 不需要專用連接埠。在 iSCSI 環境中使用非同步鏡像時、無需將儲存陣列的前端 iSCSI 連接埠專門用於非同步鏡像；這些連接埠既用於非同步鏡像流量、也用於主機到陣列的 I/O 連接。

+
控制器維護一個遠端儲存系統列表，iSCSI 發起程式會嘗試與這些系統建立工作階段。第一個成功建立 iSCSI 連線的連接埠將用於與該遠端儲存陣列的所有後續通訊。如果通訊失敗，則會嘗試使用所有可用連接埠建立新的工作階段。

+
iSCSI 連接埠在陣列層級逐埠配置。控制器間通訊（用於組態訊息傳遞和資料傳輸）使用全域設定，包括以下設定：

+
** VLAN：本機系統和遠端系統必須具有相同的 VLAN 設定才能通訊
** iSCSI 監聽連接埠
** 巨型訊框
** 乙太網路優先順序
+
[NOTE]
====
iSCSI 控制器間通訊必須使用主機連接埠，而不能使用管理乙太網路連接埠。

====


+
非同步鏡像使用儲存陣列的主機端 I/O 連接埠，將鏡像資料從主要端傳送到次要端。由於非同步鏡像適用於高延遲、低成本的網路，因此 iSCSI（以及基於 TCP/IP 的）連線非常適合。在 iSCSI 環境中使用非同步鏡像時，不需要將陣列的任何前端 iSCSI 連接埠專門用於非同步鏡像；這些連接埠可同時用於非同步鏡像流量和主機到陣列的 I/O 連線。



[NOTE]
====
E4000 在使用 iSCSI 協定時不支援非同步鏡像。

====


== 鏡像磁碟區候選項目

* 非同步鏡像配對的主要磁碟區和次要磁碟區上的 RAID 層級、快取參數和區段大小可以不同。
+

NOTE: 對於 EF600 和 EF300 控制器，非同步鏡像對的主磁碟區和輔助磁碟區必須具有相同的協定、托架等級、區段大小、安全性類型和 RAID 等級。不符合資格的非同步鏡像對將不會出現在可用磁碟區清單中。

* 次要磁碟區必須至少與主要磁碟區一樣大。
* 一個磁碟區只能參與一種鏡射關係。
* Volume 候選者必須具備相同的 Data Security 功能。
+
** 如果主磁碟區支援 FIPS、則次要磁碟區也必須支援 FIPS。
** 如果主磁碟區支援 FDE，則次要磁碟區也必須支援 FDE。
** 如果主磁碟區未使用 Drive Security，則輔助磁碟區也必須不使用 Drive Security。


* 主磁碟區和次要磁碟區必須共用相同的磁碟機類型。主磁碟區和次要磁碟區之間不支援混用 NVMe 和 SAS 磁碟機。
* 主磁碟區和次要磁碟區不得啟用資源分割。




== 預留容量

* 對於鏡像對中的主磁碟區和次要磁碟區，需要保留容量磁碟區來記錄寫入資訊，以便從控制器重設和其他暫時中斷中恢復。
* 由於鏡像配對中的主要磁碟區和次要磁碟區都需要額外的保留容量，因此您必須確保鏡像關係中的兩個儲存陣列都有可用的可用容量。
* 預留容量磁碟區必須與其關聯的鏡像磁碟區共用相同的磁碟機類型。
+
** 如果預留容量磁碟區建立在 NVMe 磁碟機上，則其鏡像磁碟區也必須建立在 NVMe 磁碟機上。
** 如果在 SAS 磁碟機上建立了保留容量磁碟區，則其鏡像磁碟區也必須在 SAS 磁碟機上建立。






== 磁碟機安全功能

* 如果您使用的是支援安全功能的磁碟機，則主磁碟區和次要磁碟區必須具有相容的安全設定。此限制並非強制執行，因此您必須自行驗證。
* 如果您使用的是安全驅動器，則主磁碟區和輔助磁碟區應使用相同的磁碟機類型。此限制並非強制執行，因此您必須自行驗證。
* 如果您使用 Data Assurance (DA)，則主磁碟區和次要磁碟區必須具有相同的 DA 設定。

