---
permalink: sm-mirroring/role-change-of-a-mirror-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, role, change, mirror, consistency, group, secondary, mirror, consistency, group, 
summary: 您可以變更鏡像一致性群組中鏡像配對之間的角色。您可以透過將主要鏡像一致性群組降級為次要角色，或將次要鏡像一致性群組提升為主要角色來執行此操作。 
---
= 在 SANtricity 軟體中變更鏡像一致性群組角色
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以變更鏡像一致性群組中鏡像配對之間的角色。您可以透過將主要鏡像一致性群組降級為次要角色，或將次要鏡像一致性群組提升為主要角色來執行此操作。

請查看以下有關角色變更操作的資訊：

* 角色變更會影響所選鏡像一致性群組內的所有鏡像配對。
* 當鏡像一致性群組降級為次要角色時，該鏡像一致性群組內的所有鏡像配對也會降級為次要角色，反之亦然。
* 當主鏡像一致性群組降級為次要角色時，已指派給該群組內成員磁碟區的主機將不再具有這些磁碟區的寫入存取權。
* 當鏡像一致性群組被提升為主角色時，任何存取該群組內成員磁碟區的主機現在都可以寫入這些磁碟區。
* 如果本機儲存陣列無法與遠端儲存陣列通訊，您可以強制本機儲存陣列變更角色。




== 強制角色變更

當本機儲存陣列和遠端儲存陣列之間的通訊問題阻止輔助鏡像一致性群組中成員磁碟區的提升或主鏡像一致性群組中成員磁碟區的降級時，您可以強制鏡像一致性群組之間進行角色變更。

您可以強制輔助端的鏡像一致性群組轉換為主角色。然後，恢復主機即可存取該鏡像一致性群組中新提升的成員磁碟區，業務操作即可繼續進行。



== 何時允許強制升級，何時不允許？

只有當鏡像一致性群組的所有成員磁碟區都已同步且具有一致的還原點時，才允許強制提升鏡像一致性群組。

在下列情況下，不允許強制提升鏡像一致性群組：

* 鏡像一致性群組的任何成員磁碟區都處於初始同步過程中。
* 鏡像一致性群組的任何成員磁碟區都沒有復原點的時間點映像（例如，由於保留容量已滿錯誤）。
* 鏡像一致性群組不包含成員磁碟區。
* 鏡像一致性群組處於 Failed、Role-Change-Pending 或 Role-Change-In-Progress 狀態，或任何關聯的成員磁碟區或預留容量磁碟區發生故障。




== 鏡像群組角色衝突

當本地儲存陣列和遠端儲存陣列之間的通訊問題解決後，會出現 Mirror Group Role Conflict 的情況。請使用 Recovery Guru 來復原此錯誤。解決雙重角色衝突時，不允許強制提升角色。

為避免鏡像組角色衝突狀況及後續復原步驟，請等到儲存陣列之間的連線恢復正常後再強制變更角色。



== 角色變更進行中狀態

如果鏡像配置中的兩個儲存陣列中斷連線，且鏡像一致性群組的主要端被強制降級為次要角色，而鏡像一致性群組的次要端被強制提升為主要角色，則當通訊恢復時，兩個儲存陣列上的鏡像一致性群組都會處於「角色變更進行中」狀態。

系統將透過傳輸變更日誌、重新同步、將鏡像一致性群組狀態設定回正常運作狀態，並繼續進行定期同步來完成角色變更程序。
