---
permalink: sm-mirroring/role-change-of-volumes-in-a-mirrored-pair.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, role, change, between, volume, mirrored, pair, 
summary: 您可以變更鏡射配對中磁碟區之間的角色。您可以將主要磁碟區降級為次要角色，或將次要磁碟區提升為主要角色來執行此操作。 
---
= 了解 SANtricity 軟體中鏡像配對的磁碟區角色變更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以變更鏡射配對中磁碟區之間的角色。您可以將主要磁碟區降級為次要角色，或將次要磁碟區提升為主要角色來執行此操作。

[NOTE]
====
EF600/EF600C 或 EF300/EF300C 儲存系統不提供同步鏡像。

====
請查看以下有關角色變更操作的資訊：

* 當主磁碟區降級為次要角色時，該鏡像配對中的次要磁碟區會提升為主角色，反之亦然。
* 當主磁碟區降級為次要角色時，已指派給該磁碟區的主機將不再具有對該磁碟區的寫入存取權。
* 當次要磁碟區提升為主要角色時、存取該磁碟區的任何主機現在都能夠寫入該磁碟區。
* 如果本機儲存陣列無法與遠端儲存陣列通訊，您可以強制本機儲存陣列變更角色。




== 強制角色變更

當本機儲存陣列和遠端儲存陣列之間的通訊問題阻止次要磁碟區的升級或主要磁碟區的降級時、您可以強制鏡射配對中的磁碟區之間進行角色變更。

您可以強制將次要端的磁碟區轉換為主要角色。然後，恢復主機即可存取新提升的磁碟區，業務運作即可繼續進行。

[NOTE]
====
當遠端儲存陣列恢復且所有通訊問題已解決後，會出現「同步鏡像 - 主磁碟區衝突」錯誤。復原步驟包括重新同步磁碟區。請使用 Recovery Guru 從此錯誤中復原。

====


== 何時允許強制升級，何時不允許？

在下列情況下，不允許強制提升鏡像配對中的磁碟區：

* 鏡像配對中的任何磁碟區都正在進行初始同步處理。
* 鏡像配對處於「失敗」、「角色變更待處理」或「角色變更進行中」狀態，或任何相關的保留容量磁碟區發生故障。




== 角色變更進行中狀態

如果鏡像配置中的兩個儲存陣列中斷連線，並且鏡像配對的主要磁碟區被強制降級為次要角色，而鏡像配對的次要磁碟區被強制提升為主要角色，那麼當通訊恢復時，兩個儲存陣列上的磁碟區都會置於 Role-Change-In-Progress 狀態。

系統將透過傳輸變更日誌、重新同步、將鏡像配對狀態設定回正常運作狀態並繼續同步來完成角色變更程序。
