---
permalink: sm-mirroring/test-communication-for-mirror-consistency-groups.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, test, communication, mirror, consistency, groups, 
summary: 您可以測試通訊鏈路，以診斷本機儲存陣列與鏡像一致性群組相關聯的遠端儲存陣列之間可能存在的通訊問題。 
---
= 在 SANtricity System Manager 中測試鏡射一致性群組的通訊
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以測試通訊鏈路，以診斷本機儲存陣列與鏡像一致性群組相關聯的遠端儲存陣列之間可能存在的通訊問題。

.開始之前
您要測試的鏡像一致性群組必須存在於本機儲存陣列和遠端儲存陣列上。

.關於此任務
您可以執行四種不同的測試：

* * 連線能力 * -- 驗證兩個控制器是否有通訊路徑。連線能力測試會在儲存陣列之間傳送陣列間訊息，然後驗證遠端儲存陣列上是否存在對應的鏡射一致性群組。它也會驗證遠端儲存陣列上鏡射一致性群組的成員磁碟區是否與本機儲存陣列上鏡射一致性群組的成員磁碟區相符。
* *延遲* -- 向與鏡像一致性群組關聯的遠端儲存陣列上的每個鏡像磁碟區傳送 SCSI Test Unit 命令，以測試最小、平均和最大延遲。
* *頻寬* -- 向遠端儲存陣列傳送兩個陣列間訊息，以測試執行測試的陣列上連接埠的最小、平均和最大頻寬以及協商的連結速度。
* *連接埠連線* -- 顯示本機儲存陣列上用於鏡射的連接埠，以及遠端儲存陣列上接收鏡射資料的連接埠。


.步驟
. 選擇功能表：Storage[Asynchronous Mirroring]。
. 選擇 *Mirror Consistency Groups* 選項卡，然後選擇要測試的鏡像一致性組。
. 選擇 *Test Communication* 。
+
Test Communication 對話方塊隨即出現。

. 選擇要執行的與所選鏡像一致性群組關聯的本機儲存陣列和遠端儲存陣列之間的一個或多個通訊測試，然後按一下 *Test* 。
. 檢閱結果視窗中顯示的資訊。
+
[cols="35h,~"]
|===
| 通訊測試狀態 | 說明 


 a| 
正常，無錯誤
 a| 
鏡像一致性群組正常通訊。



 a| 
狀態已通過 （但並非正常）
 a| 
檢查可能存在的網路或連線問題，然後重試測試。



 a| 
失敗狀態
 a| 
故障原因已標明。請參閱 Recovery Guru 以解決問題。



 a| 
連接埠連線錯誤
 a| 
原因可能是本機儲存陣列未連接，或無法聯繫到遠端儲存陣列。請參閱 Recovery Guru 以修正問題。

|===


.結果
通訊測試完成後，此對話方塊會顯示 Normal 狀態、Passed 狀態或 Failed 狀態。

如果通訊測試傳回失敗狀態，則在您關閉此對話方塊後，測試將繼續執行，直到鏡像一致性群組之間的通訊恢復為止。
