---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, admin password 
summary: 您必須為儲存陣列配置管理員密碼，以防止未經授權的存取。 
---
= 在 SANtricity System Manager 中管理密碼保護
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須為儲存陣列配置密碼，以防止未經授權的存取。



== 設定和變更密碼

首次啟動 System Manager 時，系統會提示您設定管理員密碼。任何擁有管理員密碼的使用者都可以對儲存陣列進行配置更改，例如新增、更改或刪除物件或設定。若要在初始啟動期間設定管理員密碼，請參閱 link:../san-getstarted/access-sam.html["存取 System Manager"]。

出於安全考慮，您只能嘗試輸入密碼五次，之後儲存陣列將進入「鎖定」狀態。在此狀態下，儲存陣列將拒絕後續的密碼輸入。您必須等待 10 分鐘，待儲存陣列重設為「正常」狀態後，才能再次嘗試輸入密碼。

除了管理員密碼外，儲存陣列還包含預先定義的使用者設定檔，每個設定檔都映射了一個或多個角色。如需詳細資訊，請參閱link:../sm-settings/permissions-for-mapped-roles.html["映射角色的權限"]。使用者設定檔和映射關係無法變更。只能修改密碼。如果您想要變更管理員密碼或其他使用者密碼，請參閱link:../sm-settings/change-passwords.html["更改密碼"]。



== 工作階段逾時後重新輸入密碼

在單一管理工作階段期間，系統只會提示您輸入一次密碼。但是，工作階段會在 30 分鐘無活動後逾時，屆時您必須再次輸入密碼。如果其他使用者在您的工作階段進行期間從其他管理用戶端管理相同儲存陣列時變更了密碼，則在您下次嘗試組態操作或檢視操作時，系統會提示您輸入密碼。

您可以調整工作階段逾時時間，也可以完全停用工作階段逾時。請參閱 link:../sm-settings/manage-session-timeouts-sam.html["管理工作階段逾時"]。



== 移除磁碟機或密碼保護

如果您要移除受密碼保護的磁碟機或想要停用密碼保護，請注意以下事項：

* *如果您移除受密碼保護的磁碟機* -- 密碼儲存在儲存陣列中每個磁碟機的預留區域中。如果您從儲存陣列中移除所有磁碟機，則其密碼將失效。若要解決此問題，請將其中一個原始磁碟機重新安裝到儲存陣列中。
* *如果您想移除密碼保護* -- 如果您不再希望命令受到密碼保護，請輸入目前管理員密碼，並將新密碼文字方塊留空。


[CAUTION]
====
在儲存陣列上執行組態命令可能會造成嚴重損害，包括資料遺失。因此，您應該始終為儲存陣列設定管理員密碼。使用至少 15 個英數字元的長管理員密碼以提高安全性。

====