---
permalink: sm-interface/faq-management-interface.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= SANtricity System Manager 的管理介面常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 支援哪些瀏覽器？

SANtricity System Manager 支援以下瀏覽器版本。

[cols="1a,1a"]
|===
| 瀏覽器 | 最低版本 


 a| 
Google Chrome
 a| 
89



 a| 
Mozilla Firefox
 a| 
80



 a| 
Safari
 a| 
14



 a| 
Microsoft Edge
 a| 
90

|===


== 有哪些鍵盤快速鍵？

您可以僅使用鍵盤在 SANtricity System Manager 中進行導覽。



=== 整體導覽

[cols="1a,1a"]
|===
| 行動 | 鍵盤快速鍵 


 a| 
移至下一個項目。
 a| 
標籤頁



 a| 
移至上一項。
 a| 
Shift + Tab



 a| 
請選擇一項。
 a| 
輸入



 a| 
下拉式清單 - 移至下一個或上一個項目。
 a| 
向下箭頭或向上箭頭



 a| 
核取方塊 -- 選取項目。
 a| 
空白鍵



 a| 
單選按鈕 -- 在不同選項之間切換。
 a| 
向下箭頭或向上箭頭



 a| 
可展開文字 - 展開或縮小項目。
 a| 
輸入

|===


=== 表格導覽

[cols="1a,1a"]
|===
| 行動 | 鍵盤快速鍵 


 a| 
選擇一行。
 a| 
按 Tab 鍵選擇一行，然後按 Enter 鍵



 a| 
向上或向下捲動。
 a| 
向下箭頭/向上箭頭或 Page Down/Page Up



 a| 
更改欄的排序順序。
 a| 
按 Tab 鍵選擇列標題，然後按 Enter 鍵

|===


=== 日曆導覽

[cols="1a,1a"]
|===
| 行動 | 鍵盤快速鍵 


 a| 
移至上個月。
 a| 
上一頁



 a| 
移至下個月。
 a| 
往下翻頁



 a| 
移至上一年。
 a| 
Control + Page Up



 a| 
移至下一年。
 a| 
Control + Page Down



 a| 
如果日期選擇器已關閉，請將其開啟。
 a| 
Control + Home



 a| 
移至當月。
 a| 
Control / Command + Home



 a| 
移至前一天。
 a| 
Control / Command + 左鍵



 a| 
移至下一天。
 a| 
Control / Command + 右鍵



 a| 
移至上一周。
 a| 
Control / Command + 上



 a| 
移至下一週。
 a| 
Control / Command + 向下



 a| 
選擇焦點日期。
 a| 
輸入



 a| 
關閉日期選擇器並清除日期。
 a| 
Control / Command + End



 a| 
關閉日期選擇器而不進行選擇。
 a| 
離開

|===


== 個別磁碟區的效能統計資料與總計有何關係？

集區和磁碟區群組的統計資料是透過彙總所有磁碟區（包括保留容量磁碟區）計算得出的。

儲存系統內部使用保留容量來支援精簡磁碟區、快照和非同步鏡像，I/O 主機無法看到這些容量。因此，儲存池、控制器和儲存陣列統計資料的總和可能與可檢視磁碟區的總和不符。

但是，對於應用程式和工作負載統計資訊，僅彙總可見的磁碟區。



== 為什麼圖表和表格中的資料顯示為零？

當圖表和表格中的某個資料點顯示為零時，表示該物件在該時間點沒有 I/O 活動。這種情況可能是由於主機未向該物件發起 I/O 操作，也可能是物件本身有問題。

該物件的歷史資料仍然可供查看。一旦該物件開始發生 I/O 活動，圖表和表格將顯示非零資料。

下表列出了任何給定物件的資料點值為零的最常見原因。

[cols="25h,~"]
|===
| 陣列層級物件類型 | 資料顯示為零的原因 


 a| 
磁碟區
 a| 
* 磁碟區未分配主機。




 a| 
磁碟區群組
 a| 
* 正在匯入磁碟區群組。
* 磁碟區群組不包含指派給主機的磁碟區、*_且_* 磁碟區群組不包含任何保留容量。




 a| 
磁碟機
 a| 
* 磁碟機故障。
* 磁碟機已被移除。
* 磁碟機處於未知狀態。




 a| 
控制器
 a| 
* 控制器已離線。
* 控制器故障。
* 控制器已移除。
* 控制器處於未知狀態。




 a| 
儲存陣列
 a| 
* 儲存陣列不包含磁碟區。


|===


== 延遲圖表顯示什麼？

延遲圖表以毫秒 (ms) 為單位，提供磁碟區、磁碟區群組、集區、應用程式和工作負載的延遲統計資料。此圖表會顯示在 Logical View、Physical View 和 Applications & Workloads View 標籤中。

延遲是指資料讀取或寫入過程中發生的任何延遲。將滑鼠停留在圖表上的某個點上，即可查看該時間點的以下值（以毫秒（ms）為單位）：

* 閱讀時間。
* 寫入時間。
* 平均 I/O 大小。




== IOPS 圖表顯示了什麼？

IOPS 圖表顯示每秒輸入 / 輸出作業的統計資料。在首頁上，此圖表顯示儲存陣列的統計資料。在效能磁貼的邏輯檢視、實體檢視和應用程式與工作負載檢視標籤中，此圖表顯示儲存陣列、磁碟區、磁碟區群組、集區、應用程式和工作負載的統計資料。

IOPS 是每秒輸入 / 輸出（I/O）作業的縮寫。將游標暫留在圖表上的某個點上，即可檢視該時間點的下列值：

* 讀取操作次數。
* 寫入操作次數。
* 讀取和寫入作業總數。




== MiB/s 圖表顯示什麼？

MiB/s 圖表以 mebibytes 每秒為單位顯示傳輸速度統計資料。在主頁上，此圖表顯示儲存陣列的統計資料。在「效能」磁貼的「邏輯視圖」、「實體視圖」和「應用程式與工作負載檢視」標籤中，此圖表顯示儲存陣列、磁碟區、磁碟區群組、儲存池、應用程式和工作負載的統計資料。

MiB/s 是 _mebibytes per second_ 的縮寫，即每秒 1,048,576 位元組。將滑鼠游標懸停在圖表上的某個點上，即可查看該時間點的以下值：

* 讀取的資料量。
* 寫入的資料量。
* 讀取和寫入的資料總量。




== CPU 圖表顯示了什麼？

CPU 圖表顯示每個控制器（控制器 A 和控制器 B）的處理能力統計資料。CPU 是中央處理器的縮寫。在主頁上，此圖表顯示儲存陣列的統計資料。在「效能」磁貼的「實體檢視」標籤上，此圖表顯示儲存陣列和磁碟機的統計資料。

CPU 圖表顯示陣列上作業所使用的 CPU 處理容量百分比。即使沒有發生外部 I/O、CPU 使用率百分比也可能不為零、因為儲存作業系統可能正在執行背景作業和監控。將游標暫留在圖表上的某個點上、即可檢視該時間點所使用的處理能力百分比。



== Headroom 圖表顯示什麼？

Headroom 圖表與儲存陣列控制器的剩餘效能能力相關。此圖表顯示在 Home 頁面和 Performance 磁貼的 Physical View 標籤中。

Headroom 圖表顯示儲存系統中實體物件的剩餘效能能力。將游標停留在圖表上的某個點，即可檢視控制器 A 和控制器 B 的剩餘 IOPS 和 MiB/s 能力百分比。



== 在哪裡可以找到更多關於顯示偏好設定的資訊？

若要尋找可用顯示選項的相關資訊：

* 若要深入瞭解顯示容量值的預設單位，請參閱 link:set-default-units-for-capacity-values.html["設定容量值的預設單位"]。
* 若要深入瞭解顯示效能圖表的預設時間範圍，請參閱 link:set-default-time-frame-for-performance-graphs.html["設定效能圖表的預設時間範圍"]。

