---
permalink: sm-interface/faq-storage-system-setup.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= SANtricity System Manager 儲存系統設定常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 如果我無法看到所有的硬體元件怎麼辦？

如果在「驗證硬體」對話方塊中看不到所有硬體元件，則可能表示磁碟機櫃未正確連接，或儲存陣列中安裝了不相容的磁碟機櫃。

請確認所有磁碟機櫃均已正確連接。如果您不確定哪些磁碟機櫃相容，請聯絡技術支援。



== 如果我無法看到所有主機怎麼辦？

如果您看不到已連線的主機，表示自動偵測失敗、主機連線不正確或目前沒有主機連線。

設定完成後，您可以稍後配置主機。您可以如下手動建立主機：

* 您可以透過前往選單：Storage[Hosts] 手動建立主機並關聯對應的主機連接埠識別碼。手動建立的主機也會顯示在 *Initial Setup* 精靈中。
* 目標和主機必須針對主機連接埠類型進行設定（例如 iSCSI 或 NVMe over RoCE），並且必須先建立與儲存設備的工作階段，自動偵測才能運作。




== 識別應用程式如何協助我管理儲存陣列？

當您識別應用程式時，SANtricity System Manager 會自動推薦一種磁碟區配置，該配置可根據應用程式類型最佳化儲存。

依應用程式最佳化磁碟區可以提高資料儲存作業的效率。磁碟區組態中包含 I/O 類型、區段大小、控制器擁有權以及讀取和寫入快取等特性。此外，您還可以依應用程式和工作負載檢視效能資料，以評估應用程式及其相關工作負載的延遲、IOPS 和 MiB/s。



== 什麼是工作負載？

對於網路中的某些應用程式（例如 SQL Server 或 Exchange ），您可以定義一個工作負載，以最佳化該應用程式的儲存。

工作負載是支援應用程式的儲存物件。您可以為每個應用程式定義一個或多個工作負載（或執行個體）。對於某些應用程式，系統會將工作負載配置為包含具有相似底層磁碟區特性的磁碟區。這些磁碟區特性會根據工作負載支援的應用程式類型進行最佳化。例如，如果您建立了支援 Microsoft SQL Server 應用程式的工作負載，然後隨後為該工作負載建立磁碟區，則底層磁碟區特性會針對 Microsoft SQL Server 進行最佳化。

建立磁碟區時，系統會提示您回答有關工作負載使用情況的問題。例如，如果您要建立 Microsoft Exchange 磁碟區，系統會詢問您需要多少個郵箱、平均郵箱容量需求以及所需的資料庫副本數量。系統會使用這些資訊為您建立最佳磁碟區配置，您可以根據需要進行編輯。



== 如何配置 AutoSupport 的傳送方式？

若要存取 AutoSupport 交付方式的設定任務,請前往功能表:支援 [支援中心],然後按一下 *AutoSupport* 標籤。

支援以下通訊協定：HTTPS 和 SMTP。



== 我如何知道是否應該接受建議的資源池組態？

是否接受建議的資源池組態取決於幾個因素。

請回答以下問題，以確定最符合您需求的儲存類型：

* 您偏好使用多個容量較小的資源池，而非盡可能使用最大的資源池嗎？
* 您偏好使用 RAID 磁碟區群組而非儲存池嗎？
* 您是否偏好手動配置磁碟機，而非讓系統為您建議配置？


如果您對以上任何問題回答「是」，請考慮拒絕建議的資源池組態。



== SANtricity System Manager 未偵測到任何主機。我該怎麼辦？

如果您看不到已連線的主機，表示自動偵測失敗、主機連線不正確或目前沒有主機連線。

設定完成後，您可以稍後配置主機。您可以如下手動建立主機：

* 您可以透過前往選單：Storage[Hosts] 手動建立主機並關聯對應的主機連接埠識別碼。手動建立的主機也會顯示在 *Initial Setup* 精靈中。
* 目標和主機必須針對主機連接埠類型進行設定（例如 iSCSI 或 NVMe over RoCE），並且必須先建立與儲存設備的工作階段，自動偵測才能運作。

