---
permalink: sm-interface/setup-wizard-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, setup wizard 
summary: 使用設定精靈配置儲存陣列，包括硬體、主機、應用程式、工作負載、池、警報和 AutoSupport。 
---
= 了解 SANtricity System Manager 設定精靈
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用設定精靈配置儲存陣列，包括硬體、主機、應用程式、工作負載、池、警報和 AutoSupport。



== 首次設定

首次開啟 System Manager 時，Setup 精靈將會啟動。Setup 精靈會提示您執行基本組態作業，例如命名儲存陣列、組態主機、選取應用程式以及建立儲存資源池。


NOTE: 在繼續進行初始設定之前，請前往升級中心（選單：支援 [升級中心]），確保您的 SANtricity OS 軟體已更新至最新版本。如有需要，請升級至最新版本並刷新瀏覽器以繼續設定。如需詳細資訊，請參閱 link:../sm-support/overview-upgrade-center.html["升級中心概覽"]。

如果取消精靈，則無法手動重新啟動。當您開啟 System Manager 或重新整理瀏覽器，且符合以下「至少一個」條件時，精靈會自動重新啟動：

* 未偵測到任何資源池和磁碟區群組。
* 未偵測到任何工作負載。
* 未配置任何通知。




== 術語

設定精靈使用以下術語。

[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
應用程式
 a| 
應用程式是軟體程式，例如 Microsoft SQL Server 或 Microsoft Exchange。



 a| 
警示
 a| 
警示會通知管理員儲存陣列上發生的重要事件。警示可透過電子郵件、SNMP 設陷或 syslog 傳送。



 a| 
AutoSupport
 a| 
AutoSupport 功能可監控儲存陣列的運作狀況，並自動向技術支援發送排程資訊。



 a| 
硬體
 a| 
儲存系統硬體包括儲存陣列、控制器和磁碟機。



 a| 
主機
 a| 
主機是向儲存陣列上的磁碟區發送 I/O 的伺服器。



 a| 
物件
 a| 
物件是指任何邏輯或實體儲存元件。邏輯物件包括磁碟區組、儲存池和磁碟區。實體物件包括儲存陣列、陣列控制器、主機和磁碟機。



 a| 
資源池
 a| 
儲存池是一組邏輯上分組的磁碟機。您可以使用儲存池建立一個或多個可供主機存取的磁碟區。（您可以從儲存池或磁碟區組建立磁碟區。）



 a| 
磁碟區
 a| 
磁碟區是應用程式、資料庫和檔案系統儲存資料的容器。它是為主機存取儲存陣列上的儲存設備而建立的邏輯元件。

磁碟區是根據儲存池或磁碟區群組中的可用容量建立的。磁碟區具有已定義的容量。儘管一個磁碟區可能包含多個磁碟機，但對於主機而言，該磁碟區表現為一個邏輯元件。



 a| 
磁碟區群組
 a| 
磁碟區群組是用來存放具有共用特徵的磁碟區的容器。磁碟區群組具有已定義的容量和 RAID 等級。您可以使用磁碟區群組建立一個或多個可供主機存取的磁碟區。（您可以從磁碟區群組或儲存池建立磁碟區。）



 a| 
工作負載
 a| 
工作負載是支援應用程式的儲存物件。您可以為每個應用程式定義一個或多個工作負載（或執行個體）。對於某些應用程式，系統會將工作負載配置為包含具有相似底層磁碟區特性的磁碟區。這些磁碟區特性會根據工作負載支援的應用程式類型進行最佳化。例如，如果您建立了支援 Microsoft SQL Server 應用程式的工作負載，然後隨後為該工作負載建立磁碟區，則底層磁碟區特性會針對 Microsoft SQL Server 進行最佳化。

|===