---
permalink: sm-interface/view-storage-hierarchy.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, storage hierarchy 
summary: 主介面上的 Storage Hierarchy 提供了儲存陣列所管理之各種硬體元件和儲存物件的組織化檢視。 
---
= 在 SANtricity System Manager 中檢視儲存階層
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
主介面上的 Storage Hierarchy 提供了儲存陣列所管理之各種硬體元件和儲存物件的組織化檢視。

若要查看儲存層次結構，請前往主頁，然後按一下儲存陣列元件或儲存物件上的下拉箭頭。儲存陣列由實體元件和邏輯元件的集合組成。



== 實體元件

此表說明儲存陣列的實體元件。

[cols="25h,~"]
|===
| 元件 | 說明 


 a| 
控制器
 a| 
控制器由電路板、韌體和軟體組成。它控制驅動器並實現 System Manager 功能。



 a| 
機櫃
 a| 
機架是安裝在機櫃或機架中的機箱。其中包含儲存陣列的硬體元件。機架有兩種類型：控制器機架和磁碟機機架。控制器機架包含控制器和磁碟機。磁碟機機架包含輸入 / 輸出模組（IOM）和磁碟機。

[NOTE]
====
如果您的儲存陣列包含不同的媒體類型或不同的介面類型，則會為每種磁碟機類型顯示一個磁碟機櫃。

====


 a| 
磁碟機
 a| 
磁碟機是一種電磁機械裝置或固態記憶體裝置，可為資料提供實體儲存媒體。



 a| 
主機
 a| 
主機是向儲存陣列上的磁碟區發送 I/O 的伺服器。



 a| 
主機匯流排適配器 (HBA)
 a| 
主機匯流排適配器（HBA）是位於主機中的一塊電路板，包含一個或多個主機連接埠。



 a| 
主機連接埠
 a| 
主機連接埠是主機匯流排適配器（HBA）上的連接埠，可提供與控制器的實體連線，並用於 I/O 作業。



 a| 
管理用戶端
 a| 
管理用戶端是指安裝了瀏覽器以存取 System Manager 的電腦。

|===


== 邏輯元件

儲存陣列中的磁碟機提供資料的實體儲存容量。使用 System Manager 將實體容量配置為邏輯元件，例如儲存池、磁碟區群組和磁碟區。這些元件是您用來在儲存陣列上配置、儲存、維護和保留資料的工具。此表說明儲存陣列的邏輯元件。

[cols="25h,~"]
|===
| 元件 | 說明 


 a| 
資源池
 a| 
儲存池是一組邏輯上分組的磁碟機。您可以使用儲存池建立一個或多個可供主機存取的磁碟區。（您可以從儲存池或磁碟區組建立磁碟區。）



 a| 
磁碟區群組
 a| 
磁碟區群組是用來存放具有共用特徵的磁碟區的容器。磁碟區群組具有已定義的容量和 RAID 等級。您可以使用磁碟區群組建立一個或多個可供主機存取的磁碟區。（您可以從磁碟區群組或儲存池建立磁碟區。）



 a| 
磁碟區
 a| 
磁碟區是應用程式、資料庫和檔案系統儲存資料的容器。它是為主機存取儲存陣列上的儲存設備而建立的邏輯元件。



 a| 
邏輯單元號碼（LUN）
 a| 
邏輯單元號碼（LUN）是指派給主機用於存取磁碟區的位址空間的編號。磁碟區以 LUN 的形式作為容量呈現給主機。

每台主機都有自己的 LUN 位址空間。因此，同一個 LUN 可以被不同的主機用來存取不同的磁碟區。

|===