---
permalink: sm-hardware/allow-remote-login.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, login, 
summary: 遠端登入允許區域網路外的使用者啟動 SSH 工作階段並變更控制器上的設定。 
---
= 在 SANtricity System Manager 中設定遠端登入（SSH）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
啟用遠端登入後，您可以允許區域網路外的使用者啟動 SSH 工作階段並存取控制器上的設定。

對於 SANtricity 11.74 及更高版本，您也可以設定多因素授權（MFA），要求使用者輸入 SSH 金鑰和/或 SSH 密碼。對於 SANtricity 11.73 及更早版本，此功能_不_包含使用 SSH 金鑰和密碼進行多因素授權的選項。

[CAUTION]
====
*安全風險* -- 出於安全考慮，只有技術支援人員才能使用 Remote Login 功能。

====
.步驟
. 選擇 *Hardware* 。
. 如果圖形顯示了磁碟機，請按一下 *Controllers & Components* 標籤。
+
圖形變更為顯示控制器，而非磁碟機。

. 按一下要為其配置遠端登入的控制器。
+
控制器的內容功能表隨即出現。

. 選擇 *Configure remote login (SSH)*。（對於 SANtricity 11.73 及更早版本，此選單項目為 *Change remote login*。）
+
此時會開啟用於啟用遠端登入的對話方塊。

. 選取 *Enable remote login* 複選框。
+
此設定提供遠端登入功能，並提供三種授權選項：

+
** *僅限密碼*。對於此選項，您已完成並可以點擊 *儲存*。如果您有雙工系統，可以按照先前的步驟在第二個控制器上啟用遠端登入。
** *SSH 金鑰或密碼*。選擇此選項，請繼續下一步。
** *密碼和 SSH 金鑰*。對於此選項，請選取 *Require authorized public key and password for remote login* 複選框，然後繼續下一步。


. 填寫 *Authorized public key* 欄位。此欄位包含已授權公鑰列表，格式與 OpenSSH *authorized_keys* 檔案相同。
+
填寫 *Authorized public key* 欄位時，請注意以下準則：

+
** * 授權公鑰 * 欄位適用於兩個控制器，但只需在第一個控制器上進行設定。
** *authorized_keys* 檔案每行只能包含一個金鑰。以 # 開頭的行和空白行將被忽略。有關檔案格式的更多資訊，請參閱 link:https://www.ssh.com/academy/ssh/authorized-keys-openssh["設定 OpenSSH 的授權金鑰"^]。
** *authorized_keys* 檔案應類似於下列範例：
+
[listing]
----
ssh-rsa
AAAAB3NzaC1yc2EAAAADAQABAAABAQDJlG20rYTk4ok+xFjkPHYp/R0LfJqEYDLXA5AJ49w3DvAWLrUg+1CpNq76WSqmQBmoG9jgbcAB5ABGdswdeMQZHilJcu29iJ3OKKv6SlCulAj1tHymwtbdhPuipd2wIDAQAB
----


. 完成後，點選 *Save* 。
. 對於雙工系統，您可以按照上述步驟在第二個控制器上啟用遠端登入。如果您同時設定了密碼和 SSH 金鑰選項，請務必再次勾選 *遠端登入需要授權的公開金鑰和密碼* 核取方塊。
. 技術支援完成故障排除後，您可以返回「設定遠端登入」對話方塊，取消勾選 *啟用遠端登入* 核取方塊來停用遠端登入。如果第二個控制器上啟用了遠端登入，則會開啟確認對話方塊，允許您在第二個控制器上也停用遠端登入。
+
停用遠端登入會終止所有目前的 SSH 工作階段並拒絕任何新的登入要求。


