---
permalink: sm-hardware/assign-hot-spares-hardware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, assign, hot, spares, raid, 
summary: 您可以將熱備援磁碟指定為 RAID 1、RAID 5 或 RAID 6 磁碟區群組中的待命磁碟機，以提供額外的資料保護。如果其中一個磁碟區群組中的磁碟機故障，控制器會將故障磁碟機的資料重建至熱備援磁碟。 
---
= 在 SANtricity System Manager 中指派熱備援
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將熱備援磁碟指定為 RAID 1、RAID 5 或 RAID 6 磁碟區群組中的待命磁碟機，以提供額外的資料保護。如果其中一個磁碟區群組中的磁碟機故障，控制器會將故障磁碟機的資料重建至熱備援磁碟。

.開始之前
* 必須建立 RAID 1、RAID 5 或 RAID 6 磁碟區組。（熱備盤不能用於儲存池。儲存池使用每個磁碟機內的備用容量進行資料保護。）
* 必須提供符合下列條件的磁碟機：
+
** 未分配，狀態為最佳。
** 與磁碟區群組中的磁碟機相同的媒體類型（例如 SSD）。
** 與磁碟區群組中磁碟機相同的介面類型（例如 SAS）。
** 容量等於或大於磁碟區群組中磁碟機的已使用容量。




.關於此任務
本任務介紹如何從「硬體」頁面手動指派熱備用磁碟。建議每個磁碟機組配備兩個熱備用磁碟。

[NOTE]
====
也可以透過初始設定精靈分配熱備盤。您可以透過檢視硬體頁面上以粉紅色顯示的磁碟機托架來確定熱備盤是否已指派。

====
.步驟
. 選擇 *Hardware* 。
. 如果圖形顯示了控制器，請按一下 *Drives* 標籤。
+
圖形變更為顯示磁碟機而非控制器。

. 選擇要用作熱備碟的未指派磁碟機 （以灰色顯示）。
+
磁碟機的內容功能表隨即開啟。

. 選擇 *Assign hot spare* 。
+
如果磁碟機已啟用安全功能，則會開啟「安全擦除磁碟機？」對話方塊。若要將已啟用安全功能的磁碟機用作熱備盤，必須先執行安全擦除操作，以刪除其所有資料並重設其安全屬性。

+
[CAUTION]
====
*資料可能遺失* -- 請確保已選擇正確的磁碟機。完成 Secure Erase 操作後，您將無法恢復任何資料。

====
+
如果磁碟機*未*啟用安全功能，則會開啟 Confirm Assign Hot Spare Drive 對話方塊。

. 檢閱對話方塊中的文字，然後確認作業。
+
該磁碟機在硬體頁面上顯示為粉紅色，表示它現在是熱備援磁碟機。



.結果
如果 RAID 1、RAID 5 或 RAID 6 磁碟區群組中的磁碟機故障，控制器會自動使用備援資料，將故障磁碟機的資料重建至熱備援磁碟機。
