---
permalink: sm-hardware/configure-nvme-over-infiniband-ports-hardware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, infiniband, ports, nvme, 
summary: 如果您的控制器包含 NVMe over InfiniBand 連接，您可以從硬體頁面設定 NVMe 連接埠設定。 
---
= 在 SANtricity System Manager 中設定 NVMe over InfiniBand 連接埠
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的控制器包含 NVMe over InfiniBand 連接，您可以從硬體頁面設定 NVMe 連接埠設定。

.開始之前
* 您的控制器必須包含 NVMe over InfiniBand host 連接埠；否則，System Manager 中將無法使用 NVMe over InfiniBand 設定。
* 您必須知道主機連線的 IP 位址。


[NOTE]
====
只有當儲存陣列的控制器包含 NVMe over InfiniBand 連接埠時，才會顯示 NVMe over InfiniBand 設定和功能。

====
.步驟
. 選擇 *Hardware* 。
. 如果圖形顯示了磁碟機，請按一下 *Controllers & Components* 標籤。
+
圖形變更為顯示控制器，而非磁碟機。

. 按一下具有您要設定之 NVMe over InfiniBand 連接埠的控制器。
+
控制器的內容功能表隨即出現。

. 選擇 *Configure NVMe over InfiniBand ports* 。
+
「透過 InfiniBand 連接埠配置 NVMe」對話方塊開啟。

. 從下拉清單中選擇要設定的 HIC 連接埠，然後輸入 IP 位址。
+
如果您正在配置配備 200Gb 容量 HIC 的 EF600 儲存陣列，此對話方塊將顯示兩個 IP 位址欄位，一個用於實體連接埠（外部），一個用於虛擬連接埠（內部）。您應該為這兩個連接埠指派唯一的 IP 位址。這些設定允許主機在每個連接埠之間建立路徑，並使 HIC 發揮最佳效能。如果您未為虛擬連接埠指派 IP 位址，則 HIC 將以其額定速度的一半左右運作。

. 點選 *Configure* 。
. 完成配置後，按一下 *Yes* 重設 NVMe over InfiniBand 連接埠。

