---
permalink: sm-hardware/erase-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, erase, drives, removal, 
summary: 您可以使用「擦除」選項來準備未指派的磁碟機，以便從系統中移除。此程序會永久移除資料，確保資料無法再次讀取。 
---
= 在 SANtricity System Manager 中清除磁碟機
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「擦除」選項來準備未指派的磁碟機，以便從系統中移除。此程序會永久移除資料，確保資料無法再次讀取。

.開始之前
磁碟機必須處於未指派狀態。

.關於此任務
僅當您想要永久刪除磁碟機上的所有資料時才使用「擦除」選項。如果磁碟機啟用了安全功能，「擦除」選項將執行加密擦除，並將磁碟機的安全屬性重設為具備安全功能。

[NOTE]
====
擦除功能不支援部分較舊的磁碟機型號。如果您嘗試清除這些較舊的型號，則會顯示錯誤訊息。

====
.步驟
. 選擇 *Hardware* 。
. 如果圖形顯示了控制器，請按一下 *Drives* 標籤。
+
圖形變更為顯示磁碟機而非控制器。

. 您也可以使用篩選欄位檢視機架中所有未指派的磁碟機。從 *Show drives that are...* 下拉清單中、選取 *Unassigned* 。
+
機架視圖僅顯示未指派的磁碟機；所有其他磁碟機均顯示為灰色。

. 若要開啟磁碟機的內容功能表，請按一下要清除的磁碟機。（如果要選取多個磁碟機，可以在「清除磁碟機」對話方塊中進行。）
+
[CAUTION]
====
* 資料可能遺失 * -- Erase 操作無法撤銷。請確保在操作過程中選擇正確的磁碟機。

====
. 從內容功能表中，選取 *Erase* 。
+
「 Erase Drives 」對話方塊隨即開啟，顯示所有符合擦除作業資格的磁碟機。

. 如果需要，可以從表格中選擇其他磁碟機。您不能選擇_所有_磁碟機；請確保至少有一個磁碟機未選取。
. 輸入  `erase` 確認操作，然後點選 *Erase*。
+
[CAUTION]
====
請確認您是否要繼續執行此操作。一旦您在下一個對話方塊中按一下 Yes，則操作將無法中止。

====
. 在「預計完成時間」對話方塊中、按一下 *Yes* 繼續執行清除作業。


.結果
擦除操作可能需要幾分鐘到幾小時。您可以在 menu:Home[View Operations in Progress] 中查看狀態。擦除操作完成後，這些磁碟機即可用於其他 volume group 或 disk pool，或其他儲存陣列。

.完成後
如果想再次使用該驅動器，必須先對其進行初始化。為此，請從磁碟機的上下文功能表中選擇 *Initialize*。
