---
permalink: sm-hardware/faq-storage-shelf.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= SANtricity System Manager 的儲存櫃常見問題
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 什麼是貨架防損和抽屜防損？

機櫃遺失保護和抽屜遺失保護是儲存池和磁碟區群組的屬性，可讓您在單一機櫃或抽屜發生故障時維持資料存取。



=== 貨架損耗保護

硬碟架是指容納硬碟或硬碟和控制器的機殼。硬碟架遺失保護功能可確保在單一硬碟架發生完全通訊中斷時，仍能存取儲存池或磁碟區群組中的磁碟區資料。完全通訊中斷的一個例子是硬碟架斷電或兩個 I/O 模組（IOM）同時發生故障。

[NOTE]
====
如果儲存池或磁碟區組中已有磁碟機發生故障，則無法保證磁碟櫃遺失保護。在這種情況下，失去對磁碟櫃的存取權限，進而導致儲存池或磁碟區組中另一個磁碟機無法存取，將造成資料遺失。

====
貨架遺失保護的標準取決於保護方法，如下表所示：

[cols="1a,1a,1a"]
|===
| 等級 | 貨架損失保障標準 | 所需的最少磁碟櫃數量 


 a| 
資源池
 a| 
儲存池必須包含至少五個硬碟架上的硬碟，且每個硬碟架上的硬碟數量必須相等。硬碟架遺失保護不適用於高容量硬碟架；如果您的系統包含高容量硬碟架，請參閱 Drawer Loss Protection。
 a| 
5



 a| 
RAID 6
 a| 
磁碟區群組在單一機櫃中包含的磁碟機不超過兩個。
 a| 
3



 a| 
RAID 3 或 RAID 5
 a| 
磁碟區群組中的每個磁碟機都位於不同的機櫃中。
 a| 
3



 a| 
RAID 1
 a| 
RAID 1 配對中的每個磁碟機都必須位於不同的磁碟櫃中。
 a| 
2



 a| 
RAID 0
 a| 
無法實現貨架損耗保護。
 a| 
不適用

|===


=== 抽屜遺失保護

抽屜是硬碟架上的一個隔間，您可以將其拉出以存取硬碟。只有高容量硬碟架才配備抽屜。抽屜遺失保護功能可確保在單一抽屜完全失去通訊的情況下，仍可存取儲存池或磁碟區組中的磁碟區上的資料。完全失去通訊的情況包括抽屜斷電或抽屜內部組件故障。

[NOTE]
====
如果儲存池或磁碟區群組中已有磁碟機發生故障，則無法保證抽屜遺失保護。在這種情況下，無法存取某個抽屜（並因此無法存取儲存池或磁碟區群組中的另一個磁碟機）會導致資料遺失。

====
抽屜遺失保護的標準取決於保護方法，如下表所示：

[cols="1a,1a,1a"]
|===
| 等級 | 抽屜遺失保護標準 | 所需的抽屜數量下限 


 a| 
資源池
 a| 
資源池候選項目必須包含所有磁碟機櫃中的磁碟機，且每個磁碟機櫃中的磁碟機數量必須相等。

資源池必須包含至少五個磁碟機櫃中的磁碟機，且每個磁碟機櫃中的磁碟機數量必須相等。

當儲存池包含 15、20、25、30、35、40、45、50、55 或 60 個磁碟機時,一個 60 磁碟機機櫃可以實現磁碟櫃遺失保護。初始建立後,可以以 5 的倍數遞增新增至儲存池。
 a| 
5



 a| 
RAID 6
 a| 
磁碟區群組在單一抽屜中包含的磁碟機不超過兩個。
 a| 
3



 a| 
RAID 3 或 RAID 5
 a| 
磁碟區群組中的每個磁碟機都位於不同的抽屜中。
 a| 
3



 a| 
RAID 1
 a| 
鏡像配對中的每個磁碟機都必須位於不同的抽屜中。
 a| 
2



 a| 
RAID 0
 a| 
無法實現抽屜遺失保護。
 a| 
不適用

|===


== 什麼是電池學習週期？

學習週期是用於校準智慧型電池電量計的自動週期。

學習週期包含以下階段：

* 受控電池放電
* 休息期
* 收費


電池放電至預設閾值。在此階段，電池電量指示器將進行校準。

學習週期需要以下參數：

* 充滿電的電池
* 電池不會過熱


雙工控制器系統的學習週期同時進行。對於使用多個電池或電池組作為備用電源的控制器，學習週期則依序進行。

學習週期會以固定的時間間隔自動啟動，啟動時間固定在每週的同一天且時間相同。週期之間的間隔以週為單位描述。

[NOTE]
====
一個學習週期可能需要幾個小時才能完成。

====