---
permalink: sm-hardware/faq-storage-controller.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= SANtricity System Manager 的儲存控制器常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 什麼是自動協商？

自動協商是指網路介面能夠自動協調自身與其他網路介面的連線參數（速度與雙工模式）。

自動協商通常是配置管理連接埠的首選設定；但是，如果協商失敗，不匹配的網路介面設定可能會嚴重影響網路效能。在這種情況不可接受的情況下，您應該手動將網路介面設定設為正確的配置。自動協商由控制器的乙太網路管理連接埠執行。iSCSI 主機匯流排介面卡不會執行自動協商。

[NOTE]
====
如果自動協商失敗，控制器會嘗試以 10BASE-T 半雙工建立連線，這是最低的共同標準。

====


== 什麼是 IPv6 無狀態位址自動配置？

採用無狀態自動設定時、主機不會從伺服器取得位址和其他組態資訊。

IPv6 中的無狀態自動設定具有連結本機位址、多點傳播和鄰居發現（ND）協定等特性。IPv6 可以根據底層資料鏈結層位址產生位址的介面 ID。

無狀態自動配置和有狀態自動配置相輔相成。例如，主機可以使用無狀態自動配置來配置自身的位址，而使用有狀態自動配置來取得其他資訊。有狀態自動配置允許主機從伺服器取得位址和其他設定資訊。網際網路協定版本 6 (IPv6) 也定義了一種方法，可以一次重新編號網路上的所有 IP 位址。IPv6 定義了一種方法，使網路上的設備無需伺服器即可自動配置其 IP 位址和其他參數。

裝置在使用無狀態自動組態時會執行下列步驟：

. *產生連結本機位址* -- 裝置產生連結本機位址，該位址由 10 位元、54 個零和 64 位元介面 ID 組成。
. *測試鏈路本地地址的唯一性* -- 節點會測試以確保其產生的鏈路本地地址尚未在本地網路上使用。節點使用 ND 協定發送鄰居請求訊息。作為回應，本地網路會監聽鄰居通告訊息，該訊息指示另一個裝置是否已在使用該鏈路本地地址。如果是，則必須產生新的鏈路本地地址或自動配置失敗，並且必須使用其他方法。
. *指派連結本機位址* -- 如果裝置通過唯一性測試，則會將連結本機位址指派給其 IP 介面。連結本機位址可用於本機網路上的通訊，但不能用於 Internet 上的通訊。
. *聯絡路由器* -- 節點嘗試聯絡本機路由器，以取得有關繼續設定的更多資訊。此聯絡可透過監聽路由器定期傳送的路由器通告訊息、或傳送特定的路由器請求訊息以要求路由器提供下一步操作的相關資訊來執行。
. *為節點提供指導* -- 路由器提供節點關於如何進行自動設定的指導。或者，路由器會告訴主機如何決定全域 Internet 位址。
. *配置全域位址* -- 主機配置其全域唯一的網際網路位址。此位址通常由路由器提供給主機的網路前綴構成。




== 我應該選擇哪種方式— DHCP 還是手動設定？

網路組態的預設方法是動態主機組態協定（DHCP）。除非您的網路沒有 DHCP 伺服器，否則請始終使用此選項。



== 什麼是 DHCP 伺服器？

動態主機設定協定（DHCP）是一種自動分配網際網路協定（IP）位址的協定。

連接到 TCP/IP 網路的每個裝置都必須指派唯一的 IP 位址。這些裝置包括儲存陣列中的控制器。

如果沒有 DHCP，網路管理員需要手動輸入這些 IP 位址。有了 DHCP，當客戶端需要啟動 TCP/IP 操作時，用戶端會廣播位址資訊請求。DHCP 伺服器接收到請求後，會指派一個新位址，有效期為一段稱為租約的指定時間，並將該位址傳送給客戶端。有了 DHCP，設備每次連接到網路時都可以擁有不同的 IP 位址。在某些系統中，即使設備仍連接著網路，其 IP 位址也可能會變更。



== 如何設定我的 DHCP 伺服器？

您必須設定動態主機設定協定（DHCP）伺服器，以便為儲存陣列中的控制器使用靜態網際網路通訊協定（IP）位址。

DHCP 伺服器指派的 IP 位址通常是動態的，會因為租約到期而改變。某些設備，例如伺服器和路由器，需要使用靜態位址。儲存陣列中的控制器也需要靜態 IP 位址。

有關如何指派靜態位址的資訊，請參閱 DHCP 伺服器的說明文件。



== 為什麼需要變更控制器網路組態？

使用頻外管理時，您必須為每個控制器設定網路組態，包括其網際網路通訊協定（IP）位址、子網路遮罩（子網路遮罩）和閘道。

您可以使用 Dynamic Host Configuration Protocol （ DHCP ）伺服器來設定網路組態。如果您不使用 DHCP 伺服器、則必須手動輸入網路組態。



== 我應該從哪裡獲取網路組態？

您可以從網路管理員取得網際網路通訊協定（IP）位址、子網路遮罩（subnet mask）和閘道資訊。

在控制器上設定連接埠時，您需要這些資訊。



== 什麼是 ICMP PING 回應？

網際網路控制訊息協定 (ICMP) 是 TCP/IP 協定族中的一種協定。

 `ICMP echo request` 和 (`ICMP echo reply` 訊息通常被稱為  `ping` 訊息。 `Ping` 是系統管理員用來手動測試網路設備之間連接性以及測試網路延遲和丟包的故障排除工具。 `ping` 命令向網路上的設備發送  `ICMP echo request`，設備會立即回應 (`ICMP echo reply`。有時，公司的網路安全策略要求在所有裝置上停用  `ping` (`ICMP echo reply`，以增加未經授權人員發現這些裝置的難度。



== 何時應該重新整理連接埠組態？

當伺服器被修改或升級，並且與目前儲存陣列和您要使用的儲存陣列相關的 DHCP 資訊發生變更時，請重新整理 DHCP 伺服器。

具體來說，當您知道 DHCP 伺服器將分配不同的位址時，請從 DHCP 伺服器重新整理連接埠組態或 iSNS 伺服器。

[NOTE]
====
重新整理連接埠組態會破壞該連接埠上的所有 iSCSI 連線。

====


== 配置管理連接埠後，我該做什麼？

如果您變更了儲存陣列的 IP 位址、您可能需要在 SANtricity Unified Manager 中更新全域陣列檢視。

若要更新 Unified Manager 中的全域陣列檢視、請開啟介面並前往功能表： Manage[ Discover ]。

如果您仍在使用 SANtricity Storage Manager，請前往企業管理視窗（EMW），在那裡您必須刪除並重新新增新的 IP 位址。



== 為什麼儲存系統處於非最佳模式？

儲存系統處於非最佳模式是由於系統組態無效所致。儘管如此，對現有磁碟區的正常 I/O 存取仍然完全受支援；但是，SANtricity System Manager 將禁止某些操作。

儲存系統可能會因下列其中一項原因而轉換為「無效系統組態」：

* 控制器不符合規範，可能是因為它的子型號 ID（SMID）代碼不正確，或者它超出了進階功能的限制。
* 內部服務作業正在進行中，例如磁碟機韌體下載。
* 控制器超過了同位檢查錯誤臨界值並進入鎖定狀態。
* 發生一般鎖定狀況。

