---
permalink: sm-hardware/hardware-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hardware, terms 
summary: 了解硬體術語如何應用於您的儲存陣列。 
---
= 了解 SANtricity 軟體中使用的硬體術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下硬體術語適用於儲存陣列。

.一般硬體術語：
[%collapsible]
====
[cols="25h,~"]
|===
| 元件 | 說明 


 a| 
機槽
 a| 
硬碟托架是機架上的插槽，用於安裝磁碟機或其他元件。



 a| 
控制器
 a| 
控制器由電路板、韌體和軟體組成。它控制驅動器並實現 System Manager 功能。



 a| 
控制器機櫃
 a| 
控制器機架包含一組磁碟機和一個或多個控制器盒。控制器盒內裝有控制器、主機介面卡（HIC）和電池。



 a| 
磁碟機
 a| 
磁碟機是一種電磁機械裝置或固態記憶體裝置，可為資料提供實體儲存媒體。



 a| 
磁碟機櫃
 a| 
磁碟機櫃（也稱為擴充櫃）包含一組磁碟機和兩個輸入 / 輸出模組（IOM）。IOM 包含 SAS 連接埠，可將磁碟機櫃連接至控制器櫃或其他磁碟機櫃。



 a| 
IOM（ESM）
 a| 
IOM 是一種輸入/輸出模組，包含用於將磁碟機櫃連接至控制器櫃的 SAS 連接埠。在先前的控制器型號中，IOM 被稱為環境服務模組（ESM）。



 a| 
電源 / 風扇罐
 a| 
電源 / 風扇盒是一種可以滑入層架的組件。它包含電源供應器和整合風扇。



 a| 
SFP
 a| 
SFP 是 Small Form-factor Pluggable (SFP) 收發器。



 a| 
機櫃
 a| 
機架是安裝在機櫃或機架中的機箱。其中包含儲存陣列的硬體元件。機架有兩種類型：控制器機架和磁碟機機架。控制器機架包含控制器和磁碟機。磁碟機機架包含輸入 / 輸出模組（IOM）和磁碟機。



 a| 
儲存陣列
 a| 
儲存陣列包括機架、控制器、磁碟機、軟體和韌體。

|===
====
.控制器條款：
[%collapsible]
====
[cols="25h,~"]
|===
| 元件 | 說明 


 a| 
控制器
 a| 
控制器由電路板、韌體和軟體組成。它控制驅動器並實現 System Manager 功能。



 a| 
控制器機櫃
 a| 
控制器機架包含一組磁碟機和一個或多個控制器盒。控制器盒內裝有控制器、主機介面卡（HIC）和電池。



 a| 
DHCP
 a| 
動態主機組態協定（Dynamic Host Configuration Protocol，DHCP）是網際網路協定（Internet Protocol，IP）網路上使用的一種協議，用於動態分送網路設定參數，例如 IP 位址。



 a| 
DNS
 a| 
網域名稱系統（Domain Name System，DNS）是連接到網際網路或專用網路的裝置所提供的命名系統。DNS 伺服器維護一個網域名稱目錄，並將網域名稱轉換為網際網路通訊協定（Internet Protocol，IP）位址。



 a| 
雙工組態
 a| 
雙工模式是指儲存陣列中採用雙控制器模組配置。雙工系統在控制器、邏輯磁碟區路徑和磁碟路徑方面都具有完全冗餘。如果一個控制器發生故障，另一個控制器會接管其 I/O 操作，以確保系統可用性。雙工系統還配備冗餘風扇和電源。



 a| 
全雙工 / 半雙工連接
 a| 
全雙工和半雙工指的是連接模式。在全雙工模式下，兩個裝置可以同時進行雙向通訊。在半雙工模式下，裝置一次只能進行單向通訊（一個裝置傳送訊息，另一個裝置接收訊息）。



 a| 
HIC
 a| 
主機介面卡（HIC）可選擇性地安裝在控制器外殼內。內建於控制器中的主機連接埠稱為底板主機連接埠。內建於 HIC 中的主機連接埠稱為 HIC 連接埠。



 a| 
ICMP PING 回應
 a| 
網際網路控制訊息協定（ICMP）是網路電腦作業系統用於傳送訊息的協定。ICMP 訊息用於確定主機是否可達以及封包往返該主機所需的時間。



 a| 
MAC 位址
 a| 
乙太網路使用媒體存取控制標識符（MAC 位址）來區分連接相同實體傳輸網路介面上兩個連接埠的不同邏輯通道。



 a| 
管理用戶端
 a| 
管理用戶端是指安裝了瀏覽器以存取 System Manager 的電腦。



 a| 
MTU
 a| 
最大傳輸單元 (MTU) 是網路中可以傳送的最大封包或訊框大小。



 a| 
NTP
 a| 
網路時間協定 (NTP) 是一種用於資料網路中電腦系統之間時脈同步的網路協定。



 a| 
單工配置
 a| 
Simplex 是儲存陣列中的單一控制器模組組態。Simplex 系統不提供控制器或磁碟路徑備援，但具有備援風扇和電源供應器。



 a| 
VLAN
 a| 
虛擬區域網路（VLAN）是一種邏輯網路，其行為就像它與其他由相同裝置（交換器、路由器等）支援的網路在實體上是分離的一樣。

|===
====
.磁碟機條款：
[%collapsible]
====
[cols="25h,~"]
|===
| 元件 | 說明 


 a| 
DA
 a| 
Data Assurance (DA) 是一項功能，用於檢查和修正資料從控制器傳輸到磁碟機過程中可能出現的錯誤。Data Assurance 可以在儲存池或磁碟區群組層級啟用，主機需要使用支援 DA 的 I/O 介面，例如 Fibre Channel。



 a| 
磁碟機安全功能
 a| 
磁碟機安全性是儲存陣列的功能，它透過全磁碟加密（FDE）磁碟機或聯邦資訊處理標準（FIPS）磁碟機提供額外的安全層。當這些磁碟機與磁碟機安全性功能配合使用時，需要安全金鑰才能存取其資料。當磁碟機從陣列中實體移除時，必須將其安裝到另一個陣列中才能運作，此時磁碟機將處於安全鎖定狀態，直到提供正確的安全金鑰為止。



 a| 
磁碟機櫃
 a| 
磁碟機櫃（也稱為擴充櫃）包含一組磁碟機和兩個輸入 / 輸出模組（IOM）。IOM 包含 SAS 連接埠，可將磁碟機櫃連接至控制器櫃或其他磁碟機櫃。



 a| 
DULBE
 a| 
已釋放或未寫入的邏輯區塊錯誤（DULBE）是 NVMe 磁碟機上的選項，它允許 EF300 或 EF600 儲存陣列支援資源配置磁碟區。



 a| 
FDE 驅動器
 a| 
全碟加密（FDE）磁碟機在硬體層級執行磁碟機加密。硬碟包含一個 ASIC 晶片，在寫入時加密資料，然後在讀取時解密資料。



 a| 
FIPS 驅動
 a| 
FIPS 硬碟採用聯邦資訊處理標準（FIPS）140-2 二級標準。它們本質上是全盤加密（FDE）硬碟，但符合美國政府關於確保強大加密演算法和方法的標準。FIPS 硬碟的安全標準高於全碟加密（FDE）硬碟。



 a| 
HDD
 a| 
硬碟機 (HDD) 是一種使用具有磁性塗層的旋轉金屬盤片的資料儲存裝置。



 a| 
熱備援磁碟機
 a| 
熱備援磁碟在 RAID 1、RAID 5 或 RAID 6 磁碟區群組中作為待命磁碟機。它們是功能完整且不含任何資料的磁碟機。如果磁碟區群組中的磁碟機故障，控制器會自動將故障磁碟機的資料重建至熱備援磁碟。



 a| 
NVMe
 a| 
非揮發性記憶體高速介面（NVMe）是專為快閃記憶體儲存裝置（例如 SSD 磁碟機）設計的介面。與先前的邏輯裝置介面相比、NVMe 可降低 I/O 負荷、並提升效能。



 a| 
SAS
 a| 
Serial Attached SCSI （ SAS ）是一種點對點串列協定，可將控制器直接連結至磁碟機。



 a| 
具備安全功能的磁碟機
 a| 
具備安全功能的磁碟機可以是全磁碟加密（FDE）磁碟機或聯邦資訊處理標準（FIPS）磁碟機，它們在寫入時加密資料，並在讀取時解密資料。這些磁碟機之所以被認為是具備安全_功能_的，是因為它們可以使用 Drive Security 功能來增強安全性。如果為與這些磁碟機一起使用的磁碟區群組和儲存池啟用了 Drive Security 功能，則這些磁碟機將變為已_啟用_安全功能。



 a| 
安全啟用磁碟機
 a| 
啟用安全功能的磁碟機與 Drive Security 功能配合使用。當您啟用 Drive Security 功能，然後將 Drive Security 套用至具備安全功能的磁碟機上的儲存池或磁碟區群組時，這些磁碟機即變為啟用安全功能。只有配置了正確安全金鑰的控制器才能進行讀寫存取。此額外的安全措施可防止未經授權存取已從儲存陣列中實體移除的磁碟機上的資料。



 a| 
SSD
 a| 
固態硬碟（SSD）是一種使用固態記憶體（快閃記憶體）持久儲存資料的資料儲存裝置。SSD 模擬傳統硬碟，並採用與硬碟相同的介面。

|===
====
.iSCSI 術語：
[%collapsible]
====
[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
CHAP
 a| 
挑戰握手認證協定（CHAP）方法在初始連結期間驗證目標和啟動器的身分。驗證基於稱為 CHAP __secret__ 的共用安全金鑰。



 a| 
控制器
 a| 
控制器由電路板、韌體和軟體組成。它控制驅動器並實現 System Manager 功能。



 a| 
DHCP
 a| 
動態主機組態協定（Dynamic Host Configuration Protocol，DHCP）是網際網路協定（Internet Protocol，IP）網路上使用的一種協議，用於動態分送網路設定參數，例如 IP 位址。



 a| 
IB
 a| 
InfiniBand (IB) 是高效能伺服器和儲存系統之間資料傳輸的通訊標準。



 a| 
ICMP PING 回應
 a| 
網際網路控制訊息協定（ICMP）是網路電腦作業系統用於傳送訊息的協定。ICMP 訊息用於確定主機是否可達以及封包往返該主機所需的時間。



 a| 
IQN
 a| 
iSCSI 限定名稱（IQN）識別碼是 iSCSI 發起程序或 iSCSI 目標的唯一名稱。



 a| 
iSER
 a| 
iSCSI Extensions for RDMA (iSER) 是一種擴展 iSCSI 協定以使其能夠在 RDMA 傳輸（例如 InfiniBand 或 Ethernet）上運作的協定。



 a| 
iSNS
 a| 
Internet Storage Name Service （ iSNS ）是一種協議，可在 TCP/IP 網路上自動發現、管理和設定 iSCSI 和 Fibre Channel 裝置。



 a| 
MAC 位址
 a| 
乙太網路使用媒體存取控制標識符（MAC 位址）來區分連接相同實體傳輸網路介面上兩個連接埠的不同邏輯通道。



 a| 
管理用戶端
 a| 
管理用戶端是指安裝了瀏覽器以存取 System Manager 的電腦。



 a| 
MTU
 a| 
最大傳輸單元 (MTU) 是網路中可以傳送的最大封包或訊框大小。



 a| 
RDMA
 a| 
遠端直接記憶體存取（RDMA）是一種允許網路電腦在不涉及任何一台電腦的作業系統的情況下交換主記憶體中的資料的技術。



 a| 
未命名的探索工作階段
 a| 
啟用未命名探索工作階段選項後，iSCSI 啟動器無需指定目標 IQN 即可擷取控制器的資訊。

|===
====
.NVMe 術語：
[%collapsible]
====
[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
InfiniBand
 a| 
InfiniBand (IB) 是高效能伺服器和儲存系統之間資料傳輸的通訊標準。



 a| 
命名空間
 a| 
命名空間是格式化為區塊存取的 NVM 儲存設備。它類似於 SCSI 中的邏輯單元，後者對應於儲存陣列中的磁碟區。



 a| 
命名空間 ID
 a| 
命名空間 ID 是 NVMe 控制器對命名空間的唯一標識符，其值可設定為 1 到 255 之間。它類似於 SCSI 中的邏輯單元號碼（LUN）。



 a| 
NQN
 a| 
NVMe 限定名稱（NQN）用於識別遠端儲存目標（儲存陣列）。



 a| 
NVM
 a| 
非揮發性記憶體 （NVM） 是一種持久性記憶體，廣泛應用於多種儲存裝置。



 a| 
NVMe
 a| 
非揮發性記憶體高速介面（NVMe）是專為快閃記憶體儲存裝置（例如 SSD 磁碟機）設計的介面。與先前的邏輯裝置介面相比、NVMe 可降低 I/O 負荷、並提升效能。



 a| 
NVMe-oF
 a| 
Non-Volatile Memory Express over Fabrics（NVMe-oF）是一種規範，可讓 NVMe 命令和資料透過網路在主機和儲存設備之間傳輸。



 a| 
NVMe 控制器
 a| 
NVMe 控制器是在主機連線過程中建立的。它提供主機與儲存陣列中的命名空間之間的存取路徑。



 a| 
NVMe 佇列
 a| 
佇列用於透過 NVMe 介面傳遞命令和訊息。



 a| 
NVMe 子系統
 a| 
具有 NVMe 主機連線的儲存陣列。



 a| 
RDMA
 a| 
遠端直接記憶體存取（RDMA）透過在網路介面卡（NIC）硬體中實作傳輸協定，使伺服器能夠更直接地進行資料傳輸。



 a| 
RoCE
 a| 
RDMA over Converged Ethernet （ RoCE ）是一種網路協定，允許透過乙太網路進行遠端直接記憶體存取（ RDMA ）。



 a| 
SSD
 a| 
固態硬碟（SSD）是一種使用固態記憶體（快閃記憶體）持久儲存資料的資料儲存裝置。SSD 模擬傳統硬碟，並採用與硬碟相同的介面。

|===
====