---
permalink: sm-hardware/hardware-page-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hardware, page, components, 
summary: Hardware 頁面以圖形方式展示了儲存陣列的實體組件。您可以在此處查看元件狀態並執行與這些元件相關的一些功能。 
---
= SANtricity System Manager 硬體頁面和元件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hardware 頁面以圖形方式展示了儲存陣列的實體組件。您可以在此處查看元件狀態並執行與這些元件相關的一些功能。



== 書架

儲存架是容納儲存陣列硬體（控制器、電源 / 風扇箱和磁碟機）的組件。儲存架有兩種類型：

* *Controller shelf* -- 包含磁碟機、電源 / 風扇罐和控制器。
* *硬碟架*（或*擴充架*）-- 包含硬碟、電源供應器/風扇箱和兩個輸入/輸出模組 (IOM)。IOM 也稱為環境服務模組 (ESM)，包含用於將硬碟架連接到控制器架的 SAS 連接埠。


硬碟架有三種尺寸，分別可容納 12 個、24 個或 60 個磁碟機。每個硬碟架都有一個 ID 號碼，由控制器韌體指派。該 ID 會顯示在硬碟架檢視的左上角。

硬體頁面上的機架視圖顯示正面或背面組件。您可以透過選擇機架視圖右上角的 *磁碟機* 或 *控制器* 標籤在兩種視圖之間切換。您也可以從頁面底部選擇 *顯示所有正面* 或 *顯示所有背面*。正面視圖和背面視圖顯示以下內容：

* *前組件* -- 磁碟機和空磁碟機托架。
* *後部組件* -- 控制器和電源 / 風扇罐（用於控制器架）或 IOM 和電源 / 風扇罐（用於驅動器架）。


您可以執行以下與機櫃相關的功能：

* 打開機櫃的定位燈，以便找到機櫃在櫃子或機架中的實際位置。
* 變更貨架檢視左上角顯示的 ID 號碼。
* 檢視機櫃設定，例如已安裝的磁碟機類型和序號。
* 上下移動機櫃視圖，以符合儲存陣列中的實體配置。




== 控制器

控制器是將硬體和韌體結合在一起，實現儲存陣列和管理功能。它包括快取記憶體、磁碟機支援和主機介面支援。

您可以執行以下與控制器相關的功能：

* 設定管理連接埠的 IP 位址和速度。
* 設定 iSCSI 主機連線（如果您有 iSCSI 主機）。
* 設定網路時間協定（NTP）伺服器和網域名稱系統（DNS）伺服器。
* 查看控制器狀態和設定。
* 允許區域網路外的使用者啟動 SSH 工作階段並變更控制器上的設定。
* 將控制器置於離線、線上或服務模式。




== 磁碟機

儲存陣列可包含硬碟機（HDD）或固態硬碟（SSD）。根據機櫃尺寸，機櫃中最多可安裝 12、24 或 60 個磁碟機。

您可以執行以下與磁碟機相關的功能：

* 開啟磁碟機的定位燈，以便找到磁碟機在機櫃中的實體位置。
* 查看磁碟機狀態和設定。
* 重新指派磁碟機 （以邏輯方式將故障磁碟機更換為未指派的磁碟機）、並視需要手動重建磁碟機。
* 手動將磁碟機標記為故障，以便更換磁碟機。（將磁碟機標記為故障可讓您在更換磁碟機之前複製磁碟機內容。）
* 指派或取消指派熱備援磁碟。
* 擦除磁碟機。

