---
permalink: sm-hardware/hot-spare-drives.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hot, spare, drives, raid1, raid6, raid5 
summary: 熱備援磁碟機在 System Manager 的 RAID 1、RAID 5 或 RAID 6 磁碟區群組中作為待命磁碟機。 
---
= 了解 SANtricity System Manager 中的熱備用磁碟機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
熱備援磁碟機在 SANtricity System Manager 的 RAID 1、RAID 5 或 RAID 6 磁碟區群組中作為待命磁碟機。

它們是功能齊全但內部不包含任何資料的磁碟機。如果磁碟區群組中的某個磁碟機發生故障，控制器會自動將故障磁碟機上的資料重建到指定為熱備援磁碟機的磁碟機上。

熱備援磁碟並非專用於特定的磁碟區群組。只要熱備援磁碟和磁碟機共用以下屬性，它們就可以用於儲存陣列中任何故障的磁碟機：

* 容量相等 （或熱備援容量較大）
* 相同媒體類型（例如 HDD 或 SSD）
* 相同介面類型 （例如，SAS）




== 如何識別熱備援

您可以透過初始設定精靈或硬體頁面指派熱備盤。若要確定是否已指派熱備盤，請前往硬體頁面並尋找以粉紅色顯示的磁碟機托架。



== 熱備援涵蓋範圍的運作方式

熱備援涵蓋範圍的運作方式如下：

* 您可以將未指派的磁碟機保留為 RAID 1、RAID 5 或 RAID 6 磁碟區群組的熱備用磁碟。
+
[NOTE]
====
熱備盤不能用於儲存池，儲存池採用不同的資料保護方法。儲存池不會預留額外的磁碟機，而是在儲存池中的每個磁碟機內預留備用容量（稱為_保留容量_）。如果儲存池中的某個磁碟機發生故障，控制器會利用該備用容量重建資料。

====
* 如果 RAID 1、RAID 5 或 RAID 6 磁碟區群組中的某個磁碟機發生故障，控制器會自動使用備援資料從故障磁碟機重建資料。熱備援磁碟機會自動替換故障磁碟機，無需進行實體更換。
* 當您實際更換了故障硬碟後，系統會將熱備用硬碟上的資料複製回傳到被更換的硬碟。如果您已將熱備用硬碟指定為磁碟區群組的永久成員，則無需執行此複製回傳操作。
* 磁碟區群組的紙匣遺失保護和抽屜遺失保護的可用性取決於組成該磁碟區群組的磁碟機位置。由於磁碟機故障以及熱備援磁碟機的位置，紙匣遺失保護和抽屜遺失保護可能會遺失。為確保紙匣遺失保護和抽屜遺失保護不受影響，您必須更換故障磁碟機以啟動回寫程序。
* 在更換故障磁碟機時，儲存陣列磁碟區仍保持連線和可存取狀態，因為熱備援磁碟機會自動取代故障磁碟機。




== 熱備援磁碟機容量的考量因素

選擇容量等於或大於要保護的磁碟機總容量的磁碟機。例如、如果您有一個 18 GiB 的磁碟機、配置容量為 8 GiB、則可以使用 9 GiB 或更大的磁碟機作為熱備援磁碟機。一般而言、除非磁碟機的容量等於或大於儲存陣列中最大磁碟機的容量、否則請勿將磁碟機指派為熱備援磁碟機。

[NOTE]
====
如果沒有物理容量相同的熱備援磁碟，則可以使用容量較低的磁碟作為熱備援磁碟，但前提是該磁碟的「已使用容量」等於或小於熱備援磁碟的容量。

====


== 媒體和介面類型的考量

用作熱備盤的磁碟機必須與它要保護的磁碟機具有相同的媒體類型和介面類型。例如，HDD 磁碟機不能用作 SSD 磁碟機的熱備盤。



== 安全功能磁碟機的考量事項

具備安全功能的磁碟機(例如 FDE 或 FIPS)可作為具有或不具有安全功能的磁碟機的熱備援磁碟機。但是,不具備安全功能的磁碟機無法作為具有安全功能的磁碟機的熱備援磁碟機。

當您選擇一塊已啟用安全功能的磁碟機用作熱備援時，System Manager 會提示您先執行安全清除才能繼續。安全清除會將磁碟機的安全屬性重設為具備安全功能，但不會啟用安全功能。

[NOTE]
====
啟用 Drive Security 功能後，如果使用支援安全功能的磁碟機建立儲存池或磁碟區群組，則這些磁碟機將變為_安全啟用_狀態。只有配置了正確安全金鑰的控制器才能對其進行讀寫存取。這種增強的安全機制可防止未經授權存取已從儲存陣列中實體移除的磁碟機上的資料。

====


== 建議的熱備援磁碟機數量

如果您使用 Initial Setup 精靈自動建立熱備盤，System Manager 會為特定媒體類型和介面類型的每 30 個磁碟機建立一個熱備盤。否則，您可以手動在儲存陣列的磁碟區群組中建立熱備盤。
