---
permalink: sm-hardware/limit-the-drive-view.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, limit, drive, view, 
summary: 如果儲存陣列包含具有不同類型實體和邏輯屬性的磁碟機、「硬體」頁面會提供篩選欄位、協助您限制磁碟機檢視並找出特定磁碟機。 
---
= 在 SANtricity System Manager 中篩選磁碟機檢視
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果儲存陣列包含具有不同類型實體和邏輯屬性的磁碟機、「硬體」頁面會提供篩選欄位、協助您限制磁碟機檢視並找出特定磁碟機。

.關於此任務
磁碟機篩選器可將檢視限制為僅顯示特定類型的實體磁碟機（例如所有 SAS）、具有特定安全性屬性（例如具有安全功能）或位於特定邏輯位置（例如 Volume Group 1）的磁碟機。您可以同時使用這些篩選器或單獨使用。

[NOTE]
====
如果所有磁碟機都具有相同的實體屬性，則不會顯示 *Show drives that are...* 篩選欄位。如果所有磁碟機都具有相同的邏輯屬性，則不會顯示 *Anywhere in the storage array* 篩選欄位。

====
.步驟
. 選擇 *Hardware* 。
. 在第一個篩選欄位（*Show drives that are...* 下）中，按一下下拉箭頭以顯示可用的磁碟機類型和安全性屬性。
+
磁碟機類型可能包括：

+
** 磁碟機媒體類型 （SSD、HDD）
** 磁碟機介面類型
** 磁碟機容量（從高到低）
** 磁碟機速度（從高到低）安全屬性可能包括：
** 具備安全能力
** 已啟用安全功能
** 具備 DA (Data Assurance) 能力
** 符合 FIPS 標準
** 符合 FIPS 標準（FIPS 140-2）
** 符合 FIPS 標準（FIPS 140-3）
+
如果所有硬碟的某些屬性相同，則下拉清單中不會顯示這些屬性。例如，如果儲存陣列包含所有具有 SAS 介面且轉速為 15000 RPM 的 SSD 硬碟，但部分 SSD 的容量不同，則下拉清單僅顯示容量作為篩選選項。

+
當您從欄位中選擇選項時，不符合您的篩選條件的磁碟機在圖形檢視中會顯示為灰色。



. 在第二個篩選方塊中，按一下下拉箭頭以顯示磁碟機的可用邏輯位置。
+
[NOTE]
====
如果需要清除篩選條件，請選擇篩選框最右邊的 *Clear* 。

====
+
邏輯位置可能包括：

+
** 資源池
** 磁碟區群組
** 熱備援
** SSD 快取
** 未分配
+
當您從欄位中選擇選項時，不符合您的篩選條件的磁碟機在圖形檢視中會顯示為灰色。



. 您也可以選擇篩選欄位最右側的 *Turn on locator lights*，為顯示的磁碟機開啟定位燈。
+
此操作可協助您在儲存陣列中實際找到磁碟機。


