---
permalink: sm-hardware/unlock-or-reset-a-locked-nvme-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unlock, reset, locked, fips, nvme, drives, 
summary: 如果將一個或多個鎖定的 NVMe 或 FIPS 磁碟機插入儲存陣列，您可以透過新增與這些磁碟機相關聯的安全金鑰檔案來解鎖磁碟機資料。如果您沒有安全金鑰，您可以透過輸入每個鎖定磁碟機的實體安全 ID （PSID）來對其執行重設，以重設其安全屬性並清除磁碟機資料。 
---
= 在 SANtricity System Manager 中解鎖或重設鎖定的 NVMe 或 FIPS 磁碟機
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果將一個或多個鎖定的 NVMe 或 FIPS 磁碟機插入儲存陣列，您可以透過新增與這些磁碟機相關聯的安全金鑰檔案來解鎖磁碟機資料。如果您沒有安全金鑰，您可以透過輸入每個鎖定磁碟機的實體安全 ID （PSID）來對其執行重設，以重設其安全屬性並清除磁碟機資料。

.開始之前
* 對於「解鎖」選項，請確保安全金鑰檔案（副檔名為 `.slk`）位於管理用戶端（用於存取 System Manager 的具有瀏覽器的系統）上。您還必須知道與該金鑰關聯的密碼短語。
* 對於 Reset 選項，您必須找到要重置的每個磁碟機上的 PSID。若要找到 PSID，請實際移除磁碟機並在磁碟機標籤上找到 PSID 字串（最多 32 個字元），然後重新安裝磁碟機。


.關於此任務
本任務介紹如何透過將安全金鑰檔案匯入儲存陣列來解鎖 NVMe 或 FIPS 磁碟機中的資料。如果安全金鑰無法使用，本任務也會介紹如何重置已鎖定的磁碟機。

[NOTE]
====
如果磁碟機是使用外部金鑰管理伺服器鎖定的，請在 System Manager 中選擇功能表：Settings[System > Security key management] 來設定外部金鑰管理並解鎖磁碟機。

====
您可以從硬體頁面或從功能表：設定 [系統 > 安全金鑰管理] 存取解鎖功能。以下工作提供從硬體頁面進行的說明。

.步驟
. 選擇 *Hardware* 。
. 如果圖形顯示了控制器，請按一下 *Drives* 標籤。
+
圖形變更為顯示磁碟機而非控制器。

. 選擇要解鎖或重設的 NVMe 或 FIPS 硬碟。
+
磁碟機的內容功能表隨即開啟。

. 選擇 *Unlock* 以套用安全金鑰檔案，或如果沒有安全金鑰檔案，請選擇 *Reset* 。
+
只有在選擇鎖定的 NVMe 或 FIPS 磁碟機時，才會顯示這些選項。

+
[CAUTION]
====
重置操作會清除所有資料。僅當您沒有安全金鑰時才可執行重設操作。重置已鎖定的磁碟機會永久刪除磁碟機上的所有資料，並將其安全屬性重設為「具備安全功能」，但不會啟用安全功能。*此操作不可逆。*

====
. 請執行下列其中一項操作：
+
.. *解鎖*：在 *解鎖安全磁碟機* 對話方塊中、按一下 *瀏覽*、然後選擇與要解鎖的磁碟機對應的安全金鑰檔案。接下來、輸入密碼短語、然後按一下 *解鎖*。
.. *重設*：在 *重設鎖定磁碟機* 對話方塊中，在欄位中輸入 PSID 字串，然後鍵入 `RESET`以確認。按一下 *重設*。
+
對於解鎖操作，您只需執行一次此操作即可解鎖所有 NVMe 或 FIPS 磁碟機。對於重設操作，您必須個別選取要重設的每個磁碟機。





.結果
該磁碟機現在可以用於其他磁碟區群組或磁碟集區，或其他儲存陣列。
