---
permalink: sm-hardware/view-drive-status-and-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, drive, status, settings, media, 
summary: 您可以檢視磁碟機的狀態和設定，例如媒體類型、介面類型和容量。 
---
= 在 SANtricity System Manager 中檢視磁碟機狀態和設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以檢視磁碟機的狀態和設定，例如媒體類型、介面類型和容量。

.步驟
. 選擇 *Hardware* 。
. 如果圖形顯示了控制器，請按一下 *Drives* 標籤。
+
圖形變更為顯示磁碟機而非控制器。

. 選擇要檢視狀態和設定的磁碟機。
+
磁碟機的內容功能表隨即開啟。

. 選擇 *View settings* 。
+
Drive Settings 對話方塊開啟。

. 若要查看所有設定，請按一下對話方塊右上角的 *Show more settings*。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
狀態
 a| 
顯示「最佳」、「離線」、「非關鍵故障」和「故障」狀態。「最佳」狀態表示理想的工作狀態。



 a| 
模式
 a| 
顯示已指派、未指派、熱備待命或使用中的熱備。



 a| 
地點
 a| 
顯示磁碟機所在的機櫃和插槽編號。



 a| 
指派給 / 可以保護 / 保護
 a| 
如果磁碟機已指派給儲存池、磁碟區組或 SSD 快取，則此欄位顯示「已指派給」。該值可以是儲存池名稱、磁碟區組名稱或 SSD 快取名稱。如果磁碟機已指派給熱備磁碟且其模式為待機，則此欄位顯示「可保護」。如果熱備磁碟可以保護一個或多個磁碟區組，則會顯示磁碟區組名稱。如果熱備磁碟無法保護任何磁碟區組，則顯示 0 個磁碟區組。

如果磁碟機被指派給熱備用磁碟且其模式為 In Use，則此欄位會顯示「Protecting」。該值是受影響磁碟區群組的名稱。

如果磁碟機未指派，則此欄位不會顯示。



 a| 
媒體類型
 a| 
顯示磁碟機使用的記錄媒體類型，可以是硬碟（HDD）或固態硬碟（SSD）。



 a| 
已用耐久度百分比（僅當有 SSD 磁碟機時顯示）
 a| 
迄今為止寫入磁碟機的資料量，除以理論總寫入限制。



 a| 
介面類型
 a| 
顯示磁碟機使用的介面類型，例如 SAS。



 a| 
磁碟機路徑備援
 a| 
顯示磁碟機與控制器之間的連線是否為備援（是）或非備援（否）。



 a| 
容量 (GiB)
 a| 
顯示磁碟機的可用容量（總配置容量）。



 a| 
轉速 (RPM)
 a| 
以 RPM 為單位顯示轉速（SSD 不顯示）。



 a| 
目前資料速率
 a| 
顯示磁碟機和儲存陣列之間的資料傳輸速率。



 a| 
邏輯磁區大小 （位元組）
 a| 
顯示磁碟機使用的邏輯磁區大小。



 a| 
實體磁區大小 （位元組）
 a| 
顯示磁碟機所使用的實體磁區大小。通常，硬碟機的實體磁區大小為 4096 位元組。



 a| 
磁碟機韌體版本
 a| 
顯示磁碟機韌體的修訂層級。



 a| 
全球識別碼
 a| 
顯示磁碟機的唯一十六進位識別碼。



 a| 
產品 ID
 a| 
顯示產品識別碼，由製造商指派。



 a| 
序號
 a| 
顯示磁碟機的序號。



 a| 
製造商
 a| 
顯示磁碟機的廠商。



 a| 
製造日期
 a| 
顯示磁碟機的製造日期。


NOTE: 不適用於 NVMe 磁碟機。



 a| 
具備安全能力
 a| 
顯示磁碟機是否具備安全功能（是）或不具備安全功能（否）。具備安全功能的磁碟機可以是全磁碟加密（FDE）磁碟機或聯邦資訊處理標準（FIPS）磁碟機（140-2 級或 140-3 級），它們在寫入時加密資料，並在讀取時解密資料。這些磁碟機之所以被視為具備安全_功能_，是因為它們可以使用「磁碟機安全性」功能來增強安全性。如果為與這些磁碟機一起使用的磁碟區群組和儲存池啟用了「磁碟機安全性」功能，則這些磁碟機將變為_已啟用_安全功能。



 a| 
已啟用安全功能
 a| 
顯示磁碟機是否已啟用安全功能（是）或未啟用（否）。已啟用安全功能的磁碟機與 Drive Security 功能搭配使用。當您啟用 Drive Security 功能，然後將 Drive Security 套用至具有安全_功能_的磁碟機上的儲存池或 Volume 群組時，這些磁碟機就會變成已_啟用_安全功能。只有使用正確安全金鑰設定的控制器才能進行讀取和寫入存取。這項額外的安全措施可防止未經授權存取實際從儲存陣列中移除的磁碟機上的資料。



 a| 
可讀寫存取
 a| 
顯示磁碟機是否可讀取 / 寫入存取（是）或不可（否）。



 a| 
磁碟機安全金鑰識別碼
 a| 
顯示已啟用安全功能的磁碟機的安全性金鑰。磁碟機安全功能是儲存陣列的特性，可為全磁碟加密（FDE）磁碟機或聯邦資訊處理標準（FIPS）磁碟機提供額外的安全層。當這些磁碟機與磁碟機安全功能配合使用時，需要安全金鑰才能存取其資料。如果磁碟機從陣列中實體移除，則必須將其安裝到另一個陣列中才能運作。安裝後，磁碟機將處於安全鎖定狀態，直到提供正確的安全金鑰為止。



 a| 
具備 Data Assurance (DA) 能力
 a| 
顯示 Data Assurance (DA) 功能是否已啟用（是）或未啟用（否）。Data Assurance (DA) 是一項功能，可在資料透過控制器傳輸到磁碟機時檢查並修正可能發生的錯誤。Data Assurance 可在儲存池或磁碟區群組層級啟用，主機使用支援 DA 的 I/O 介面，例如 Fibre Channel。



 a| 
具備 DULBE 功能
 a| 
指示是否啟用「已釋放或未寫入邏輯區塊錯誤（DULBE）」選項（是）或未啟用（否）。DULBE 是 NVMe 驅動器上的選項，可讓 EF300 或 EF600 儲存陣列支援資源預置磁碟區。

|===
====
. 按一下 *Close* 。

