---
permalink: sm-hardware/view-hardware-components.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, hardware, components, filtering, 
summary: 硬體頁面提供排序和篩選功能，使查找元件更加容易。 
---
= 在 SANtricity System Manager 中檢視硬體元件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
硬體頁面提供排序和篩選功能，使查找元件更加容易。

.步驟
. 選擇 *Hardware* 。
. 使用下表中所述的功能來檢視硬體元件。


[cols="25h,~"]
|===
| 功能 | 說明 


 a| 
磁碟機、控制器和元件檢視
 a| 
若要在前視圖和後視圖之間切換，請從最右側選擇 *Drives* 或 *Controllers & Components*（顯示的連結取決於目前視圖）。*Drives* 視圖顯示磁碟機和任何空的磁碟機插槽。*Controllers & Components* 視圖顯示控制器以及任何 IOM（ESM）模組、電源/風扇盒或空的控制器插槽。在頁面底部，您也可以選擇 *Show all drives*。



 a| 
磁碟機檢視篩選器
 a| 
如果儲存陣列包含具有不同實體和邏輯屬性的磁碟機，*硬體* 頁面會包含磁碟機檢視篩選器。這些篩選欄位可協助您透過限制頁面上顯示的磁碟機類型來快速找到特定磁碟機。在 *顯示以下類型的磁碟機...* 下，按一下左側的篩選欄位（預設顯示 *任何磁碟機類型*），即可查看實體屬性（例如容量和速度）的下拉清單。按一下右側的篩選欄位（預設顯示 *儲存陣列中的任何位置*），即可查看邏輯屬性（例如磁碟區群組指派）的下拉清單。您可以同時使用這些篩選器，也可以單獨使用。

[NOTE]
====
如果儲存陣列包含的磁碟機都具有相同的實體屬性，則左側的 *Any drive type* 欄位不會顯示。如果磁碟機都位於相同的邏輯位置，則右側的 *Anywhere in the storage array* 欄位不會顯示。

====


 a| 
圖例
 a| 
組件以特定顏色顯示，以描述其角色狀態。若要展開和收合這些狀態的說明，請按一下 *Legend* 。



 a| 
顯示狀態圖示詳細資料
 a| 
狀態指示器可以包含可用性狀態的文字描述。點選 *Show status icon details* 可顯示或隱藏此狀態文字。



 a| 
機櫃/機櫃圖示
 a| 
每個機架視圖都提供相關指令列表，以及屬性和狀態。點擊 *Shelf* 即可查看命令下拉清單。您也可以選擇頂部的圖標，查看各個組件的狀態和屬性，例如：控制器、IOM（ESM）、電源、風扇、溫度、電池和 SFP。



 a| 
貨架順序
 a| 
您可以在「硬體」頁面重新排列機櫃。使用每個機櫃檢視右上角的向上和向下箭頭來變更機櫃的上下順序。

|===