---
permalink: um-manage/create-asynchronous-mirrored-pair-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, create, asynchronous, mirrored, pair 
summary: 若要設定非同步鏡像，您需要建立一個鏡像配對，其中包括本機陣列上的主要磁碟區和遠端陣列上的次要磁碟區。 
---
= 在 SANtricity Unified Manager 中建立非同步鏡像配對
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要設定非同步鏡像，您需要建立一個鏡像配對，其中包括本機陣列上的主要磁碟區和遠端陣列上的次要磁碟區。

.開始之前
在建立鏡像配對之前，請先滿足 Unified Manager 的以下要求：

* Web Services Proxy 服務必須正在執行。
* Unified Manager 必須透過 HTTPS 連線在本機主機上執行。
* Unified Manager 必須顯示儲存陣列的有效 SSL 憑證。您可以接受自簽憑證，或使用 Unified Manager 並瀏覽至功能表：Certificate[Certificate Management] 來安裝您自己的安全性憑證。


此外，請確保儲存陣列和磁碟區符合以下要求：

* 每個儲存陣列必須有兩個控制器。
* 必須在 Unified Manager 中發現這兩個儲存陣列。
* 主陣列和次要陣列中的每個控制器都必須配置 Ethernet 管理連接埠，並且必須連接到您的網路。
* 儲存陣列的最低韌體版本為 7.84。（它們可以運行不同的作業系統版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 遠端儲存陣列上必須有足夠的可用容量來建立等於或大於要鏡像的主磁碟區的輔助磁碟區。
* 您的本機和遠端儲存陣列透過 Fibre Channel 架構或 iSCSI 介面連接。
* 您已建立要在非同步鏡像關係中使用的主磁碟區和次要磁碟區。
* 次要磁碟區必須至少與主要磁碟區一樣大。


.關於此任務
建立非同步鏡像配對的程序是一個多步驟程序。



== 步驟 1：建立或選取鏡像一致性群組

在此步驟中，您可以建立新的鏡像一致性群組或選擇現有群組。鏡像一致性群組是主磁碟區和次要磁碟區（鏡像配對）的容器，並指定群組中所有配對所需的重新同步方法（手動或自動）。

.步驟
. 從 *Manage* 頁面中，選擇要用作來源的本機儲存陣列。
. 選擇選單：Actions [ 建立非同步鏡像對 ] 。
+
建立非同步鏡像配對精靈隨即開啟。

. 選擇現有的鏡像一致性群組或建立新的鏡像一致性群組。
+
若要選擇現有群組，請確保已選取 *現有鏡像一致性群組*，然後從表格中選取該群組。一個一致性群組可以包含多個鏡像配對。

+
若要建立新群組，請執行下列操作：

+
.. 選擇 *A new mirror consistency group*，然後按一下 *Next*。
.. 請輸入一個唯一名稱，該名稱應能最準確地描述將在兩個儲存陣列之間鏡像的磁碟區上的資料。名稱只能包含字母、數字以及特殊字符，例如底線（_）、短橫線（-）和井號（#）。名稱長度不得超過 30 個字符，且不能包含空格。
.. 選擇要與本機儲存陣列建立鏡像關係的遠端儲存陣列。
+
[NOTE]
====
如果您的遠端儲存陣列受密碼保護，系統會提示輸入密碼。

====
.. 選擇您要手動或自動同步鏡像配對：
+
*** *手動* -- 選擇此選項可手動啟動此群組內所有鏡像對的同步。請注意，如果您以後想要執行重新同步，則必須啟動主儲存陣列的 System Manager，然後轉到選單：Storage［Asynchronous Mirroring］，從 *Mirror Consistency Groups* 標籤中選擇該群組，然後選擇選單：More［Manually resynchronize］。
*** *自動* -- 選擇所需的時間間隔，單位為 *分鐘*、*小時* 或 *天*，從上次更新開始到下次更新開始。例如，如果同步間隔設定為 30 分鐘，且同步過程從下午 4:00 開始，則下一次同步過程將於下午 4:30 開始。


.. 選擇所需的提醒設定：
+
*** 對於手動同步，請指定接收警報的閾值（由剩餘容量的百分比定義）。
*** 對於自動同步，您可以設定三種警示方法：當同步在特定時間長度內未完成時、當遠端陣列上的復原點資料超過特定時間限制時，以及當保留容量接近特定臨界值（由剩餘容量的百分比定義）時。




. 選擇 *Next* ，然後轉到 <<步驟 2：選取主要磁碟區>>。
+
如果您定義了新的鏡像一致性群組，Unified Manager 會先在本機儲存陣列上建立該鏡像一致性群組，然後再在遠端儲存陣列上建立該鏡像一致性群組。您可以透過為每個陣列啟動 System Manager 來檢視和管理鏡像一致性群組。

+
[NOTE]
====
如果 Unified Manager 成功在本機儲存陣列上建立了鏡像一致性群組，但在遠端儲存陣列上建立失敗，它會自動從本機儲存陣列中刪除該鏡像一致性群組。如果 Unified Manager 在嘗試刪除鏡像一致性群組時發生錯誤，則必須手動刪除該群組。

====




== 步驟 2：選取主要磁碟區

在此步驟中，您需要選擇鏡像關係中使用的主磁碟區並分配其保留容量。當您在本機儲存陣列上選擇主磁碟區時，系統會顯示該鏡像配對所有符合條件的磁碟區清單。任何不符合條件的磁碟區都不會顯示在該清單中。

新增至本機儲存陣列鏡像一致性群組的任何磁碟區都將在鏡像關係中扮演主要角色。

.步驟
. 從符合條件的磁碟區清單中，選擇要用作主磁碟區的磁碟區，然後按一下 *Next* 以分配保留容量。
. 從符合資格的候選清單中，選取主要磁碟區的保留容量。
+
請牢記以下準則：

+
** 預留容量的預設設定為基礎磁碟區容量的 20% ，通常這個容量就夠用了。如果變更此百分比，請點選 *Refresh Candidates* 。
** 所需容量會根據對主磁碟區的 I/O 寫入頻率和大小，以及您需要保留容量的時間而有所不同。
** 一般而言，如果存在以下一個或兩個條件，請選擇較大的保留容量：
+
*** 您打算長期保留鏡像配對。
*** 由於 I/O 活動頻繁，主磁碟區上很大一部分資料區塊將會發生變化。請使用歷史效能資料或其他作業系統公用程式來協助您確定主磁碟區的典型 I/O 活動。




. 選擇 *Next* ，然後轉到 <<步驟 3：選取次要磁碟區>>。




== 步驟 3：選取次要磁碟區

在此步驟中，您需要選擇鏡像關係中使用的輔助磁碟區並指派其預留容量。當您在遠端儲存陣列上選擇輔助磁碟區時，系統會顯示該鏡像配對所有符合條件的磁碟區清單。任何不符合使用條件的磁碟區都不會顯示在該清單中。

新增至遠端儲存陣列上鏡像一致性群組的任何磁碟區都將在鏡像關係中扮演次要角色。

.步驟
. 從符合條件的磁碟區清單中，選擇要用作鏡像配對中次要磁碟區的磁碟區，然後按一下 *Next* 以分配保留容量。
. 從符合條件的候選清單中，選取次要磁碟區的保留容量。
+
請牢記以下準則：

+
** 預留容量的預設設定為基礎磁碟區容量的 20% ，通常這個容量就夠用了。如果變更此百分比，請點選 *Refresh Candidates* 。
** 所需容量會根據對主磁碟區的 I/O 寫入頻率和大小，以及您需要保留容量的時間而有所不同。
** 一般而言，如果存在以下一個或兩個條件，請選擇較大的保留容量：
+
*** 您打算長期保留鏡像配對。
*** 由於 I/O 活動頻繁，主磁碟區上很大一部分資料區塊將會發生變化。請使用歷史效能資料或其他作業系統公用程式來協助您確定主磁碟區的典型 I/O 活動。




. 選擇 *Finish* 以完成非同步鏡像序列。


.結果
Unified Manager 執行以下操作：

* 開始本機儲存陣列和遠端儲存陣列之間的初始同步。
* 在本機儲存陣列和遠端儲存陣列上為鏡像配對建立保留容量。



NOTE: 如果被鏡像的磁碟區是精簡磁碟區，則在初始同步期間，只會將已配置的資料區塊（已分配的容量而非已報告的容量）傳送至次要磁碟區。這減少了完成初始同步所需傳輸的資料量。
