---
permalink: um-manage/create-synchronous-mirrored-pair-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, create, synchronous, mirrored, pair 
summary: 若要設定同步鏡像，您需要建立一個鏡像配對，其中包括本機陣列上的主要磁碟區和遠端陣列上的次要磁碟區。 
---
= 在 SANtricity Unified Manager 中建立同步鏡像配對
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要設定同步鏡像，您需要建立一個鏡像配對，其中包括本機陣列上的主要磁碟區和遠端陣列上的次要磁碟區。

[NOTE]
====
EF600/EF600C 或 EF300/EF300C 儲存系統不提供此功能。

====
.開始之前
在建立鏡像配對之前，請先滿足 Unified Manager 的以下要求：

* Web Services Proxy 服務必須正在執行。
* Unified Manager 必須透過 HTTPS 連線在本機主機上執行。
* Unified Manager 必須顯示儲存陣列的有效 SSL 憑證。您可以接受自簽憑證，或使用 Unified Manager 並瀏覽至功能表：Certificate[Certificate Management] 來安裝您自己的安全性憑證。


此外，請確保儲存陣列和磁碟區符合以下要求：

* 您計劃用於鏡像的兩個儲存陣列已在 Unified Manager 中發現。
* 每個儲存陣列必須有兩個控制器。
* 主陣列和次要陣列中的每個控制器都必須配置 Ethernet 管理連接埠，並且必須連接到您的網路。
* 儲存陣列的最低韌體版本為 7.84。（它們可以運行不同的作業系統版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 本機和遠端儲存陣列透過 Fibre Channel 架構連接。
* 您已建立要在同步鏡像關係中使用的主磁碟區和次要磁碟區。
* 主磁碟區必須是標準磁碟區。不能是精簡磁碟區或快照磁碟區。
* 輔助卷必須是標準卷。不能是精簡卷或快照卷。
* 次要磁碟區至少應與主要磁碟區一樣大。


.關於此任務
建立同步鏡像配對的程序是一個多步驟程序。



== 步驟 1：選取主要磁碟區

在此步驟中，您需要選擇同步鏡像關係中的主磁碟區。當您在本機儲存陣列上選擇主磁碟區時，系統會顯示該鏡像對中所有可用磁碟區的清單。任何不符合條件的磁碟區都不會顯示在清單中。您選擇的磁碟區將在鏡像關係中扮演主角色。

.步驟
. 從 *Manage* 頁面中，選擇要用作來源的本機儲存陣列。
. 選擇選單：Actions [ Create Synchronous Mirrored Pair ]。
+
「建立同步鏡像對」精靈開啟。

. 從符合條件的磁碟區清單中，選擇要用作鏡像主磁碟區的磁碟區。
. 選擇 *Next* ，然後轉到 <<步驟 2：選取次要磁碟區>>。




== 步驟 2：選取次要磁碟區

在此步驟中，您需要選擇鏡像關係中使用的輔助磁碟區。當您在遠端儲存陣列上選擇輔助磁碟區時，系統會顯示該鏡像配對中所有符合條件的磁碟區清單。任何不符合使用條件的磁碟區都不會顯示在該清單中。您選擇的磁碟區將在鏡像關係中扮演輔助角色。

.步驟
. 選擇要與本機儲存陣列建立鏡像關係的遠端儲存陣列。
+
[NOTE]
====
如果您的遠端儲存陣列受密碼保護，系統會提示輸入密碼。

====
+
** 儲存陣列以其儲存陣列名稱列出。如果您尚未命名儲存陣列、則會列為「未命名」。
** 如果您要使用的儲存陣列不在清單中，請確保已在 Unified Manager 中發現它。


. 從符合條件的磁碟區清單中，選擇要用作鏡像中次要磁碟區的磁碟區。
+
[NOTE]
====
如果選擇容量大於主要磁碟區的次要磁碟區，可用容量將限制為主要磁碟區的大小。

====
. 點擊 *Next* ，然後轉到 <<步驟 3：選取同步設定>>。




== 步驟 3：選取同步設定

在此步驟中，您可以選擇通訊中斷後資料同步方式的設定。您可以設定主磁碟區的控制器擁有者在通訊中斷後與輔助磁碟區重新同步資料的優先權。您還必須選擇重新同步策略，可以是手動或自動。

.步驟
. 使用滑桿設定同步優先順序。
+
同步優先順序決定了與服務 I/O 請求相比，用於完成初始同步和通訊中斷後重新同步作業的系統資源量。

+
此對話方塊中設定的優先順序同時適用於主磁碟區和輔助磁碟區。您可以稍後透過前往 System Manager 並選擇選單：Storage（儲存）[Synchronous Mirroring（同步鏡像）> More（更多）> Edit Settings（編輯設定）] 來修改主磁碟區的速率。

+
同步優先權共有五種：

+
** 最低
** 低
** 中
** 高
** 最高
+
如果將同步優先權設為最低，則優先執行 I/O 活動，重新同步操作所需時間會更長。如果將同步優先權設為最高，則優先執行重新同步操作，但儲存陣列的 I/O 活動可能會受到影響。



. 選擇是否要手動或自動重新同步遠端儲存陣列上的鏡像配對。
+
** *手動*（建議選項）-- 選擇此選項可在鏡像配對恢復通訊後，要求手動恢復同步。此選項能最大程度地提高資料恢復的成功率。
** *Automatic* -- 選擇此選項可在恢復與鏡像對的通訊後自動開始重新同步。
+
若要手動恢復同步，請前往 System Manager 並選取功能表：Storage［Synchronous Mirroring］，在表格中反白顯示鏡像配對，然後在*更多*下選取*恢復*。



. 按一下 *Finish* 以完成同步鏡像序列。


.結果
鏡像功能啟動後，系統將執行以下操作：

* 開始本機儲存陣列和遠端儲存陣列之間的初始同步。
* 設定同步優先順序和重新同步原則。
* 為鏡像資料傳輸保留控制器 HIC 的最高編號連接埠。
+
此連接埠收到的 I/O 請求僅接受來自鏡像對中輔助磁碟區的遠端首選控制器擁有者的請求。（允許對主磁碟區進行保留。）

* 建立兩個保留容量磁碟區，每個控制器一個，用於記錄寫入資訊，以便從控制器重設和其他暫時中斷中恢復。
+
每個磁碟區的容量為 128 MiB。但是，如果將磁碟區放在資源池中，則每個磁碟區將保留 4 GiB。



.完成後
請前往 System Manager 並選擇功能表：首頁 [View Operations in Progress] 以檢視同步鏡像操作的進度。此操作可能耗時較長，並可能影響系統效能。
