---
permalink: um-manage/discover-single-array.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, discover, single, array 
summary: 使用「新增 / 發現單一儲存陣列」選項手動發現單一儲存陣列並將其新增至您組織的網路。 
---
= 在 SANtricity Unified Manager 中探索單一陣列
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用「新增 / 探索單一儲存陣列」選項，手動探索單一儲存陣列並將其新增至您組織的網路。

.開始之前
* 儲存陣列必須正確設定和配置。
* 必須使用 System Manager 的「存取管理」磁貼來設定儲存陣列密碼。


.步驟
. 在「管理」頁面中，選取 *Add/Discover* 。
+
Add/Discover 對話方塊隨即出現。

. 選擇 *Discover a single storage array* 選項按鈕。
. 輸入儲存陣列中某個控制器的 IP 位址、然後按一下 *Start Discovery* 。
+
Unified Manager 連接到指定的儲存陣列可能需要幾分鐘的時間。

+
[NOTE]
====
當與指定控制器的 IP 位址的連線失敗時，會顯示 Storage Array Not Accessible 訊息。

====
. 如果出現提示，請解決任何自我簽署的憑證。
+
作為發現過程的一部分，系統會驗證已發現的儲存陣列是否使用來自可信任來源的憑證。如果找不到某個儲存陣列的數位憑證，系統會提示您透過新增安全例外來解決該憑證並非由認可的憑證授權單位（CA）簽署的問題。

. 如果出現提示，請解決任何不受信任的憑證。
+
當儲存陣列嘗試與 Unified Manager 建立安全連線，但連線未能確認安全性時，就會出現不受信任的憑證。若要解決不受信任的憑證問題，請匯入由受信任的第三方所核發的憑證授權單位 （CA） 憑證。

. 按一下 *Next* 。
. *選用：* 將探索到的儲存陣列與群組建立關聯：從下拉式清單中，選取要與儲存陣列建立關聯的所需群組。
+
預設情況下會選取「全部」群組。

. 輸入要新增至管理網域的儲存陣列的管理員密碼，然後按一下 *OK* 。


.完成後
儲存陣列將會新增至 Unified Manager，如果已指定，也會新增至您選取的群組。

如果啟用了自動支援資料收集，則會自動收集您新增之儲存陣列的支援資料。
