---
permalink: um-manage/discover-multiple-arrays.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, discover, multiple, storage, arrays 
summary: 您可以透過發現多個陣列來偵測管理伺服器所在子網路中的所有儲存陣列，並將發現的陣列自動新增至您的管理網域。 
---
= 在 SANtricity Unified Manager 中探索多個儲存陣列
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以透過發現多個陣列來偵測管理伺服器所在子網路中的所有儲存陣列，並將發現的陣列自動新增至您的管理網域。

.開始之前
* 您必須使用具有 Security Admin 權限的使用者設定檔登入。
* 儲存陣列必須正確設定和配置。
* 必須使用 System Manager 的「存取管理」磁貼來設定儲存陣列密碼。
* 若要解決不受信任的憑證問題，您必須擁有來自憑證授權單位（Certificate Authority，CA）的受信任憑證檔案，並且這些憑證檔案必須位於您的本機系統中。


探索陣列是一個多步驟的程序。



== 步驟 1：輸入網路位址

您輸入網路位址範圍，以在本機子網路中進行搜尋。任何成功連接的儲存陣列都會顯示在「探索」頁面上，並可能新增至您的管理網域。

如果出於任何原因需要停止探索作業，請按一下 *Stop Discovery*。

.步驟
. 在「管理」頁面中，選取 *Add/Discover* 。
+
Add/Discover 對話方塊隨即出現。

. 選擇 *Discover all storage arrays within a network range* 選項按鈕。
. 輸入起始網路位址和結束網路位址，以便在本機子網路中進行搜尋，然後按一下 *Start Discovery*。
+
探索程序開始。此探索程序可能需要幾分鐘才能完成。「探索」頁面上的表格會在探索到儲存陣列時填入資料。

+
[NOTE]
====
如果未發現可管理的陣列，請確認儲存陣列已正確連接到您的網路，並且其指派的位址在範圍內。按一下 *New Discovery Parameters* 返回 Add/Discover 頁面。

====
. 檢閱已探索到的儲存陣列清單。
. 選取要新增至管理網域的任何儲存陣列旁的核取方塊，然後按一下 *Next* 。
+
Unified Manager 會對您新增至管理網域的每個陣列執行憑證檢查。您可能需要解決與該陣列關聯的任何自我簽署憑證和不受信任的憑證。

. 按一下 *Next* 以繼續執行精靈中的下一步。




== 步驟 2：在探索期間解析自我簽署的憑證

作為探索程序的一部分，系統會驗證儲存陣列是否使用來自可信任來源的憑證。

.步驟
. 請執行下列其中一項操作：
+
** 如果您信任與已發現儲存陣列的連線，請繼續執行精靈中的下一張卡片。自我簽署憑證將被標記為受信任，並且儲存陣列將被新增到 Unified Manager 中。
** 如果您不信任與儲存陣列的連線、請選取 * 取消 * 、並在將任何儲存陣列新增至 Unified Manager 之前驗證每個儲存陣列的安全性憑證策略。


. 按一下 *Next* 以繼續執行精靈中的下一步。




== 步驟 3：在探索期間解決不受信任的憑證

當儲存陣列嘗試與 Unified Manager 建立安全連線但連線未能確認安全性時，就會出現不受信任的憑證。在陣列探索過程中，您可以透過匯入由受信任的第三方所核發的憑證授權單位（CA）憑證（或 CA 簽章憑證）來解決不受信任的憑證問題。

如果出現以下任何一種情況、您可能需要安裝其他受信任的 CA 憑證：

* 您最近新增了一個儲存陣列。
* 其中一份或兩份憑證已過期。
* 一份或兩份憑證已撤銷。
* 一個或兩個憑證缺少根憑證或中繼憑證。


.步驟
. 選取要為其解析不受信任憑證的任何儲存陣列旁的複選框，然後選取 **Import** 按鈕。
+
此時會開啟一個對話方塊，用於匯入受信任的憑證檔案。

. 按一下 *Browse* 選擇儲存陣列的憑證檔案。
+
檔案名稱會顯示在對話方塊中。

. 點選 *Import* 。
+
檔案已上傳並通過驗證。

+
[NOTE]
====
任何存在未解決的不受信任憑證問題的儲存陣列都不會新增至 Unified Manager 。

====
. 按一下 *Next* 以繼續執行精靈中的下一步。




== 步驟 4：提供密碼

您必須輸入要新增至管理網域的儲存陣列密碼。

.步驟
. 輸入要新增到 Unified Manager 的每個儲存陣列的密碼。
. *選用：* 將儲存陣列關聯至群組：從下拉式清單中，選取要與所選儲存陣列建立關聯的所需群組。
. 點選 *Finish* 。


.完成後
儲存陣列會新增至您的管理網域，並與選定的群組（如果已指定）建立關聯。

[NOTE]
====
Unified Manager 可能需要幾分鐘才能連接到指定的儲存陣列。

====