---
permalink: um-manage/faq-storage-mirroring.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= SANtricity Unified Manager 的儲存映像常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 在建立鏡像一致性群組之前，我需要了解哪些資訊？

在建立鏡像一致性群組之前，請遵循下列準則。

請滿足以下 Unified Manager 的要求：

* Web Services Proxy 服務必須正在執行。
* Unified Manager 必須透過 HTTPS 連線在本機主機上執行。
* Unified Manager 必須顯示儲存陣列的有效 SSL 憑證。您可以接受自簽憑證，或使用 Unified Manager 並瀏覽至功能表：Certificate[Certificate Management] 來安裝您自己的安全性憑證。


此外，請確保儲存陣列符合以下要求：

* 必須在 Unified Manager 中發現這兩個儲存陣列。
* 每個儲存陣列必須有兩個控制器。
* 主陣列和次要陣列中的每個控制器都必須配置 Ethernet 管理連接埠，並且必須連接到您的網路。
* 儲存陣列的最低韌體版本為 7.84。（它們可以運行不同的作業系統版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 您的本機和遠端儲存陣列透過 Fibre Channel 架構或 iSCSI 介面連接。


[NOTE]
====
EF600/EF600C 或 EF300/EF300C 儲存系統不提供同步鏡像。

====


== 在建立鏡像配對之前，我需要了解哪些資訊？

在建立鏡像配對之前、請遵循下列準則。

* 您必須有兩個儲存陣列。
* 每個儲存陣列必須有兩個控制器。
* 必須在 Unified Manager 中發現這兩個儲存陣列。
* 主陣列和次要陣列中的每個控制器都必須配置 Ethernet 管理連接埠，並且必須連接到您的網路。
* 儲存陣列的最低韌體版本為 7.84。（它們可以運行不同的作業系統版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 遠端儲存陣列上必須有足夠的可用容量來建立等於或大於要鏡像的主磁碟區的輔助磁碟區。
* 非同步鏡像在具有光纖通道 (FC) 或 iSCSI 主機連接埠的控制器上受支援，而同步鏡像僅在具有 FC 主機連接埠的控制器上受支援。


[NOTE]
====
EF600/EF600C 或 EF300/EF300C 儲存系統不提供同步鏡像。

====


== 為什麼要變更此百分比？

保留容量通常為非同步鏡像作業的基礎磁碟區的 20%。通常此容量已足夠。

所需容量取決於對基礎磁碟區的 I/O 寫入頻率和大小，以及您打算使用儲存物件複製服務作業的時間長度。通常，如果滿足以下一個或兩個條件，則應選擇較大的預留容量百分比：

* 如果特定儲存物件的複製服務作業生命週期非常長。
* 如果由於 I/O 活動頻繁，導致基礎磁碟區上大量資料區塊發生變化。請使用歷史效能資料或其他作業系統公用程式來協助您確定基礎磁碟區的典型 I/O 活動。




== 為什麼我看到不只一個保留容量候選項目？

如果儲存資源池或磁碟區群組中有多個磁碟區符合您為儲存物件選擇的容量百分比，則您會看到多個候選磁碟區。

您可以透過變更要為複製服務作業在基礎磁碟區上預留的實體磁碟機空間百分比來重新整理建議候選清單。系統會根據您的選擇顯示最佳候選方案。



== 為什麼我看不到所有的磁碟區？

在為鏡像對選擇主磁碟區時，會顯示一個列表，其中列出了所有符合條件的磁碟區。

任何不符合使用條件的磁碟區都不會顯示在該清單中。磁碟區可能由於以下任何原因不符合使用條件：

* 磁碟區並不理想。
* 該磁碟區已參與鏡像關係。
* 對於同步鏡像、鏡像配對中的主要磁碟區和次要磁碟區必須是標準磁碟區。它們不能是精簡磁碟區或快照磁碟區。
* 對於非同步鏡像、精簡磁碟區必須啟用自動擴充功能。



NOTE: 對於 EF600 和 EF300 控制器，非同步鏡像對的主磁碟區和輔助磁碟區必須具有相同的協定、托架等級、區段大小、安全性類型和 RAID 等級。不符合資格的非同步鏡像對將不會出現在可用磁碟區清單中。



== 為什麼我在遠端儲存陣列上看不到所有磁碟區？

在遠端儲存陣列上選擇次要磁碟區時，會顯示一個列表，其中列出了該鏡像配對的所有合格磁碟區。

任何不符合使用條件的磁碟區都不會顯示在該清單中。磁碟區可能由於以下任何原因不符合使用條件：

* 該磁碟區為非標準磁碟區，例如快照磁碟區。
* 磁碟區並不理想。
* 該磁碟區已參與鏡像關係。
* 對於非同步鏡像、主磁碟區和次要磁碟區之間的精簡磁碟區屬性不相符。
* 如果您使用 Data Assurance (DA)，則主磁碟區和次要磁碟區必須具有相同的 DA 設定。
+
** 如果主磁碟區已啟用 DA，則次要磁碟區也必須啟用 DA。
** 如果主磁碟區未啟用 DA，則次要磁碟區也必須未啟用 DA。


* 對於非同步鏡像、主磁碟區和次要磁碟區必須具有相同的磁碟機安全功能。
+
** 如果主磁碟區支援 FIPS、則次要磁碟區也必須支援 FIPS。
** 如果主磁碟區支援 FDE，則次要磁碟區也必須支援 FDE。
** 如果主磁碟區未使用 Drive Security，則輔助磁碟區也必須不使用 Drive Security。






== 同步優先順序對同步速率有何影響？

同步優先權定義了相對於系統效能，分配給同步活動的處理時間量。

主磁碟區的控制器擁有者在背景執行此操作。同時，控制器擁有者處理對主磁碟區的本機 I/O 寫入以及對輔助磁碟區的相關遠端寫入。由於重新同步會將控制器處理資源從 I/O 活動中轉移出去，因此重新同步可能會對主機應用程式的效能產生影響。

請記住以下準則，以幫助您確定同步優先順序可能需要多長時間，以及同步優先順序如何影響系統效能。

可使用以下優先順序速率：

* 最低
* 低
* 中
* 高
* 最高


最低優先權速率有利於系統效能，但重新同步所需時間較長。最高優先權速率有利於重新同步，但系統效能可能會受到影響。

這些準則大致反映了優先順序之間的差異。

[cols="45h,~"]
|===
| 完全同步的優先順序速率 | 與最高同步速率相比所經過的時間 


 a| 
最低
 a| 
大約是最高優先順序速率的八倍。



 a| 
低
 a| 
大約是最高優先順序速率的六倍。



 a| 
中
 a| 
大約是最高優先權處理時間的 3.5 倍。



 a| 
高
 a| 
大約是最高優先順序速率的兩倍時長。

|===
磁碟區大小和主機 I/O 速率負載會影響同步時間比較。



== 為什麼建議使用手動同步策略？

建議手動重新同步，因為它可以讓您以最佳方式管理重新同步過程，從而為資料恢復提供最佳機會。

如果您使用 Automatic 重新同步策略，並且在重新同步期間出現間歇性通訊問題，則輔助磁碟區上的資料可能會暫時損壞。重新同步完成後，資料將會修復。
