---
permalink: um-manage/mirroring-overview.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, 
summary: Unified Manager 包含 SANtricity 鏡射功能的組態選項，可讓管理員在兩個儲存陣列之間複寫資料以進行資料保護。 
---
= 了解 SANtricity 鏡像
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity Unified Manager 包含 SANtricity 鏡射功能的組態選項，可讓管理員在兩個儲存陣列之間複寫資料以保護資料。

[NOTE]
====
EF600/EF600C 或 EF300/EF300C 儲存系統不提供同步鏡像。

====


== 鏡像類型

SANtricity 應用程式包含兩種類型的鏡像 -- 非同步和同步。

非同步鏡像可按需或按計劃複製資料磁碟區，從而最大限度地減少或避免因資料毀損或遺失而導致的停機時間。非同步鏡像會在特定時間點擷取主磁碟區的狀態，並僅複製自上次映像擷取以來發生變更的資料。主站台可以立即更新，而次要站台則可根據頻寬情況進行更新。資訊會被快取，並在網路資源可用時稍後傳送。這種鏡像類型非常適合備份和歸檔等定期程序。

同步鏡像即時複製資料卷，以確保持續可用性。其目的是透過確保在兩個儲存陣列之一發生災難時，重要資料的副本可用，從而實現零資料遺失的復原點目標（RPO）。由於每次對主磁碟區進行寫入作業時，輔助磁碟區也會同步寫入，因此副本始終與生產資料完全一致。只有當輔助磁碟區更新了主磁碟區上的變更後，主機才會收到寫入成功的確認訊息。這種鏡像方式非常適合用於業務連續性，例如災難復原。



== 鏡像類型之間的差異

下表說明兩種鏡射類型之間的主要差異。

[cols="1a,1a,1a"]
|===
| 屬性 | 非同步 | 同步 


 a| 
複寫方法
 a| 
時間點鏡像 -- 鏡像可以按需進行，也可以根據使用者定義的計畫自動進行。
 a| 
連續 -- 鏡像操作會自動連續執行，每次主機寫入資料時都會複製資料。



 a| 
距離
 a| 
支援陣列之間的長距離。通常，距離僅受網路功能和通道延伸技術的限制。
 a| 
陣列間的距離僅限於較短距離。通常情況下，為了滿足延遲和應用效能要求，陣列與本地儲存陣列之間的距離必須在 10 公里（6.2 英里）以內。



 a| 
通訊方法
 a| 
標準 IP 或光纖通道網路。
 a| 
僅限 Fibre Channel 網路。



 a| 
磁碟區類型
 a| 
標準或薄型。
 a| 
僅限標準版。

|===