---
permalink: um-manage/mirroring-configuration-workflow.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, configuration, workflow 
summary: 您可以在 Unified Manager 中設定非同步或同步鏡射，然後使用 System Manager 管理同步。 
---
= 鏡像 SANtricity 組態工作流程
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在 SANtricity Unified Manager 中設定非同步或同步鏡射，然後使用 SANtricity System Manager 管理同步。



== 非同步鏡像工作流程

非同步鏡像涉及以下工作流程：

. 在 Unified Manager 中執行初始組態：
+
.. 選擇本機儲存陣列作為資料傳輸來源。
.. 建立或選擇現有的鏡像一致性群組，該群組包含本機陣列上的主磁碟區和遠端陣列上的輔助磁碟區。主磁碟區和輔助磁碟區被稱為「鏡像配對」。如果是首次建立鏡像一致性群組，則需要指定是執行手動同步還是排程同步。
.. 從本機儲存陣列中選擇一個主磁碟區，然後確定其保留容量。保留容量是指用於複製作業的實體分配容量。
.. 選擇遠端儲存陣列作為傳輸目標、次要磁碟區，然後決定其保留容量。
.. 開始將資料從主磁碟區傳送到輔助磁碟區。根據磁碟區大小，此初始傳輸可能需要幾個小時。


. 檢查初始同步的進度：
+
.. 在 Unified Manager 中、啟動本機陣列的 System Manager 。
.. 在 System Manager 中、檢視鏡射作業的狀態。鏡射完成後、鏡射配對的狀態為「最佳」。


. 您也可以在 System Manager 中重新排程或手動執行後續資料傳輸。只有新增和已變更的資料塊才會從主磁碟區傳送到輔助磁碟區。
+
[NOTE]
====
由於非同步複製是週期性的，系統可以合併已更改的資料區塊，從而節省網路頻寬。對寫入吞吐量和寫入延遲的影響極小。

====




== 同步鏡像工作流程

同步鏡像涉及以下工作流程：

. 在 Unified Manager 中執行初始組態：
+
.. 選擇本機儲存陣列作為資料傳輸來源。
.. 從本機儲存陣列中選取主要磁碟區。
.. 選擇遠端儲存陣列作為資料傳輸的目的地，然後選擇次要磁碟區。
.. 選擇同步和重新同步優先順序。
.. 開始將資料從主磁碟區傳送到輔助磁碟區。根據磁碟區大小，此初始傳輸可能需要幾個小時。


. 檢查初始同步的進度：
+
.. 在 Unified Manager 中、啟動本機陣列的 System Manager 。
.. 在 System Manager 中，查看鏡像操作的狀態。鏡像完成後，鏡像配對的狀態為「最佳」。兩個陣列會透過正常操作嘗試保持同步。只有新的和變更的區塊會從主要磁碟區傳輸到次要磁碟區。


. 您也可以在 System Manager 中變更同步設定。
+
[NOTE]
====
由於同步複製是連續進行的，因此兩個站台之間的複製鏈路必須提供足夠的頻寬功能。

====

