---
permalink: sm-settings/access-management-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, terms 
summary: 了解存取管理術語如何應用於您的儲存陣列。 
---
= 了解 SANtricity 軟體中的存取管理術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解存取管理術語如何應用於您的儲存陣列。

[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
存取權杖
 a| 
存取權杖用於取代使用者名稱和密碼，透過 REST API 或命令列介面（CLI）進行身份驗證。權杖與特定使用者（包括 LDAP 使用者）關聯，並包含一組權限和過期時間。



 a| 
Active Directory
 a| 
Active Directory (AD) 是 Microsoft 的目錄服務，使用 LDAP 來管理 Windows 網域網路。



 a| 
繫結
 a| 
綁定操作用於對目錄伺服器的客戶端進行身份驗證。綁定通常需要帳戶和密碼憑證，但有些伺服器允許匿名綁定操作。



 a| 
加州
 a| 
憑證授權單位（CA）是一個受信任的實體，它頒發用於網際網路安全的電子文件，稱為數位憑證。這些憑證用於識別網站擁有者，從而實現用戶端和伺服器之間的安全連線。



 a| 
證書
 a| 
證書用於識別網站所有者，以確保網站安全，防止攻擊者冒充網站。證書包含網站所有者的資訊以及對這些資訊進行認證（簽署）的可信任實體的身份資訊。



 a| 
IdP
 a| 
身分提供者 (IdP) 是一個外部系統，用於向使用者請求憑證並確定該使用者是否已成功通過身份驗證。IdP 可以設定為提供多因素身份驗證，並使用任何使用者資料庫，例如 Active Directory。您的安全團隊負責維護 IdP。



 a| 
LDAP
 a| 
輕量級目錄存取協定（LDAP）是一種用於存取和維護分散式目錄資訊服務的應用層協定。該協定允許多種不同的應用程式和服務連接到 LDAP 伺服器以驗證使用者身份。



 a| 
RBAC
 a| 
基於角色的存取控制（RBAC）是一種根據個別使用者角色來管理對電腦或網路資源存取的方法。RBAC 控制在儲存陣列上強制執行，並包含預先定義的角色。



 a| 
SAML
 a| 
Security Assertion Markup Language (SAML) 是一種基於 XML 的標準，用於兩個實體之間的身份驗證和授權。SAML 支援多因素身份驗證，使用者必須提供兩項或多項資訊來證明其身分（例如，密碼和指紋）。儲存陣列內建的 SAML 功能符合 SAML 2.0 標準，可用於身分斷言、身分驗證和授權。



 a| 
SP
 a| 
服務提供者（SP）是控制使用者驗證和存取的系統。當 Access Management 配置 SAML 時，儲存陣列會做為 Service Provider 向 Identity Provider 要求驗證。



 a| 
單一登入（SSO）
 a| 
單一登入（SSO）是一種驗證服務，允許使用一組登入憑證存取多個應用程式。

|===