---
permalink: sm-settings/cache-settings-and-performance.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cache, settings, performance, 
summary: 快取記憶體是控制器上的臨時揮發性儲存區域，其存取時間比磁碟機媒體更快。 
---
= 了解 SANtricity 軟體中的快取設定和效能
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
快取記憶體是控制器上的臨時揮發性儲存區域，其存取時間比磁碟機媒體更快。

透過快取，整體 I/O 效能可以如下提升：

* 從主機請求讀取的資料可能已經存在於先前操作的快取中、因此無需存取磁碟機。
* 寫入資料首先寫入快取，這樣應用程式就可以繼續運行，而無需等待資料寫入磁碟機。


預設快取設定可滿足大多數環境的需求，但您可以視需要進行變更。



== 儲存陣列快取設定

您可以在「系統」頁面中為儲存陣列中的所有磁碟區指定下列值：

* *刷新起始值* -- 快取中未寫入資料的百分比，超過此百分比將觸發快取刷新（寫入磁碟）。當快取中未寫入資料的百分比達到指定值時，將觸發刷新。預設情況下，當快取達到 80% 時，控制器開始刷新快取。
* *快取區塊大小* -- 每個快取區塊的最大大小，快取區塊是快取管理的組織單元。快取區塊大小預設為 8 KiB，但可以設定為 4、8、16 或 32 KiB。理想情況下，快取區塊大小應設定為應用程式的主要 I/O 大小。檔案系統或資料庫應用程式通常使用較小的大小，而較大的大小則適用於需要大量資料傳輸或順序 I/O 的應用程式。




== 磁碟區快取設定

對於儲存陣列中的各個磁碟區，您可以從 Volumes 頁面（功能表：Storage[Volumes]）指定以下值：

* *讀取快取* -- 讀取快取是一個緩衝區，用於儲存從磁碟機讀取的資料。讀取操作所需的資料可能已經存在於快取中（來自先前的操作），這樣就無需存取磁碟機。資料會一直保留在讀取快取中，直到被刷新。
+
** *Dynamic read cache prefetch* -- Dynamic cache read prefetch 允許控制器在從磁碟機讀取資料區塊到快取的同時，將額外的順序資料區塊複製到快取中。這種快取機制提高了後續資料請求能夠從快取中獲取所需資料的機率。Dynamic cache read prefetch 對於使用順序 I/O 的多媒體應用至關重要。預取到快取中的資料速率和數量會根據主機讀取的速率和請求大小自動調整。隨機存取不會導致資料預取到快取中。停用讀取快取時，此功能無效。


* *寫入快取* -- 寫入快取是一個緩衝區，用於儲存來自主機但尚未寫入磁碟機的資料。資料會一直保留在寫入快取中，直到被寫入磁碟機為止。寫入快取可以提高 I/O 效能。
+
[CAUTION]
====
*資料可能遺失* -- 如果您啟用 *Write caching without batteries* 選項，且沒有通用電源進行保護，則可能會遺失資料。此外，如果您沒有控制器電池，並且啟用了 *Write caching without batteries* 選項，也可能導致資料遺失。

====
+
** *無電池寫入快取* -- 無電池寫入快取設定可讓寫入快取繼續運作，即使電池遺失、故障、完全放電或未充滿電也一樣。通常不建議選擇無電池寫入快取，因為如果電源中斷，資料可能會遺失。一般而言，控制器會暫時關閉寫入快取，直到電池充滿電或更換故障電池為止。
** *帶有鏡像的寫入快取* -- 帶有鏡像的寫入快取是指將寫入一個控制器快取記憶體的資料也寫入另一個控制器的快取記憶體。因此，如果一個控制器發生故障，另一個控制器可以完成所有未完成的寫入操作。僅當啟用寫入快取且存在兩個控制器時，寫入快取鏡像才可用。建立磁碟區時，預設設定是帶有鏡像的寫入快取。



