---
permalink: sm-settings/certificate-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, certificate, terms, 
summary: 以下術語適用於憑證管理。 
---
= 了解 SANtricity 軟體中的憑證術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下術語適用於憑證管理。

[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
加州
 a| 
憑證授權單位（CA）是一個受信任的實體，它頒發用於網際網路安全的電子文件，稱為數位憑證。這些憑證用於識別網站擁有者，從而實現用戶端和伺服器之間的安全連線。



 a| 
企業社會責任
 a| 
憑證簽署請求（CSR）是申請人傳送給憑證授權單位（CA）的訊息。CSR 用於驗證 CA 頒發憑證所需的資訊。



 a| 
證書
 a| 
證書用於識別網站所有者，以確保網站安全，防止攻擊者冒充網站。證書包含網站所有者的資訊以及對這些資訊進行認證（簽署）的可信任實體的身份資訊。



 a| 
憑證鏈
 a| 
為憑證增加一層安全性的檔案層級結構。通常，此證書鏈包含位於層級結構頂端的根證書、一個或多個中間證書，以及用於識別各個實體的伺服器證書。



 a| 
用戶端憑證
 a| 
對於安全金鑰管理，用戶端憑證會驗證儲存陣列的控制器，以便金鑰管理伺服器可以信任它們的 IP 位址。



 a| 
中繼憑證
 a| 
在憑證鏈中，一個或多個中間憑證從根憑證分支而出。CA 頒發一個或多個中間憑證，作為受保護的根憑證和伺服器憑證之間的中間層。



 a| 
金鑰管理伺服器憑證
 a| 
對於安全金鑰管理，金鑰管理伺服器憑證用於驗證伺服器，以便儲存陣列可以信任其 IP 位址。



 a| 
金鑰庫
 a| 
金鑰庫是主機管理系統上的一個儲存庫，其中包含私鑰及其對應的公鑰和憑證。這些金鑰和憑證用於標識您自己的實體，例如控制器。



 a| 
OCSP 伺服器
 a| 
線上憑證狀態協定 (OCSP) 伺服器會判斷憑證授權單位 (CA) 是否在排定的到期日之前撤銷任何憑證，如果憑證已撤銷，則會封鎖使用者存取伺服器。



 a| 
根憑證
 a| 
根憑證位於憑證鏈層次結構的頂端，包含用於簽署其他憑證的私鑰。根憑證標識特定的 CA 組織。如果您對所有網路裝置使用同一個 CA，則只需要一個根憑證。



 a| 
已簽署的憑證
 a| 
由憑證授權單位（CA）驗證的憑證。此資料檔案包含私密金鑰，可確保伺服器與用戶端之間透過 HTTPS 連線以加密形式傳送資料。此外，簽署的憑證還包含實體擁有者（通常是伺服器或網站）的詳細資料，以及由字母和數字組成的數位簽章。簽署的憑證使用信任鏈結，因此最常用於正式作業環境。也稱為「CA 簽署的憑證」或「管理憑證」。



 a| 
自我簽署憑證
 a| 
自簽名憑證由實體擁有者驗證。此資料檔案包含私鑰，確保伺服器和客戶端之間透過 HTTPS 連線傳輸的資料以加密形式傳送。它還包含由字母和數字組成的數位簽名。自簽名憑證不使用與 CA 簽章憑證相同的信任鏈，因此最常用於測試環境。也稱為「預先安裝」憑證。



 a| 
伺服器憑證
 a| 
伺服器憑證位於憑證鏈的最底層。用於識別您的特定實體，例如網站或其他裝置。儲存系統中的每個控制器都需要單獨的伺服器憑證。

|===