---
permalink: sm-settings/change-cache-settings-for-storage-array.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, cache, settings, 
summary: 對於儲存陣列中的所有磁碟區，您可以調整快取記憶體設定以進行刷新和區塊大小。 
---
= 在 SANtricity System Manager 中變更儲存陣列快取設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於儲存陣列中的所有磁碟區，您可以調整快取記憶體設定以進行刷新和區塊大小。

.關於此任務
快取記憶體是控制器上的臨時揮發性儲存區域，其存取時間比磁碟機媒體更快。若要調整快取效能，您可以調整以下設定：

[cols="25h,~"]
|===
| 快取設定 | 說明 


 a| 
啟動隨需快取排清
 a| 
啟動需求快取排清會指定快取中未寫入資料的百分比，以觸發快取排清（寫入磁碟）。根據預設，當未寫入資料達到 80% 容量時，快取排清就會開始。對於主要以寫入作業為主的環境而言，較高的百分比是不錯的選擇，因此新的寫入要求可由快取處理，而無需存取磁碟。在 I/O 不穩定（資料突發）的環境中，較低的設定較為理想，因此系統會在資料突發之間頻繁排清快取。不過，低於 80% 的啟動百分比可能會導致效能降低。



 a| 
快取區塊大小
 a| 
快取區塊大小決定了每個快取區塊的最大容量，快取區塊是快取管理的組織單元。預設情況下，區塊大小為 32 KiB。系統允許快取區塊大小為 4、8、16 或 32 KiBs。應用程式使用不同的區塊大小，這會影響儲存效能。較小的區塊大小適用於檔案系統或資料庫應用程式。較大的區塊大小則更適合產生順序 I/O 的應用程式，例如多媒體應用。

|===
.步驟
. 選擇功能表：Settings[System]。
. 向下捲動到 *Additional Settings*，然後點擊 *Change Cache Settings*。
+
「變更快取設定」對話方塊隨即開啟。

. 調整以下數值：
+
** *啟動按需快取刷新* -- 選擇適合您環境中 I/O 使用的百分比。如果選擇的值低於 80% ，您可能會注意到效能下降。
** **快取區塊大小 -- ** 選擇適合您應用程式的大小。


. 按一下 *Save* 。

