---
permalink: sm-settings/change-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, security, key, 
summary: 您可以隨時使用新金鑰取代安全金鑰。在公司發生潛在安全漏洞、且您想要確保未經授權的人員無法存取磁碟機資料的情況下、您可能需要變更安全金鑰。 
---
= 在 SANtricity System Manager 中變更安全性金鑰
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以隨時使用新金鑰取代安全金鑰。在公司可能發生安全漏洞且您想要確保未經授權的人員無法存取磁碟機資料的情況下，您可能需要變更安全金鑰。

.步驟
. 選擇功能表：Settings[System]。
. 在 *Security key management* 下，選擇 *Change Key* 。
+
Change Security Key 對話方塊開啟。

. 請在下列欄位中輸入資訊。
+
** *定義安全金鑰識別碼* -- （僅適用於內部安全金鑰。）接受預設值（儲存陣列名稱和時間戳記，由控制器韌體產生）或輸入您自己的值。您最多可以輸入 189 個英數字元，不含空格、標點符號或符號。
+
[NOTE]
====
系統會自動產生額外的字元，並將其附加到您輸入的字串的兩端。這些產生的字元有助於確保識別碼的唯一性。

====
** *Define a pass phrase/Re-enter pass phrase* -- 在這些欄位中輸入您的密碼短語。此值的長度必須介於 8 到 32 個字元之間，且必須包含下列各項：
+
*** 一個或多個大寫字母。請注意，複雜密碼區分大小寫。
*** 一個數字（一個或多個）。
*** 非字母數字字元，例如 !、*、@ （一個或多個）。




. 對於外部安全性金鑰，如果要在建立新安全性金鑰時刪除舊安全性金鑰，請勾選對話方塊底部的「刪除目前安全性金鑰...」核取方塊。
+
[CAUTION]
====
*務必記錄您的條目以備後用* -- 如果您需要將啟用安全功能的磁碟機從儲存陣列中移動，則必須知道識別碼和密碼短語才能解鎖磁碟機資料。

====
. 按一下 *Change* 。
+
新的安全金鑰會覆蓋先前的金鑰，先前的金鑰將失效。

+
[NOTE]
====
下載檔案的路徑可能取決於瀏覽器的預設下載位置。

====
. 記錄您的金鑰識別碼、密碼短語和已下載金鑰檔案的位置，然後按一下 *Close* 。


.完成後
您應該驗證安全金鑰，以確保金鑰檔案未損毀。
