---
permalink: sm-settings/clear-storage-array-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, clear, storage, array, configuration, 
summary: 如果要從儲存陣列中刪除所有資源池、磁碟區群組、磁碟區、主機定義和主機指派，請使用 Clear Configuration 操作。 
---
= 在 SANtricity System Manager 中清除儲存陣列組態
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要從儲存陣列中刪除所有資源池、磁碟區群組、磁碟區、主機定義和主機指派，請使用 Clear Configuration 操作。

.開始之前
清除儲存陣列組態之前，請先備份資料。

.關於此任務
有兩種清除儲存陣列組態選項：

* *磁碟區* -- 通常，您可以使用磁碟區選項將測試儲存陣列重新配置為正式作業儲存陣列。例如，您可以設定用於測試的儲存陣列，然後在測試完成後，移除測試配置並將該儲存陣列設定為正式作業環境。
* *儲存陣列* -- 通常情況下，您可以使用「儲存陣列」選項將儲存陣列移至其他部門或群組。例如，您可能在 Engineering 使用一個儲存陣列，而現在 Engineering 要新增一個新的儲存陣列，因此您希望將目前的儲存陣列移至 Administration 進行重新設定。
+
Storage Array 選項會刪除一些額外的設定。



[cols="1a,1a,1a"]
|===
|  | 磁碟區 | 儲存陣列 


 a| 
停用 ARVM
 a| 
X
 a| 
X



 a| 
刪除資源池和磁碟區群組
 a| 
X
 a| 
X



 a| 
刪除磁碟區
 a| 
X
 a| 
X



 a| 
刪除主機和主機叢集
 a| 
X
 a| 
X



 a| 
刪除主機指派
 a| 
X
 a| 
X



 a| 
刪除儲存陣列名稱
 a| 
 a| 
X



 a| 
將儲存陣列快取設定重設為預設值
 a| 
 a| 
X

|===
[CAUTION]
====
*資料遺失風險* -- 此操作會刪除儲存陣列中的所有資料。（並非安全擦除。）操作開始後無法取消。僅在技術支援人員指示的情況下執行此操作。

====
.步驟
. 選擇功能表：Settings[System]。
. 選擇 *Clear Storage Array Configuration* 。
. 在下拉清單中、選擇 *Volume* 或 *Storage Array* 。
. *可選：* 如果您想儲存配置 （而不是資料），請使用對話方塊中的連結。
. 確認您要執行此操作。


.結果
* 目前的組態已刪除，儲存陣列上的所有現有資料都會銷毀。
* 所有磁碟機均未指派。
+

NOTE: 儲存陣列將進入復原模式。使用儲存陣列前，必須先清除復原模式。如需詳細資訊，請參閱 https://docs.netapp.com/us-en/e-series-santricity/sm-support/clear-recovery-mode.html["清除復原模式"^]。


