---
permalink: sm-settings/configure-mail-server-and-recipients-for-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, mail, server, recipients, alerts, 
summary: 若要設定電子郵件警示、您必須指定郵件伺服器位址和警示收件者的電子郵件地址。最多允許 20 個電子郵件地址。 
---
= 在 SANtricity System Manager 中設定郵件伺服器和警示收件者
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要設定電子郵件警示、您必須指定郵件伺服器位址和警示收件者的電子郵件地址。最多允許 20 個電子郵件地址。

.開始之前
* 郵件伺服器的位址必須可用。該位址可以是 IPv4 或 IPv6 位址，也可以是完整網域名稱。
+
[NOTE]
====
若要使用完全限定網域名稱，您必須在兩個控制器上設定 DNS 伺服器。您可以從「硬體」頁面設定 DNS 伺服器。

====
* 必須提供可用於發送警報的電子郵件地址。該地址將顯示在警報郵件的「寄件者」欄位中。SMTP 協定需要寄件者地址；缺少寄件者地址會導致錯誤。
* 必須提供警示接收者的電子郵件地址。接收者通常是網路管理員或儲存管理員的地址。您最多可以輸入 20 個電子郵件地址。


.關於此任務
本任務說明如何設定郵件伺服器、輸入寄件者和收件者的電子郵件地址，以及從 Alerts 頁面測試所有輸入的電子郵件地址。

[NOTE]
====
也可以從初始設定精靈設定電子郵件警示。

====
.步驟
. 選擇選單：Settings [ Alerts ]。
. 選擇 *Email* 標籤。
+
如果尚未設定電子郵件伺服器、則 Email 標籤會顯示「Configure Mail Server」。

. 選擇 *Configure Mail Server* 。
+
Configure Mail Server 對話方塊隨即開啟。

. 輸入郵件伺服器資訊、然後按一下 *Save* 。
+
** *郵件伺服器位址* -- 輸入郵件伺服器的完全限定網域名稱、 IPv4 位址或 IPv6 位址。
+
[NOTE]
====
若要使用完全限定網域名稱，您必須在兩個控制器上設定 DNS 伺服器。您可以從「硬體」頁面設定 DNS 伺服器。

====
** * 電子郵件寄件者地址 * -- 輸入有效的電子郵件地址，以作為電子郵件的寄件者。此地址會顯示在電子郵件訊息的「寄件者」欄位中。
** *加密* -- 如果要加密郵件，請選擇 *SMTPS* 或 *STARTTLS* 作為加密類型，然後選擇加密郵件的連接埠號碼。否則，請選擇 *None*。
** *使用者名稱和密碼* -- 如果需要、請輸入使用者名稱和密碼、以便向外寄件者和郵件伺服器進行驗證。
** *在電子郵件中包含聯絡資訊* -- 若要在警示訊息中包含寄件者的聯絡資訊，請選取此選項，然後輸入姓名和電話號碼。
+
點擊 *Save* 後，電子郵件地址將顯示在 Alerts 頁面的 Email 標籤中。



. 選擇 *Add Emails*。
+
Add Emails 對話方塊開啟。

. 輸入一個或多個電子郵件地址作為警示收件人，然後按一下 *Add* 。
+
電子郵件地址會顯示在「警示」頁面上。

. 如果您想確認電子郵件地址是否有效，請點選 *Test All Emails* 向收件者傳送測試郵件。


.結果
設定電子郵件警示後，事件監視器會在發生可發出警示的事件時，向指定的收件者傳送電子郵件訊息。
