---
permalink: sm-settings/create-internal-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, internal, security, key, 
summary: 若要使用磁碟機安全功能，您可以建立內部安全金鑰，該金鑰由儲存陣列中的控制器和支援安全功能的磁碟機共用。內部金鑰保存在控制器的持久記憶體中。 
---
= 在 SANtricity System Manager 中建立內部安全性金鑰
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要使用 Drive Security 功能，您可以建立內部安全金鑰，該金鑰由儲存陣列中的控制器和支援安全功能的磁碟機共用。內部金鑰保存在控制器的持久記憶體中。

.開始之前
* 儲存陣列中必須安裝具備安全功能的磁碟機。這些磁碟機可以是 Full Disk Encryption（FDE）磁碟機或 Federal Information Processing Standard（FIPS）磁碟機。
* 必須啟用 Drive Security 功能。否則，在此任務期間會開啟 Cannot Create Security Key 對話方塊。如有必要，請聯絡您的儲存供應商，以取得啟用 Drive Security 功能的說明。


[NOTE]
====
如果儲存陣列中同時安裝了 FDE 和 FIPS 磁碟機，則它們都共用同一個安全金鑰。

====
.關於此任務
在此任務中、您需要定義識別碼和密碼短語、以便與內部安全金鑰建立關聯。

[NOTE]
====
磁碟機安全性密碼與儲存陣列的管理員密碼無關。

====
.步驟
. 選擇功能表：Settings[System]。
. 在 *Security key management* 下，選擇 *Create Internal Key* 。
+
如果您尚未產生安全金鑰，則會開啟「Create Security Key」對話方塊。

. 請在下列欄位中輸入資訊：
+
** *定義安全金鑰識別碼* -- 您可以接受預設值（儲存陣列名稱和時間戳記，由控制器韌體產生），也可以輸入您自己的值。最多可輸入 189 個英數字元，但不能包含空格、標點符號或符號。
+
[NOTE]
====
系統會自動產生額外的字元，並附加到您輸入的字串兩端。產生的字元可確保識別碼是唯一的。

====
** *Define a pass phrase/Re-enter pass phrase* -- 輸入並確認密碼短語。此值的長度必須介於 8 到 32 個字元之間，且必須包含下列各項：
+
*** 一個或多個大寫字母。請注意，複雜密碼區分大小寫。
*** 一個數字（一個或多個）。
*** 非字母數字字元，例如 !、*、@ （一個或多個）。




+
[CAUTION]
====
*請務必記錄您的輸入內容以備後用*。如果您需要將啟用安全功能的磁碟機從儲存陣列移出，則必須知道識別碼和密碼短語才能解鎖磁碟機資料。

====
. 按一下 *Create* 。
+
安全金鑰儲存在控制器上一個無法存取的位置。除了實際金鑰外，還有一個加密的金鑰檔案會從您的瀏覽器下載。

+
[NOTE]
====
下載檔案的路徑可能取決於瀏覽器的預設下載位置。

====
. 記錄您的金鑰識別碼、密碼短語和已下載金鑰檔案的位置，然後按一下 *Close* 。


.結果
現在您可以建立啟用安全性的磁碟區群組或集區，也可以在現有磁碟區群組和集區上啟用安全性。

[NOTE]
====
每當硬碟斷電後再重新通電，所有啟用安全功能的硬碟都會進入安全鎖定狀態。在此狀態下，資料將無法存取，直到控制器在硬碟初始化期間套用正確的安全金鑰。如果有人實際移除已鎖定的硬碟並將其安裝到另一個系統中，安全鎖定狀態可防止未經授權存取其資料。

====
.完成後
您應該驗證安全金鑰，以確保金鑰檔案未損毀。
