---
permalink: sm-settings/drive-security-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, drive, security, terms, 
summary: 了解 Drive Security 術語如何應用於您的儲存陣列。 
---
= 了解 SANtricity 軟體中的磁碟機安全性術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解 Drive Security 術語如何應用於您的儲存陣列。

[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
磁碟機安全功能
 a| 
磁碟機安全性是儲存陣列的功能，它透過全磁碟加密（FDE）磁碟機或聯邦資訊處理標準（FIPS）磁碟機提供額外的安全層。當這些磁碟機與磁碟機安全性功能配合使用時，需要安全金鑰才能存取其資料。當磁碟機從陣列中實體移除時，必須將其安裝到另一個陣列中才能運作，此時磁碟機將處於安全鎖定狀態，直到提供正確的安全金鑰為止。



 a| 
FDE 驅動器
 a| 
全碟加密（FDE）磁碟機在硬體層級執行磁碟機加密。硬碟包含一個 ASIC 晶片，在寫入時加密資料，然後在讀取時解密資料。



 a| 
FIPS 驅動
 a| 
FIPS 硬碟採用聯邦資訊處理標準（FIPS）140-2 二級標準。它們本質上是全盤加密（FDE）硬碟，但符合美國政府關於確保強大加密演算法和方法的標準。FIPS 硬碟的安全標準高於全碟加密（FDE）硬碟。



 a| 
管理用戶端
 a| 
包含用於存取 System Manager 的瀏覽器的本機系統（電腦、平板電腦等）。



 a| 
通關密語
 a| 
密碼短語用於加密安全金鑰以進行備份。當因磁碟機遷移或磁頭更換而需要匯入備份的安全金鑰時，必須提供用於加密安全金鑰的相同密碼短語。密碼短語的長度為 8 到 32 個字元。

[NOTE]
====
磁碟機安全性密碼與儲存陣列的管理員密碼無關。

====


 a| 
具備安全功能的磁碟機
 a| 
具備安全功能的磁碟機可以是全磁碟加密（FDE）磁碟機或聯邦資訊處理標準（FIPS）磁碟機，它們在寫入時加密資料，並在讀取時解密資料。這些磁碟機之所以被認為是具備安全_功能_的，是因為它們可以使用 Drive Security 功能來增強安全性。如果為與這些磁碟機一起使用的磁碟區群組和儲存池啟用了 Drive Security 功能，則這些磁碟機將變為已_啟用_安全功能。



 a| 
安全啟用磁碟機
 a| 
啟用安全功能的磁碟機與 Drive Security 功能配合使用。當您啟用 Drive Security 功能，然後將 Drive Security 套用至具備安全功能的磁碟機上的儲存池或磁碟區群組時，這些磁碟機即變為啟用安全功能。只有配置了正確安全金鑰的控制器才能進行讀寫存取。此額外的安全措施可防止未經授權存取已從儲存陣列中實體移除的磁碟機上的資料。



 a| 
安全金鑰
 a| 
安全金鑰是一串字元，在儲存陣列中啟用安全功能的磁碟機和控制器之間共用。每當磁碟機電源關閉再開啟時，啟用安全功能的磁碟機會變更為安全鎖定狀態，直到控制器套用安全金鑰為止。如果從儲存陣列中移除啟用安全功能的磁碟機，該磁碟機的資料就會被鎖定。當磁碟機重新安裝到不同的儲存陣列時，它會先尋找安全金鑰，然後才能再次存取資料。若要解除鎖定資料，您必須套用原始安全金鑰。您可以使用下列其中一種方法來建立和管理安全金鑰：

* 內部金鑰管理 -- 在控制器的持久記憶體中建立和維護安全金鑰。
* 外部金鑰管理 -- 在外部金鑰管理伺服器上建立和維護安全金鑰。




 a| 
安全金鑰識別碼
 a| 
安全金鑰識別碼是在金鑰建立過程中與安全金鑰關聯的字串。此識別碼儲存在控制器以及與該安全金鑰關聯的所有磁碟機上。

|===