---
permalink: sm-settings/save-storage-array-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, save, storage array, configuration, 
summary: 您可以將儲存陣列的組態資訊儲存在指令碼檔案中，以節省使用相同組態設定其他儲存陣列的時間。 
---
= 在 SANtricity System Manager 中儲存儲存陣列組態
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將儲存陣列的組態資訊儲存在指令碼檔案中，以節省設定具有相同組態的其他儲存陣列的時間。

.開始之前
儲存陣列不得進行任何會變更其邏輯組態設定的操作。此類操作包括建立或刪除磁碟區、下載控制器韌體、指派或修改熱備援磁碟機，或新增容量（磁碟機）至磁碟區群組。

.關於此任務
儲存儲存陣列組態會產生命令列介面 (CLI) 指令碼，其中包含儲存陣列設定、Volume 組態、主機組態或儲存陣列的主機對 Volume 指派。您可以使用此產生的 CLI 指令碼，將組態複寫到具有完全相同硬體組態的另一個儲存陣列。

但是，您不應使用此產生的 CLI 腳本進行災難復原。若要進行系統還原，請使用您手動建立的組態資料庫備份檔案，或聯絡技術支援人員以從最新的 Auto-Support 資料中取得此資料。

此操作 _不會_ 儲存這些設定：

* 電池壽命
* 控制器當日時間
* 非揮發性靜態隨機存取記憶體（NVSRAM）設定
* 任何進階功能
* 儲存陣列密碼
* 硬體元件的作業狀態和狀態
* 磁碟區群組的運作狀態（除 Optimal 外）和狀態
* 複製服務，例如鏡像和磁碟區複製


[CAUTION]
====
*應用程式錯誤風險* -- 如果儲存陣列正在執行任何會變更邏輯組態設定的作業，請勿使用此選項。這些作業的範例包括建立或刪除磁碟區、下載控制器韌體、指派或修改熱備援磁碟機，或將容量（磁碟機）新增至磁碟區群組。

====
.步驟
. 選擇功能表：Settings[System]。
. 選擇 *Save Storage Array Configuration* 。
. 選擇要儲存的組態項目：
+
** 儲存陣列設定
** Volume 組態
** 主機組態
** 主機到磁碟區指派


+
[NOTE]
====
如果選取 *Host-to-volume assignments* 項目，則預設也會選取 *Volume configuration* 項目和 *Host configuration* 項目。若未同時儲存 "Volume configuration" 和 "Host configuration"，則無法儲存 "Host-to-volume assignments"。

====
. 按一下 *Save* 。
+
該檔案以名稱  `storage-array-configuration.cfg` 儲存在瀏覽器的 Downloads 資料夾中。



.完成後
若要將已儲存的儲存陣列組態載入到另一個儲存陣列上，請使用 SANtricity 命令列介面（SMcli）搭配 `-f`選項來套用 `.cfg`檔案。

[NOTE]
====
您也可以使用 Unified Manager 介面將儲存陣列組態載入到其他儲存陣列（選擇功能表：Manage[Import Settings]）。

====