---
permalink: sm-support/faq-autosupport.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。 
---
= AutoSupport 常見問題集（FAQ）適用於 SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速找到某個問題的答案，此常見問題解答可能會有所幫助。



== 我正在收集哪些資料？

AutoSupport 功能和手動 Support Data Collection 功能為技術支援人員提供了在客戶支援套件中收集資料的方法，以便進行遠端疑難排解和問題分析。

客戶支援套件會將儲存陣列的所有類型資訊收集到單一壓縮檔案中。收集的資訊包括實體組態、邏輯組態、版本資訊、事件、記錄檔和效能資料。這些資訊僅供技術支援人員用於解決儲存陣列的問題。



== 無法讀取的磁區資料能告訴我什麼？

您可以顯示有關儲存陣列中磁碟機上偵測到的不可讀磁區的詳細資料。

不可讀磁區日誌首先顯示最新的不可讀磁區。此日誌包含有關包含不可讀磁區的磁碟區的下列資訊。這些欄位可排序。

[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
受影響的磁碟區
 a| 
顯示磁碟區的標籤。如果遺失的磁碟區包含無法讀取的磁區，則會顯示該遺失磁碟區的全球識別碼。



 a| 
邏輯單元號碼（LUN）
 a| 
顯示磁碟區的 LUN。如果磁碟區沒有 LUN，對話方塊將顯示 NA。



 a| 
指派給
 a| 
顯示有權存取該磁碟區的主機或主機叢集。如果主機、主機叢集甚至 Default Cluster 都無法存取該磁碟區，則對話方塊會顯示 NA。

|===
若要查看有關無法讀取磁區的其他資訊、請按一下磁碟區旁的加號 (+)。

[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
日期 / 時間
 a| 
顯示偵測到無法讀取磁區的日期和時間。



 a| 
磁碟區邏輯區塊位址
 a| 
顯示磁碟區的邏輯區塊位址 (LBA)。



 a| 
磁碟機位置
 a| 
顯示磁碟機櫃、抽屜（如果您的磁碟機櫃有抽屜）和插槽位置。



 a| 
磁碟機邏輯區塊位址
 a| 
顯示磁碟機的 LBA。



 a| 
故障類型
 a| 
顯示下列其中一種故障類型：

* *Physical* -- 物理媒體錯誤。
* *邏輯* -- 條帶內其他位置的讀取錯誤導致資料無法讀取。例如，由於磁碟區內其他位置的媒體錯誤導致某個磁區無法讀取。
* *不一致* -- 冗餘資料不一致。
* *Data Assurance* -- Data Assurance 錯誤。


|===


== 什麼是健康映像？

健全狀況映像是控制器處理器記憶體的原始資料傾印，技術支援人員可以使用該映像來診斷控制器的問題。

韌體在偵測到某些錯誤時會自動產生健康映像。在某些疑難排解情況下，技術支援人員可能會要求您擷取健康映像檔並將其傳送給他們。



== AutoSupport 功能有什麼作用？

AutoSupport 功能由三個獨立的功能組成，您可以分別啟用它們。

* *基本 AutoSupport* -- 允許您的儲存陣列自動收集資料並將其傳送給技術支援。
* *AutoSupport OnDemand* -- 允許技術支援人員在需要排查問題時請求重新傳送先前的 AutoSupport 調度請求。所有傳輸均由儲存陣列發起，而非 AutoSupport 伺服器。儲存陣列會定期與 AutoSupport 伺服器通信，以確定是否存在待處理的重新傳輸請求，並做出相應的回應。
* *遠端診斷* -- 允許技術支援人員在需要排查問題時請求新的最新 AutoSupport 派送。所有傳輸均由儲存陣列發起，而非 AutoSupport 伺服器。儲存陣列會定期與 AutoSupport 伺服器通信，以確定是否有待處理的新請求，並做出相應的回應。




== 透過 AutoSupport 功能收集哪些類型的資料？

AutoSupport 功能包含三種標準調度類型：事件調度、排程調度、以及隨需和遠端診斷調度。

AutoSupport 資料不包含任何使用者資料。

* *事件分派*
+
當系統發生需要主動通知技術支援的事件時，AutoSupport 功能會自動發送事件觸發調度。

+
** 當託管儲存陣列上發生支援事件時傳送。
** 包含事件發生時儲存陣列運作情況的全面快照。


* *排程派送*
+
AutoSupport 功能會自動按定期排程傳送多個派送。

+
** *每日簡報* -- 每天在使用者可設定的時間間隔內發送一次。內容包括目前系統事件日誌和效能資料。
** *每週發送* -- 每週發送一次，發送時間間隔和日期可由使用者自行設定。內容包括配置和系統狀態資訊。


* *AutoSupport OnDemand 以及遠端診斷調度*
+
** *AutoSupport OnDemand* -- 允許技術支援人員在需要排查問題時請求重新傳送先前的 AutoSupport 調度請求。所有傳輸均由儲存陣列發起，而非 AutoSupport 伺服器。儲存陣列會定期與 AutoSupport 伺服器通信，以確定是否存在待處理的重新傳輸請求，並做出相應的回應。
** *遠端診斷* -- 允許技術支援人員在需要排查問題時請求新的最新 AutoSupport 派送。所有傳輸均由儲存陣列發起，而非 AutoSupport 伺服器。儲存陣列會定期與 AutoSupport 伺服器通信，以確定是否有待處理的新請求，並做出相應的回應。






== 如何配置 AutoSupport 功能的交付方式？

AutoSupport 功能支援使用 HTTPS 和 SMTP 協定向技術支援部門傳送 AutoSupport 訊息。

.開始之前
* AutoSupport 功能必須啟用。您可以在 AutoSupport 頁面上查看其是否已啟用。
* 您的網路中必須安裝並設定 DNS 伺服器。DNS 伺服器位址必須在 System Manager 中設定（此任務可在「硬體」頁面中找到）。


.關於此任務
檢閱不同的通訊協定：

* *HTTPS* -- 讓您可以使用 HTTPS 直接連接到目標技術支援伺服器。如果您要啟用 AutoSupport OnDemand 或 Remote Diagnostics ，則必須將 AutoSupport 傳輸方式設定為 HTTPS 。
* *電子郵件* -- 允許您使用電子郵件伺服器作為傳送 AutoSupport 郵件的遞送方式。


[NOTE]
====
*HTTPS 和電子郵件方式的差異*。使用 SMTP 的電子郵件傳送方式與 HTTPS 傳送方式有一些重要差異。首先，電子郵件傳送方式的封包大小限制為 5MB，這表示某些 ASUP 資料集合將無法傳送。其次，AutoSupport OnDemand 功能僅適用於 HTTPS 傳送方式。

====
.步驟
. 選擇功能表：Support[Support Center > AutoSupport] 索引標籤。
. 選擇 *Configure AutoSupport Delivery Method* 。
+
此時會出現一個對話方塊，列出派送交付方法。

. 選擇所需的傳送方法，然後選擇該傳送方法的參數。執行下列其中一項作業：
+
** 如果您選擇了 HTTPS，請選擇下列其中一個傳送參數：
+
*** *直接* -- 此傳遞參數為預設選項。選擇此選項後，您可以使用 HTTPS 協定直接連接到目標技術支援系統。
*** *透過 Proxy 伺服器* -- 選擇此選項可指定與目標技術支援系統建立連線所需的 HTTP Proxy 伺服器詳細資訊。您必須指定主機位址和連接埠號碼。但是，只有在需要時才需要輸入主機驗證詳細資訊（使用者名稱和密碼）。
*** *透過 Proxy 自動設定指令碼（PAC）* -- 指定 Proxy Auto-Configuration（PAC）指令碼檔案的位置。PAC 檔案可讓系統自動選擇適當的 Proxy 伺服器，以便與目標技術支援系統建立連線。


** 如果您選擇的是電子郵件，請輸入以下資訊：
+
*** 郵件伺服器位址可以是完整網域名稱、IPv4 位址或 IPv6 位址。
*** 在 AutoSupport 派送電子郵件的寄件者欄位中顯示的電子郵件地址。
*** *可選；如果您想執行配置測試。*當 AutoSupport 系統收到測試派送時，會傳送確認訊息的電子郵件地址。
*** 如果要加密郵件，請選擇 *SMTPS* 或 *STARTTLS* 作為加密類型，然後選擇加密郵件的連接埠號碼。否則，請選擇 *None*。
*** 如有需要，請輸入使用者名稱和密碼，以便向外寄件者和郵件伺服器進行驗證。




. 點選 *Test Configuration* 以使用指定的交付參數測試與技術支援伺服器的連線。如果您啟用了 AutoSupport On-Demand 功能，系統也會測試 AutoSupport OnDemand 派送交付的連線。
+
如果組態測試失敗，請檢查組態設定並再次執行測試。如果測試仍然失敗，請聯絡技術支援。

. 按一下 *Save* 。




== 什麼是組態資料？

選擇「收集組態資料」時，系統會儲存 RAID 組態資料庫的目前狀態。

RAID 組態資料庫包含控制器上所有磁碟區群組和磁碟集區的資料。Collect Configuration Data 功能儲存的資訊與 CLI 指令 `save storageArray dbmDatabase`相同。



== 升級 SANtricity OS Software 之前我需要了解哪些資訊？

在升級控制器的軟體和韌體之前、請注意以下事項。

* 您已閱讀文件和  `readme.txt` 檔案，並已確定要進行升級。
* 您知道是否要升級 IOM 韌體。
+
通常情況下，您應該同時升級所有組件。但是，如果您不想將 IOM 韌體作為 SANtricity OS 控制器軟體升級的一部分進行升級，或者技術支援人員指示您降級 IOM 韌體 （您只能使用命令列介面降級韌體），則可以選擇不升級 IOM 韌體。

* 您知道是否要升級控制器 NVSRAM 檔案。
+
通常情況下，您應該同時升級所有組件。但是，如果您的檔案已修補或為自訂版本，並且您不想覆蓋它，則可以選擇不升級控制器 NVSRAM 檔案。

* 您知道是要現在啟動還是稍後啟動。
+
稍後啟動的原因可能包括：

+
** *時間因素* -- 啟動軟體和韌體可能需要很長時間，因此建議您等到 I/O 負載較低時再進行操作。啟動期間控制器會進行故障轉移，因此在升級完成之前，效能可能會低於正常水準。
** *套件類型* -- 您可能需要在升級其他儲存陣列上的檔案之前，先在一個儲存陣列上測試新的軟體和韌體。




這些元件是 SANtricity OS 控制器軟體升級的一部分：

* *管理軟體* -- System Manager 是管理儲存陣列的軟體。
* *控制器韌體* -- 控制器韌體管理主機和磁碟區之間的 I/O 。
* *Controller NVSRAM* -- Controller NVSRAM 是一個控制器檔案，用於指定控制器的預設設定。
* *IOM 韌體* -- I/O 模組（IOM）韌體管理控制器和磁碟機櫃之間的連線。它也會監控元件的狀態。
* *Supervisor 軟體* -- Supervisor 軟體是控制器上的虛擬機器，軟體在該虛擬機器中執行。


作為升級過程的一部分，主機的多路徑 / 容錯移轉驅動程式和 / 或 HBA 驅動程式可能也需要升級，以便主機能夠與控制器正確互動。

[NOTE]
====
若要確定是否如此、請參閱 https://mysupport.netapp.com/matrix["NetApp 互通性矩陣工具"^]。

====
如果您的儲存陣列只有一個控制器，或者您沒有安裝多路徑驅動程式，請停止對儲存陣列的 I/O 活動以防止應用程式錯誤。如果您的儲存陣列有兩個控制器並且您已安裝多路徑驅動程式，則無需停止 I/O 活動。


CAUTION: 升級過程中請勿對儲存陣列進行任何變更。



== 暫停 IOM 自動同步之前，我需要了解哪些資訊？

暫停 IOM 自動同步可防止在下次 SANtricity OS 控制器軟體升級時升級 IOM 韌體。

通常情況下，控制器軟體和 IOM 韌體會捆綁升級。如果您有想要保留在機箱上的特定 IOM 韌體版本，可以暫停 IOM 自動同步。否則，下次升級控制器軟體時，IOM 韌體將恢復為與控制器軟體捆綁的版本。



== 為什麼我的韌體升級進度這麼慢？

韌體升級進度取決於系統的整體負載。

在線上升級磁碟機韌體期間，如果在快速重建過程中發生磁碟區傳輸，系統將對已傳輸的磁碟區啟動完整重建。此操作可能需要相當長的時間。實際完整重建時間取決於多種因素，包括重建操作期間的 I/O 活動量、磁碟區群組中的磁碟機數量、重建優先順序設定以及磁碟機效能。



== 升級磁碟機韌體之前,我需要了解哪些資訊?

升級磁碟機韌體之前，請注意以下事項。

* 為安全起見，請使用磁碟到磁碟備份、磁碟區複製（複製到不受排程韌體升級影響的磁碟區群組）或遠端鏡射來備份您的資料。
* 您可能只想升級幾個磁碟機來測試新韌體的行為，以確保其正常運作。如果新韌體運作正常，請升級其餘的磁碟機。
* 如果存在故障硬碟、請在開始韌體升級之前修復它們。
* 如果磁碟機可以進行離線升級，請停止與這些磁碟機相關聯的所有磁碟區的 I/O 活動。停止 I/O 活動後，將無法對這些磁碟區執行任何組態操作。
* 升級磁碟機韌體時，請勿移除任何磁碟機。
* 升級磁碟機韌體時，請勿對儲存陣列進行任何組態變更。




== 我該如何選擇要執行的升級類型？

您可以根據儲存池或磁碟區群組的狀態選擇要對磁碟機執行的升級類型。

* *線上*
+
如果儲存池或磁碟區群組支援備援且處於最佳狀態，您可以使用線上方法升級磁碟機韌體。線上方法會在儲存陣列處理 I/O 至使用這些磁碟機的相關磁碟區時下載韌體。您不需要停止使用這些磁碟機的相關磁碟區的 I/O。這些磁碟機會逐一升級至與磁碟機相關的磁碟區。如果磁碟機未指派給儲存池或磁碟區群組，則可以使用線上或離線方法更新其韌體。當您使用線上方法升級磁碟機韌體時，系統效能可能會受到影響。

* *離線*
+
如果儲存池或磁碟區群組不支援備援（RAID 0）或已降級，則必須使用離線方法升級磁碟機韌體。離線方法_僅在停止使用這些磁碟機的相關磁碟區的所有 I/O 活動時_升級韌體。您必須停止使用這些磁碟機的任何相關磁碟區的所有 I/O。如果磁碟機未指派給儲存池或磁碟區群組，則可以使用線上或離線方法更新其韌體。


