---
permalink: sm-support/review-the-possible-software-and-firmware-upgrade-errors.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, software, firmware, upgrade, errors 
summary: 控制器軟體升級或磁碟機韌體升級過程中都可能發生錯誤。 
---
= 瞭解 SANtricity 軟體和韌體升級錯誤
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
控制器軟體升級或磁碟機韌體升級過程中都可能發生錯誤。

[cols="25h,~,~"]
|===
| 韌體下載錯誤 | 說明 | 建議採取的行動 


 a| 
指派失敗的磁碟機
 a| 
無法升級儲存陣列中已指派的磁碟機。
 a| 
故障原因之一可能是磁碟機缺少相應的簽名。請確保受影響的磁碟機是已授權的磁碟機。如需更多資訊，請聯繫技術支援。

更換磁碟機時、請確保更換磁碟機的容量等於或大於您要更換的故障磁碟機。

您可以在儲存陣列接收 I/O 時更換故障的磁碟機。



 a| 
整合式熱備援磁碟機
 a| 
如果磁碟機標記為熱備援磁碟機且正用於磁碟區群組，則韌體升級程序會失敗。
 a| 
必須先解決此錯誤狀況，才能升級韌體。啟動 System Manager 並使用 Recovery Guru 來解決問題。



 a| 
不完整的磁碟區群組
 a| 
如果磁碟區群組中的任何磁碟機被旁路、移除或無回應，則該磁碟區群組被視為不完整。不完整的磁碟區群組會阻止韌體升級。
 a| 
如果一個或多個磁碟區群組或磁碟集區不完整，則必須先修正此錯誤情況，然後才能升級韌體。啟動 System Manager 並使用 Recovery Guru 解決此問題。



 a| 
目前在任何磁碟區群組上執行的獨佔作業 (後台媒體 / 同位元檢查掃描除外)
 a| 
如果磁碟區上正在進行任何獨佔操作，則無法升級韌體。
 a| 
如果正在進行一項或多項互斥操作，則必須先完成這些操作才能升級韌體。請使用 System Manager 監控操作進度。



 a| 
遺失的磁碟區
 a| 
如果缺少任何磁碟區，則無法升級韌體。
 a| 
您必須先修正遺失磁碟區的狀況，才能升級韌體。啟動 System Manager 並使用 Recovery Guru 來解決問題。



 a| 
任一控制器處於非最佳狀態
 a| 
如果任一控制器處於非最佳狀態，則無法升級韌體。
 a| 
其中一個儲存陣列控制器需要檢修。必須先解決此問題，才能升級韌體。啟動 System Manager 並使用 Recovery Guru 解決此問題。



 a| 
SPM Verify Database Controller 檢查失敗
 a| 
由於儲存分割區對應資料庫已損毀，因此無法升級韌體。
 a| 
控制器上發生儲存分割區對應資料庫錯誤。請聯絡技術支援以解決此問題。



 a| 
組態資料庫驗證（如果儲存陣列的控制器版本支援）
 a| 
由於組態資料庫已損毀，因此無法升級韌體。
 a| 
控制器上發生組態資料庫錯誤。請聯絡技術支援以解決此問題。



 a| 
MEL 相關檢查
 a| 
由於事件記錄包含錯誤，因此無法升級韌體。
 a| 
請聯絡技術支援以解決此問題。



 a| 
過去 7 天內報告了超過 10 起 DDE 資訊性或關鍵性 MEL 事件
 a| 
由於過去七天內報告了超過 10 個 DDE 資訊性或關鍵性 MEL 事件，因此無法升級韌體。
 a| 
請聯絡技術支援以解決此問題。



 a| 
過去 7 天內報告了超過 2 個 Page 2C Critical MEL 事件
 a| 
由於過去七天內報告了超過兩個第 2C 頁的關鍵 MEL 事件，因此無法升級韌體。
 a| 
請聯絡技術支援以解決此問題。



 a| 
過去 7 天內報告了超過 2 起降級磁碟機通道關鍵 MEL 事件
 a| 
由於過去七天內報告了超過兩個降級的磁碟機通道關鍵 MEL 事件，因此無法升級韌體。
 a| 
請聯絡技術支援以解決此問題。



 a| 
過去 7 天內有超過 4 條關鍵的 MEL 條目
 a| 
由於過去七天內報告的關鍵事件日誌條目超過四條，因此無法升級韌體。
 a| 
請聯絡技術支援以解決此問題。



 a| 
需要有效的管理 IP 位址。
 a| 
執行此作業需要有效的控制器 IP 位址。
 a| 
請聯絡技術支援以解決此問題。



 a| 
此命令需要為每個控制器提供一個有效的管理 IP 位址。
 a| 
此操作需要與儲存陣列相關聯的每個控制器的控制器 IP 位址。
 a| 
請聯絡技術支援以解決此問題。



 a| 
傳回未處理的下載檔案類型。
 a| 
不支援指定的下載檔案。
 a| 
請聯絡技術支援以解決此問題。



 a| 
韌體下載上傳程序期間發生錯誤。
 a| 
韌體下載失敗，因為控制器無法處理請求。請確認儲存陣列狀態良好，然後重試該操作。
 a| 
如果在確認儲存陣列處於最佳狀態後再次出現此錯誤、請聯絡技術支援以解決此問題。



 a| 
韌體啟動程序期間發生錯誤。
 a| 
韌體啟動失敗，因為控制器無法處理該請求。請確認儲存陣列狀態良好，然後重試該操作。
 a| 
如果在確認儲存陣列處於最佳狀態後再次出現此錯誤、請聯絡技術支援以解決此問題。



 a| 
等待控制器 {0} 重新開機時已達逾時。
 a| 
管理軟體無法在重新啟動後重新連線到控制器 {0}。請驗證儲存陣列的連線路徑是否正常運作，如果操作未成功完成，請重試該操作。
 a| 
如果在確認儲存陣列處於最佳狀態後再次出現此錯誤、請聯絡技術支援以解決此問題。

|===
您可以使用 System Manager 中的 Recovery Guru 來修正其中某些狀況。不過，對於某些狀況，您可能需要聯絡技術支援人員。有關最新控制器韌體下載的資訊可從儲存陣列取得。此資訊有助於技術支援人員瞭解導致韌體升級和下載失敗的錯誤狀況。
