---
permalink: sm-support/upgrade-drive-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, drive, firmware 
summary: 您可以升級磁碟機的韌體，以確保擁有所有最新功能和錯誤修正程式。 
---
= 在 SANtricity System Manager 中升級磁碟機韌體
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以升級磁碟機韌體、以確保擁有所有最新功能和錯誤修正程式。

.開始之前
* 您已使用磁碟到磁碟備份、磁碟區複製（到不受計劃韌體升級影響的磁碟區群組）或遠端鏡射備份了資料。
* 儲存陣列處於最佳狀態。
* 所有磁碟機均處於最佳狀態。
* 儲存陣列上未執行任何組態變更。
* 如果磁碟機僅支援離線升級，則與磁碟機相關聯的所有磁碟區的 I/O 活動都將停止。


.步驟
. 選擇功能表：Support [Upgrade Center]。
. 從支援網站將新檔案下載至您的管理用戶端。
. 在 Drive Firmware upgrade 下，按一下 *Begin Upgrade* 。
+
此時會出現一個對話方塊，列出目前正在使用的磁碟機韌體檔案。

. 解壓縮您從支援網站下載的檔案。
. 按一下 *Browse* 、然後選取您從支援網站下載的新磁碟機韌體檔案。
+
磁碟機韌體檔案的檔案名稱類似於 `D_HUC101212CSS600_30602291_MS01_2800_0002`，副檔名為 `.dlp`。

+
您最多可以選擇四個磁碟機韌體檔案，一次選擇一個。如果有多個磁碟機韌體檔案與同一個磁碟機相容，您會收到檔案衝突錯誤。決定要用於升級的磁碟機韌體檔案，並移除其他檔案。

. 按一下 *Next* 。
+
此時會顯示 *Select Drives* 對話框，其中列出了可使用所選檔案升級的磁碟機。

+
只有相容的磁碟機才會顯示。

+
驅動器的選定韌體會顯示在「建議韌體」資訊區域中。如果您必須變更韌體，請按一下 *Back* 返回上一個對話方塊。

. 選取您要執行的升級類型：
+
** *線上（預設）* -- 顯示可在儲存陣列處理 I/O 時支援韌體下載的磁碟機。選擇此升級方法時，無需停止使用這些磁碟機的關聯磁碟區的 I/O 操作。這些磁碟機將在儲存陣列處理這些磁碟機的 I/O 操作時逐一升級。
** *離線（並行）* -- 顯示_僅當使用這些磁碟機的所有磁碟區上的所有 I/O 活動停止時_才支援韌體下載的磁碟機。選擇此升級方法時，必須停止使用要升級的磁碟機的所有磁碟區上的所有 I/O 活動。不具備備援的磁碟機必須作為離線操作進行處理。此要求包括與 SSD 快取、RAID 0 磁碟區群組關聯的任何磁碟機，或任何降級的儲存池或磁碟區群組。離線（並行）升級通常比線上（預設）方法更快。


. 在表格的第一列中、選取您要升級的磁碟機。
. 按一下 *Start* 、然後確認您要執行此作業。
+
如果需要停止升級、請按一下 *Stop* 。目前正在進行的任何韌體下載都會完成。任何尚未開始的韌體下載都會取消。

+
[CAUTION]
====
停止磁碟機韌體升級可能會導致資料遺失或磁碟機無法使用。

====
. *選用：* 若要查看已升級內容的清單，請按一下 *Save Log* 。
+
該檔案以名稱  `drive_upgrade_log-timestamp.txt` 儲存在瀏覽器的 Downloads 資料夾中。

. 如果在升級過程中出現以下任何錯誤，請採取相應的建議措施。


.錯誤和建議的動作
[%collapsible]
====
[cols="40h,~"]
|===
| 如果您遇到此韌體下載錯誤... | 然後執行以下操作... 


 a| 
指派失敗的磁碟機
 a| 
故障原因之一可能是磁碟機缺少相應的簽名。請確保受影響的磁碟機是已授權的磁碟機。如需更多資訊，請聯繫技術支援。

更換磁碟機時、請確保更換磁碟機的容量等於或大於您要更換的故障磁碟機。

您可以在儲存陣列接收 I/O 時更換故障的磁碟機。



 a| 
檢查儲存陣列
 a| 
* 請確保已為每個控制器指派 IP 位址。
* 請確保連接至控制器的所有纜線均未損壞。
* 請確保所有纜線連接牢固。




 a| 
整合式熱備援磁碟機
 a| 
必須先解決此錯誤狀況，才能升級韌體。啟動 System Manager 並使用 Recovery Guru 來解決問題。



 a| 
不完整的磁碟區群組
 a| 
如果一個或多個磁碟區群組或磁碟集區不完整，則必須先修正此錯誤情況，然後才能升級韌體。啟動 System Manager 並使用 Recovery Guru 解決此問題。



 a| 
目前在任何磁碟區群組上執行的獨佔作業（後台媒體 / 同位元檢查掃描除外）
 a| 
如果正在進行一項或多項互斥操作，則必須先完成這些操作才能升級韌體。請使用 System Manager 監控操作進度。



 a| 
遺失的磁碟區
 a| 
您必須先修正遺失磁碟區的狀況，才能升級韌體。啟動 System Manager 並使用 Recovery Guru 來解決問題。



 a| 
任一控制器處於非最佳狀態
 a| 
其中一個儲存陣列控制器需要檢修。必須先解決此問題，才能升級韌體。啟動 System Manager 並使用 Recovery Guru 解決此問題。



 a| 
Controller Object Graph 之間的儲存分割區資訊不相符
 a| 
驗證控制器上的資料時發生錯誤。請聯絡技術支援以解決此問題。



 a| 
SPM Verify Database Controller 檢查失敗
 a| 
控制器上發生儲存分割區對應資料庫錯誤。請聯絡技術支援以解決此問題。



 a| 
組態資料庫驗證（如果儲存陣列的控制器版本支援）
 a| 
控制器上發生組態資料庫錯誤。請聯絡技術支援以解決此問題。



 a| 
MEL 相關檢查
 a| 
請聯絡技術支援以解決此問題。



 a| 
過去 7 天內報告了超過 10 起 DDE 資訊性或關鍵性 MEL 事件
 a| 
請聯絡技術支援以解決此問題。



 a| 
過去 7 天內報告了超過 2 個 Page 2C Critical MEL 事件
 a| 
請聯絡技術支援以解決此問題。



 a| 
過去 7 天內報告了超過 2 起降級磁碟機通道關鍵 MEL 事件
 a| 
請聯絡技術支援以解決此問題。



 a| 
過去 7 天內有超過 4 條關鍵的 MEL 條目
 a| 
請聯絡技術支援以解決此問題。

|===
====
.完成後
您的硬碟韌體升級已完成。您可以恢復正常作業。
