---
permalink: sm-support/upgrade-controller-software-and-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, software, firmware 
summary: 您可以升級儲存陣列的軟體，也可以選擇升級 IOM 韌體和非揮發性靜態隨機存取記憶體（NVSRAM），以確保您擁有所有最新功能和錯誤修復。 
---
= 在 SANtricity System Manager 中升級控制器軟體和韌體
:allow-uri-read: 


[role="lead"]
您可以升級儲存陣列的軟體，也可以選擇升級 IOM 韌體和非揮發性靜態隨機存取記憶體（NVSRAM），以確保您擁有所有最新功能和錯誤修復。

.開始之前
* 您知道是否要升級 IOM 韌體。
+
通常情況下，您應該同時升級所有元件。但是，如果您不想將 IOM 韌體作為 SANtricity OS 軟體升級的一部分進行升級，或者技術支援人員指示您降級 IOM 韌體（您只能使用命令列介面降級韌體），則可以選擇不升級 IOM 韌體。

* 您知道是否要升級控制器 NVSRAM 檔案。
+
通常情況下，您應該同時升級所有組件。但是，如果您的檔案已修補或為自訂版本，並且您不想覆蓋它，則可以選擇不升級控制器 NVSRAM 檔案。

* 您知道是要現在還是稍後啟動作業系統升級。
+
稍後啟動的原因可能包括：

+
** *時間因素* -- 啟動軟體和韌體可能需要很長時間，因此建議您等到 I/O 負載較低時再進行操作。啟動期間控制器會進行故障轉移，因此在升級完成之前，效能可能會低於正常水準。
** *套件類型* -- 您可能需要在升級其他儲存陣列上的檔案之前，先在一個儲存陣列上測試新的軟體和韌體。


* 您知道是否要從不安全的磁碟機或內部安全的磁碟機切換到使用外部金鑰管理伺服器（KMS）來保護磁碟機安全性。
* 您知道是否要在儲存陣列中使用角色型存取控制。


.關於此任務
您可以選擇只升級 OS 軟體檔案、只升級 Controller NVSRAM 檔案，或選擇同時升級這兩個檔案。

僅在技術支援人員指示時才執行此操作。

[CAUTION]
====
*資料遺失或儲存陣列損壞的風險* -- 升級過程中請勿對儲存陣列進行任何變更。請保持儲存陣列的電源供應。

====
.步驟
. 如果您的儲存陣列只有一個控制器，或者您沒有安裝多路徑驅動程式，請停止對儲存陣列的 I/O 活動以防止應用程式錯誤。如果您的儲存陣列有兩個控制器並且您已安裝多路徑驅動程式，則無需停止 I/O 活動。
. 選擇功能表：Support [Upgrade Center]。
. 從 Support 網站下載新檔案到您的管理客戶端。
+
.. 點擊 *NetApp Support* 以啟動 Support 網站。
.. 在支援網站上、按一下 *Downloads* 索引標籤、然後選取 *Downloads* 。
.. 選擇 *E 系列 SANtricity 作業系統控制器軟體*。
.. 請按照其餘指示操作。


+
[NOTE]
====
8.42 版及更高版本需要經過數位簽章的韌體。如果您嘗試下載未簽署的韌體，系統將顯示錯誤訊息並中止下載。

====
. 如果您目前不想升級 IOM 韌體，請按一下 *暫停 IOM 自動同步*。
+
如果您的儲存陣列只有一個控制器，則 IOM 韌體不會升級。

. 在 SANtricity OS 軟體升級下、按一下 *Begin Upgrade* 。
+
出現「升級 SANtricity 作業系統軟體」對話框。

. 選取一或多個檔案以開始升級程序：
+
.. 點擊 * 瀏覽 * 並導覽至您從支援網站下載的 OS 軟體檔案，以選擇 SANtricity OS 軟體檔案。
.. 點擊 *Browse* 並瀏覽至您從 Support 網站下載的 NVSRAM 檔案，以選擇 Controller NVSRAM 檔案。Controller NVSRAM 檔案的檔案名稱類似於 `N2800-830000-000.dlp`。


+
這些動作會發生：

+
** 根據預設，僅顯示與目前儲存陣列組態相容的檔案。
** 選擇要升級的檔案時、會顯示檔案名稱和大小。


. *可選：* 如果您選擇 SANtricity OS 軟體檔案進行升級，您可以透過選取「立即傳輸檔案，但不升級（稍後啟動升級）」核取方塊，將檔案傳輸到控制器而不啟動它們。
. 按一下 *Start* 、然後確認您要執行此作業。
+
您可以在升級前的健康檢查期間取消操作，但不能在傳輸或啟動期間取消操作。

. *選用：* 若要查看已升級內容的清單，請按一下 *Save Log* 。
+
該檔案以名稱  `drive_upgrade_log-timestamp.txt` 儲存在瀏覽器的 Downloads 資料夾中。



.完成後
* 請確認所有元件都顯示在 Hardware 頁面上。
* 透過檢查「軟體和韌體清單」對話方塊來驗證新的軟體和韌體版本（前往功能表：Support[Upgrade Center]，然後按一下 *Software and Firmware Inventory* 連結）。
* 如果您升級了控制器 NVSRAM，則在啟動過程中，您先前套用於現有 NVSRAM 的所有自訂設定都會遺失。啟動過程完成後，您需要重新將這些自訂設定套用到 NVSRAM。

