---
permalink: sm-support/view-iscsi-sessions-support.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, iscsi, sessions 
summary: 您可以檢視有關儲存陣列的 iSCSI 連線的詳細資訊。iSCSI 工作階段可以與主機或處於非同步鏡射關係中的遠端儲存陣列一起發生。 
---
= 在 SANtricity System Manager 中檢視 iSCSI 工作階段
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以檢視有關儲存陣列的 iSCSI 連線的詳細資訊。iSCSI 工作階段可以與主機或處於非同步鏡射關係中的遠端儲存陣列一起發生。

.步驟
. 選擇功能表：Support [ Support Center > Diagnostics ] 標籤。
. 選擇 *View/End iSCSI Sessions* 。
+
目前 iSCSI 工作階段的清單隨即顯示。

. 若要查看特定 iSCSI 工作階段的其他資訊，請選取工作階段，然後按一下 *View Details*。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 項目 | 說明 


 a| 
Session ID (SSID)
 a| 
用於識別 iSCSI 發起程序和 iSCSI 目標之間會話的十六進位字串。SSID 由 ISID 和 TPGT 組成。



 a| 
發起方 Session ID （ISID）
 a| 
工作階段識別碼的啟動器部分。啟動器會在登入期間指定 ISID。



 a| 
目標入口網站群組
 a| 
iSCSI 目標。



 a| 
目標入口網站群組標籤（TPGT）
 a| 
工作階段識別碼的目標部分。iSCSI 目標入口網站群組的 16 位元數字識別碼。



 a| 
啟動器 iSCSI 名稱
 a| 
啟動器的全球唯一名稱。



 a| 
啟動器 iSCSI 標籤
 a| 
在 System Manager 中設定的使用者標籤。



 a| 
啟動器 iSCSI 別名
 a| 
也可以與 iSCSI 節點關聯的名稱。別名允許組織將易於理解的字串與 iSCSI 名稱關聯起來。但是，別名不能取代 iSCSI 名稱。啟動器 iSCSI 別名只能在主機上設定，不能在 System Manager 中設定



 a| 
主機
 a| 
向儲存陣列傳送輸入和輸出的伺服器。



 a| 
連線 ID（CID）
 a| 
會話中發起方和目標方之間連線的唯一名稱。發起方產生此 ID，並在登入請求期間提供給目標方。登出並關閉連線時，也會提供此連線 ID。



 a| 
乙太網路連接埠識別碼
 a| 
與連線相關聯的控制器連接埠。



 a| 
發起方 IP 位址
 a| 
發起者的 IP 位址。



 a| 
協商的登入參數
 a| 
iSCSI 工作階段登入期間處理的參數。



 a| 
驗證方法
 a| 
用於驗證希望存取 iSCSI 網路的使用者身分的技術。有效值為 *CHAP* 和 *None*。



 a| 
標頭摘要方法
 a| 
此技術用於顯示 iSCSI 會話的可能標頭值。HeaderDigest 和 DataDigest 可以是 *None* 或 *CRC32C*。兩者的預設值均為 *None*。



 a| 
資料摘要方法
 a| 
此技術用於顯示 iSCSI 會話的可能資料值。HeaderDigest 和 DataDigest 可以是 *None* 或 *CRC32C*。兩者的預設值均為 *None*。



 a| 
最大連線數
 a| 
iSCSI 工作階段允許的最大連線數。最大連線數可以為 1 到 4。預設值為 *1* 。



 a| 
目標別名
 a| 
與目標關聯的標籤。



 a| 
啟動器別名
 a| 
與啟動器相關的標籤。



 a| 
目標 IP 位址
 a| 
iSCSI 會話目標的 IP 位址。不支援 DNS 名稱。



 a| 
初始 R2T
 a| 
初始轉移準備狀態。狀態可以是 *Yes* 或 *No* 。



 a| 
最大突發長度
 a| 
此 iSCSI 工作階段的最大 SCSI 承載（以位元組為單位）。最大突發長度範圍為 512 至 262,144 （256 KB）。預設值為 *262,144 （256 KB）*。



 a| 
第一次突發長度
 a| 
此 iSCSI 工作階段中未經請求的資料的 SCSI 有效負載（以位元組為單位）。第一個突發長度可以介於 512 到 131,072（128 KB）之間。預設值為 *65,536（64 KB）*。



 a| 
預設等待時間
 a| 
連線終止或連線重設後，嘗試建立連線前等待的最短秒數。預設等待時間值可以是 0 到 3600。預設值為 *2*。



 a| 
預設保留時間
 a| 
連線終止或重設後，連線仍可保持的最長時間（以秒為單位）。預設保持時間範圍為 0 到 3600 秒。預設值為 *20*。



 a| 
最大未完成 R2T
 a| 
此 iSCSI 工作階段未完成的「準備傳輸」數量上限。未完成的準備傳輸值上限可以是 1 到 16。預設值為 *1*。



 a| 
錯誤恢復層級
 a| 
此 iSCSI 工作階段的錯誤復原層級。錯誤復原層級值一律設為 *0*。



 a| 
最大接收資料區段長度
 a| 
發起方或目標方可以在任何 iSCSI 有效載荷資料單元（PDU）中接收的最大資料量。



 a| 
目標名稱
 a| 
目標的正式名稱（非別名）。目標名稱採 _iqn_ 格式。



 a| 
啟動器名稱
 a| 
發起者的正式名稱（非別名）。使用 _iqn_ 或 _eui_ 格式的發起者名稱。

|===
====
. 若要將報告儲存至檔案，請按一下 *Save*。
+
檔案會以檔案名稱  `iscsi-session-connections.txt` 儲存在瀏覽器的「下載」資料夾中。


