---
permalink: sm-support/view-events-using-the-event-log.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, events, 
summary: 您可以檢視事件記錄，其中提供了儲存陣列上發生的事件的歷史記錄。 
---
= 使用 SANtricity System Manager 中的事件日誌檢視事件
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以檢視事件記錄，其中提供了儲存陣列上發生的事件的歷史記錄。

.步驟
. 選擇功能表：Support [ 事件記錄 ] 。
+
此時會顯示「事件記錄」頁面。

+
.頁面詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 項目 | 說明 


 a| 
檢視所有欄位
 a| 
可在所有事件及僅關鍵事件和警告事件之間切換。



 a| 
篩選欄位
 a| 
篩選事件。可用於僅顯示與特定元件、特定事件等相關的事件。



 a| 
選取欄圖示。
 a| 
允許您選擇要檢視的其他欄位。其他欄位可提供有關事件的其他資訊。



 a| 
核取方塊
 a| 
允許您選擇要儲存的事件。表格標題中的核取方塊可選取所有事件。



 a| 
日期 / 時間欄
 a| 
根據控制器時鐘的事件日期和時間戳記。


NOTE: 事件日誌最初會根據序號對事件進行排序。通常，該序號與日期和時間相對應。但是，儲存陣列中的兩個控制器時脈可能會不同步。在這種情況下，事件日誌中顯示的事件及其日期和時間可能會出現一些不一致的情況。



 a| 
優先順序欄
 a| 
存在以下優先順序值：

** *Critical* -- 儲存陣列出現問題。但是，如果您立即採取措施，則可能避免資料遺失。Critical 事件用於發出警報通知。所有 Critical 事件都會傳送到任何網路管理用戶端（透過 SNMP 陷阱）或您設定的電子郵件收件者。
** *警告* -- 發生錯誤，導致儲存陣列的效能下降，並且無法從另一個錯誤中復原。
** *資訊性* -- 與儲存陣列相關的非關鍵資訊。




 a| 
元件類型欄
 a| 
受事件影響的元件。該元件可能是硬體，例如磁碟機或控制器，也可能是軟體，例如控制器韌體。



 a| 
元件位置欄
 a| 
元件在儲存陣列中的實體位置。



 a| 
描述欄
 a| 
事件的說明。

*範例* -- `Drive write failure - retries exhausted`



 a| 
序號欄
 a| 
一個 64 位元數字，用於唯一標識儲存陣列中的特定日誌條目。每次出現新的事件日誌條目時，此數字都會遞增 1。若要顯示此資訊，請按一下 *Select columns* 圖示。



 a| 
事件類型欄
 a| 
一個四位數編號，用於識別每種已記錄事件類型。若要顯示此資訊，請按一下 *Select columns* 圖示。



 a| 
事件特定代碼欄
 a| 
此資訊供技術支援使用。若要顯示此資訊，請按一下 *Select columns* 圖示。



 a| 
事件類別欄
 a| 
** **故障** – 儲存陣列中的元件發生故障；例如磁碟機故障或電池故障。
** **狀態變更** – 儲存陣列中的某個元素的狀態發生了變化；例如，磁碟區轉換為 Optimal 狀態，或控制器轉換為 Offline 狀態。
** **內部** – 不需要使用者操作的內部控制器作業；例如，控制器已完成每日啟動作業。
** **命令** – 已向儲存陣列發出的命令；例如，已指派熱備援。
** **錯誤** – 儲存陣列上偵測到錯誤情況；例如，控制器無法同步和清除快取，或儲存陣列上偵測到備援錯誤。
** **一般** – 任何不適合歸入其他任何類別的事件。若要顯示此資訊，請按一下**選取欄**圖示。




 a| 
記錄者欄
 a| 
記錄該事件的控制器名稱。若要顯示此資訊，請按一下 **選取欄** 圖示。

|===
====
. 若要從儲存陣列擷取新事件，請按一下 **Refresh** 。
+
事件可能需要幾分鐘才能被記錄並顯示在 Event Log 頁面中。

. 若要將事件日誌儲存至檔案：
+
.. 選取要儲存的每個事件旁邊的核取方塊。
.. 按一下 *Save* 。
+
該檔案以名稱  `major-event-log-timestamp.log` 儲存在瀏覽器的 Downloads 資料夾中。



. 若要從事件日誌中清除事件：
+
事件日誌大約會儲存 8,000 個事件，之後才會用新事件取代舊事件。如果您想保留這些事件，可以儲存它們，然後從事件日誌中清除它們。

+
.. 首先，儲存事件記錄。
.. 點擊 *Clear All* ，並確認要執行此操作。



