---
permalink: sm-support/view-storage-array-profile.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, storage, array, profile 
summary: 儲存陣列設定檔提供儲存陣列所有元件和屬性的說明。 
---
= 在 SANtricity System Manager 中檢視儲存陣列的設定檔
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存陣列設定檔提供儲存陣列所有元件和屬性的說明。

.關於此任務
您可以在復原過程中使用儲存陣列設定檔作為輔助工具，或將其作為儲存陣列目前組態的概覽。建議您在管理用戶端上儲存一份儲存陣列設定檔副本，並在儲存陣列上保留一份紙本副本。如果組態發生變更，請建立新的儲存陣列設定檔副本。

.步驟
. 選擇功能表：Support [ Support Center > Support Resources ] 標籤。
. 向下捲動至 *Launch detailed storage array information* ，然後選擇 *Storage Array Profile* 。
+
報告會顯示在螢幕上。

+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 章節 | 說明 


 a| 
儲存陣列
 a| 
顯示您可以設定的所有選項以及儲存陣列的系統靜態選項。這些選項包括控制器、磁碟機櫃、磁碟機、磁碟集區、磁碟區群組、磁碟區和熱備援磁碟機的數量；允許的磁碟機櫃、磁碟機、固態磁碟（SSD）和磁碟區的最大數量；快照群組、快照映像、快照磁碟區和一致性群組的數量；功能相關資訊；韌體版本資訊；機箱序號資訊；AutoSupport 狀態和 AutoSupport 排程資訊；自動支援資料收集和排程支援資料收集的設定；儲存陣列全球識別碼（WWID）；以及媒體掃描和快取設定。



 a| 
儲存
 a| 
顯示儲存陣列中所有儲存設備的清單。根據您的儲存陣列組態，Storage 區段可能會顯示這些子區段。

** *磁碟集區* -- 顯示儲存陣列中所有磁碟集區的清單。
** *Volume Groups* -- 顯示儲存陣列中所有 Volume Groups 的清單。磁碟區和可用容量按建立順序排列。
** *Volumes* -- 顯示儲存陣列中所有磁碟區的清單。列出的資訊包括磁碟區名稱、磁碟區狀態、容量、RAID 等級、磁碟區群組或磁碟集區、磁碟機類型以及其他詳細資訊。
** *缺失磁碟區* -- 顯示儲存陣列中所有目前狀態為缺失的磁碟區清單。所列資訊包括每個缺失磁碟區的全球識別碼（WWID）。




 a| 
複製服務
 a| 
顯示儲存陣列使用的所有複製服務清單。根據您的儲存陣列組態，「複製服務」區段可能會顯示下列子區段：

** *Volume Copies* -- 顯示儲存陣列中所有副本對的清單。列出的資訊包括副本數量、副本對名稱、狀態、開始時間戳記和其他詳細資訊。
** * Snapshot Groups* -- 顯示儲存陣列中所有 Snapshot Groups 的清單。
** *Snapshot Images* -- 顯示儲存陣列中所有快照的清單。
** *Snapshot Volumes* -- 顯示儲存陣列中所有 Snapshot Volume 的清單。
** *一致性群組* -- 顯示儲存陣列中所有一致性群組的清單。
** *成員磁碟區* -- 顯示儲存陣列中所有一致性群組成員磁碟區的清單。
** *鏡像群組* -- 顯示所有鏡像磁碟區的清單。
** *Reserved Capacity* -- 顯示儲存陣列中所有預留容量磁碟區的清單。




 a| 
主機指派
 a| 
顯示儲存陣列中的主機指派清單。列出的資訊包括磁碟區名稱、邏輯單元編號（LUN）、控制器 ID、主機名稱或主機叢集名稱，以及磁碟區狀態。列出的其他資訊包括拓撲定義和主機類型定義。



 a| 
硬體
 a| 
顯示儲存陣列中所有硬體的清單。根據您的儲存陣列組態、硬體區段可能會顯示這些子區段。

** *Controllers* -- 顯示儲存陣列中所有控制器的列表，包括控制器位置、狀態和配置。此外，還包括磁碟機通道資訊、主機通道資訊和乙太網路連接埠資訊。
** *磁碟機* -- 顯示儲存陣列中所有磁碟機的清單。磁碟機依機架 ID、抽屜 ID、插槽 ID 的順序排列。列出的資訊包括每個磁碟機的機架 ID、抽屜 ID、插槽 ID、狀態、原始容量、媒體類型、介面類型、目前資料速率、產品 ID 和韌體版本。磁碟機部分還包括磁碟機通道資訊、熱備援涵蓋範圍資訊和損耗壽命資訊（僅適用於 SSD 磁碟機）。損耗壽命資訊包括已使用耐久度百分比，即 SSD 磁碟機迄今為止寫入的資料量除以磁碟機的理論總寫入限制。
** *Drive Channels* -- 顯示儲存陣列中所有磁碟機通道的資訊。列出的資訊包括通道狀態、連結狀態（如果適用）、磁碟機數量和累計錯誤計數。
** *儲存架* -- 顯示儲存陣列中所有儲存架的資訊。所列資訊包括磁碟機類型以及儲存架中每個組件的狀態資訊。儲存架組件可能包括電池組、Small Form-factor Pluggable（SFP）收發器、電源風扇盒或輸入/輸出模組（IOM）盒。如果儲存陣列使用了安全性金鑰，硬體部分也會顯示安全金鑰識別碼。




 a| 
功能
 a| 
顯示已安裝的功能包列表，以及每個主機或主機叢集允許的最大快照群組數、快照（舊式）數和磁碟區數。「功能」部分的資訊還包括磁碟機安全性，即儲存陣列是否啟用了安全功能。

|===
====
. 若要搜尋儲存陣列設定檔、請在 *Find* 文字方塊中輸入搜尋字詞、然後按一下 *Find* 。
+
所有符合項目均已高亮顯示。若要逐一瀏覽所有結果，請繼續點選 *Find*。

. 若要儲存儲存陣列設定檔，請按一下 *儲存* 。
+
該檔案以名稱  `storage-array-profile.txt` 儲存在瀏覽器的 Downloads 資料夾中。


