---
permalink: sm-support/view-unreadable-sectors-log.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, unreadable, sectors, log 
summary: 您可以儲存無法讀取的磁區記錄、並將檔案傳送給技術支援部門進行分析。 
---
= 在 SANtricity System Manager 中檢視無法讀取的磁區記錄
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以儲存無法讀取的磁區記錄、並將檔案傳送給技術支援部門進行分析。

.關於此任務
不可讀磁區日誌包含由磁碟機報告無法復原的媒體錯誤而導致的不可讀磁區的詳細記錄。在正常的 I/O 操作和修改操作（例如重建）期間都會偵測到不可讀磁區。當儲存陣列上偵測到不可讀磁區時，此儲存陣列會顯示「需要注意」警報。Recovery Guru 會區分哪些不可讀磁區需要注意。任何包含在不可讀磁區中的資料都無法恢復，應視為遺失。

不可讀磁區日誌最多可儲存 1,000 個不可讀磁區。當不可讀磁區日誌達到 1,000 個項目時，適用下列條件：

* 如果在重建過程中偵測到新的不可讀磁區，則重建失敗，並且不會記錄任何項目。
* 對於在 I/O 過程中偵測到的新不可讀磁區，I/O 操作失敗，且不會記錄任何項目。
+
[NOTE]
====
這些操作包括在溢出之前本應成功的 RAID 5 寫入和 RAID 6 寫入。

====


[CAUTION]
====
* 資料可能遺失 * -- 從無法讀取的磁區恢復資料是一個複雜的程序，可能涉及多種不同的方法。僅在技術支援人員指示時執行此操作。

====
.步驟
. 選擇功能表：Support [ Support Center > Diagnostics ] 標籤。
. 選擇 *View/Clear Unreadable Sectors* 。
. 若要儲存無法讀取的磁區記錄：
+
.. 在表格的第一欄中，您可以選擇要儲存無法讀取磁區記錄的個別磁碟區（按一下每個磁碟區旁的核取方塊），或選取所有磁碟區（選取表格標題中的核取方塊）。
+
若要尋找特定磁碟區，您可以對任何欄進行排序，或在 *Filter* 方塊中輸入字元。

.. 按一下 *Save* 。


+
該檔案以名稱  `unreadable-sectors.txt` 儲存在瀏覽器的 Downloads 資料夾中。

. 如果技術支援人員指示您清除無法讀取的磁區記錄、請執行下列步驟：
+
.. 在表格的第一列中，您可以選擇要清除無法讀取的磁區記錄的個別磁碟區（按一下每個磁碟區旁的核取方塊），或選取所有磁碟區（選取表格標題中的核取方塊）。
.. 點擊 *Clear* ，並確認要執行此操作。



