---
permalink: um-certificates/change-saml-role-mappings.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, saml, role, mappings, 
summary: 如果您先前已為 Access Management 設定了 SAML，則可以變更 IdP 群組和儲存陣列預先定義角色之間的角色對應。 
---
= 在 SANtricity Unified Manager 中變更 SAML 角色映射
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您先前已為 Access Management 設定了 SAML，則可以變更 IdP 群組和儲存陣列預先定義角色之間的角色對應。

.開始之前
* 您必須使用具有 Security admin 權限的使用者設定檔登入。否則，Access Management 功能將不會顯示。
* IdP 管理員已在 IdP 系統中設定使用者屬性和群組成員資格。
* SAML 已設定並啟用。


.步驟
. 選擇選單：Settings[ 存取管理 ]。
. 選擇 *SAML* 選項卡。
. 選擇 *Role Mapping* 。
+
角色映射對話方塊開啟。

. 將 IdP 使用者屬性和群組指派給預先定義的角色。一個群組可以擁有多個已指派的角色。
+
[CAUTION]
====
請注意，在啟用 SAML 的情況下，不要撤銷您的權限，否則您將失去對 Unified Manager 的存取權限。

====
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
*對應*



 a| 
使用者屬性
 a| 
指定要對應的 SAML 群組的屬性（例如「member of」）。



 a| 
屬性值
 a| 
指定要對應的群組的屬性值。



 a| 
角色
 a| 
按一下該欄位，然後選擇要對應到該屬性的儲存陣列角色之一。您必須單獨選擇要包含在此群組中的每個角色。Monitor 角色必須與其他角色結合使用才能登入 Unified Manager。Security Admin 角色必須至少指派給一個群組。對應的角色包含以下權限：

** *Storage admin* -- 對儲存物件（例如、磁碟區和磁碟集區）具有完全的讀取 / 寫入權限、但無權存取安全性組態。
** *Security admin* -- 可以存取 Access Management 中的安全性設定、憑證管理、稽核日誌管理，以及啟用或停用舊版管理介面（SYMbol）的功能。
** *Support admin* -- 可存取儲存陣列上的所有硬體資源、故障資料、MEL 事件和控制器韌體升級。無權存取儲存物件或安全性配置。
** *Monitor* -- 對所有儲存物件具有唯讀存取權限，但無權存取安全性組態。


|===
====
+

NOTE: 所有使用者（包括管理員）都必須擁有 Monitor 角色。如果使用者沒有 Monitor 角色，Unified Manager 將無法正常運作。

. （可選）按一下 *Add another mapping* 以輸入更多群組到角色的對應。
. 按一下 *Save* 。


.結果
完成此工作後，所有作用中的使用者工作階段都會終止。只會保留您目前的使用者工作階段。
