---
permalink: um-certificates/how-access-management-works-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, authentication, users, roles, access management 
summary: 使用存取管理在 SANtricity Unified Manager 中建立使用者驗證。 
---
= SANtricity Unified Manager 中的存取管理工作原理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用存取管理在 SANtricity Unified Manager 中建立使用者驗證。



== 組態工作流程

存取管理組態的運作方式如下：

. 管理員使用包含 Security admin 權限的使用者設定檔登入 Unified Manager。
+
[NOTE]
====
首次登入時，使用者名稱 `admin`會自動顯示且無法變更。 `admin`使用者擁有系統所有功能的完整存取權限。密碼必須在首次登入時設定。

====
. 管理員在使用者介面中導航至 Access Management，其中包含預先配置的本機使用者角色。這些角色是 RBAC（role-based access control）功能的實作。
. 管理員會設定下列一或多種驗證方法：
+
** *本機使用者角色* -- 驗證透過 RBAC 功能進行管理。本機使用者角色包括預先定義的使用者和角色，具有特定存取權限。管理員可以將這些本機使用者角色作為單一驗證方法，或與目錄服務結合使用。除了為使用者設定密碼之外，無需進行其他配置。
** *目錄服務* -- 驗證透過 LDAP（Lightweight Directory Access Protocol）伺服器和目錄服務（例如 Microsoft 的 Active Directory）進行管理。管理員連接到 LDAP 伺服器，然後將 LDAP 使用者對應到本機使用者角色。
** *SAML* -- 驗證透過身分提供者（IdP）使用 Security Assertion Markup Language（SAML）2.0 進行管理。管理員在 IdP 系統和儲存陣列之間建立通訊，然後將 IdP 使用者對應到嵌入儲存陣列中的本機使用者角色。


. 管理員為使用者提供 Unified Manager 的登入認證。
. 使用者透過輸入憑證登入系統。登入期間，系統會在背景執行下列任務：
+
** 根據使用者帳戶驗證使用者名稱和密碼。
** 根據指派的角色決定使用者的權限。
** 為使用者提供使用者介面中各項功能的存取權限。
** 在頂部橫幅中顯示使用者名稱。






== Unified Manager 中可用的功能

使用者對功能的存取權限取決於其被指派的角色，包括以下角色：

* *Storage admin* -- 對陣列上的儲存物件具有完全讀取 / 寫入權限，但無權存取安全性配置。
* *Security admin* -- 存取 Access Management 和 Certificate Management 中的安全性組態。
* *Support admin* -- 可存取儲存陣列上的所有硬體資源、故障資料和 MEL 事件。無權存取儲存物件或安全性組態。
* *Monitor* -- 對所有儲存物件具有唯讀存取權限，但無權存取安全性組態。


無法使用的功能會顯示為灰色或不會在使用者介面中顯示。
