---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, administrator, password, protection 
summary: 您必須為 SANtricity Unified Manager 設定管理員密碼，以防止未經授權的存取。 
---
= 了解 SANtricity Unified Manager 中的管理員密碼保護功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須為 SANtricity Unified Manager 設定管理員密碼，以防止未經授權的存取。



== 管理員密碼和使用者設定檔

首次啟動 Unified Manager 時，系統會提示您設定管理員密碼。任何擁有管理員密碼的使用者都可以對儲存陣列進行組態變更。

除了管理員密碼之外， Unified Manager 介面還包含預先配置的使用者設定檔，每個設定檔都映射了一個或多個角色。如需詳細資訊，請參閱link:../um-certificates/how-access-management-works-unified.html["存取管理的運作方式"]。

使用者和對應無法變更。只能修改密碼。若要變更密碼，請參閱：

* link:change-admin-password-unified.html["更改管理員密碼"]
* link:../um-certificates/change-passwords-unified.html["變更本機使用者設定檔的密碼"]




== 工作階段逾時

軟體在單次管理工作階段期間只會提示您輸入一次密碼。預設情況下，工作階段會在 30 分鐘無活動後逾時，屆時您必須重新輸入密碼。如果其他使用者透過其他管理用戶端存取軟體並在您的工作階段期間變更了密碼，則下次您嘗試進行組態操作或檢視操作時，系統會提示您輸入密碼。

出於安全考慮，您只能嘗試輸入密碼五次，之後軟體將進入「鎖定」狀態。在此狀態下，軟體將拒絕後續的密碼輸入。您必須等待 10 分鐘才能恢復到「正常」狀態，之後才能再次嘗試輸入密碼。

您可以調整工作階段逾時時間，也可以完全停用工作階段逾時。如需詳細資訊、請參閱 link:manage-session-timeouts-unified.html["管理工作階段逾時"]。
